### PR TITLE
Set pipeline status when all tasks complete

### LINKED ISSUE #1680: (*PipelineRun).IsDone() is incorrect
The `(*PipelineRun).IsDone()` function returns true when the Success condition is no longer `Unknown`. However, as soon as the first task in the PipelineRun fails it sets the PipelineRun's Success condition to `False`, and `IsDone()` immediately returns `true`, despite several other tasks still `Running`.

Instead, `IsDone()` should check `Status.CompletionTime` or iterate through all tasks and check whether all tasks have finished executing.

Two new `HasSucceeded()` and `HasFailed()` functions can take the place of `IsDone()` if needed.

I'm happy to submit a PR if this sounds sensible.

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes
We used to set the pipeline status to failed as soon as the first
task in the pipeline failed or was cancelled.

As soon as the first task in the pipeline fails or is cancelled, we
stop scheduling new tasks, as we did before, but we will report
status Unknown until all Tasks are complete, with reason "stopping".

This allows to:
- the completion time at the same time that the status is set
  and avoid inconsistencies
- wait until all tasks are complete before we cleanup the pipeline
  artifact storage, affinity assistant and record metrics
- report the correct number of failed / cancelled tasks, as there
  may be more than one. Other tasks that were already running
  when the first failure happened may fail too
- prepare the pipeline controller more complex workflows, where
  the controller may continue working scheduling after failures

Add test coverage for isSkipped and extend the pipelineresolution
module unit test coverage to capture more input pipeline state.

The DAG / GetNextTasks functions have not been touched at all.
The pipeline run reconciler, when the pipeline run is in stopping
mode, stops asking for next tasks to run. Once all running tasks
finish, the pipeline run finally gets in failed state.

When the pipeline run is in stopping mode, tasks that have not
been started yet are also counted as skipped in the status message
reported to the user.

Fixes #1680

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [WIP] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
In case of task run failure or cancellation, the pipeline run stops scheduling new tasks like before.
The status is marked as failed however only once all the task runs already scheduled are complete.

A new reason "PipelineRunStopping" indicate that the pipeline run has found a failure and is waiting for task runs to complete.
```

### CODE REVIEW

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 1]
```diff
@@ -422,67 +440,78 @@ func GetPipelineConditionStatus(pr *v1beta1.PipelineRun, state PipelineRunState,
...
+			Reason: reason,
+			Message: fmt.Sprintf("Tasks Completed: %d (Failed: %d, Cancelled %d), Skipped: %d",
+				len(allTasks)-skipTasks, failedTasks, cancelledTasks, skipTasks),
 		}
 	}
 
-	// Hasn't timed out; no taskrun failed yet; and not all tasks have finished....
+	// Hasn't timed out; not all tasks have finished....
 	// Must keep running then....
+	if failedTasks > 0 || cancelledTasks > 0 {
```
Comment (GregDritschler) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:504]: Isn't this point reached if there are dependent tasks that haven't been (and won't be) scheduled?  I don't see anything distinguishing running from not yet running.

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:504]: Uhm, when I wrote this code I understood that isSkipped would mark descendants of failed tasks as skipped, but it doesn't, so I may need to revisit that, and add more unit tests because that should be caught by testing if it's not working as it should.

I thought the case you mentioned was covered but I'll check that again

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:504]: Uhm, when I wrote this code I understood that isSkipped would mark descendants of failed tasks as skipped, but it doesn't, so I may need to revisit that, and add more unit tests because that should be caught by testing if it's not working as it should.

I thought the case you mentioned was covered but I'll check that again

Comment (pritidesai) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:479]: @afrittoli havent looked all the changes yet but, skipped tasks are very tricky, please see my comment [here](https://github.com/tektoncd/pipeline/pull/2661#discussion_r428827199)

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:479]: Thanks for catching this issue!

I've added now logic to distinguish the running and non running cases.
When the pipeline is in stopping mode, taskrun that have not been started yet will be counted as skipped. So if there is any task that is running the pipeline stays in stopping, else it switches to failed.

I've added more test cases for this too.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 2]
```diff
@@ -421,9 +421,48 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1beta1.PipelineRun) err
...
 
+	as, err := artifacts.InitializeArtifactStorage(c.Images, pr, pipelineSpec, c.KubeClientSet, c.Logger)
+	if err != nil {
+		c.Logger.Infof("PipelineRun failed to initialize artifact storage %s", pr.Name)
+		return err
+	}
+
+	// When the pipeline run is stopping, we don't schedule any new task and only
+	// wait for all running tasks to complete and report their status
+	if !pipelineState.IsStopping() {
```
Comment (afrittoli) [inline pkg/reconciler/pipelinerun/pipelinerun.go:432]: The diff does not help very much, but the only changes here are:
- `if !pipelineState.IsStopping()`
- the code that used to be here moved "as-is" into `runNextSchedulableTask`

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 1 above)
Comment (GregDritschler) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:501]: 👍

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 3]
```diff
@@ -486,7 +534,12 @@ func isSkipped(rprt *ResolvedPipelineRunTask, stateMap map[string]*ResolvedPipel
 	// if any of the parents have been skipped, skip as well
 	node := d.Nodes[rprt.PipelineTask.Name]
 	for _, p := range node.Prev {
-		skip := isSkipped(stateMap[p.Task.HashKey()], stateMap, d)
+		rcc := stateMap[p.Task.HashKey()]
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:537]: Is this something avoidable? marking a task skipped if one of the parents is failed or cancelled, this might interfere with `except` similar to `finally` but is invoked only when a task fails 🤔 .`Pipeline` is anyways `stopped` or `paused` (may be better term), resume it where we left off and report failure. Just brainstorming here 💭 how does these changes impact pipeline run status?

Comment (pritidesai) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:537]: Today, tasks are considered `skipped` (1) when its condition check fails and hence not executed and skipped (2) Or one of the parents is skipped. Tasks dependent on failed tasks are considered as `incomplete`.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 4]
```diff
@@ -401,72 +429,92 @@ func GetPipelineConditionStatus(pr *v1beta1.PipelineRun, state PipelineRunState,
...
+		case !rprt.IsStarted() && isStopping:
+			// If the pipeline is in stopping mode, all tasks that are not running
+			// already will be skipped. Otherwise these tasks end up in the
+			// incomplete count.
 			skipTasks++
-			successOrSkipTasks = append(successOrSkipTasks, rprt.PipelineTask.Name)
+			withStatusTasks = append(withStatusTasks, rprt.PipelineTask.Name)
+		case rprt.IsSuccessful():
+			withStatusTasks = append(withStatusTasks, rprt.PipelineTask.Name)
+		case isSkipped(rprt, stateAsMap, dag):
```
Comment (vdemeester) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:464]: nit: any reason for not having `rpr.IsSkipped(stateAsMap, dag)` here ?

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 3 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:537]: > Tasks are considered `skipped` (1) when its condition check fails and hence not executed and skipped (2) Or one of the parents is skipped. Tasks dependent on failed tasks are considered as `incomplete`.

Well, that's the logic I would like to change, i.e. recognize tasks that are going to be skipped as early as possible. This is useful when a pipeline is stopping, but it also gives a better indication to users about the actual incomplete. For instance finally tasks, would never go to skipped.

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:537]: > Is this something avoidable? marking a task skipped if one of the parents is failed or cancelled, this might interfere with `except` similar to `finally` but is invoked only when a task fails 🤔 .

Well, I'm not really marking the tasks, this computation is only used to decide what the overall status of the pipeline is, but not extra info is added into the pipeline state.

> `Pipeline` is anyways `stopped` or `paused` (may be better term), resume it where we left off and report failure. Just brainstorming here 💭 how does these changes impact pipeline run status?

I used stopping because I think it better reflects the fact that some tasks are still running. No new tasks are scheduled but something is still going on.
The pipeline status, as soon as a failure/task cancel occurs, is updated as follows:
- if other tasks are still running, the status remains "unknown", the reason is changed to "stopping"  and in the message "incomplete" tasks are counted as "skipped" as they will never be executed
- if no other task is running, the status is set to "failed", the reason is set to the appropriate one (failed or cancelled) and the message shows the final count of completed / failed / cancelled / skipped tasks

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 4 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:464]: No particular reason, it was like that before and I did not change it.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 3 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:537]: But I think I should remove the check for "failed/cancelled" parent from the `isSkipped` anyways, since it does not serve any purpose right now (it did in my initial version of the code):
- if the pipeline is running normally (no failure, no cancel), this check will add anything
- if the pipeline is stopping, the actual number of skipped is given by:
```
		case !rprt.IsStarted() && isStopping:
			// If the pipeline is in stopping mode, all tasks that are not running
			// already will be skipped. Otherwise these tasks end up in the
			// incomplete count.
			skipTasks++
			withStatusTasks = append(withStatusTasks, rprt.PipelineTask.Name) 
```

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go]: Ok, I pushed a new version that removed the changes to `isSkipped` but kept the unit test coverage for that. That way we can keep better track of the behaviour of that function independently of the `GetPipelineConditionStatus`

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go]: > Is this something avoidable? 

Just to confirm, yes, it is avoidable, and I removed it now. Thank you!

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 4 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:464]: There is a small advantage in having it like this because I can run `toMap` once, so I don't have to re-build the map for every single pipeline task.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 2 above)
Comment (pritidesai) [reply pkg/reconciler/pipelinerun/pipelinerun.go:437]: May be this could be simplified and keep it as is, instead change `GetNextTasks()` such that no tasks are returned if pipeline is in stopping mode:

```
func (state PipelineRunState) GetNextTasks(candidateTasks map[string]struct{}) []*ResolvedPipelineRunTask {
	tasks := []*ResolvedPipelineRunTask{}
	if state.IsStopping() {
		return tasks
	}
```

With an empty execution queue, everything from `runNextSchedulableTask` is escaped except `InitializeArtificatStorage` (could be surrounded by the condition)

Dont worry if you are not comfortable changing it, I will have to change it in `finally` PR, as final tasks have to be executed after pipeline is stopping and once all running tasks are done.

**Comment by pritidesai** [comment]
/lgtm

This PR will impact `finally` PR #2661, I am fine merging this before we merge `finally` PR, will incorporate necessary changes into that PR.
