### PR TITLE
entrypoint: in case of step command failure, write postfile

### LINKED ISSUE #682: If an init container in a TaskRun fails, entire TaskRun should fail
# Expected Behavior

If an init container in the `Pod` created for a `TaskRun` fails, then the subsequent steps/containers will not be able to run. Therefore in this case, the entire `TaskRun` should be marked as failed.

# Actual Behavior

If an init container fails, the `TaskRun` status makes it look like it is still executing (i.e. the status of the init containers is not taken into account when determining if the `TaskRun` has failed), e.g. this is the `status` of a `TaskRun` I created where the init container [that tried to checkout a GCS storage resource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#storage-resource) failed:

```bash
  status:
    conditions:
    - lastTransitionTime: "2019-03-26T22:49:55Z"
      reason: Building
      status: Unknown
      type: Succeeded
    podName: publish-run-pod-55cc64
    startTime: "2019-03-26T22:49:21Z"
    steps:
    - running:
        startedAt: "2019-03-26T22:49:39Z"
    - running:
        startedAt: "2019-03-26T22:49:40Z"
    - terminated:
        containerID: docker://0b40cffc7651cf781b8e4c0242377e3ca2499f9a0a0c572ced025b3f562ec643
        exitCode: 0
        finishedAt: "2019-03-26T22:49:27Z"
        reason: Completed
        startedAt: "2019-03-26T22:49:27Z"
    - running:
        startedAt: "2019-03-26T22:49:39Z"
    - running:
        startedAt: "2019-03-26T22:49:39Z"
    - terminated:
        containerID: docker://33fb0da5e4dadf73c2f9c8e4d62518d960ac71ce159f26286b1558766191302d
        exitCode: 1
        finishedAt: "2019-03-26T22:49:40Z"
        reason: Error
        startedAt: "2019-03-26T22:49:37Z"
    - running:
        startedAt: "2019-03-26T22:49:39Z"
    - running:
        startedAt: "2019-03-26T22:49:40Z"
    - running:
        startedAt: "2019-03-26T22:49:40Z"
    - running:
        startedAt: "2019-03-26T22:49:40Z"
    - terminated:
        containerID: docker://8deba837738b7303625824c64aaed620025ac58aeba44337a64be535ffe4d74a
        exitCode: 0
        finishedAt: "2019-03-26T22:49:41Z"
        reason: Completed
        startedAt: "2019-03-26T22:49:41Z"
```

The condition is:

```yaml
    conditions:
    - lastTransitionTime: "2019-03-26T22:49:55Z"
      reason: Building
      status: Unknown
      type: Succeeded
```

Yet the init container failed:

```yaml
    - terminated:
        containerID: docker://33fb0da5e4dadf73c2f9c8e4d62518d960ac71ce159f26286b1558766191302d
        exitCode: 1
        finishedAt: "2019-03-26T22:49:40Z"
        reason: Error
        startedAt: "2019-03-26T22:49:37Z"
```

(Note I ran into this because I tried to run [our release Task](https://github.com/tektoncd/pipeline/tree/master/tekton#running) and ran into https://github.com/tektoncd/pipeline/issues/646)

# Steps to Reproduce the Problem

1. Create a `Task` that takes a PipelineResource, e.g. a GCS storage resource
2. Create a `TaskRun` that points at a `PipelineResource` which will have an error, e.g. reproduce #646 by providing an empty bucket but using `dir` type

# Additional Info

When we switched away from using init containers for steps, the status was briefly completely broken. In #634 we updated this logic to look at container statuses instead of init containers - but it looks like we need to look at both (and our integration tests need to cover this).

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

The entrypoint package wraps the step commands and execute them. This
allows use to use pods containers with some order. In a step, the
entrypoint binary will wait for the file of the previous step to be
present to execute the actual command.

Before this change, if a command failed (`exit 1` or something),
entrypoint would not write a file, and thus the whole pod would be
stuck running (all the next step would wait forever).

This fixes that by always writing the post-file — and making
the *waiter* a bit smarter :

- it will now look for a `{postfile}.err` to detect if the previous
  step failed or not.
- if the previous steps failed, it will fail too without executing the
  step commands.

Closes #682 

cc @pivotal-nader-ziada 

<del>I need to update `pkg/entrypoint` unit tests though :angel: </del>

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if functionality changed/added)
- <del>[ ] Includes [docs](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if user facing)</del>
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

File: test/taskrun_test.go [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+	t.Logf("Creating Task and TaskRun in namespace %s", namespace)
+	task := tb.Task("failing-task", namespace, tb.TaskSpec(
+		tb.Step("hello", "busybox",
+			tb.Command("/bin/sh"), tb.Args("-c", "echo hello"),
+		),
+		tb.Step("exit", "busybox",
+			tb.Command("/bin/sh"), tb.Args("-c", "exit 1"),
+		),
+		tb.Step("world", "busybox",
+			tb.Command("/bin/sh"), tb.Args("-c", "sleep 20s"),
```
Comment (vdemeester) [inline test/taskrun_test.go]: Added this to detect if this step is executed or not :sweat_smile:

**Comment by abayer** [comment]
Nice!

/lgtm

File: test/taskrun_test.go [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+	taskRun := tb.TaskRun("failing-taskrun", namespace, tb.TaskRunSpec(
+		tb.TaskRunTaskRef("failing-task"),
+	))
+	if _, err := c.TaskRunClient.Create(taskRun); err != nil {
+		t.Fatalf("Failed to create TaskRun: %s", err)
+	}
+
+	t.Logf("Waiting for TaskRun in namespace %s to fail", namespace)
+	if err := WaitForTaskRunState(c, "failing-taskrun", TaskRunFailed("failing-taskrun"), "TaskRunFailed"); err != nil {
+		t.Errorf("Error waiting for TaskRun to finish: %s", err)
```
Comment (pivotal-nader-ziada) [inline test/taskrun_test.go]: would be nice to check the status of the `taskrun` after it failed and make sure step 2 has failure and step 3 didn't run. Before this fix, it was failing eventually by waiting for the default timeout, somehow if we can check that's not the failure reason.

File: cmd/entrypoint/main.go [hunk 3]
```diff
@@ -106,9 +116,6 @@ type RealPostWriter struct{}
 var _ entrypoint.PostWriter = (*RealPostWriter)(nil)
 
 func (*RealPostWriter) Write(file string) {
```
Comment (pivotal-nader-ziada) [inline cmd/entrypoint/main.go]: why do we not need the check that no post file is passed in?

File: cmd/entrypoint/main.go [hunk 4]
```diff
@@ -55,15 +71,20 @@ type RealWaiter struct{ waitFile string }
...
+		return nil
 	}
 	for ; ; time.Sleep(time.Second) {
+		// Watch for the post file
 		if _, err := os.Stat(file); err == nil {
-			return
+			return nil
 		} else if !os.IsNotExist(err) {
-			log.Fatalf("Waiting for %q: %v", file, err)
+			return fmt.Errorf("Waiting for %q: %v", file, err)
```
Comment (pivotal-nader-ziada) [inline cmd/entrypoint/main.go]: is this now going to return an error right away and make it not wait?

File: cmd/entrypoint/main.go [hunk 5]
```diff
@@ -36,15 +37,30 @@ var (
...
 		Entrypoint: *ep,
 		WaitFile:   *waitFile,
 		PostFile:   *postFile,
 		Args:       flag.Args(),
 		Waiter:     &RealWaiter{},
 		Runner:     &RealRunner{},
 		PostWriter: &RealPostWriter{},
-	}.Go()
+	}
+	if err := e.Go(); err != nil {
```
Comment (pivotal-nader-ziada) [inline cmd/entrypoint/main.go]: does this block of code make sense inside the `Go` func?

Comment (vdemeester) [reply cmd/entrypoint/main.go]: I initially thought of puting it there — but it meant it was harder to "test" the `Go` function as it would call `os.Exit`.

File: cmd/entrypoint/main.go (hunk 4 above)
Comment (vdemeester) [reply cmd/entrypoint/main.go]: It doesn't change the behavior as `log.Fatalf` would have called `os.Exit` (and killed the process). We just "control" where the `kill` happens :sweat_smile:

File: cmd/entrypoint/main.go (hunk 3 above)
Comment (vdemeester) [reply cmd/entrypoint/main.go]: Ah, good point, mistake on my part :sweat_smile:

File: test/taskrun_test.go (hunk 2 above)
Comment (vdemeester) [reply test/taskrun_test.go]: Right, good point, I should validate that all steps after the `exit 1` are terminated and in the same error state :angel:
That raise a question : in the case of steps being "skipped" because a previous one failed, should we return another exit code than the default `1` ? (to be able to detect such cases)

Comment (abayer) [reply test/taskrun_test.go]: If we do that, do we end up with confusion if a step exits with a non-0/1 exit code on purpose? I'd lean towards using `Reason` or `Message` rather than `ExitCode`.

Comment (vdemeester) [reply test/taskrun_test.go]: :thinking: it won't change the status of the `TaskRun`. It would only be useful to detect that some of the container didn't have to execute. We could also "copy" the exit code of the failed process to the later ones.

File: cmd/entrypoint/main.go (hunk 5 above)
Comment (pivotal-nader-ziada) [reply cmd/entrypoint/main.go]: fair enough :)

File: test/taskrun_test.go (hunk 2 above)
Comment (pivotal-nader-ziada) [reply test/taskrun_test.go]: not sure what the best option is, would be nice to know it didn't execute, anything here makes sense? http://tldp.org/LDP/abs/html/exitcodes.html

Comment (vdemeester) [reply test/taskrun_test.go]: We discussed quiclky with @abayer on slack : 

- `exit 0` on skipped containers (the one after the failure)
- updating the TaskRun status to point to the failed step
- updating the steps status with some skipped messages for the steps that were skip

Comment (pivotal-nader-ziada) [reply test/taskrun_test.go]: - exit 0 on skipped containers (the one after the failure) 👍 
 - updating the TaskRun status to point to the failed step 🤔 but is that an api change to add that? It already has an array of steps status which should contain the same info 
 - updating the steps status with some skipped messages for the steps that were skip 🤔 I wonder if we are over thinking this. If a step fails, that should be clear enough why the taskrun failed

Comment (vdemeester) [reply test/taskrun_test.go]: Ok, I'll go for exit code 0 in here (and make sure the TaskRun status references the correct step as a failure) — we have time to think about skip messages & co later on, in a follow-up.

**Comment by abayer** [comment]
@vdemeester So for now at least, we're not making any changes to the `TaskRunStatus.Steps`, right?

**Comment by vdemeester** [comment]
> @vdemeester So for now at least, we're not making any changes to the `TaskRunStatus.Steps`, right?

Indeed, for now, no change in there :wink:

**Comment by abayer** [comment]
Excellent. =)

/lgtm

**Comment by pivotal-nader-ziada** [comment]
nice work @vdemeester  🎉

**Comment by vdemeester** [comment]
I forgot to remove a piece of code :joy_cat:
