### PR TITLE
Replace `$(context...)` values in resolver parameters

### LINKED ISSUE #5475: PipelineRef resolver part doesn't support `context` variable replacement
# Expected Behavior

Using the following `PipelineRun` should create the following `ResolutionRequest`.

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: simple-pipelinerun
spec:
  pipelineRef:
    resolver: foo
    params:
    - name: bar
      value: $(context.pipelinerun.name)
---
apiVersion: resolution.tekton.dev/v1alpha1
kind: ResolutionRequest
metadata:
  labels:
    resolution.tekton.dev/type: foo
  name: foo-bf6f3d56876eb1d6948a50c52c0d1d87
spec:
  params:
    bar: simple-pipelinerun
```

# Actual Behavior

It doesn't *resolve* the `context.*` variable, resulting in the following `ResolutionRequest`.

```
apiVersion: resolution.tekton.dev/v1alpha1
kind: ResolutionRequest
metadata:
  labels:
    resolution.tekton.dev/type: foo
  name: foo-bf6f3d56876eb1d6948a50c52c0d1d87
spec:
  params:
    bar: $(context.pipelinerun.name)
```

# Steps to Reproduce the Problem

1. Create the above `PipelineRun`
2. See what `ResolutionRequest` it creates

# Additional Info

- Tekton Pipeline version: `main`

/assign @abayer

### PR DESCRIPTION
**Pull request by abayer**
# Changes

fixes #5475

I did not think of this previously, but now it works.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

File: pkg/reconciler/pipelinerun/resources/pipelineref.go [hunk 1]
```diff
@@ -74,6 +74,9 @@ func GetPipelineFunc(ctx context.Context, k8s kubernetes.Interface, tekton clien
 		return func(ctx context.Context, name string) (v1beta1.PipelineObject, error) {
 			params := map[string]string{}
 			stringReplacements, arrayReplacements, objectReplacements := paramsFromPipelineRun(ctx, pipelineRun)
+			for k, v := range getContextReplacements("", pipelineRun) {
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/resources/pipelineref.go:77]: Is it possible to get the Pipeline name here? Do all resolvers need a param that is the pipeline name, or can we not make that guarantee?

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelineref.go:77]: We can't make any guarantee, no, in almost all cases. In practice, the hub or bundles resolver params include what we expect will be the `Pipeline` name, but even then, we can't _guarantee_ it - the actual `Pipeline` could have a different name than its key, e.g. The cluster resolver does know the name, but the git resolver has no idea.

Comment (lbernick) [reply pkg/reconciler/pipelinerun/resources/pipelineref.go:77]: Could we add a new field to resolver for Pipeline name instead of passing it in as a param? I would imagine almost all resolvers would need it

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelineref.go:77]: I don't think we should - we never create an actual `Pipeline`, we just load the spec in to `PipelineRun.Spec.PipelineSpec`...

Comment (vdemeester) [reply pkg/reconciler/pipelinerun/resources/pipelineref.go:77]: I don't think we should either.

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelineref.go:77]: That and while the name happens to be a "key" for three of the current resolvers, there's no reason to assume that'll be the case for all or even necessarily a majority of future resolvers. Plus adding another `name`-related field to `pipelineRef`/`taskRef` would be pretty dang confusing.

Comment (lbernick) [reply pkg/reconciler/pipelinerun/resources/pipelineref.go:77]: ok, sounds good
