### PR TITLE
don't validate skipped task results for pipeline results

### LINKED ISSUE #6139: Pipeline failing with "invalid pipelineresults" when referencing results of skipped tasks
# Expected Behavior

According to the documentation pipeline results can contain references to task results. If a task did not run because of it's whenConditions, the pipeline result is not emitted but the pipeline succeeds. This worked with v0.37.5 of Tekton Pipelines available on OpenShift.

# Actual Behavior

With the update of the RedHat OpenShift Pipelines Operator, which brings Tekton Pipeline v0.41.0, pipelines with skipped tasks and composed results now fail with the message `invalid pipelineresults [result-goodbye], the referred results don't exist`.

# Steps to Reproduce the Problem

Run the following PipelineRun:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-test
spec:
  pipelineSpec:
    params:
      - name: say-hello
        default: 'false'
    tasks:
      - name: hello
        taskSpec:
          results:
            - name: result-one
          steps:
          - image: alpine
            script: |
              #!/bin/sh
              echo "Hello world!"
              echo -n "RES1" > $(results.result-one.path)
  
      - name: goodbye
        runAfter:
          - hello
        taskSpec:
          results:
            - name: result-two
          steps:
          - image: alpine
            script: |
              #!/bin/sh
              echo "Goodbye world!"
              echo -n "RES2" > $(results.result-two.path)
        when:
          - input: $(params.say-hello)
            operator: in
            values: ["true"]

    results:
      - name: result-hello
        description: Result one
        value: '$(tasks.hello.results.result-one)'
      - name: result-goodbye
        description: Result two
        value: '$(tasks.goodbye.results.result-two)'
```

# Additional Info

- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+a34b9e9", GitCommit:"b6d1f054747e9886f61dd85316deac3415e2726f", GitTreeState:"clean", BuildDate:"2023-01-10T15:55:28Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Pipeline version: v0.41.0
Triggers version: v0.22.0
Openshift Pipelines Version: 1.9.0
```

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes
This commit skip the validation for skipped task results in pipeline results. This fixes #6139. The skipped task results are not emitted by design thus we shouldn't validate if they are emitted. Pipeline results referenced to skipped task will not be emitted.

/kind bug

Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
A fix for regression issue that previously we don't fail the run when skipped task results don't emit, but failed when validation is introduced.
```

### CODE REVIEW

**Comment by Yongxuanzhang** [comment]
Hi @pritidesai @jerop , could you take a look at this PR?

File: pkg/reconciler/pipelinerun/resources/apply.go [hunk 1]
```diff
@@ -318,9 +318,14 @@ func replaceParamValues(params []v1beta1.Param, stringReplacements map[string]st
 func ApplyTaskResultsToPipelineResults(
 	results []v1beta1.PipelineResult,
 	taskRunResults map[string][]v1beta1.TaskRunResult,
-	customTaskResults map[string][]v1beta1.CustomRunResult) ([]v1beta1.PipelineRunResult, error) {
+	customTaskResults map[string][]v1beta1.CustomRunResult, skipTasks []v1beta1.SkippedTask) ([]v1beta1.PipelineRunResult, error) {
```
Comment (kyubisation) [inline pkg/reconciler/pipelinerun/resources/apply.go:321]: My comment might be wrong, but is this code correctly formatted like this?

**Review by kyubisation — APPROVED** [review]
Thank you very much for the quick fix! 😃 
I'm not very familiar with the code base, but from my perspective this looks good to me. 👍

File: pkg/reconciler/pipelinerun/resources/apply.go (hunk 1 above)
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/apply.go:321]:
```suggestion
	customTaskResults map[string][]v1beta1.CustomRunResult, 
	skippedTasks []v1beta1.SkippedTask) ([]v1beta1.PipelineRunResult, error) {
```

Comment (jerop) [reply pkg/reconciler/pipelinerun/resources/apply.go:321]: +1

File: pkg/reconciler/pipelinerun/resources/apply.go [hunk 2]
```diff
@@ -318,9 +318,14 @@ func replaceParamValues(params []v1beta1.Param, stringReplacements map[string]st
...
 	var runResults []v1beta1.PipelineRunResult
 	var invalidPipelineResults []string
+	skipTaskNames := map[string]bool{}
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/apply.go:324]:
```suggestion
	skippedTaskNames := map[string]bool{}
```

File: pkg/reconciler/pipelinerun/resources/apply.go [hunk 3]
```diff
@@ -341,6 +346,11 @@ func ApplyTaskResultsToPipelineResults(
 				continue
 			}
 			variableParts := strings.Split(variable, ".")
+			// if the referenced task is skipped, we should also skip the results replacements
+			// this fixes #6139
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/apply.go:350]: we don't need the reference to the issue in the codebase

**Comment by jerop** [comment]
please fix the typo in the pr title and commit message

File: pkg/reconciler/pipelinerun/resources/apply.go (hunk 1 above)
Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply.go:321]: Oh thanks!

File: pkg/reconciler/pipelinerun/resources/apply.go (hunk 3 above)
Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply.go]: Thanks! Fixed

**Review by jerop — COMMENTED** [review]
could it be more confusing for the pipeline result to remain as is - an unsubstituted reference to a task result? what if users assume pipeline results were produced by the pipeline, but then some are just the original references? wondering if we should just wait for https://github.com/tektoncd/community/pull/954?

also @Yongxuanzhang please add to the commit message that this change is not only removing validation, but also leaving pipeline results as the original unsubstituted references to task results when the task was skipped

**Comment by Yongxuanzhang** [comment]
> could it be more confusing for the pipeline result to remain as is - an unsubstituted reference to a task result? what if users assume pipeline results were produced by the pipeline, but then some are just the original references? wondering if we should just wait for [tektoncd/community#954](https://github.com/tektoncd/community/pull/954)?
> 
> also @Yongxuanzhang please add to the commit message that this change is not only removing validation, but also leaving pipeline results as the original unsubstituted references to task results when the task was skipped

This commit skips the validation of "skipped tasks", my understanding is that if users use "when expressions" on tasks and they should be aware of some results cannot be replaced if tasks are skipped as mentioned in https://tekton.dev/docs/pipelines/pipelines/#emitting-results-from-a-pipeline

**Comment by jerop** [comment]
> This commit skips the validation of "skipped tasks", my understanding is that if users use "when expressions" on tasks and they should be aware of some results cannot be replaced if tasks are skipped as mentioned in https://tekton.dev/docs/pipelines/pipelines/#emitting-results-from-a-pipeline

in that case, please update the documentation explaining it to users so it's not surprising to see unsubstituted references to task results in the pipeline results

**Comment by Yongxuanzhang** [comment]
> could it be more confusing for the pipeline result to remain as is - an unsubstituted reference to a task result? what if users assume pipeline results were produced by the pipeline, but then some are just the original references? wondering if we should just wait for [tektoncd/community#954](https://github.com/tektoncd/community/pull/954)?
> 
> also @Yongxuanzhang please add to the commit message that this change is not only removing validation, but also leaving pipeline results as the original unsubstituted references to task results when the task was skipped

This commit should be compatible with https://github.com/tektoncd/community/pull/954? 
Another reason is it may take unexpected longer time to wait  https://github.com/tektoncd/community/pull/954 is implemented

**Comment by Yongxuanzhang** [comment]
> > This commit skips the validation of "skipped tasks", my understanding is that if users use "when expressions" on tasks and they should be aware of some results cannot be replaced if tasks are skipped as mentioned in https://tekton.dev/docs/pipelines/pipelines/#emitting-results-from-a-pipeline
> 
> in that case, please update the documentation explaining it to users so it's not surprising to see unsubstituted references to task results in the pipeline results

That makes sense! I added a note into the doc I linked

File: pkg/reconciler/pipelinerun/resources/apply.go [hunk 4]
```diff
@@ -318,9 +318,15 @@ func replaceParamValues(params []v1beta1.Param, stringReplacements map[string]st
...
-	customTaskResults map[string][]v1beta1.CustomRunResult) ([]v1beta1.PipelineRunResult, error) {
+	customTaskResults map[string][]v1beta1.CustomRunResult,
+	skippedTasks []v1beta1.SkippedTask) ([]v1beta1.PipelineRunResult, error) {
 	var runResults []v1beta1.PipelineRunResult
 	var invalidPipelineResults []string
+	skippedTaskNames := map[string]bool{}
+	for _, t := range skippedTasks {
+		skippedTaskNames[t.Name] = true
+	}
+
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/apply.go:329]: can we please add a log message or something to communicate to users that a pipelineresult references a skipped taskresult so the value cannot be substituted?

Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply.go:329]: sure

Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply.go:331]: added a log message when we skip the skipped task result reference

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/apply.go:331]: The controller log file won't typically be accessible by users, and having a log entry in the "info" level about this feels like something that might spam logs if users often skipped tasks. I would rather have a debug log level here.

If we want to let users know about this, perhaps we could replace the result reference (or extend it) with a comment, saying that the result is not available as the task was skipped, but I'm not sure if that'd be a good idea.

File: pkg/reconciler/pipelinerun/resources/apply.go [hunk 5]
```diff
@@ -341,6 +349,11 @@ func ApplyTaskResultsToPipelineResults(
 				continue
 			}
 			variableParts := strings.Split(variable, ".")
+			// if the referenced task is skipped, we should also skip the results replacements
+			if _, ok := skippedTaskNames[variableParts[1]]; ok {
```
Comment (afrittoli) [inline pkg/reconciler/pipelinerun/resources/apply.go:353]: Not something to be changed in this PR, but I wonder if having constants for the various indexes of parts and a function for the split would make this code more readable? Like, 

```golang
variableParts := splitResultVariable(variable)
skippedTaskNames[variableParts[VARIABLE_RESULT_TASK_NAME_INDEX]]
```

**Review by afrittoli — COMMENTED** [review]
Thanks for this. It might be worth adding something in the release notes for this change.
The code looks good, the only small question I have is about the log at info level 🙏

File: pkg/reconciler/pipelinerun/resources/apply.go (hunk 5 above)
Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply.go:353]: That makes sense, I can fix this

**Comment by Yongxuanzhang** [comment]
> Thanks for this. It might be worth adding something in the release notes for this change. The code looks good, the only small question I have is about the log at info level 🙏

Thanks! I will also bring this PR to the slack and/or our wg. I think we need to collect more feedback of how to deal with skipped task results.

**Comment by kyubisation** [comment]
Is it possible to provide an estimate on when this will be merged?
Unfortunately due to #6139 we are blocked in upgrading our Tekton setup and we would be very grateful for this fix.

**Comment by Yongxuanzhang** [comment]
> Is it possible to provide an estimate on when this will be merged? Unfortunately due to #6139 we are blocked in upgrading our Tekton setup and we would be very grateful for this fix.

Thanks for the reminder! I will bring this up today during the community working group.

**Comment by pritidesai** [comment]
Please update the release notes elaborating its a fix for a regression issue, thanks!

File: pkg/reconciler/pipelinerun/resources/apply.go (hunk 4 above)
Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply.go:329]: Oh sorry I missed your comment! @afrittoli 
I will change this to debug level log.

File: docs/pipelines.md [hunk 6]
```diff
@@ -1079,6 +1079,7 @@ This will cause an `InvalidTaskResultReference` validation error during `Pipelin
 
 **Note:** Since a `Pipeline Result` can contain references to multiple `Task Results`, if any of those
 `Task Result` references are invalid the entire `Pipeline Result` is not emitted.
+**Note:** If a `PipelineTask` referenced by the `Pipeline Result` was skipped, the `Pipeline Result` will remain as the original unsubstituted references.
```
Comment (lbernick) [inline docs/pipelines.md:1082]:
```suggestion
**Note:** If a `PipelineTask` referenced by the `Pipeline Result` was skipped, the `Pipeline Result` will remain as the original unsubstituted references and the `PipelineRun` will not fail due to a missing result.
```

File: pkg/reconciler/pipelinerun/resources/apply.go [hunk 7]
```diff
@@ -315,9 +317,16 @@ func replaceParamValues(params []v1beta1.Param, stringReplacements map[string]st
 func ApplyTaskResultsToPipelineResults(
 	results []v1beta1.PipelineResult,
 	taskRunResults map[string][]v1beta1.TaskRunResult,
-	customTaskResults map[string][]v1beta1.CustomRunResult) ([]v1beta1.PipelineRunResult, error) {
+	customTaskResults map[string][]v1beta1.CustomRunResult,
+	skippedTasks []v1beta1.SkippedTask,
+	logger *zap.SugaredLogger) ([]v1beta1.PipelineRunResult, error) {
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/resources/apply.go:322]: nit: I think it would be a bit cleaner to get the logger from the context instead of passing it in as a param (more consistent with the rest of the codebase)

File: pkg/reconciler/pipelinerun/resources/apply_test.go [hunk 8]
```diff
@@ -3131,7 +3132,7 @@ func TestApplyFinallyResultsToPipelineResults(t *testing.T) {
 		},
 	} {
 		t.Run(tc.description, func(t *testing.T) {
-			received, _ := ApplyTaskResultsToPipelineResults(tc.results, tc.taskResults, tc.runResults)
+			received, _ := ApplyTaskResultsToPipelineResults(tc.results, tc.taskResults, tc.runResults, nil, logtesting.TestLogger(t))
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/resources/apply_test.go:3135]:
```suggestion
			received, _ := ApplyTaskResultsToPipelineResults(tc.results, tc.taskResults, tc.runResults, nil /* skippedTasks */, logtesting.TestLogger(t))
```

File: pkg/reconciler/pipelinerun/resources/apply_test.go [hunk 9]
```diff
@@ -3599,9 +3601,34 @@ func TestApplyTaskResultsToPipelineResults(t *testing.T) {
...
+		taskResults: map[string][]v1beta1.TaskRunResult{
+			"normaltask": {{
+				Name:  "baz",
+				Value: *v1beta1.NewStructuredValues("rae"),
+			}},
+		},
+		skippedTasks: []v1beta1.SkippedTask{{
+			Name: "skippedTask",
+		}},
+		expectedResults: []v1beta1.PipelineRunResult{{
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/resources/apply_test.go:3622]: What output results existed prior to this regression? Was it just a non-replaced result expression? or was there no pipeline result? (based on the linked issue it looks like the latter.) I think an absent Pipeline result might make more sense than a Pipeline result like "$(tasks.skippedTask.results.foo)".

(everything else is mostly a nit but let's verify this)

**Review by lbernick — COMMENTED** [review]
I think it would be worth adding a reconciler unit test or an integration test with a full pipelinerun spec with skipped results

File: docs/pipelines.md (hunk 6 above)
Comment (Yongxuanzhang) [reply docs/pipelines.md:1082]: Thank you!

File: pkg/reconciler/pipelinerun/resources/apply.go (hunk 7 above)
Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply.go:322]: Oh I see, thanks! Fixed!

File: pkg/reconciler/pipelinerun/resources/apply_test.go (hunk 9 above)
Comment (Yongxuanzhang) [reply pkg/reconciler/pipelinerun/resources/apply_test.go:3621]: Ah yes this is a great point! When I implemented this fix I didn't check the previous behaviour. I checked the previous version and there are no results if the task is skipped. We should definitely keep the previous behaviour otherwise this will be another issue

**Review by afrittoli — COMMENTED** [review]
Thank you for all the updates!
/approve

**Comment by lbernick** [comment]
/lgtm

I think we'll need to cherry pick this to all the releases after v0.37 we currently support-- which is v0.41-v0.45 :( (Although v0.45 EOL is tomorrow)
