### PR TITLE
Resolve Entrypoint and Cmd if there is no command and no args

### LINKED ISSUE #4794: Task does not run the CMD of the Dockerfile
# Expected Behavior
If I do not specify the the `command` and `args` for a Task's container, then I expect the Task to default to the Dockerfile's CMD.

# Actual Behavior
The Task runs the Dockerfile's ENTRYPOINT command(s), without running the Dockerfile's CMD.

# Steps to Reproduce the Problem

1. Pick an image that has a CMD, such as `bitnami/express:latest`, and use it as the image for a Task.
2. Run the Task

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version:

  **v0.30.0**

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Prior to this change, if a Step specify neither `command` nor `args`,
the entrypoint resolver would only resolve the image `Entrypoint` and
thus, only executing that entrypoint. This is confusing to user as it
is not how a `docker run` without args produces.

This make the behavior very close to `docker run`. If there is no
command and no args specified, the entrypoint reslover will join the
image `Entrypoint` and `Cmd`.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind bug

Fixes #4794

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
The entrypoint resolve will now reslove `Entrypoint` and `Cmd` in case
the steps has no command and no args specified.
```

### CODE REVIEW

File: pkg/pod/entrypoint_lookup_impl_test.go [hunk 1]
```diff
@@ -254,11 +256,55 @@ func TestBuildCommandMap(t *testing.T) {
...
+		wantCmd: []string{"my", "entrypoint", "my", "cmd"},
+	}} {
+		t.Run(c.desc, func(t *testing.T) {
+			cmd, _, err := imageInfo(c.img, c.hasArgs)
+			if err != nil {
+				t.Fatalf("got err: %v", err)
+			}
+			if d := cmp.Diff(cmd, c.wantCmd); d != "" {
+				t.Errorf("Diff cmd %s", diff.PrintWantGot(d))
+			}
```
Comment (imjasonh) [inline pkg/pod/entrypoint_lookup_impl_test.go:307]:
```suggestion
			if d := cmp.Diff(c.wantCmd, cmd); d != "" {
				t.Errorf("Diff cmd %s", diff.PrintWantGot(d))
			}
```

Right? 🤔

Comment (vdemeester) [reply pkg/pod/entrypoint_lookup_impl_test.go:307]: @imjasonh lol.. I always forget in which order to put them 😅
