### PR TITLE
Validate PipelineTask name as Task names 📛

### LINKED ISSUE #2095: PipelineTask Names Can Be Created That Violate TaskRun Naming Rules
When creating a Pipeline that has PipelineTasks, you can give each PipelineTask a name that differs from a TaskRef's name:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sleep-pipeline
  labels:
    app: tekton-workshop
spec:
  tasks:
  - name: pipelineTask1
    taskRef:
      kind: Task
      name: sleep1s
  - name: pipelineTask2
    taskRef:
      kind: Task
      name: sleep10s
```

The PipelineTask names can include capital letters, such as in the example above. If someone does this, the TaskRuns associated with the PipelineRun for the Pipeline above will get the following error:

```
Warning  TaskRunCreationFailed  109s                pipeline-controller  Failed to create TaskRun "sleep-pipeline-run-pvs5c-pipelineTask1-6wjd6": TaskRun.tekton.dev "sleep-pipeline-run-pvs5c-pipelineTask1-6wjd6" is invalid: metadata.name: Invalid value: "sleep-pipeline-run-pvs5c-pipelineTask1-6wjd6": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
  Warning  TaskRunCreationFailed  109s
```

This error above occurs since TaskRun names must be lowercase, but PipelineTasks are allowed to be capitalized. 

This will actually cause the PipelineRun to continue running until it times out after an hour. 

# Expected Behavior

Similar to what is done for Tasks, the Pipeline above should be rejected since the PipelineTask names don't follow the rules of how TaskRun names are specified:

```
The Task "sleeP10s" is invalid: metadata.name: Invalid value: "sleeP10s": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

# Actual Behavior

The error above.

# Steps to Reproduce the Problem

1. Create a Pipeline with PipelineTask names with capital letters
2. Try to run the Pipeline

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

As reported, a `Pipeline` task name (`Pipelinetask`) can be created
that will violate `TaskRun` naming rules, making it fail at runtime.

This changes this by validation PipelineTask name the same way we
validation `TaskRun` names, to make sure we won't fail for this at
runtime.

Closes #2095 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @bobcatfish @afrittoli @danielhelfand 
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Validate PipelineTask name as Task names
```

### CODE REVIEW

File: pkg/apis/pipeline/v1alpha1/pipeline_validation.go [hunk 1]
```diff
@@ -138,6 +138,13 @@ func (ps *PipelineSpec) Validate(ctx context.Context) *apis.FieldError {
 	// Names cannot be duplicated
 	taskNames := map[string]struct{}{}
 	for i, t := range ps.Tasks {
+		if errs := validation.IsDNS1123Label(t.Name); len(errs) > 0 {
+			return &apis.FieldError{
+				Message: fmt.Sprintf("invalid value %q", t.Name),
+				Paths:   []string{fmt.Sprintf("spec.tasks[%d].name", i)},
+				Details: "Pipeline Task step name must be a valid DNS Label, For more info refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
```
Comment (danielhelfand) [inline pkg/apis/pipeline/v1alpha1/pipeline_validation.go]: Do we want the error message to be consistent with Task?

```
The Task "FooTask" is invalid: metadata.name: Invalid value: "FooTask": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Remove `step` after `Pipeline Task`:

```suggestion
				Details: "Pipeline Task name must be a valid DNS Label. For more info refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
```

Comment (danielhelfand) [reply pkg/apis/pipeline/v1alpha1/pipeline_validation.go]: Seeing there was another push here, but I am not seeing an update to the error message.

My thought is to make it so the error message here is consistent with what is shown for a Task that a user tries to create the violates naming conventions.

**Comment by danielhelfand** [comment]
@vdemeester Can this comments below be addressed before this goes in?

> Do we want the error message to be consistent with Task?
> 
> ```
> The Task "FooTask" is invalid: metadata.name: Invalid value: "FooTask": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
> ```
>
