### PR TITLE
Do not fail PipelineRun if pvc creation error is because of exceeded quotas

### LINKED ISSUE #7672: `volumeClaimTemplate` and exceeded quota for PVC (and requeues ?)
In case of using `volumeClaimTemplate` in a PipelineRun (or TaskRun), the controller is responsible to create the PVC.
If there is resource quota in place in the namespace, and if the quota are exceeded, the creation of the PVC will fail, and thus, the PipelineRun (or TaskRun) will fail immediately.

```
Failed to create PVC for PipelineRun caas-ocp-tf-prod/caas-ocp-gcp-1031-terraform-preprod-vjpcw correctly: PVC creation error: failed to create PVC pvc-f4c248dec1: persistentvolumeclaims "pvc-f4c248dec1" is forbidden: exceeded quota: caas-ocp-tf-prod-compute-resources, requested: persistentvolumeclaims=1, used: persistentvolumeclaims=20, limited: persistentvolumeclaims=20
```

This is a slightly inconsistent behavior compared to other objects and I feel we could do a better job here. Nothing should prevent us to requeue the PipelineRun or TaskRun (and pray for the quota to be free now).

What we could do:
- Change the error (permanent today) to a non permanent error
- Tell the controller to requeue that object in a minute or so (we could make this configurable, maybe ?)
- Either define a configurable timeout for this, or let the PipelineRun/TaskRun timeout do its job here. *Something to check is, do we start the timeout counter before or after trying to create the PVC, because depending on that, we may have to handle timeouts differently*.

cc @tektoncd/core-maintainers

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

In case of the PVC creation (from volumeclaimtemplate) is due to a
quota error (quota exceeded), do not fail with a permanent error, and
instead mark the PipelineRun as pending. Once there is some quota
available back, it will be able to start.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

Closes #7672

/kind feature

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
PipelineRun do not fail anymore if the pvc creation is due to an exceeded quota ; it will be requeued instead (until quota is available or it times out)
```

### CODE REVIEW

**Comment by vdemeester** [comment]
/wip
I need to update/create some e2e tests and makes sure it times out.

**Comment by vdemeester** [comment]
Timeout is taken into account 👼🏼

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 1]
```diff
@@ -73,14 +80,20 @@ func (c *defaultPVCHandler) CreatePVCFromVolumeClaimTemplate(ctx context.Context
 			if apierrors.IsAlreadyExists(err) {
```
Comment (twoGiants) [inline pkg/reconciler/volumeclaim/pvchandler.go:80]: _Optional:_ We could use the chance to untangle the conditions a bit. If you pick this suggestion the comment right below can be skipped :).


```suggestion
	_, getErr := c.clientset.CoreV1().PersistentVolumeClaims(claim.Namespace).Get(ctx, claim.Name, metav1.GetOptions{})
	switch {
	case apierrors.IsNotFound(getErr):
		_, createErr := c.clientset.CoreV1().PersistentVolumeClaims(claim.Namespace).Create(ctx, claim, metav1.CreateOptions{})
		if createErr == nil {
			c.logger.Infof("Created PersistentVolumeClaim %s in namespace %s", claim.Name, claim.Namespace)
			return nil
		}

		if apierrors.IsAlreadyExists(createErr) {
			c.logger.Infof("Tried to create PersistentVolumeClaim %s in namespace %s, but it already exists",
				claim.Name, claim.Namespace)
			return nil
		}

		// This is a retry-able error
		if apierrors.IsForbidden(createErr) && strings.Contains(createErr.Error(), "exceeded quota") {
			return fmt.Errorf("%w: %v", ErrPvcCreationFailedRetryable, createErr.Error())
		}

		return fmt.Errorf("%w for %s: %w", ErrPvcCreationFailed, claim.Name, createErr)
	case getErr != nil:
		return fmt.Errorf("%w: failed to retrieve PVC %s: %w", ErrPvcCreationFailed, claim.Name, getErr)
	}
}
```

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 2]
```diff
@@ -73,14 +80,20 @@ func (c *defaultPVCHandler) CreatePVCFromVolumeClaimTemplate(ctx context.Context
...
 				c.logger.Infof("Tried to create PersistentVolumeClaim %s in namespace %s, but it already exists",
 					claim.Name, claim.Namespace)
+			} else if apierrors.IsForbidden(err) {
+				if strings.Contains(err.Error(), "exceeded quota") {
+					// This is a retry-able error
+					return fmt.Errorf("%w: %v", ErrPvcCreationFailedRetryable, err.Error())
+				}
+				return fmt.Errorf("%w for %s: %w", ErrPvcCreationFailed, claim.Name, err)
```
Comment (twoGiants) [inline pkg/reconciler/volumeclaim/pvchandler.go]: This return and the one in the `else` right after can be simplified.


```suggestion
			} else if apierrors.IsForbidden(err) && strings.Contains(err.Error(), "exceeded quota") {
       			// This is a retry-able error
				return fmt.Errorf("%w: %v", ErrPvcCreationFailedRetryable, err.Error())
			}
			return fmt.Errorf("%w for %s: %w", ErrPvcCreationFailed, claim.Name, err)

```

File: pkg/reconciler/volumeclaim/pvchandler.go
Comment (twoGiants) [inline pkg/reconciler/volumeclaim/pvchandler.go:1]: Unit tests for the new conditional logic in `CreatePVCFromVolumeClaimTemplate` should be added.

File: pkg/reconciler/pipelinerun/affinity_assistant.go [hunk 3]
```diff
@@ -50,7 +50,8 @@ const (
 )
 
 var (
-	ErrPvcCreationFailed               = errors.New("PVC creation error")
+	ErrPvcCreationFailed               = volumeclaim.ErrPvcCreationFailed
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/affinity_assistant.go]: I wouldn't re-declare them here if they are already declared in `volumeclaim` and public. You don't use them in this file anyway.

File: pkg/reconciler/pipelinerun/affinity_assistant_test.go [hunk 4]
```diff
@@ -577,54 +577,56 @@ func TestCreateOrUpdateAffinityAssistantsAndPVCs_Failure(t *testing.T) {
 		name:        "pvc creation failed - per workspace",
 		failureType: "pvc",
 		aaBehavior:  aa.AffinityAssistantPerWorkspace,
-		expectedErr: fmt.Errorf("%w: failed to create PVC pvc-b9eea16dce: error creating persistentvolumeclaims", ErrPvcCreationFailed),
+		expectedErr: fmt.Errorf("%w for pvc-b9eea16dce: error creating persistentvolumeclaims", ErrPvcCreationFailed),
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/affinity_assistant_test.go:580]: You could use `volumeclaim.ErrPvcCreationFailed` instead, then you don't need to re-declare them in `affinity_assistant.go`.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 5]
```diff
@@ -755,6 +755,10 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1.PipelineRun, getPipel
 				pr.Status.MarkFailed(volumeclaim.ReasonCouldntCreateWorkspacePVC,
 					"Failed to create PVC for PipelineRun %s/%s correctly: %s",
 					pr.Namespace, pr.Name, err)
+			case errors.Is(err, ErrPvcCreationFailedRetryable):
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/pipelinerun.go]: Here I would also use it from `volumeclaim.ErrPvcCreationFailed`.

**Review by twoGiants — CHANGES_REQUESTED** [review]
Good job, it makes sense to set the status to pending and let it retry 😸 👍. 

Now it will re-queue right away. Do you want to make it configurable at some point like suggested in the issue?

My comments are below. I would add unit tests, simplify the conditional logic and remove the re-declaration of the errors in `affinity_assistant.go`.

File: pkg/reconciler/pipelinerun/affinity_assistant.go (hunk 3 above)
Comment (vdemeester) [reply pkg/reconciler/pipelinerun/affinity_assistant.go]: @twoGiants this was more to not break anyone using those outside of the package as it is exported. I think this is the var referred by the `pipelinerun.go` reconciler code and I didn't want to change it - but it can apply to external users as well.

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 6]
```diff
@@ -77,15 +77,44 @@ func (c *defaultPVCHandler) CreatePVCFromVolumeClaimTemplate(ctx context.Context
...
+		if apierrors.IsAlreadyExists(createErr) {
+			c.logger.Infof("Tried to create PersistentVolumeClaim %s in namespace %s, but it already exists",
+				claim.Name, claim.Namespace)
+			return nil
+		}
+
+		// This is a retry-able error
+		if apierrors.IsForbidden(createErr) && strings.Contains(createErr.Error(), "exceeded quota") {
+			return fmt.Errorf("%w: %v", ErrPvcCreationFailedRetryable, createErr.Error())
+		}
```
Comment (aThorp96) [inline pkg/reconciler/volumeclaim/pvchandler.go]: Would it make sense to also include `apierrors.IsConflict()` if the conflict is not on the PVC itself? For example if there is a conflict updating a PVC Resource Quota

Comment (khrm) [reply pkg/reconciler/volumeclaim/pvchandler.go]: Yes, it makes sense to include this. 
We need to include it separately in switch case also.

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 7]
```diff
@@ -70,17 +77,52 @@ func (c *defaultPVCHandler) CreatePVCFromVolumeClaimTemplate(ctx context.Context
...
+
+		if apierrors.IsAlreadyExists(createErr) {
+			c.logger.Infof("Tried to create PersistentVolumeClaim %s in namespace %s, but it already exists",
+				claim.Name, claim.Namespace)
+			return nil
+		}
+
+		// This is a retry-able error
+		if apierrors.IsForbidden(createErr) && strings.Contains(createErr.Error(), "exceeded quota") {
```
Comment (waveywaves) [inline pkg/reconciler/volumeclaim/pvchandler.go]: this check can be put in a function called `isRetryableError(createErr)` as this check is being used more than once.

```
func isRetryableError(err error) bool {
  if apierrors.IsForbidden(err) && strings.Contains(err.Error(), "exceeded quota") {
    return true
  }
  return false
}
```

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 8]
```diff
@@ -70,17 +77,52 @@ func (c *defaultPVCHandler) CreatePVCFromVolumeClaimTemplate(ctx context.Context
...
+	}
+}
 				c.logger.Infof("Tried to create PersistentVolumeClaim %s in namespace %s, but it already exists",
 					claim.Name, claim.Namespace)
+			} else if apierrors.IsForbidden(err) {
+				if strings.Contains(err.Error(), "exceeded quota") {
+					// This is a retry-able error
+					return fmt.Errorf("%w: %v", ErrPvcCreationFailedRetryable, err.Error())
+				}
+			} else if apierrors.IsForbidden(err) && strings.Contains(err.Error(), "exceeded quota") {
```
Comment (waveywaves) [inline pkg/reconciler/volumeclaim/pvchandler.go]: same as the above comment related to using a function to applying this check like `isRetryableError(err)`

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 9]
```diff
@@ -70,17 +77,52 @@ func (c *defaultPVCHandler) CreatePVCFromVolumeClaimTemplate(ctx context.Context
 	case apierrors.IsNotFound(err):
 		_, err := c.clientset.CoreV1().PersistentVolumeClaims(claim.Namespace).Create(ctx, claim, metav1.CreateOptions{})
 		if err != nil {
-			if apierrors.IsAlreadyExists(err) {
+	_, getErr := c.clientset.CoreV1().PersistentVolumeClaims(claim.Namespace).Get(ctx, claim.Name, metav1.GetOptions{})
```
Comment (waveywaves) [inline pkg/reconciler/volumeclaim/pvchandler.go]: here we are running the GET api call and then the CREATE if the PVC is not found, is it possible to do just the CREATE and if already exists the return nil, we will be reducing network calls as well this way

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 10]
```diff
@@ -755,6 +755,10 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1.PipelineRun, getPipel
...
+				logger.Errorf("Failed to create PVC for PipelineRun %s: %v", pr.Name, err)
+				pr.Status.MarkRunning(ReasonPending, "Waiting for PVC creation to succeed: %v", err)
```
Comment (waveywaves) [inline pkg/reconciler/pipelinerun/pipelinerun.go:763]: So, we will keep retrying until the pipeline run timeout, right? Is it possible to set a different timeout and possibly a backoff for retries of PVC creation? Also, should we track retry attempts to avoid infinite loops if quota never becomes available? The latter part can be covered in another PR if it's out of scope for this one.

Comment (vdemeester) [reply pkg/reconciler/pipelinerun/pipelinerun.go:763]: Yes, right now we retry until it times out, either the default timeout or the specified one.

I think we should create an issue to work on some back-off retry and different timeout specifically for this.

File: pkg/reconciler/volumeclaim/pvchandler.go (hunk 6 above)
Comment (vdemeester) [reply pkg/reconciler/volumeclaim/pvchandler.go]: I am not sure I fully follow 🤔

Comment (aThorp96) [reply pkg/reconciler/volumeclaim/pvchandler.go]: `apierrors.IsConflict()` will return true if the error is due to a conflict. The only hangup with just checking `apierrors.IsConflict()` is that it could mean the PVC itself had a conflict on creation, which may or may not be retryable (e.g. on a name conflict) so I don't know if it's completely safe to just retry on any conflict error. However I believe we can be sure the error is retryable if the conflict was not on the PVC resource itself. On a [StatusError](https://godocs.io/k8s.io/apimachinery/pkg/api/errors#StatusError)  this is accessible with `statusErr.Status().Details` via the [Kind and/or Group](https://godocs.io/k8s.io/apimachinery/pkg/apis/meta/v1#StatusDetails) fields. Might just be fine to retry all conflict errors too though, since `CreatePVCFromVolumeClaimTemplate` won't recreate the PVC if one already exists.

Either way, retrying on conflicts ensures we retry if for example there is a conflict updating tangential resources such as a ResourceQuota

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 11]
```diff
@@ -168,3 +178,10 @@ func getPersistentVolumeClaimIdentity(workspaceName, ownerName string) string {
 	hashString := hex.EncodeToString(hashBytes[:])
 	return hashString[:10]
 }
+
+func isRetryableError(err error) bool {
+	if apierrors.IsForbidden(err) && strings.Contains(err.Error(), "exceeded quota") {
```
Comment (khrm) [inline pkg/reconciler/volumeclaim/pvchandler.go:183]:
```suggestion
if (apierrors.IsForbidden(createErr) && strings.Contains(createErr.Error(), "exceeded quota")) || apierrors.IsConflict(createErr) { 
```

Comment (khrm) [inline pkg/reconciler/volumeclaim/pvchandler.go]:
```suggestion
	if (apierrors.IsForbidden(createErr) && strings.Contains(createErr.Error(), "exceeded quota")) || apierrors.IsConflict(createErr) { 
```

Comment (khrm) [reply pkg/reconciler/volumeclaim/pvchandler.go]: @vdemeester I meant this. This is also a retryable error.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 10 above)
Comment (waveywaves) [reply pkg/reconciler/pipelinerun/pipelinerun.go:763]: created an issue for this https://github.com/tektoncd/pipeline/issues/8981

File: pkg/reconciler/volumeclaim/pvchandler.go (hunk 6 above)
Comment (aThorp96) [reply pkg/reconciler/volumeclaim/pvchandler.go]: GH won't let me mark this as "resolved" since it's just a comment, but it's been addressed: https://github.com/tektoncd/pipeline/pull/8903/files#diff-84c34cf80deed4f1e6c26d944802b4aeb0db366b28a188477463d66bcfa9439dR183

**Review by waveywaves — APPROVED** [review]

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by aThorp96** [comment]
I believe the `isConflict()` addition here is necessary because of this kubernetes bug: https://github.com/kubernetes/kubernetes/issues/67761
