### PR TITLE
Call `gcloud auth activate-service-account` if GOOGLE_APPLICATION_CREDENTIALS is set

### LINKED ISSUE #1748: Insufficient Permission error when using a gcs PipelineResource
# Expected Behavior

We have a PipelineRun that outputs to a storage resource of type `gcs`. We authenticate this PipelineResource with a secret in the spec that looks like this:

```
  secrets:
    - fieldName: GOOGLE_APPLICATION_CREDENTIALS
      secretName: bucket-sa
      secretKey: ci-service.json
```

This has worked since we rolled out v0.7.0. We upgraded from v0.8.0 to v0.9.0 expecting this behavior to continue to work.

# Actual Behavior

After upgrading to v0.9.0, our PipelineRun started to fail when uploading this resource. I spent a while double checking our configuration. If I roll back to v0.8.0 everything would work again.

The error we see in the logs from the upload step is: 

```
ResumableUploadAbortException: 403 Insufficient Permission
```

# Steps to Reproduce the Problem

1. Create a PipelineResource that utilizes a GOOGLE_APPLICATION_CREDENTIALS secret to upload to a GCS bucket and try to upload to it

# Additional Info

I created a test TaskRun with the PipelineResource and made a previous step `sleep` indefinitely. I then connected into the  upload step. There is an environment variable for the secret specified above:

```
GOOGLE_APPLICATION_CREDENTIALS=/var/secret/bucket-sa/ci-service.json
```

However when I run `gcloud auth list` the service account in that key is not listed as available, only the k8s service account the pod is configured to use is available. A `gsutil cp` to the bucket test confirms insufficient permissions. If I run

```
gsutil auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
```

The test `gsutil cp` will then work as expected.

After googling a bit, I found GoogleCloudPlatform/cloud-sdk-docker#152 which is later referenced by tektoncd/pipeline#402 that was resolved by 2021783dd958054fe9cf5cc2584d5b731b9c1e09. 

The code for that change was removed in #1504 and it seems like there was no replacement for the `activate-service-account` behavior put back in place.

### PR DESCRIPTION
**Pull request by ImJasonH**
This used to be done by our own gsutil image. When that image was replaced
by the vanilla `google/cloud-sdk` image, this documented behavior broke.

By adding this as a step added by the resource, the behavior is
maintained without needing to maintain our own image to perform
activation.

Fixes #1748
/hold needs e2e test
cc @dustym

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Fix regression in v0.9 whereby GOOGLE_APPLICATION_CREDENTIALS were ignored when using the GCS resource
```

### CODE REVIEW

File: pkg/apis/pipeline/v1alpha1/gcs_resource_test.go [hunk 1]
```diff
@@ -26,7 +26,14 @@ import (
 	corev1 "k8s.io/api/core/v1"
 )
 
-func Test_Invalid_NewStorageResource(t *testing.T) {
+const activateServiceAccountScript = `#!/usr/bin/env bash
```
Comment (ImJasonH) [inline pkg/apis/pipeline/v1alpha1/gcs_resource_test.go]: NB: This is copied here because the other version is not exported (and shouldn't be), and tests are in `package v1alpha1_test`.

Is there a preferred way to maintain these invariants together?

Comment (vdemeester) [reply pkg/apis/pipeline/v1alpha1/gcs_resource_test.go]: Should this be in an external package ? (as it's solely related to `gcs`, maybe it should be in the `apis` package at all ?

Comment (ImJasonH) [reply pkg/apis/pipeline/v1alpha1/gcs_resource_test.go]: I'd like it not to be exported anywhere at all. But I guess if I have to, a separate package is better.

At least when resources are pluggable all this will leave this repo, right?

Comment (vdemeester) [reply pkg/apis/pipeline/v1alpha1/gcs_resource_test.go]: @ImJasonH that's kinda my thought yeah :angel:

File: pkg/apis/pipeline/v1alpha1/gcs_resource_test.go [hunk 2]
```diff
@@ -226,14 +261,14 @@ func Test_GetInputSteps(t *testing.T) {
 			if tc.wantErr && err == nil {
 				t.Fatalf("Expected error to be %t but got %v:", tc.wantErr, err)
 			}
-			if d := cmp.Diff(gotSpec.GetStepsToPrepend(), tc.wantSteps); d != "" {
-				t.Errorf("Error mismatch between download containers spec: %s", d)
+			if d := cmp.Diff(tc.wantSteps, gotSpec.GetStepsToPrepend()); d != "" {
```
Comment (dibyom) [inline pkg/apis/pipeline/v1alpha1/gcs_resource_test.go]: Nice!

File: pkg/apis/pipeline/v1alpha1/gcs_resource_test.go (hunk 1 above)
Comment (dibyom) [reply pkg/apis/pipeline/v1alpha1/gcs_resource_test.go]: +1 for separate package. Seems like the best option for now!

Comment (ImJasonH) [reply pkg/apis/pipeline/v1alpha1/gcs_resource_test.go]: In the end I decided to make the resource add a single step with a script that activates the SA then calls `gsutil cp`/`gsutil rsync`, and to just put the full details of the script into each test.

When this gets extensible-ized this will all get cleaner tests will be split out with the code.

File: go.mod [hunk 3]
```diff
@@ -50,7 +51,7 @@ require (
 	golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e // indirect
 	golang.org/x/sys v0.0.0-20191110163157-d32e6e3b99c4 // indirect
 	golang.org/x/time v0.0.0-20191024005414-555d28b269f0 // indirect
-	google.golang.org/api v0.10.0 // indirect
+	google.golang.org/api v0.10.0
```
Comment (vdemeester) [inline go.mod]: why is this not `indirect` anymore ? same for `cloud.google.com/go/storage` above, I don't see any imports in our code for those, shouldn't this mean they should be `indirect` ?

Comment (ImJasonH) [reply go.mod]: I have no idea. I just build and commit whatever Go thinks is right. 🤷‍♂️
