### PR TITLE
Make generated pods only request the maximum necessary resources

### LINKED ISSUE #598: All containers in a TaskRun's Pod are combined to calculate required resources
# Expected Behavior

We're only running one container per `TaskRun` pod at a time, so the required resources for that pod should be the max values needed amongst all the containers we're running. While we were using init containers, that's how things worked.

# Actual Behavior

With containers instead of init containers, the pod's required resources are the *sum* of the required resources for each container. See https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources for more info on how pod resource requirements are calculated. The result is that a `TaskRun` of 10 steps results in a pod that thinks it needs the resources to be able to run all 10 step containers concurrently. So the required resources jumps a *ton* from what it had been with init containers.

# Steps to Reproduce the Problem

1. Run a `TaskRun` with 10 steps, on a cluster with sufficient resources available for a pod with <10 concurrent containers with the resource requirements of one of those steps.

# Additional Info

### PR DESCRIPTION
**Pull request by dwnusbaum**
# Changes

Before this change, if CPU, memory, or ephemeral storage resource requests were set in a Task's steps (which are Containers), the generated Pod would require the sum of all of the steps' requests to be scheduled on a Node. However, because Tekton overwrites Container entrypoints in Tasks to make the Containers logically execute one at a time, we want to make Pods generated by the TaskRun only request the maximum resources that will be necessary for any single Container rather than the sum of all resource requests.
    
To make this happen, when generating a Pod for a Task, we find the Step with largest resource requests among all Steps, and set the resource requests for all other steps to 0 for the respective resource. If no Step has an explicit resource request, all requests are set to 0. If we unset resource requests instead of setting them to 0 explicitly, then the limits would be used for the requests, which would defeat the purpose of unsetting the requested values (and could end up making the Pod request more memory than it did in the first place).

I did not add any e2e tests, but would be happy to do so if desired by reviewers. I think the tests would need to look up `Nodes` in the cluster to find the maximum allowed resources and then create some tasks dynamically that would have been unschedulable before this change but work after the change.

CC @bbrowning, @abayer

Fixes #598

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
Set CPU, memory, and ephemeral storage resource requests for each
step in a Task to zero if the step does not have the largest resource
request out of all steps in the Task. This ensures that the Pod that
executes the Task will only request the resources necessary to
execute any single step in the Task, rather than requesting the sum
of all of the step's resource requests, and is safe because Tekton
executes steps sequentially rather than all at once.
```

### CODE REVIEW

File: pkg/reconciler/v1alpha1/taskrun/resources/pod.go [hunk 1]
```diff
@@ -174,6 +177,9 @@ func MakePod(taskRun *v1alpha1.TaskRun, taskSpec v1alpha1.TaskSpec, kubeclient k
 	initContainers := []corev1.Container{*cred}
 	podContainers := []corev1.Container{}
 
+	maxCpuIdx := findMaxResourceRequest(taskSpec.Steps, corev1.ResourceCPU)
+	maxMemIdx := findMaxResourceRequest(taskSpec.Steps, corev1.ResourceMemory)
```
Comment (dwnusbaum) [inline pkg/reconciler/v1alpha1/taskrun/resources/pod.go]: Looping through the containers twice is not the most efficient, but this approach seemed like the most readable code. I am happy to make it more efficient if desired.

File: pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go [hunk 2]
```diff
@@ -33,8 +32,10 @@ import (
 )
 
 var (
-	ignorePrivateResourceFields = cmpopts.IgnoreUnexported(resource.Quantity{})
-	nopContainer                = corev1.Container{
+	resourceQuantityCmp = cmp.Comparer(func(x, y resource.Quantity) bool {
+		return x.Cmp(y) == 0
```
Comment (dwnusbaum) [inline pkg/reconciler/v1alpha1/taskrun/resources/pod_test.go]: I added this comparator in 3 places. It would be nice to have a default comparator with some helpful default settings for use in tests, but I didn't see any kind of util package or anything for that kind of thing. Is there a place for something like that?

File: test/builder/container.go [hunk 3]
```diff
@@ -67,3 +74,45 @@ func VolumeMount(name, mountPath string, ops ...VolumeMountOp) ContainerOp {
...
+	}
+}
+
+func CPU(val string) ResourceListOp {
+	return func(r corev1.ResourceList) {
+		r[corev1.ResourceCPU] = resource.MustParse(val)
+	}
+}
+
+func Memory(val string) ResourceListOp {
```
Comment (dwnusbaum) [inline test/builder/container.go]: Alternatively we could just have `func Resource(name corev1.ResourceName, val string)` so we don't need a separate method for every function, but that is a little more verbose.

File: pkg/reconciler/v1alpha1/taskrun/resources/pod.go (hunk 1 above)
Comment (dwnusbaum) [reply pkg/reconciler/v1alpha1/taskrun/resources/pod.go]: Also, maybe we should also do the same thing for `corev1.ResourceEphemeralStorage`? Thoughts? If so, it would probably makes sense to switch the signature of `findMaxResourceRequest` to take a list of names and return a map from resource names to max indices.

**Comment by dwnusbaum** [comment]
I guess the tests are failing for the reason Nader described [here](https://github.com/tektoncd/pipeline/pull/722#issuecomment-479997713)?

/test pull-tekton-pipeline-integration-tests

File: pkg/reconciler/v1alpha1/taskrun/resources/pod.go (hunk 1 above)
Comment (vdemeester) [reply pkg/reconciler/v1alpha1/taskrun/resources/pod.go]: @dwnusbaum I do agree on your 2nd comment :+1:

Comment (dwnusbaum) [reply pkg/reconciler/v1alpha1/taskrun/resources/pod.go]: Updated to handle ephemeral storage and avoid repeated looping in be66897.

**Comment by dwnusbaum** [comment]
@vdemeester No preference from me, it would be relatively easy to switch to applying the max requests to the first container. It might be a bit cleaner to do things that way rather than needing to track indices.

**Comment by dwnusbaum** [comment]
@vdemeester Actually I think moving the max requests to the first container is problematic because of resource limits. Take the following example: 

```
steps:
  - name: step1
    ...
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "1Gi"
  - name: step2
    ...
    resources:
      requests:
        memory: "5Gi"
```
The current approach turns this into:

```
steps:
  - name: step1
    ...
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "0"
  - name: step2
    ...
    resources:
      requests:
        memory: "5Gi"
```

But the other approach would cause the first step to request resources beyond its limit: 

```
steps:
  - name: step1
    ...
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "5Gi"
  - name: step2
    ...
    resources:
      requests:
        memory: "0"
```

We could adjust the limit in these cases, but I'd prefer to avoid modifying limits if we don't have to.

**Comment by vdemeester** [comment]
> @vdemeester Actually I think moving the max requests to the first container is problematic because of resource limits. Take the following example:
> 
> […]
> 
> But the other approach would cause the first step to request resources beyond its limit:
> 
> […]
> 
> We could adjust the limit in these cases, but I'd prefer to avoid modifying limits if we don't have to.

Ah ! Make sense :sweat_smile: Let's go for the initial take then :angel:

File: docs/tasks.md [hunk 4]
```diff
@@ -129,6 +129,12 @@ or container images that you define:
   the configuration file.
 - Each container image runs until completion or until the first failure is
   detected.
+- The CPU, memory, and ephemeral storage resource requests will be set to zero
```
Comment (dwnusbaum) [inline docs/tasks.md]: Any thoughts on a better place to put this documentation or a better way to phrase it would be welcome!

**Comment by abayer** [comment]
/hold cancel

...forgot the syntax. =)

**Comment by dwnusbaum** [comment]
Looks like the unit tests are failing after other PRs were merged (maybe #748?), probably a logical conflict somewhere with the changes in this PR. I'll rebase and fix the tests.

**Comment by vdemeester** [comment]
arf sorry @dwnusbaum :sweat: :bowing_man:

**Comment by dwnusbaum** [comment]
@vdemeester No problem, probably trivial to fix 😄

File: pkg/reconciler/v1alpha1/taskrun/resources/pod.go [hunk 5]
```diff
@@ -264,3 +270,43 @@ func makeLabels(s *v1alpha1.TaskRun) map[string]string {
...
 }
+
+// zeroNonMaxResourceRequests zeroes out the container's cpu, memory, or
+// ephemeral storage resource requests if the container does not have the
+// largest request out of all containers in the pod. This is done because Tekton
+// overwrites each container's entrypoint to make containers effectively execute
+// one at a time, so we want pods to only request the maximum resources needed
+// at any single point in time. If no contianer has an explicit resource
+// request, all requests are set to 0.
+func zeroNonMaxResourceRequests(container *corev1.Container, containerIndex int, maxIndicesByResource map[corev1.ResourceName]int) {
```
Comment (bobcatfish) [inline pkg/reconciler/v1alpha1/taskrun/resources/pod.go]: these functions are excellent! nice focused interface and clear short functions. My only too-late-to-the-party request would be to have unit tests covering these functions directly as well but im fully expecting to be ignored since im so late haha :D

Comment (dwnusbaum) [reply pkg/reconciler/v1alpha1/taskrun/resources/pod.go]: Good point! I'm going to file an issue for a followup I thought of the other day, and if I'm in this area again I'll add some unit tests.

Comment (bobcatfish) [reply pkg/reconciler/v1alpha1/taskrun/resources/pod.go]: awesome, that sounds great @dwnusbaum :heart: !!
