### PR TITLE
Check parent task's status when calculating pipelinerun status

### LINKED ISSUE #1173: Pipeline status not updated when `runAfter is used with a `condition`
Say we have a pipeline with two pipeline tasks A and B. A is a conditional task that only runs if a condition is true while B is dependent on A using either `from` or `runAfter`.

# Expected Behavior
If task A is skipped due to a condition failure, task B should not run. The pipeline status should be set to success since both A and B are skipped 

# Actual Behavior
Task A is skipped due to condition failure and Task B is also skipped due to it being dependent on a condition failure. But the pipeline status is never updated from `Running` to `Successful`

# Steps to Reproduce the Problem

1. Run this pipeline: https://gist.github.com/dibyom/761199a1af98f435951fe1c8c2c8a08c
2. Run `kubectl get prs -o yaml` to see the status is not updated properly even after the first task is skipped.
3.

# Additional Info

/kind bug
/assign

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

Before conditionals, a pipelinerun was marked successful only
if all tasks were successfully run. Now, a pipelinerun is successful
if all tasks were either successfully run or skipped due to a condition
check failure.

Currently while updating status, we only see if a task's own condition
check failed. This is not sufficient if that task (B) is dependent on another
task (A) using `from` or `runAfter`. If A is skipped due to a condition failure,
task B is not scheduled to be execute, and there are no other tasks left to run.
However, the pipeline status is never updated from `Running` to `Successful`.

To fix this, this commit changes the `GetPipelineConditionStatus` function to
recursively look at a task's parent tasks to see if they are skipped. If any single
parent task is skipped, we skip the task. If all tasks in a pipeline are either
successful or skipped, we update the pipeline run status to successful.
 
Fixes #1173

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

File: pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go [hunk 1]
```diff
@@ -320,84 +354,93 @@ func getTaskRunName(taskRunsStatus map[string]*v1alpha1.PipelineRunTaskRunStatus
...
-			allFinished = false
-			continue
-		}
-		logger.Infof("TaskRun %s status : %v", rprt.TaskRunName, c.Status)
-		// If any TaskRuns have failed, we should halt execution and consider the run failed
-		if c.Status == corev1.ConditionFalse && rprt.IsDone() {
-			logger.Infof("TaskRun %s has failed, so PipelineRun %s has failed, retries done: %b", rprt.TaskRunName, prName, len(rprt.TaskRun.Status.RetriesStatus))
+	// A single failed task mean we fail the pipeline
+	for _, rprt := range state {
+		if rprt.IsFailure() { //IsDone ensures we have crossed the retry limit
```
Comment (sbwsg) [inline pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go]: I'm a bit unclear what the `IsDone` comment is referring to here. Did you mean `IsFailure ensures we have crossed...`?

Comment (dibyom) [reply pkg/reconciler/v1alpha1/pipelinerun/resources/pipelinerunresolution.go]: Yeah old comment. Will fix
