### PR TITLE
fix: Detect pod configuration errors early instead of timeout

### LINKED ISSUE #9144: Misconfigured TaskRun pods cause PipelineRuns to silently timeout
# Expected Behavior
A TaskRun with a TaskRun Pod that cannot start would either fail early, or when it times out the TaskRun's "Succeeded" failed condition should give some helpful message indicating that the TaskRun Pod could not start. Something like `TaskRun "configmap-4qrgb" failed to finish within "1m0s: pod status "PodReadyToStartContainers":"False";" 

# Actual Behavior
The `Succeeded` failed condition does not indicate that the Pod could not start: `TaskRun "my-taskrun" failed to finish within "$timeout"`. 

# Steps to Reproduce the Problem

1. Create the following TaskRun:
```yaml
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: missing-configmap-
spec:
  timeout: 1m
  taskSpec:
    steps:
    - name: secret
      image: mirror.gcr.io/ubuntu
      script: |
        #!/usr/bin/env bash
        [[ $(cat /config/test.data) == $TEST_DATA ]]
      env:
      - name: TEST_DATA
        valueFrom:
          configMapKeyRef:
            name: config-for-testing-configmaps
            key: test.data
      volumeMounts:
      - name: config-volume
        mountPath: /config
    volumes:
    - name: config-volume
      configMap:
        name: config-for-testing-configmaps
```
2. Observe that the TaskRun Pod never starts, the TaskRun remains in a "Pending" instead of "Running", and that the timeout of the TaskRun doesn't indicate there was any issue starting the TaskRun pod

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
~/c/tektoncd-pipeline (main|✚1) $ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.0
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
$ tkn version
Client version: 0.41.0
Pipeline version: v1.4.0
Dashboard version: v0.61.0
```

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

- Fail fast on missing ConfigMaps/Secrets used in env variables, using `valueFrom`, within seconds of detection
- Show actionable error messages instead of generic timeout failures
- Add early detection for CreateContainerConfigError and related failures

/kind bug

Fixes #9144 

/cc @afrittoli @aThorp96 @arewm 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Fixed TaskRuns to fail immediately when pod containers have configuration errors (missing ConfigMap/Secret) instead of silently timing out.
```

### CODE REVIEW

**Comment by afrittoli** [comment]
> * Fail fast on missing ConfigMaps/Secrets within seconds of detection

WRT to this, users may be relying on the current behaviour in cases where a config map or secret is provisioned roughly at the same as the `TaskRun` or `PipelineRun` and may not yet be on the cluster during the first reconcile. Would it make sense to have a configurable timeout for this or at least a configurable on/off switch for the feature?

**Comment by vdemeester** [comment]
> > * Fail fast on missing ConfigMaps/Secrets within seconds of detection
> 
> WRT to this, users may be relying on the current behaviour in cases where a config map or secret is provisioned roughly at the same as the `TaskRun` or `PipelineRun` and may not yet be on the cluster during the first reconcile. Would it make sense to have a configurable timeout for this or at least a configurable on/off switch for the feature?

Ah I should have written a better description. Essentially, if they use Volumes/VolumeMounts for configmaps or secrets, the behavior doesn't change at all, as it is a recoverable issue (from the Pod and thus TaskRun stand-point). But if they use the EnvSource (aka loading an environment variable value from a ConfigMap or a Secret), this is where it will *fail-fast* as it won't ever be recovered. See https://github.com/tektoncd/pipeline/issues/9144#issuecomment-3602099215.

So users who were relying on current behavior will either see a failure early instead of a timeout (always), or it won't change a thing. If there was a failure before, there is a failure now, just quicker ; if there was no failure before, there is no failure now either (from the user point of view).

I'll update the description.

File: pkg/apis/pipeline/v1/taskrun_types.go [hunk 1]
```diff
@@ -212,6 +212,10 @@ const (
 	TaskRunReasonResolvingStepActionRef = "ResolvingStepActionRef"
 	// TaskRunReasonImagePullFailed is the reason set when the step of a task fails due to image not being pulled
 	TaskRunReasonImagePullFailed TaskRunReason = "TaskRunImagePullFailed"
+	// TaskRunReasonCreateContainerConfigError is the reason set when the step of a task fails due to config error (e.g., missing ConfigMap or Secret)
+	TaskRunReasonCreateContainerConfigError TaskRunReason = "CreateContainerConfigError"
+	// TaskRunReasonPodCreationFailed is the reason set when the pod backing the TaskRun fails to be created (e.g., CreateContainerError)
+	TaskRunReasonPodCreationFailed TaskRunReason = "PodCreationFailed"
```
Comment (aThorp96) [inline pkg/apis/pipeline/v1/taskrun_types.go:218]: Is `TaskRunReasonCreateContainerConfigError` a subset of `TaskRunReasonPodCreationFailed`? Since `CreateContainerError` is listed as the example here I'm hoping to understand the difference between these two failure modes better

~TODO: this might become obvious as I continue to review~ 
_It looks to me like `TaskRunReasonCreateContainerConfigError` is for known container configuration errors, and `TaskRunReasonPodCreationFailed` is the unknown "it broke" reason. Is that right?_

File: pkg/pod/status.go [hunk 2]
```diff
@@ -827,28 +827,43 @@ func IsPodExceedingNodeResources(pod *corev1.Pod) bool {
 	return false
 }
 
-// isPodHitConfigError returns true if the Pod's status undicates there are config error raised
-func isPodHitConfigError(pod *corev1.Pod) bool {
+// hasContainerWaitingReason checks if any container (init or regular) is waiting with a reason
+// that matches the provided predicate function
+func hasContainerWaitingReason(pod *corev1.Pod, predicate func(corev1.ContainerStateWaiting) bool) bool {
```
Comment (aThorp96) [inline pkg/pod/status.go:832]: Love this helper

File: pkg/reconciler/taskrun/taskrun.go [hunk 3]
```diff
@@ -105,8 +105,11 @@ var (
...
 	// Pod failure reasons that trigger failure of the TaskRun
 	podFailureReasons = map[string]struct{}{
-		ImagePullBackOff:   {},
-		"InvalidImageName": {},
+		ImagePullBackOff:             {},
+		"InvalidImageName":           {},
+		"CreateContainerConfigError": {}, // Missing ConfigMap/Secret, invalid env vars, etc.
+		"CreateContainerError":       {}, // Other container creation failures
+		"ErrImagePull":               {}, // Initial image pull failure
 	}
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go:120]: Optional nitpick:

Can this be constantized since we're comparing the values below?
```suggestion
const (
	ImagePullBackoff = "ImagePullBackoff"
	InvalidImageName = "InvalidImageName"
	CreateContainerConfigError = "CreateContainerConfigError" // Missing ConfigMap/Secret, invalid env vars, etc.
	CreateContainerError = "CreateContainerError"  // Other container creation failures
	ErrImagePull = "ErrImagePull" // Initial image pull pailure
)

// Imagine a language not including basic types like Sets in 2025
var podFailureReasons = map[string]struct{}{
		ImagePullBackOff:             {},
		InvalidImageName:           {},
		CreateContainerConfigError: {},
		CreateContainerError:       {}, 
		ErrImagePull:               {}, 
}
```

```
...
if step.Waiting.Reason == CreateContainerConfigError {
	...
}
...
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 4]
```diff
@@ -270,16 +274,35 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
 							}
 						}
 					}
+					// ImagePullBackOff timeout exceeded or not configured
+					image := step.ImageID
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, step.Name, tr.Name, image, step.Waiting.Message)
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]: optional nit: no need to alloc
```suggestion
					message := fmt.Sprintf(`the step %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, step.Name, tr.Name, step.ImageID, step.Waiting.Message)
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 5]
```diff
@@ -270,16 +274,35 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
...
+				// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
+				if step.Waiting.Reason == "CreateContainerConfigError" {
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, step.Name, tr.Name, step.Waiting.Message)
+					return true, v1.TaskRunReasonCreateContainerConfigError, message
+				}
+
+				// Handle other image-related errors
+				if step.Waiting.Reason == "ErrImagePull" || step.Waiting.Reason == "InvalidImageName" {
+					image := step.ImageID
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, step.Name, tr.Name, image, step.Waiting.Message)
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]: optional nit: no need to alloc
 ```suggestion
						message := fmt.Sprintf(`the step %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, step.Name, tr.Name, step.ImageID, step.Waiting.Message)
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 6]
```diff
@@ -299,10 +322,28 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
 							}
 						}
 					}
+					// ImagePullBackOff timeout exceeded or not configured
+					image := sidecar.ImageID
+					message := fmt.Sprintf(`the sidecar %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, sidecar.Name, tr.Name, image, sidecar.Waiting.Message)
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]: Optional nit: no need to alloc
```suggestion
					message := fmt.Sprintf(`the sidecar %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, sidecar.Name, tr.Name, sidecar.ImageID, sidecar.Waiting.Message)
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 7]
```diff
@@ -299,10 +322,28 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
...
+				// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
+				if sidecar.Waiting.Reason == "CreateContainerConfigError" {
+					message := fmt.Sprintf(`the sidecar %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, sidecar.Name, tr.Name, sidecar.Waiting.Message)
+					return true, v1.TaskRunReasonCreateContainerConfigError, message
+				}
+
+				// Handle other image-related errors
+				if sidecar.Waiting.Reason == "ErrImagePull" || sidecar.Waiting.Reason == "InvalidImageName" {
+					image := sidecar.ImageID
+					message := fmt.Sprintf(`the sidecar %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, sidecar.Name, tr.Name, image, sidecar.Waiting.Message)
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]: Optional nit: no need to alloc
```suggestion
					message := fmt.Sprintf(`the sidecar %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, sidecar.Name, tr.Name, sidecar.ImageID, sidecar.Waiting.Message)
```

File: pkg/reconciler/taskrun/taskrun_test.go [hunk 8]
```diff
@@ -2772,16 +2792,32 @@ status:
...
+			switch tc.reason {
+			case "CreateContainerConfigError":
+				expectedReason = "CreateContainerConfigError"
+				expectedMessage = fmt.Sprintf(`the %s "unnamed-%d" in TaskRun "test-imagepull-fail" failed to start. The pod errored with the message: "%s."`, tc.failure, stepNumber, tc.message)
+				wantFailedEvent = fmt.Sprintf(`Warning Failed the %s "unnamed-%d" in TaskRun "test-imagepull-fail" failed to start. The pod errored with the message: "%s.`, tc.failure, stepNumber, tc.message)
+			case "CreateContainerError":
+				expectedReason = "PodCreationFailed"
+				expectedMessage = fmt.Sprintf(`the %s "unnamed-%d" in TaskRun "test-imagepull-fail" failed to start. The pod errored with the message: "%s."`, tc.failure, stepNumber, tc.message)
+				wantFailedEvent = fmt.Sprintf(`Warning Failed the %s "unnamed-%d" in TaskRun "test-imagepull-fail" failed to start. The pod errored with the message: "%s.`, tc.failure, stepNumber, tc.message)
+			default: // Image pull errors
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun_test.go]: Optional suggestion:

Better to be explicit IMO. WDYT?
```suggestion
			case "InvalidImageName", "ImagePullBackOff":
```

File: pkg/reconciler/taskrun/taskrun.go (hunk 3 above)
Comment (aThorp96) [reply pkg/reconciler/taskrun/taskrun.go:120]: Also, where do these values come from? Ideally they'd be referenced instead of hardcode as strings, if they are defined by a package.

File: pkg/reconciler/taskrun/taskrun.go [hunk 9]
```diff
@@ -270,16 +274,35 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
...
-				return true, v1.TaskRunReasonImagePullFailed, message
+
+				// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
+				if step.Waiting.Reason == "CreateContainerConfigError" {
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, step.Name, tr.Name, step.Waiting.Message)
+					return true, v1.TaskRunReasonCreateContainerConfigError, message
+				}
+
+				// Handle other image-related errors
+				if step.Waiting.Reason == "ErrImagePull" || step.Waiting.Reason == "InvalidImageName" {
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]: Potential bug: 
IIUC ErrImagePull can happen transiently and is automatically retried before the ImagePullBackoff. If that's the case, would this logic cause TaskRuns to fail instead of the image pull being retried? If I am reading this right, if we include `step.Waiting.Reason == "ErrImagePull"` then we'll fast fail before we ever allow the retry to get to `ErrImagePullBackoff`. Is that right? Maybe that's the point of the PR, but I do worry that it could make Tekton seem "flakier" to users if TaskRuns are more prone to fast-fail on transient issues.

**Review by aThorp96 — COMMENTED** [review]
Overall seems good to me! Couple questions and a few optional suggestions/nits (mostly regarding patterns which were already in the code)

File: pkg/apis/pipeline/v1/taskrun_types.go (hunk 1 above)
Comment (vdemeester) [reply pkg/apis/pipeline/v1/taskrun_types.go:218]: Yes, that is right 😛

File: pkg/reconciler/taskrun/taskrun.go (hunk 3 above)
Comment (vdemeester) [reply pkg/reconciler/taskrun/taskrun.go:120]: @aThorp96 well, I don't want to rely on a k8s package just for constants 😛

File: pkg/reconciler/taskrun/taskrun.go (hunk 9 above)
Comment (vdemeester) [reply pkg/reconciler/taskrun/taskrun.go]: Ah you are right, I'll remove that one.

File: pkg/reconciler/taskrun/taskrun.go [hunk 10]
```diff
@@ -270,16 +280,35 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
 							}
 						}
 					}
+					// ImagePullBackOff timeout exceeded or not configured
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, step.Name, tr.Name, step.ImageID, step.Waiting.Message)
+					return true, v1.TaskRunReasonImagePullFailed, message
+				}
+
+				// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
+				if step.Waiting.Reason == "CreateContainerConfigError" {
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]:
```suggestion
				if step.Waiting.Reason == CreateContainerConfigError {
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 11]
```diff
@@ -270,16 +280,35 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
...
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, step.Name, tr.Name, step.Waiting.Message)
+					return true, v1.TaskRunReasonCreateContainerConfigError, message
+				}
+
+				// Handle InvalidImageName (unrecoverable error)
+				// Note: ErrImagePull is not handled here as it's a transient state that Kubernetes
+				// will automatically retry before transitioning to ImagePullBackOff
+				if step.Waiting.Reason == "InvalidImageName" {
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]:
```suggestion
				if step.Waiting.Reason == InvalidImageName {
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 12]
```diff
@@ -299,10 +328,28 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
 							}
 						}
 					}
+					// ImagePullBackOff timeout exceeded or not configured
+					message := fmt.Sprintf(`the sidecar %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, sidecar.Name, tr.Name, sidecar.ImageID, sidecar.Waiting.Message)
+					return true, v1.TaskRunReasonImagePullFailed, message
+				}
+
+				// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
+				if sidecar.Waiting.Reason == "CreateContainerConfigError" {
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]:
```suggestion
				if sidecar.Waiting.Reason == CreateContainerConfigError {
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 13]
```diff
@@ -299,10 +328,28 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
...
+					return true, v1.TaskRunReasonCreateContainerConfigError, message
 				}
-				image := sidecar.ImageID
-				message := fmt.Sprintf(`the sidecar %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, sidecar.Name, tr.Name, image, sidecar.Waiting.Message)
-				return true, v1.TaskRunReasonImagePullFailed, message
+
+				// Handle InvalidImageName (unrecoverable error)
+				// Note: ErrImagePull is not handled here as it's a transient state that Kubernetes
+				// will automatically retry before transitioning to ImagePullBackOff
+				if sidecar.Waiting.Reason == "InvalidImageName" {
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]:
```suggestion
				if sidecar.Waiting.Reason == InvalidImageName {
```

File: pkg/reconciler/taskrun/taskrun.go [hunk 14]
```diff
@@ -270,16 +280,35 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
...
+
+				// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
+				if step.Waiting.Reason == "CreateContainerConfigError" {
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, step.Name, tr.Name, step.Waiting.Message)
+					return true, v1.TaskRunReasonCreateContainerConfigError, message
+				}
+
+				// Handle InvalidImageName (unrecoverable error)
+				// Note: ErrImagePull is not handled here as it's a transient state that Kubernetes
+				// will automatically retry before transitioning to ImagePullBackOff
```
Comment (aThorp96) [inline pkg/reconciler/taskrun/taskrun.go]: 🙏🏼

**Review by aThorp96 — APPROVED** [review]
/lgtm

Two minor suggestions to utilize the new constants

File: pkg/reconciler/taskrun/taskrun.go [hunk 15]
```diff
@@ -251,6 +260,7 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
 	for _, step := range tr.Status.Steps {
 		if step.Waiting != nil {
 			if _, found := podFailureReasons[step.Waiting.Reason]; found {
```
Comment (twoGiants) [inline pkg/reconciler/taskrun/taskrun.go]: Great opportunity to clean this up a bit. You could use the guard pattern twice here (and below for the sidecars) and reduce the nesting of the ifs by 2 and then extract the duplicated checks into a helper :smile_cat:  =>

```go
		if step.Waiting == nil {
			continue
		}

		if _, found := podFailureReasons[step.Waiting.Reason]; !found {
			continue
		}

		c.checkContainerFailure(
			ctx,
			tr,
			step.Waiting,
			step.Name,
			step.ImageID,
			"step",
		)

``` 

And the waiting reason checks can go into a helper and reused below for the sidecars as well:

```go
func (c *Reconciler) checkContainerFailure(
	ctx context.Context,
	tr *v1.TaskRun,
	waiting *corev1.ContainerStateWaiting,
	name,
	imageID,
	containerType string,
) (bool, v1.TaskRunReason, string) {
	if waiting.Reason == ImagePullBackOff {
		imagePullBackOffTimeOut := config.FromContextOrDefaults(ctx).Defaults.DefaultImagePullBackOffTimeout
		// only attempt to recover from the imagePullBackOff if specified
		if imagePullBackOffTimeOut.Seconds() != 0 {
			p, err := c.KubeClientSet.CoreV1().Pods(tr.Namespace).Get(ctx, tr.Status.PodName, metav1.GetOptions{})
			if err != nil {
				message := fmt.Sprintf(`the %s %q in TaskRun %q failed to pull the image %q. Failed to get pod with error: "%s."`, containerType, name, tr.Name, imageID, err)
				return true, v1.TaskRunReasonImagePullFailed, message
			}
			for _, condition := range p.Status.Conditions {
				// check the pod condition to get the time when the pod was ready to start containers / initialized.
				// keep trying until the pod schedule time has exceeded the specified imagePullBackOff timeout duration
				if slices.Contains(imagePullBackOffTimeoutPodConditions, string(condition.Type)) {
					if c.Clock.Since(condition.LastTransitionTime.Time) < imagePullBackOffTimeOut {
						return false, "", ""
					}
				}
			}
		}
		// ImagePullBackOff timeout exceeded or not configured
		message := fmt.Sprintf(`the %s %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, containerType, name, tr.Name, imageID, waiting.Message)
		return true, v1.TaskRunReasonImagePullFailed, message
	}

	// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
	if waiting.Reason == CreateContainerConfigError {
		message := fmt.Sprintf(`the %s %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, containerType, name, tr.Name, waiting.Message)
		return true, v1.TaskRunReasonCreateContainerConfigError, message
	}

	// Handle InvalidImageName (unrecoverable error)
	// Note: ErrImagePull is not handled here as it's a transient state that Kubernetes
	// will automatically retry before transitioning to ImagePullBackOff
	if waiting.Reason == InvalidImageName {
		message := fmt.Sprintf(`the %s %q in TaskRun %q failed to pull the image %q. The pod errored with the message: "%s."`, containerType, name, tr.Name, imageID, waiting.Message)
		return true, v1.TaskRunReasonImagePullFailed, message
	}

	// Handle CreateContainerError and other generic failures
	message := fmt.Sprintf(`the %s %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, containerType, name, tr.Name, waiting.Message)
	return true, v1.TaskRunReasonPodCreationFailed, message
}
``` 

I also changed this message in the `ImagePullBackOff` error => _the step %q in TaskRun %q failed to pull the image %q **and the pod with error**_, the last part sounds wrong. I used: _the %s %q in TaskRun %q failed to pull the image %q. Failed to get pod with error: "%s._

File: pkg/reconciler/taskrun/taskrun.go [hunk 16]
```diff
@@ -270,16 +280,35 @@ func (c *Reconciler) checkPodFailed(ctx context.Context, tr *v1.TaskRun) (bool,
...
+				}
+
+				// Handle CreateContainerConfigError (missing ConfigMap/Secret, invalid env vars, etc.)
+				if step.Waiting.Reason == CreateContainerConfigError {
+					message := fmt.Sprintf(`the step %q in TaskRun %q failed to start. The pod errored with the message: "%s."`, step.Name, tr.Name, step.Waiting.Message)
+					return true, v1.TaskRunReasonCreateContainerConfigError, message
+				}
+
+				// Handle InvalidImageName (unrecoverable error)
+				// Note: ErrImagePull is not handled here as it's a transient state that Kubernetes
```
Comment (twoGiants) [inline pkg/reconciler/taskrun/taskrun.go]: But when `ErrImagePull` is the reason the method returns `true` in [line 304](https://github.com/tektoncd/pipeline/pull/9197/files#diff-6e67e9c647bbe2a08807ff5ccbdd7dc9036df373e56b9774d3996f92ab7ceabaR304) and the reconciler fails the `TaskRun`. It looks like we either should not check for this transient state or if we do then return `false` with a message like `retrying pulling image`.

File: pkg/reconciler/taskrun/taskrun_test.go [hunk 17]
```diff
@@ -2717,6 +2717,21 @@ func TestReconcilePodFailures(t *testing.T) {
...
+		reason:  "CreateContainerConfigError",
+		message: "configmap \"config-for-testing-configmaps\" not found",
+		failure: "step",
+	}, {
+		desc:    "create container config error sidecar - missing secret",
+		reason:  "CreateContainerConfigError",
+		message: "secret \"secret-for-testing\" not found",
+		failure: "sidecar",
+	}, {
+		desc:    "create container error step",
```
Comment (twoGiants) [inline pkg/reconciler/taskrun/taskrun_test.go]: The same test case for sidecar is missing.

File: pkg/reconciler/taskrun/taskrun_test.go [hunk 18]
```diff
@@ -2717,6 +2717,21 @@ func TestReconcilePodFailures(t *testing.T) {
 		message:                 "Invalid image \"whatever\"",
 		failure:                 "step",
 		imagePullBackOffTimeout: "5h",
+	}, {
```
Comment (twoGiants) [inline pkg/reconciler/taskrun/taskrun_test.go]: If the `ErrImagePull` case is added in the implementation it must be added here too for both.

File: pkg/reconciler/taskrun/taskrun_test.go [hunk 19]
```diff
@@ -2772,16 +2787,32 @@ status:
 				stepNumber = 1
 			}
 
+			var expectedReason, expectedMessage, wantFailedEvent string
```
Comment (twoGiants) [inline pkg/reconciler/taskrun/taskrun_test.go]: It took me a while to get this :smiling_face_with_tear:. But I got it! :rofl: 

This test is quite complex already with all its conditions down below. The additional switch makes it a even more difficult to understand. 

What do you think about extracting the tests for the new container failure logic into it's own table driven test function with a simpler setup, execution and assertions instead of extending this one?

Comment (aThorp96) [reply pkg/reconciler/taskrun/taskrun_test.go]: +1
Enumerating the almost-entirely-identical message and event strings inside the test cases would certainly be verbose and tedious, but the switch statement and various string formatting does add a lot of mental complexity. I think I'd even prefer setting/updating `expectedStatus` and `wantEvents` directly in the switch. It would be a lot more straightforward and clear though to either enumerate the events and strings in the cases or add an entirely different test function for the new behavior

Comment (vdemeester) [reply pkg/reconciler/taskrun/taskrun_test.go]: It's already in TestReconcileContainerFailures, I forgot to remove that part...
