### PR TITLE
Do not panic if Timeout is nil

### LINKED ISSUE #1075: SIGSEGV in Reconciler
# Expected Behavior
Should run fine

# Actual Behavior
Leads to a _segmentation violation_.

# Steps to Reproduce the Problem

1. Created `TaskRun` on OpenShift 3.11
```
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: git-mirror-run
spec:
  serviceAccount: git-mirror
  taskRef:
    name: git-mirror-task
  inputs:
    params:
      - name: srcRepo
        value: ssh://git@bitbucket.foo.bar/foo/bar.git
      - name: destRepo
        value: git@github.com:foo/bar_common.git
```

# Additional Info
Logs print:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x134621b]

goroutine 204 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun.(*Reconciler).checkTimeout(0xc0004956c0, 0xc00037a280, 0xc000940c30, 0xc0009012f8, 0xc00090f820, 0x0, 0x69e489)
	/workspace/go/src/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/taskrun.go:536 +0x9b
github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun.(*Reconciler).reconcile(0xc0004956c0, 0x19aa620, 0xc0007f1d10, 0xc00037a280, 0xed4be7aee, 0x27a75a0)
	/workspace/go/src/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/taskrun.go:264 +0x3fd
github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun.(*Reconciler).Reconcile(0xc0004956c0, 0x19aa620, 0xc0007f1d10, 0xc000bdc780, 0x1f, 0xc00097e8a8, 0x19aa620)
	/workspace/go/src/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/taskrun/taskrun.go:171 +0x58b
github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller.(*Impl).processNextWorkItem(0xc00059d200, 0x175be00)
	/workspace/go/src/github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller/controller.go:330 +0x514
github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller.(*Impl).Run.func1(0xc00089c7f4, 0xc00059d200)
	/workspace/go/src/github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller/controller.go:282 +0x51
created by github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller.(*Impl).Run
	/workspace/go/src/github.com/tektoncd/pipeline/vendor/github.com/knative/pkg/controller/controller.go:280 +0x1a5
```

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

`TaskRun` and `PipelineRun` should have a default Timeout set by the
webhook. That said, if the webhook didn't do its work, or the object
where created before those webhook defaults, it could be nil and makes
the controller panicking.

This is a simplest fix for #1075 than #1083 to make the simplest fix for the bug-fix release. Closes #1075.

/cc @bobcatfish 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

# Release Notes

```
Fix controller panicking on missing Timeout on TaskRun (existing or new)
```

### CODE REVIEW

**Comment by bobcatfish** [comment]
woot seems like a reasonable simple fix for this! Thanks @vdemeester 🎉 

/lgtm
/meow space

**Comment by bobcatfish** [comment]
hm I wonder if we should add a test case @vdemeester 

I think we need to revisit this asap anyway so its not critical 🤔  and like you were pointing out in the original PR, we shouldn't get into this state anyway (once we fix the defaulting) 🤔🤔🤔

**Comment by vdemeester** [comment]
> hm I wonder if we should add a test case @vdemeester
> 
> I think we need to revisit this asap anyway so its not critical thinking and like you were pointing out in the original PR, we shouldn't get into this state anyway (once we fix the defaulting) thinkingthinkingthinking

Let me take a look real quick

/hold

**Comment by vdemeester** [comment]
Updated with a test case :angel: 
/hold cancel

File: pkg/reconciler/v1alpha1/taskrun/taskrun.go [hunk 1]
```diff
@@ -495,6 +498,7 @@ func (c *Reconciler) updateTaskRunStatusForTimeout(tr *v1alpha1.TaskRun, dp Dele
 		}
 	}
 
+	timeout := tr.Spec.Timeout.Duration
```
Comment (bobcatfish) [inline pkg/reconciler/v1alpha1/taskrun/taskrun.go]: hm this is interesting cuz it means if the order of the call to this function were to change, this could still be nil 🤔

**Comment by bobcatfish** [comment]
Thanks for adding the tests! ❤️❤️❤️
