### PR TITLE
Switch PipelineRun timeout -> TaskRun logic to instead signal the TaskRuns to stop

### LINKED ISSUE #5127: PipelineRuns with deprecated `timeout` field sometimes are marked as failed rather than timed out
`TestPipelineRunTimeout`, which is exercising the deprecated `PipelineRunSpec.Timeout` field, is one of our semi-regular flakes, and when I just saw it fail, I decided to deep-dive to try to figure out what's going on. I compared a successful run of the test with a failure, and found that the only real difference in the logs I could find is this:

From the successful run:
```
stream.go:238: Invalid log format for pod tekton-pipelines-controller-56459f9bf-qkq84: {"level":"info","ts":"2022-07-12T18:12:24.001Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:609","msg":"PipelineRun pipeline-run-timeout-zxjdknwx status is being set to &{Succeeded False  {2022-07-12 18:12:24.00139379 +0000 UTC m=+403.016411199} PipelineRunTimeout PipelineRun \"pipeline-run-timeout-zxjdknwx\" failed to finish within \"5s\"}","commit":"a38bee9","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"2a7e659c-b7c2-47d1-8855-197e5732b0ff","knative.dev/key":"arendelle-fc7nc/pipeline-run-timeout-zxjdknwx"}
```

From the failed run:
```
    stream.go:238: Invalid log format for pod tekton-pipelines-controller-56459f9bf-cqsg7: {"level":"info","ts":"2022-07-12T18:36:29.900Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:609","msg":"PipelineRun pipeline-run-timeout-hzggferi status is being set to &{Succeeded False  {2022-07-12 18:36:29.900532453 +0000 UTC m=+417.364871320} Failed Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0}","commit":"a38bee9","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"f2c06272-7e5c-4107-a12f-9a565a9eefa1","knative.dev/key":"arendelle-95sb7/pipeline-run-timeout-hzggferi"}
```

Ignore the `Invalid log format ...` noise - that's just the harmless-but-annoying #4777.

So here we can see that the failed run did get marked as failed. The line before that in the failure was this:
```
stream.go:238: Invalid log format for pod tekton-pipelines-controller-56459f9bf-cqsg7: {"level":"info","ts":"2022-07-12T18:36:29.900Z","logger":"tekton-pipelines-controller","caller":"resources/pipelinerunstate.go:486","msg":"All TaskRuns have finished for PipelineRun pipeline-run-timeout-hzggferi so it has finished","commit":"a38bee9","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"f2c06272-7e5c-4107-a12f-9a565a9eefa1","knative.dev/key":"arendelle-95sb7/pipeline-run-timeout-hzggferi"}
```

But I can't find an equivalent of that line for that `PipelineRun` in the successful log. What seems to be happening is this: https://github.com/tektoncd/pipeline/blob/d71d7dbd0ef30a857035015e0dda2a864caf8039/pkg/reconciler/pipelinerun/resources/pipelinerunstate.go#L441

...is returning false in the failure case, and true in the success case. So in the success case, it never gets further in the function and spits out that log line above. 

So...I think that something's wrong with [HasTimedOut](https://github.com/tektoncd/pipeline/blob/0d1d87a0a98840f78acd0e47e78ee9360019b2f7/pkg/apis/pipeline/v1beta1/pipelinerun_types.go#L160). I wonder whether [calculateTaskRunTimeout](https://github.com/tektoncd/pipeline/blob/d71d7dbd0ef30a857035015e0dda2a864caf8039/pkg/reconciler/pipelinerun/pipelinerun.go#L1137) (and the `Run` equivalent) are setting the `TaskRun`'s timeout to ever so slightly before the `PipelineRun` would be timed out, resulting in rare but real race conditions where the `TaskRun` times out and is killed, but the `PipelineRun` is reconciled in the very brief window between when the `TaskRun` times out and when the `PipelineRun` would timeout. That would explain what we're seeing pretty well.

/kind flake
/kind bug

### PR DESCRIPTION
**Pull request by abayer**
# Changes

Fixes #5127, #3460

An alternative approach vs #5133, attempting to eliminate the problem entirely rather than just working around it.

As noted in #5127, the logic around calculating a timeout for a `PipelineRun`'s `TaskRun` to make sure that the `TaskRun`'s timeout is always going to end before the `PipelineRun`'s timeout ends is problematic. It can result in race conditions where a `TaskRun` gets timed out, immediately followed by the `PipelineRun` being reconciled while not yet having hit the end of its own timeout. This change gets rid of that behavior, and instead sets the `TaskRun.Spec.Status` to a new value, `TaskRunTimedOut`, with the `TaskRun` reconciler handling that in the same way it does setting `TaskRun.Spec.Status` to `TaskRunCancelled`.

By doing this, we can unify the behavior for both `TaskRun`s and `Run`s upon `PipelineRun`s timing out, given that we already cancel `Run`s upon `PipelineRun` timeout, and we can kill off a bunch of flaky outcomes for `PipelineRun`s.

Also, rather than setting a 1s timeout on tasks which are created after the `.timeouts.pipeline`, `.timeouts.tasks`, or `.timeouts.finally` timeouts have been passed, this change will skip creation of those `TaskRun`s or `Run`s completely. However, it will still report those "tasks" as failed, not skipped, since attempted creation of tasks after the appropriate timeout has been reached is a failure case, and that's the existing expected behavior for `PipelineTask`s which try to start after timeouts have elapsed.

Huge thanks to @jerop for suggesting this approach!

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Change PipelineRun timeout behavior for child TaskRuns and Runs to behave like cancellation rather than explicitly setting timeouts on the child tasks at runtime.
```

### CODE REVIEW

**Comment by abayer** [comment]
/wip
/assign @jerop @pritidesai @dibyom @afrittoli @vdemeester 

(marking this as WIP because I want to get a good amount of test runs in to be sure it actually fixes the `TestPipelineRunTimeout` flaky test)

This is a rather significant change to how we actually time out `TaskRun`s for a timed-out `PipelineRun`, but I think it's reasonable/safe - this is what we do for cancellation already, so it's not that new, and it's frankly significantly more logical than the current "subtract the elapsed time from the PR start time plus PR timeout, and tada, that's the TR timeout" behavior.

**Comment by jerop** [comment]
> since I did the cherry-pick, none have failed due to `TestPipelineRunTimeout`. In previous testing on that branch, I saw it fail 7 times out of 34 runs. So...I think this does the trick. =)

@abayer glad to see these results, and thank you! 😀

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 1]
```diff
@@ -3259,7 +3401,7 @@ func TestGetTaskRunTimeout(t *testing.T) {
 				},
 			},
 		},
-		expected: &metav1.Duration{Duration: 10 * time.Minute},
+		expected: &metav1.Duration{Duration: 15 * time.Minute},
 	}, {
 		name: "taskrun with elapsed time; timeouts.pipeline applies",
```
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:3406]: Yeah, lemme change that.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go [hunk 2]
```diff
@@ -88,6 +88,9 @@ const (
 	// TaskRunSpecStatusCancelled indicates that the user wants to cancel the task,
 	// if not already cancelled or terminated
 	TaskRunSpecStatusCancelled = "TaskRunCancelled"
+	// TaskRunSpecStatusTimedOut indicates that the PipelineRun owning this task wants to mark it as timed out,
+	// if not already cancelled or terminated
+	TaskRunSpecStatusTimedOut = "TaskRunTimedOut"
```
Comment (lbernick) [inline pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: I'm not sure I understand why this is going in the spec. SpecStatusCancelled is for letting a user cancel the TaskRun, but I'm not sure we'd want to be able to set the spec to TimedOut

File: pkg/reconciler/pipelinerun/timeout.go [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+			Reason:  ReasonCouldntTimeOut,
+			Message: fmt.Sprintf("PipelineRun %q was timed out but had errors trying to time out TaskRuns and/or Runs: %s", pr.Name, e),
+		})
+		return fmt.Errorf("error(s) from timing out TaskRun(s) from PipelineRun %s: %s", pr.Name, e)
+	}
+	return nil
+}
+
+// timeoutPipelineTaskRuns patches `TaskRun` and `Run` with timed out status
+func timeoutPipelineTaskRuns(ctx context.Context, logger *zap.SugaredLogger, pr *v1beta1.PipelineRun, clientSet clientset.Interface) []string {
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/timeout.go:82]: this function name is confusing - made me think we were timing out `taskruns` but it's also timing out `runs`

can we split it into two functions - `timeoutTaskRuns` and `timeoutRuns`? then we call both of them in `timeoutPipelineRun`?

Comment (abayer) [reply pkg/reconciler/pipelinerun/timeout.go:82]: I'd actually go with renaming it to just `timeoutPipelineTasks` and keeping `TaskRun` and `Run` timeout in here - the name was just copy-pasted from `cancel.go` and renamed from `cancelPipelineTaskRuns`.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go [hunk 4]
```diff
@@ -424,6 +427,11 @@ func (tr *TaskRun) IsCancelled() bool {
 	return tr.Spec.Status == TaskRunSpecStatusCancelled
 }
 
+// IsSpecTimedOut returns true if the TaskRun's spec status is set to TimedOut state
+func (tr *TaskRun) IsSpecTimedOut() bool {
+	return tr.Spec.Status == TaskRunSpecStatusTimedOut
+}
+
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/taskrun_types.go:434]: please add tests for this function 🙏🏾

Comment (abayer) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:434]: Good catch!

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 5]
```diff
@@ -1141,12 +1151,10 @@ func calculateTaskRunTimeout(timeout time.Duration, pr *v1beta1.PipelineRun, rpt
 		if pElapsedTime > timeout {
 			return &metav1.Duration{Duration: 1 * time.Second}
 		}
-		timeRemaining := (timeout - pElapsedTime)
-		// Return the smaller of timeRemaining and rpt.pipelineTask.timeout
-		if rpt.PipelineTask.Timeout != nil && rpt.PipelineTask.Timeout.Duration < timeRemaining {
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1146]: To make sure I understand what's going on here, the timeout to be set for new taskruns and runs will now just be based on the pipelineTask timeout? If so, this logic can probably be simplified.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 6]
```diff
@@ -579,6 +582,13 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1beta1.PipelineRun, get
 	// Reset the skipped status to trigger recalculation
 	pipelineRunFacts.ResetSkippedCache()
 
+	// If the pipelinerun has timed out, mark tasks as timed out and update status
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun.go:585]: I think this is generally the right approach, but my concern is that this will only work for `timeouts.Pipeline` and not `timeouts.Tasks` or `timeouts.Finally`.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 7]
```diff
@@ -621,7 +631,7 @@ func (c *Reconciler) processRunTimeouts(ctx context.Context, pr *v1beta1.Pipelin
 	}
 	for _, rpt := range pipelineState {
 		if rpt.IsCustomTask() {
-			if rpt.Run != nil && !rpt.Run.IsCancelled() && (pr.HasTimedOut(ctx, c.Clock) || (rpt.Run.HasTimedOut(c.Clock) && !rpt.Run.IsDone())) {
+			if rpt.Run != nil && !rpt.Run.IsCancelled() && rpt.Run.HasTimedOut(c.Clock) && !rpt.Run.IsDone() {
```
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:634]: I'm going to add docstrings to clarify this.

**Review by lbernick — COMMENTED** [review]
I really like this approach and it will probably help with #4071 as well! Nice catch, this was a sneaky bug! One challenge here is that our test coverage for timeouts is not very good, and I think this will result in timeouts.tasks and timeouts.finally not working as intended.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 2 above)
Comment (abayer) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: @jerop's idea was to leverage the same approach we use when cancelling a `PipelineRun` to get its child `TaskRun`s and `Run`s to cancel as well, which is to set `spec.status` to`TaskRunSpecStatusCancelled`. If there's another way to signal the `TaskRun` that it should stop itself and report as timed out, I'm more than happy to see it. =)

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 5 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1146]: I'm updating the docstring on a new push shortly - let's see if that clarifies things for you?

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 6 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:585]: Ok, so this is all a bit messy and could definitely use a refactoring, but...

`getTaskRunTimeout` calls `calculateTaskRunTimeout` with `timeouts.Tasks` as the `timeout` parameter if `timeout.Tasks` is set, and otherwise with `timeouts.Pipeline`. So that covers `timeouts.Tasks`.

`getFinallyTaskRunTimeout` first calls `calculateTaskRunTimeout` with `timeouts.Pipeline` as the `timeout` parameter. Then it returns the lesser of the result of `calculateTaskRunTimeout` or `timeouts.Finally`. Which, in practice, should be the smallest of `PipelineTask.Timeout`, `timeouts.Finally`, or `timeouts.Pipeline`.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:634]: It's not actually duplication any more - `processRunTimeouts` and `timeoutPipelineTasks` both end up calling `cancelRun`, but the "should I time out the `Run`?" logic is different.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 2 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: could we reuse the timeout strategy we use for runs? https://github.com/tektoncd/pipeline/blob/d3b8017e652115ac102a5d10fc455240c1331a49/pkg/reconciler/pipelinerun/pipelinerun.go#L623-L648

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 6 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:585]: fwiw, I'd like to defer a refactor of the various functions/flow/etc for after this PR. I'd prefer to keep this PR focused on the behavioral change.

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:585]: Just to make sure I get it now - what we want is for `timeouts.Tasks` to result in task 1 getting the full value, task 2 to get the value minus the time since the `PipelineRun` started, etc? `timeouts.Finally` is a bit more confusing to me - we don't have a timestamp for when we started processing `finally` tasks, so it's harder to come up an equivalent bit of logic...

Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun.go:585]: Yeah exactly. For finally tasks, they all run in parallel, so they can all just get the smaller of (finally timeout, pipeline timeout - elapsed time). The one exception is retries of finally tasks which is a problem we haven't solved yet.

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:585]: Really, in general, I'm not sure what the point of `timeouts.Finally` is? `timeouts.Pipeline` is obvious, and I get `timeouts.Tasks` is meant to ensure that the non-finally tasks only take up so much of the run, but even before this change, what was the practical impact of `timeouts.Finally`? 

If `timeouts.Tasks+timeouts.Finally < timeouts.Pipeline`, then we never hit `timeouts.Pipeline`, and if `timeouts.Tasks+timeouts.Finally == timeouts.Pipeline`, then we're always timing out finally tasks based on the overall `PipelineRun` timeout anyway...

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 8]
```diff
@@ -1135,7 +1146,9 @@ func getFinallyTaskRunTimeout(ctx context.Context, pr *v1beta1.PipelineRun, rpt
 func getTaskRunTimeout(ctx context.Context, pr *v1beta1.PipelineRun, rpt *resources.ResolvedPipelineTask, c clock.PassiveClock) *metav1.Duration {
 	var timeout time.Duration
 	if pr.TasksTimeout() != nil {
-		timeout = pr.TasksTimeout().Duration
+		// Subtract the current run time of the PipelineRun from the tasks timeout to ensure that the maximum timeout for this task
+		// is the remaining time in the tasks timeout since the PipelineRun was started.
+		timeout = pr.TasksTimeout().Duration - c.Since(pr.Status.StartTime.Time)
```
Comment (abayer) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1151]: @lbernick - I think this solves the `timeouts.Tasks` issue you raised.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 6 above)
Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun.go:594]: I think you can specify `timeouts.Finally` without specifying `timeouts.Pipeline`

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 9]
```diff
@@ -2569,6 +2597,56 @@ status:
...
+	prs := []*v1beta1.PipelineRun{parse.MustParsePipelineRun(t, `
+metadata:
+  name: test-pipeline-run-with-timeout
+  namespace: foo
+spec:
+  pipelineRef:
+    name: test-pipeline
+  serviceAccountName: test-sa
+  timeouts:
+    tasks: 15m
```
Comment (abayer) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:2613]: @lbernick - here's a test verifying that the new `TaskRun` gets a timeout of `timeouts.Tasks` minus the current run time of the `PipelineRun`.

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 10]
```diff
@@ -3430,26 +3622,6 @@ func TestGetFinallyTaskRunTimeout(t *testing.T) {
 			},
 		},
 		expected: &metav1.Duration{Duration: 15 * time.Minute},
-	}, {
-		name: "finally taskrun with elapsed time; timeouts.pipeline applies",
```
Comment (abayer) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:3434]: I removed this because what it was testing for - finally tasks getting the remaining time in `timeouts.Pipeline` as their timeout, rather than `timeouts.Finally` or `PipelineTask.Timeout` - is no longer relevant, since that's exactly the behavior we're replacing with the signal approach.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 6 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:594]: Actually, in practice, if you don't specify `timeouts.Pipeline`, you get a default timeout of 60m for the whole `PipelineRun`, and if you specify 0 for `timeouts.Pipeline`, you'll get a validation error. I think. It's all a bit messy. It feels like if we want to support the scenario of no timeout on the `PipelineRun` as a whole but an explicit timeout just for finally tasks, we'd need to pass validation when `timeouts.Finally` is greater than `timeouts.Pipeline` and `timeouts.Pipeline` is 0 (aka `config.NoTimeoutDuration`), and then add a field to `PipelineRunStatusFields` like `FinallyStartTime` to track when we started running the finally tasks...

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 2 above)
Comment (vdemeester) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: I tend to agree with @abayer there

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 9 above)
Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:2613]: sorry, I still think this doesn't work. The pipelinerun started 1 day before ["now"](https://github.com/tektoncd/pipeline/blob/a0c7d31e23f472cca39690410253a0739f3189db/pkg/reconciler/pipelinerun/pipelinerun_test.go#L104-L105), but its tasks timeout is 15 minutes. This means the task has already exceeded its timeout and will be created with a timeout of 1s [here](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/pipelinerun.go#L1154-L1156). (That's a known bug I've been wrestling with.)

I think the test case we actually want is a pipelinerun with some elapsed time having occurred, but still not having passed its "tasks" timeout. Previously, we would have set the taskrun timeout to the tasks timeout minus the elapsed time (covered in the test case below called "taskrun with elapsed time; task.timeout applies"), but it sounds like now, the new approach will be for the pipelinerun to cancel all taskruns when the "tasks" timeout is exceeded.

If it would be helpful, I can create a PR adding some test cases to the PR reconciler with what I have in mind and you can rebase onto that, so it's easier to tell what your PR changes? (I think it will be helpful regardless)

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:2613]: Right, that's actually what this test does - the `PipelineRun` started 5 minutes before "now" - `startTime: "2021-12-31T23:55:00Z"`. =)

**Comment by vdemeester** [comment]
SGTM 👍🏼

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 2 above)
Comment (afrittoli) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: I would argue that if it's the `PipelineRun` that times out, the `TaskRun` itself did not timeout, but it was cancelled because of some timeout logic that the `TaskRun` itself is not aware of. 
I think using cancellation might actually help users identity where the timeout occurred. We could add a place for the canceller to give an explanation or reason for the cancellation.
Using cancellation might be even more helpful when doing pipeline in pipeline, where the chain of cancellations may go deeper.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 6 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:594]: I'm seriously tempted to add new `TasksStartTime` and `FinallyStartTime` fields to `PipelineRunStatusFields`, and rather than setting explicit timeouts on child `TaskRun`s and `Run`s, have the `PipelineRun` reconciler check `now - TasksStartTime > Timeouts.Tasks` and `now - FinallyStartTime > Timeouts.Finally`, then cancel/timeout the child tasks when that's the case...

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:594]: (though when I took a quick look to see how one would go about adding `FinallyStartTime`, I didn't find an obvious way to tell when we've switched to executing finally tasks)

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 9 above)
Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:2613]: oh oops I didn't look at the start time carefully enough!

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 2 above)
Comment (abayer) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: 👍

**Comment by abayer** [comment]
https://github.com/tektoncd/pipeline/pull/5134/commits/6275baa83e1406d2545094f87bb1c276a3ff0597 changes handling of `Timeouts.Tasks` and `Timeouts.Finally` to also be done via signaling - I _think_ (or at least hope!) that this is the comprehensive solution. =)

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 2 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: I think a user shouldn't need to provide a cancellation reason, and the PR controller can provide the reason for cancelling the taskrun, so I'm not sure we need to change `pipelineRun.spec.status`, however we might need to add a field to `taskrun.spec.status`

Comment (abayer) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:93]: Oops, yeah, I meant `taskRun.spec.status`. Also I forgot to delete this in my latest commit. heh.

Comment (afrittoli) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go]: I agree a user shouldn't need to provide a cancellation reason, but they might want to - it could be an interesting possibility to give our users for auditing. That said, the same could be achieved a bit more loosely with annotations.

**Comment by abayer** [comment]
/retest

Unit tests are getting weirdly flaky lately...

**Comment by abayer** [comment]
Ok, an annoying quirk of the "just use `TaskRunSpecStatusCancelled`" approach vs the distinct `TaskRunSpecStatusTimedOut` - depending on which of the `TaskRun` or `PipelineRun` gets reconciled first after the overall `PipelineRun` timeout is reached, you'll either get a reason of `TaskRunCancelled` if the `PipelineRun` gets timed out first, or `TaskRunTimedOut` if the `TaskRun` gets reconciled first. That inconsistency is not ideal.

I'm rolling back to having `TaskRunSpecStatusTimedOut` for now so that at least there's a consistent reason for the `TaskRun` being killed.

**Comment by lbernick** [comment]
would it make sense to block on https://github.com/tektoncd/pipeline/issues/5150 being implemented first?

> Ok, an annoying quirk of the "just use `TaskRunSpecStatusCancelled`" approach vs the distinct `TaskRunSpecStatusTimedOut` - depending on which of the `TaskRun` or `PipelineRun` gets reconciled first after the overall `PipelineRun` timeout is reached, you'll either get a reason of `TaskRunCancelled` if the `PipelineRun` gets timed out first, or `TaskRunTimedOut` if the `TaskRun` gets reconciled first. That inconsistency is not ideal.

If we swap the TaskRun timeout to be just based on the PipelineTask timeout, it seems like this would only happen if the PipelineTask timeout happened to expire at the same time one of the PipelineRun's timeouts expired. Am I missing something?

**Comment by abayer** [comment]
> If we swap the TaskRun timeout to be just based on the PipelineTask timeout, it seems like this would only happen if the PipelineTask timeout happened to expire at the same time one of the PipelineRun's timeouts expired. Am I missing something?

Yup, that's exactly what I was seeing happen, hence rolling back to `TaskRunSpecStatusTimedOut` for the moment, at least.

And yeah, might make sense to hold this until #5150 lands. I felt like it could go in either order, but that was in part because I was planning on switching to `TaskRunSpecStatusCancelled` until discovering the timing issue. But #5150's approach should let us set the failure reason for the `TaskRun` to timed out for a cancellation with a timeout reason, maybe?

**Comment by abayer** [comment]
I've marked this as WIP until we nail down the ordering between this change and #5150.

**Comment by lbernick** [comment]
chatted with Andrew-- will be easier to implement once #5150 is landed

**Comment by abayer** [comment]
cc @lbernick, @jerop, @afrittoli, @vdemeester - with #5224 merged, I've updated this PR accordingly, and I think it's ready to go.

**Comment by abayer** [comment]
Whoops - missed a couple things! Fixing.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 11]
```diff
@@ -238,6 +238,59 @@ func (t ResolvedPipelineTask) hasRemainingRetries() bool {
...
+			return false
+		}
+		isDone := true
+		atLeastOneCancelled := false
+		for _, run := range t.Runs {
+			isDone = isDone && run.IsDone()
+			c := run.Status.GetCondition(apis.ConditionSucceeded)
+			runCancelled := c.IsFalse() &&
+				c.Reason == v1alpha1.RunReasonCancelled &&
+				run.Spec.StatusMessage == v1alpha1.RunCancelledByPipelineTimeoutMsg
```
Comment (abayer) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:256]: I don't love having to do this, but we needed some way to determine that a `Run` or `TaskRun` that was nominally cancelled due to the `PipelineRun` deciding it had timed out was cancelled for that reason and marked as a failure, for consistency with how we behave if a `TaskRun`/`Run` with an explicit timeout set on its spec times out. The easiest way to do that was to look at `.Spec.StatusMessage`, which will be set on any `Run` or `TaskRun` we cancel-for-time-out.

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go [hunk 12]
```diff
@@ -417,6 +417,10 @@ type PipelineRunStatusFields struct {
 	// +optional
 	// +listType=atomic
 	ChildReferences []ChildStatusReference `json:"childReferences,omitempty"`
+
+	// FinallyStartTime is when all non-finally tasks have been completed and only finally tasks are being executed.
```
Comment (lbernick) [inline pkg/apis/pipeline/v1beta1/pipelinerun_types.go:421]: I'm wondering if there's a way to look at any of the finally TaskRuns and get their start time? Or would this introduce more race conditions?

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 13]
```diff
@@ -1116,18 +1170,22 @@ func addMetadataByPrecedence(metadata map[string]string, addedMetadata map[strin
 // If there is no timeout for the finally TaskRun, returns 0.
 // If pipeline level timeouts have already been exceeded, returns 1 second.
 func getFinallyTaskRunTimeout(ctx context.Context, pr *v1beta1.PipelineRun, rpt *resources.ResolvedPipelineTask, c clock.PassiveClock) *metav1.Duration {
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1172]: I'd like to propose the following strategy:

- Set a taskrun/run's timeout to the timeout of the pipeline task
- when a pipelinerun has hit its tasks timeout, cancel all the non-finally tasks
- when a pipelinerun has hit its finally timeout, cancel all the finally tasks
- when a pipelinerun has hit its pipeline timeout, cancel all the tasks

the functions `getFinallyTaskRunTimeout` and `getTaskRunTimeout` can go away entirely

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 11 above)
Comment (lbernick) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:256]: I'm not sure I understand the reason for this-- I only see this function used in pipelinerunstate.go to increment the count of failed tasks. why is this necessary?

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:256]: Because otherwise a `Run` or `TaskRun` that gets cancelled-for-timeout will show up in `facts.getPipelineTasksCount()` as cancelled, and [the `PipelineRun` itself will be marked as cancelled](https://github.com/tektoncd/pipeline/blob/bd8958cb09e1f75f95c7d7edce3e4b54f5c861f9/pkg/reconciler/pipelinerun/resources/pipelinerunstate.go#L505-L509).

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go (hunk 12 above)
Comment (abayer) [reply pkg/apis/pipeline/v1beta1/pipelinerun_types.go:421]: I thought about this, but at best it'd be messy, and I can't rule out the possibility of race conditions, inconsistent behavior, etc, so I opted for this. It's not bad information to have in general, I think - the dashboard or CLI or some other downstream consumer of `PipelineRun`s can just look at this field (plus `StartTime` and `CompletionTime`) to see how long just tasks took and how long finally tasks took, etc.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 13 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: That's basically what we're doing in this PR, isn't it? With the caveat that in `calculateTaskRunTimeout`, we're also checking if the current time is past the appropriate `.timeouts` value (calculating based on `StartTime` or `FinallyStartTime` for `.timeouts.tasks` and `.timeouts.finally` respectively, falling back to `.timeouts.pipeline` when `.timeouts.tasks` or `.timeouts.finally` is unset) to do the admittedly hacky 1s timeout for "too late to launch" tasks, then falling back on `PipelineTask.Timeout`, so it's slightly more complicated.

So I guess you'd like to get rid of the 1s timeout for "too late to launch" tasks, since that's the only real difference from what you're proposing. I do not care for the 1s thing, so if you have any suggestions for an alternative that retains the general behavior we've got currently, I'm more than open to it. =) I'll also poke at the code to see if anything comes to mind myself.

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: Ok, so I think we could switch from the "make this fail right away" 1s timeout to returning -1 as the timeout duration, and instead marking the task as skipped (with a new skipped reason for being past timeout) if we're past the latest possible launch time for it. That seems like a good idea to me, but it still would require `calculateTaskRunTimeout`, `getFinallyTaskRunTimeout`, and `getTaskRunTimeout`, _and_ would be a decent refactor. So I don't think that would simplify the code in the context of this PR, and it feels like it's a separate issue/change.

Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: I think this PR is sort of doing what I described in that it's cancelling the taskruns when the appropriate timeout is reached. I'm suggesting removing the logic that takes `pipelinerun.spec.timeouts` into account when setting `taskrun.timeout`. I don't think it should be needed anymore, and I would think it will continue to lead to the type of race conditions this PR is attempting to fix.

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: The reason that logic is there is to deal with the cases where we go to create a `TaskRun`/`Run` but we're already past the `.timeouts.tasks` or `.timeouts.finally` timeout for that `TaskRun`/`Run` - that's what I was talking about redoing separately to not create a `TaskRun`/`Run` with a `1s` timeout in those scenarios, but instead to mark that task as skipped. Which, like I said, I think should be in a separate PR.

Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: ok, I think I understand. I'm wondering if instead we can change the logic so the PipelineRun doesn't continue on to `runNextSchedulableTask` if it's reached its `pipeline` timeout or `finally` timeout? I guess we'd have to write some function like `runFinallyTasks` for if it reaches its `tasks` timeout.
basically, within `reconcile`, it feels like we need a way to transition into the `finally` stage or something, similar to [finishReconcileUpdateEmitEvents](https://github.com/tektoncd/pipeline/blob/deb0fec6e861ed9c74c7f43791b6e52823a62e0d/pkg/reconciler/pipelinerun/pipelinerun.go#L263)

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: Yeah, I'd have to think about it - this is why I think it's a separate issue. =)

Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: Hm I am not sure we can push this off for a follow-up PR, because I think the strategy being used here introduces a new race condition (for timeouts.tasks and timeouts.finally) even as it's fixing an existing one

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: What's the race condition?

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: Ah, yeah, that is possible, though I think significantly less likely than the current race condition. I'd still prefer to immediately follow up with revamping the "don't run after timeout" logic in a separate PR, just to keep this one from getting more complex, but I'll defer to your judgment there.

Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: I think it'll happen whenever a user configures `timeouts.tasks`. Could you maybe experiment with another commit on top of this one? While I want to avoid making this PR more complex, refactoring the behavior we're talking about could be good to do first, as it'll allow us to remove the functions `getFinallyTaskRunTimeout` and `getTaskRunTimeout` entirely.

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1172]: I'm playing around with having `ResolvedPipelineTask.Skip(facts)` mark a task as skipped if it's past the `tasks` or `finally` timeout right now, which feels like the right way to do it to me. =)

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go]: @lbernick Take a look at https://github.com/tektoncd/pipeline/pull/5134/commits/daf32f408d70c417da898effbdba465da7c89a14 - that's my first draft of the skipping approach.

File: pkg/reconciler/pipelinerun/resources/pipelinerunstate.go [hunk 14]
```diff
@@ -51,10 +52,16 @@ type PipelineRunState []*ResolvedPipelineTask
...
+	State            PipelineRunState
+	SpecStatus       v1beta1.PipelineRunSpecStatus
+	TasksGraph       *dag.Graph
+	FinalTasksGraph  *dag.Graph
+	StartTime        *time.Time
+	FinallyStartTime *time.Time
+	PipelineTimeout  *time.Duration
+	TasksTimeout     *time.Duration
+	FinallyTimeout   *time.Duration
+	Clock            clock.PassiveClock
```
Comment (abayer) [inline pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:64]: The most direct way to get this information available to the new functions on `ResolvedPipelineTask` was to add them to `PipelineRunFacts` - but I feel like it's probably not the _optimal_ way to do it. This is just a first draft on getting rid of `getFinallyTaskRunTimeout` and `getTaskRunTimeout` completely, so I am completely open to alternative approaches for getting this information available to `skipBecausePipelineRunPipelineTimeoutReached`, `skipBecausePipelineRunTasksTimeoutReached`, and `skipBecausePipelineRunFinallyTimeoutReached`.

File: pkg/reconciler/pipelinerun/resources/pipelinerunstate.go [hunk 15]
```diff
@@ -643,12 +674,20 @@ func (facts *PipelineRunFacts) getPipelineTasksCount() pipelineRunStatusCount {
...
 		case t.isCancelled():
 			s.Cancelled++
 		// increment failure counter since the task has failed
 		case t.isFailure():
 			s.Failed++
+		// increment failure counter since the task was skipped due to the pipeline, tasks, or finally timeout being reached before the task was launched
+		case t.Skip(facts).SkippingReason == v1beta1.PipelineTimedOutSkip ||
+			t.Skip(facts).SkippingReason == v1beta1.TasksTimedOutSkip ||
+			t.IsFinallySkipped(facts).SkippingReason == v1beta1.FinallyTimedOutSkip:
+			s.Failed++
```
Comment (abayer) [inline pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:690]: The reason for this is that the current behavior when a `TaskRun` or `Run` is "created" after the appropriate timeout (`.timeouts.pipeline`, `.timeouts.tasks`, `.timeouts.finally`) has been reached is to actually create the `TaskRun`/`Run`, but with a timeout of `1s`, so that it fails immediately. While I believe that having `rpt.Skip(facts).IsSkipped` return true for `ResolvedPipelineTask`s which shouldn't be created due to timeouts is a much better approach, without this additional change, the `PipelineRun` wouldn't end up marked as failed, because the tasks are marked as skipped. So let's categorize them as failed instead here.

**Comment by abayer** [comment]
/hold

ping @lbernick as a reminder that you said you'd take a look at my attempt to rework after-pipeline-timeout `TaskRun`/`Run` creation handling. =)

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 6 above)
Comment (lbernick) [reply pkg/reconciler/pipelinerun/pipelinerun.go:641]: I think this conversation can be resolved!

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 16]
```diff
@@ -698,45 +756,56 @@ func (c *Reconciler) runNextSchedulableTask(ctx context.Context, pr *v1beta1.Pip
 	}
 
 	for _, rpt := range nextRpts {
+		if rpt.IsFinalTask(pipelineRunFacts) {
+			c.setFinallyStartedTimeIfNeeded(pr)
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun.go:760]: should this function also receive a pointer to pipelinerun facts and be responsible for updating that as well?

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 17]
```diff
@@ -1112,63 +1192,6 @@ func addMetadataByPrecedence(metadata map[string]string, addedMetadata map[strin
 	}
 }
 
-// getFinallyTaskRunTimeout returns the timeout to set when creating the ResolvedPipelineTask, which is a finally Task.
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1115]: I'm so happy to see these functions go away :D

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 18]
```diff
@@ -1770,9 +1794,9 @@ status:
 			}
 
 			gotTimeoutValue := postReconcileRun.GetTimeout()
-			expectedTimeoutValue := time.Second
+			expectedTimeoutValue := time.Hour
 
-			if d := cmp.Diff(gotTimeoutValue, expectedTimeoutValue); d != "" {
+			if d := cmp.Diff(expectedTimeoutValue, gotTimeoutValue); d != "" {
 				t.Fatalf("Expected timeout for created Run, but got a mismatch %s", diff.PrintWantGot(d))
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:1800]: I think this block should be removed. We are no longer changing the timeout for the run after it's created.

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 19]
```diff
@@ -2521,17 +2545,16 @@ status:
...
-	actual := getTaskRunCreations(t, clients.Pipeline.Actions(), 2)[0]
-
-	// The TaskRun timeout should be less than or equal to the PipelineRun timeout.
-	if actual.Spec.Timeout.Duration > prs[0].Spec.Timeout.Duration {
-		t.Errorf("TaskRun timeout %s should be less than or equal to PipelineRun timeout %s", actual.Spec.Timeout.Duration.String(), prs[0].Spec.Timeout.Duration.String())
+	// Check that there is a skipped task for the expected reason
+	if len(reconciledRun.Status.SkippedTasks) != 1 {
+		t.Errorf("expected one skipped task, found %d", len(reconciledRun.Status.SkippedTasks))
+	} else if reconciledRun.Status.SkippedTasks[0].Reason != v1beta1.PipelineTimedOutSkip {
+		t.Errorf("expected skipped reason to be '%s', but was '%s", v1beta1.PipelineTimedOutSkip, reconciledRun.Status.SkippedTasks[0].Reason)
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:2552]: could you please update the description of the test to explain that it verifies that no new runs are created, and that the pipeline task is marked as skipped?

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 20]
```diff
@@ -1743,16 +1739,44 @@ spec:
...
+      pipelineTaskName: hello-world-1
+      status:
+        conditions:
+        - status: Unknown
+          type: Succeeded
 `)}
 			prs[0].Spec.Timeout = tc.timeout
 			prs[0].Spec.Timeouts = tc.timeouts
 
+			runs := []*v1alpha1.Run{mustParseRunWithObjectMeta(t,
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:1759]: As far as I know this is the only timeout test where the existing runs/taskruns have already been created. (The other ones have the runs/taskruns not created yet.) I think we should test the cases where runs/taskruns have already been created, and are canceled after timeouts.tasks and timeouts.finally.

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 21]
```diff
@@ -6541,7 +6430,7 @@ spec:
 		map[string]string{},
 	)
 
-	if d := cmp.Diff(actualTaskRun, expectedTaskRun); d != "" {
+	if d := cmp.Diff(expectedTaskRun, actualTaskRun); d != "" {
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:6433]: Thank you for fixing these changes! would you be OK splitting changes to pipelinerun tests that aren't related to this PR into a separate one?

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 11 above)
Comment (lbernick) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:256]: It seems weird that we decide whether the PipelineRun is canceled based on whether any of its child taskruns are canceled; I would think it should be the other way around. can we change this?

**Review by lbernick — COMMENTED** [review]
Thanks Andrew! I really like where this PR is going; I think it looks much better!

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 22]
```diff
@@ -577,6 +601,32 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1beta1.PipelineRun, get
...
+		}
+	} else if pr.Spec.Timeouts != nil &&
+		pr.Spec.Timeouts.Finally != nil &&
+		pr.Spec.Timeouts.Finally.Duration != apisconfig.NoTimeoutDuration &&
+		c.Clock.Since(pr.Status.FinallyStartTime.Time) > pr.Spec.Timeouts.Finally.Duration {
+		logger.Infof("PipelineRun finally timeout of %s reached, cancelling finally tasks", pr.Spec.Timeouts.Finally.Duration.String())
+		errs := timeoutPipelineTasksForTaskNames(ctx, logger, pr, c.PipelineClientSet, pipelineRunFacts.GetFinalTaskNames())
+		if len(errs) > 0 {
+			errString := strings.Join(errs, "\n")
+			logger.Errorf("Failed to timeout tasks for PipelineRun %s/%s: %s", pr.Name, pr.Name, errString)
```
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:625]: 👍

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 23]
```diff
@@ -577,6 +601,32 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1beta1.PipelineRun, get
 		return controller.NewPermanentError(err)
 	}
 
+	if pr.Status.FinallyStartTime == nil {
+		if pr.Spec.Timeouts != nil &&
+			pr.Spec.Timeouts.Tasks != nil &&
+			pr.Spec.Timeouts.Tasks.Duration != apisconfig.NoTimeoutDuration &&
+			c.Clock.Since(pr.Status.StartTime.Time) > pr.Spec.Timeouts.Tasks.Duration {
+			logger.Infof("PipelineRun tasks timeout of %s reached, cancelling tasks", pr.Spec.Timeouts.Tasks.Duration.String())
+			errs := timeoutPipelineTasksForTaskNames(ctx, logger, pr, c.PipelineClientSet, pipelineRunFacts.GetTaskNames())
```
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:610]: It'll still update the `spec.status` - so yeah, I'll tweak these calls to filter out finished pipeline tasks.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 16 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:760]: Good idea!

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 18 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:1800]: 👍

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 19 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:2552]: 👍

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 20 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:1759]: Good point. I'll add that.

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 21 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:6433]: These changes are so minor that I'd prefer to just leave them in here if that's alright.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 24]
```diff
@@ -577,6 +601,32 @@ func (c *Reconciler) reconcile(ctx context.Context, pr *v1beta1.PipelineRun, get
 		return controller.NewPermanentError(err)
 	}
 
+	if pr.Status.FinallyStartTime == nil {
+		if pr.Spec.Timeouts != nil &&
+			pr.Spec.Timeouts.Tasks != nil &&
+			pr.Spec.Timeouts.Tasks.Duration != apisconfig.NoTimeoutDuration &&
+			c.Clock.Since(pr.Status.StartTime.Time) > pr.Spec.Timeouts.Tasks.Duration {
```
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:608]: 👍

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 11 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:256]: Since that's a behavioral change outside of the scope of the particular issue I'm trying to fix here, I'd prefer to deal with that separately.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 25]
```diff
@@ -422,6 +479,45 @@ func (t *ResolvedPipelineTask) skipBecauseResultReferencesAreMissing(facts *Pipe
...
+	if t.checkParentsDone(facts) && t.IsFinalTask(facts) {
+		if facts.FinallyTimeout != nil && *facts.FinallyTimeout != config.NoTimeoutDuration && facts.FinallyStartTime != nil {
+			// If the elapsed time since the PipelineRun's finally start time is greater than the the PipelineRun's finally timeout, skip.
+			return facts.Clock.Since(*facts.FinallyStartTime) > *facts.FinallyTimeout
+		}
+	}
+
+	return false
+}
+
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:520]: these scenarios for not scheduling a taskrun or run because of timeouts could be included in "stopping mode" - this will also prevent complicating the skipping logic further (already handles "stopping mode") - what do you think @abayer?

https://github.com/abayer/tektoncd-pipeline/blob/8b740d50ef106c9cf633634851615ac316289a54/pkg/reconciler/pipelinerun/resources/pipelinerunstate.go#L357-L368

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 26]
```diff
@@ -440,6 +536,10 @@ func (t *ResolvedPipelineTask) IsFinallySkipped(facts *PipelineRunFacts) TaskSki
 			skippingReason = v1beta1.MissingResultsSkip
 		case t.skipBecauseWhenExpressionsEvaluatedToFalse(facts):
 			skippingReason = v1beta1.WhenExpressionsSkip
+		case t.skipBecausePipelineRunPipelineTimeoutReached(facts):
+			skippingReason = v1beta1.PipelineTimedOutSkip
+		case t.skipBecausePipelineRunFinallyTimeoutReached(facts):
+			skippingReason = v1beta1.FinallyTimedOutSkip
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:542]: just noticing that stopping mode is not handled in `IsFinallySkipped` 🤔 

expected it to be here, or do we check if it's in stopping mode before starting finally tasks (which run in parallel)?

**Review by jerop — COMMENTED** [review]
thanks for the hard work here @abayer!

what do you think of folding the "not scheduling new taskrun or run due to timeout" into "stopping mode"?

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 26 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:542]: I feel like we wouldn't want to be "stopping" if one of the finally tasks fails, since they're running in parallel...

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:542]: Oh, and `IsStopping` would return true if any of the non-finally tasks failed, so we definitely don't want to use that as a signal to not run finally tasks!

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 25 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:520]: Good question! I _think_ I prefer having the explicit checks for `.timeouts.tasks`, `.timeouts.finally`, and `.timeouts.pipeline` - that lets us set a more specific reason for skipping pertinent tasks, but I'm willing to be persuaded otherwise.

**Comment by pritidesai** [comment]
Hey @abayer, I would like to understand this before we merge. I will take a look at this after I am done reviewing https://github.com/tektoncd/pipeline/pull/5039 which is not related but open since early this year. I am putting this on hold to make sure I get a chance to review. Please feel free to cancel the hold if you get sufficient reviews 🙏 

/hold

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 27]
```diff
@@ -101,6 +101,8 @@ const (
 	// RunCancelledByPipelineMsg indicates that the PipelineRun of which part this Run was
 	// has been cancelled.
 	RunCancelledByPipelineMsg RunSpecStatusMessage = "Run cancelled as the PipelineRun it belongs to has been cancelled."
+	// RunCancelledByPipelineTimeoutMsg indicates that the Run was cancelled because the PipelineRun running it timed out.
+	RunCancelledByPipelineTimeoutMsg RunSpecStatusMessage = "Run cancelled as the PipelineRun it belongs to has timed out."
```
Comment (pritidesai) [inline pkg/apis/pipeline/v1alpha1/run_types.go:105]: Is this status message visible to the user?

Comment (abayer) [reply pkg/apis/pipeline/v1alpha1/run_types.go:105]: It shows up as the condition message on the `TaskRun` or `Run`.

**Comment by abayer** [comment]
Adding this to the v0.39 milestone, because I'd really like to get this done. cc @pritidesai @lbernick for updated reviews. Thanks!

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 28]
```diff
@@ -236,8 +239,14 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1beta1.PipelineRun)
 	if pr.Status.StartTime != nil {
 		// Compute the time since the task started.
 		elapsed := c.Clock.Since(pr.Status.StartTime.Time)
-		// Snooze this resource until the timeout has elapsed.
-		return controller.NewRequeueAfter(pr.PipelineTimeout(ctx) - elapsed)
+		// Snooze this resource until the appropriate timeout has elapsed.
+		waitTime := pr.PipelineTimeout(ctx) - elapsed
+		if pr.Status.FinallyStartTime == nil && pr.TasksTimeout() != nil {
+			waitTime = pr.TasksTimeout().Duration - elapsed
+		} else if pr.FinallyTimeout() != nil {
```
Comment (lbernick) [inline pkg/reconciler/pipelinerun/pipelinerun.go:246]: this logic might not be quite right if the time until a Pipeline timeout is less than the time until a finally timeout. Ex: Pipeline timeout is 10 minutes, finally timeout is 9 minutes, and finally tasks started 5 minutes into execution.

**Comment by lbernick** [comment]
This looks really good other than the one bug I mentioned! Just want to double check that this still fixes the race condition after your changes?

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 28 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:246]: Good catch - it should always be the smallest. Fixing.

**Comment by abayer** [comment]
> This looks really good other than the one bug I mentioned! Just want to double check that this still fixes the race condition after your changes?

As far as I can tell so far, yes. I haven't been able to reproduce the race, at least, and previously was able to after enough test runs.

File: pkg/reconciler/pipelinerun/cancel.go [hunk 29]
```diff
@@ -136,9 +141,15 @@ func cancelPipelineTaskRuns(ctx context.Context, logger *zap.SugaredLogger, pr *
 	return errs
 }
 
-// getChildObjectsFromPRStatus returns taskruns and runs in the PipelineRunStatus's ChildReferences or TaskRuns/Runs,
+// getChildObjectsFromPRStatus returns all taskruns and runs in the PipelineRunStatus's ChildReferences or TaskRuns/Runs,
 // based on the value of the embedded status flag.
 func getChildObjectsFromPRStatus(ctx context.Context, prs v1beta1.PipelineRunStatus) ([]string, []string, error) {
+	return getChildObjectsFromPRStatusForTaskNames(ctx, prs, sets.NewString())
+}
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/cancel.go:148]: is this function still used? can't seem to find it in use 🤔 

also it's a wrapper around `getChildObjectsFromPRStatusForTaskNames` so if there's any use, can we remove it and use `getChildObjectsFromPRStatusForTaskNames` directly?

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 30]
```diff
@@ -748,6 +804,16 @@ func (c *Reconciler) runNextSchedulableTask(ctx context.Context, pr *v1beta1.Pip
...
 
+// setFinallyStartedTimeIfNeeded sets the PipelineRun.Status.FinallyStartedTime to the current time if it's nil.
+func (c *Reconciler) setFinallyStartedTimeIfNeeded(pr *v1beta1.PipelineRun, facts *resources.PipelineRunFacts) {
+	if pr.Status.FinallyStartTime == nil {
+		pr.Status.FinallyStartTime = &metav1.Time{Time: c.Clock.Now()}
+	}
+	if facts.FinallyStartTime == nil {
+		facts.FinallyStartTime = &pr.Status.FinallyStartTime.Time
+	}
+}
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/pipelinerun.go:815]: can we be in a state where `facts.FinallyStartTime` is not nil but `pr.Status.FinallyStartTime` was nil? can those values could ever be different? if so, what's the source of truth (maybe facts because pipelinerun status can be modified)? or could we have this value recorded at one point only?

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 17 above)
Comment (jerop) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1115]: same here, thanks @abayer 🎉

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 11 above)
Comment (jerop) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:259]: so I understand, the current behavior is that both:
1. when a pipelinerun is cancelled, all its taskruns are cancelled
2. when a taskrun is cancelled, the parent pipelinerun is also cancelled

is that correct @abayer @lbernick?

File: pkg/reconciler/pipelinerun/resources/pipelinerunstate.go (hunk 14 above)
Comment (jerop) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:64]: I suggest that we group the timeouts state fields that are referenced in `PipelineRunFacts`, such as is done for `State`, what do you think @abayer? 

For example:

```go

type PipelineRunFacts struct {
	State            PipelineRunState
	SpecStatus       v1beta1.PipelineRunSpecStatus
	TasksGraph       *dag.Graph
	FinalTasksGraph  *dag.Graph
        TimeoutsState       PipelineRunTimeoutsState
}

type PipelineRunTimeoutsState struct {
	StartTime        *time.Time
	FinallyStartTime *time.Time
	PipelineTimeout  *time.Duration
	TasksTimeout     *time.Duration
	FinallyTimeout   *time.Duration
	Clock            clock.PassiveClock
}
```

I think it makes the code cleaner, and easier to pass around the timeouts state from facts to other functions, instead of passing `PipelineRunFacts` as a whole or the list of timeouts fields as arguments

**Review by jerop — COMMENTED** [review]
thanks again @abayer!

File: pkg/reconciler/pipelinerun/cancel.go (hunk 29 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/cancel.go:148]: Good call - doing so now.

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 30 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun.go:815]: I can't think of a scenario where we could be - the nil checks are just to be perfectly safe.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 11 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:259]: Yeah, the `PipelineRun` reconciler will mark the `PipelineRun` as cancelled if any of the `TaskRun`s or `Run`s in it are marked as cancelled.

File: pkg/reconciler/pipelinerun/resources/pipelinerunstate.go (hunk 14 above)
Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:64]: 👍

File: pkg/reconciler/pipelinerun/resources/pipelinerunstate.go (hunk 15 above)
Comment (jerop) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:694]: What about `PipelineRun.Status.SkippedTasks` -- I think it'd be confusing if these `Tasks` are still listed in `SkippedTasks` but they are not counted as skipped Tasks in another part of the status

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:694]: That's a good question. I guess we could special-case things to keep them out of `SkippedTasks` too...

Also, in practice, there's a real question as to whether it actually matters if they're marked as cancelled/skipped or failed - if the `PipelineRun` gets past the relevant timeout, there's only the tiniest of chances that all previous tasks succeeded before it hit the timeout. So perhaps we can just not worry about it and update the tests accordingly.

Comment (jerop) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:694]: or we could leave them as skipped tasks instead of counting these skipped tasks as failed tasks in this section of the status only

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:694]: Actually, I think I like the idea of adding a `SkippedDueToTimeout` counter alongside `Skipped`, `Failed`, etc, incrementing both that counter and `Skipped` when a task is skipped due to timeout. Then, when setting the `PipelineRun` status, we change the "did this fail" case to `s.Failed > 0 || s.SkippedDueToTimeout > 0`. That keeps the overall `PipelineRun` status as failed for timeout skips, but also keeps the tasks in `SkippedTasks`.

Comment (jerop) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:694]: I like that idea, let's do it 🚀

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go]: Done. =)

File: pkg/reconciler/pipelinerun/resources/pipelinerunstate.go [hunk 31]
```diff
@@ -467,7 +506,7 @@ func (facts *PipelineRunFacts) GetPipelineConditionStatus(ctx context.Context, p
 		}
 
 		switch {
-		case s.Failed > 0:
+		case s.Failed > 0 || s.SkippedDueToTimeout > 0:
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:509]: we need to update the `message` added to the pipelinerun status to include `SkippedDueToTimeout`

https://github.com/tektoncd/pipeline/blob/ef73cfecafaf5b3870f5b3c7d2b83f99c73d50fd/pkg/reconciler/pipelinerun/resources/pipelinerunstate.go#L462-L463

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:509]: I deliberately didn't do that - they _are_ skipped, so I think it makes sense to just leave them in that count. `SkippedDueToTimeout` is a subset of `Skipped` with the sole purpose of ensuring that the `PipelineRun` as a whole is marked as failed, but the actual tasks are just skipped.

Comment (jerop) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate.go:509]: aah I'd missed that you increment `skipped` whenever you increment `skippedduetotimeout`, sounds good!

**Comment by abayer** [comment]
ping @pritidesai - I'd really like to get this merged. =)

**Comment by jerop** [comment]
really appreciate all your hard work here @abayer, excited to put the timeout flakiness behind us 😁 

/approve

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 27 above)
Comment (pritidesai) [reply pkg/apis/pipeline/v1alpha1/run_types.go:105]: thanks @abayer, please document this update - https://github.com/tektoncd/pipeline/blob/main/docs/taskruns.md#monitoring-execution-status

**Comment by pritidesai** [comment]
> Change PipelineRun timeout behavior for child TaskRuns and Runs to behave like cancellation rather than explicitly setting timeouts on the child tasks at runtime.

Hi @abayer, @lbernick, and @jerop, I would like to understand the `status` transition as part of this fix compared to what we have today.

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 27 above)
Comment (abayer) [reply pkg/apis/pipeline/v1alpha1/run_types.go:105]: Done.

**Comment by abayer** [comment]
> > Change PipelineRun timeout behavior for child TaskRuns and Runs to behave like cancellation rather than explicitly setting timeouts on the child tasks at runtime.
> 
> Hi @abayer, @lbernick, and @jerop, I would like to understand the `status` transition as part of this fix compared to what we have today.

I'm not sure what you mean?

**Comment by pritidesai** [comment]
> > > Change PipelineRun timeout behavior for child TaskRuns and Runs to behave like cancellation rather than explicitly setting timeouts on the child tasks at runtime.
> > 
> > 
> > Hi @abayer, @lbernick, and @jerop, I would like to understand the `status` transition as part of this fix compared to what we have today.
> 
> I'm not sure what you mean? 

What I mean or rather my concern is - is there any change in the state transition which might impact existing use case. 

For example, when a `pipelineRun` is cancelled - it's state transition looks like:

Unknown/Started (controller picked up this pipelineRun) -> Unknown/Running (validated and started running) -> Unknown/Cancelled (user requested cancellation) -> False/Cancelled (cancelled successfully)

Thanks for [documenting](https://github.com/tektoncd/pipeline/blob/f2c4eced7941f5b4173f366ab6c7e3af373c6790/docs/taskruns.md#monitoring-execution-status) new status/reason introduced in this PR.

Screen Shot 2022-08-12 at 10 41 44 AM

`TaskRunCancelled` is now overloaded with taskrun cancellation and pipelinerun timing out. The distinguishing factor might be the `message`. Is it enough for the users to distinguish between cancellation and timeout? 

_Please know that I am not in favor of raising objection on any changes but I want to make sure we are not making our users unhappy by accidentally breaking/changing existing functionalities just like all of you 👼 _

**Comment by abayer** [comment]
> What I mean or rather my concern is - is there any change in the state transition which might impact existing use case.

Aaaah - then no. The state transitions for the `PipelineRun` are the same - well, technically, they're more accurate to what we expect them to be than they were without this, since the race condition caused by slightly-off timing between calculated timeouts for `TaskRun`s and the timeout for the `PipelineRun`, sometimes resulting in the `PipelineRun` getting marked as cancelled when it should be marked as timed out. This change's whole point is to get rid of that inconsistency and always mark the `PipelineRun` as timed out when it has, in fact, timed out. =)

The change to not create `TaskRun`s/`Run`s if we've already passed the relevant `PipelineRunSpec.Timeouts.{Tasks,Finally,Pipeline}` and instead record the relevant `PipelineTask` as skipped very explicitly retains the previous state transition as well, in that the `PipelineRun` will be marked the same way it would now, where a `TaskRun`/`Run` that would get created after the relevant `PipelineRun` timeout had elapsed does get created, but with a `1s` timeout on its spec. The old approach results in the "shouldn't really run" pipeline tasks showing up as instantly-failed `TaskRun`s/`Run`s, and the new approach specifically records the count of pipeline tasks which are skipped due to being past the relevant timeout, and for the overall `PipelineRun` status, those tasks are treated equivalently to the instantly-failed ones in the old approach.

Basically, the whole change is built around making sure that the state transitions and overall experience match before and after the change, even though the underlying implementation is radically different. If anything, I tend to err in the direction of avoiding API/status/etc changes too much. =)

> _Please know that I am not in favor of raising objection on any changes but I want to make sure we are not making our users unhappy by accidentally breaking/changing existing functionalities just like all of you 👼_

No worries! =)

**Comment by pritidesai** [comment]
Thanks @abayer (once again appreciate all your efforts on this 💯)

> So my original idea was to have a new spec status value specifically for "time out this TaskRun because its parent PipelineRun timed out", but the consensus was that it was better to just overload the existing cancellation spec status value with the additional message for clarity. I do think it's sufficient.

Overloading existing cancellation spec status value will not be consistent with how we have added very explicit and specific status values such as `"CancelledRunFinally"` and `"StoppedRunFinally"`. Those could have been distinguished with messages rather than creating a new status. But it's always easier (and common practice) to rely on status to identify the execution status. The other concern this overloading is, the systems watching this status `TaskRunCancelled` will start seeing cancelled events/status updates for timed out tasks too. Do you follow?

**Comment by jerop** [comment]
@pritidesai to share some context (@abayer feel free to respond as well 😁), there's a discussion thread from earlier in this PR - https://github.com/tektoncd/pipeline/pull/5134#discussion_r922197115 - where @afrittoli pointed out that:

> I would argue that if it's the `PipelineRun` that times out, the `TaskRun` itself did not timeout, but it was cancelled because of some timeout logic that the `TaskRun` itself is not aware of. I think using cancellation might actually help users identity where the timeout occurred. We could add a place for the canceller to give an explanation or reason for the cancellation. Using cancellation might be even more helpful when doing pipeline in pipeline, where the chain of cancellations may go deeper.

**Comment by abayer** [comment]
I'm honestly open to either using `TaskRunCancelled` as we are now, or my original approach of a new timeout-specific spec status, but I do think that `TaskRunCancelled` is more accurate. If a `TaskRun` times out due to the `PipelineTask.Timeout`, it'll show up as `TaskRunTimedOut`, but if it's cancelled due to the `PipelineRun` timeout settings, it'll show up as `TaskRunCancelled`. That's entirely accurate, and also matches `TaskRun` behavior with what `Run` behavior for `PipelineRun` timeouts has always been up to this point.

**Comment by pritidesai** [comment]
Thank you @jerop for the reference 🤗 thank you @abayer, @lbernick, @vdemeester, and @afrittoli for the feedback 🤗 

> If a TaskRun times out due to the PipelineTask.Timeout, it'll show up as TaskRunTimedOut, but if it's cancelled due to the PipelineRun timeout settings, it'll show up as TaskRunCancelled. 

I am still having hard time settling on this but if most of you have voted for this, please go ahead with it. I still see this as inconsistent and mixing cancellation with timeout. Why is a taskRun cancelled with `TaskRunCancelled` when `pipelineRun` has timed out. Irrespective of whether it was my own timeout or my parent's (`pipelineRun` that I belong to) timeout, as a `taskRun`, I timed out. 

Also, I treat `runs` a little different from `taskRuns` since `runs` are managed by their own controllers whereas `taskRuns` are managed by the `taskRun` controller which is part of the same `pipelineRun` controller.   

BTW, I didn't find any mention of `RunTimedOut` other than the constant that we have defined - https://github.com/tektoncd/pipeline/blob/217b12de93b0211687cee930f703c5c5d4ad8f43/pkg/apis/pipeline/v1alpha1/run_types.go#L121

**Comment by pritidesai** [comment]
Also, I haven't got chance to review the code further, I will resume reviewing back next week if it's still open 🤣

**Comment by abayer** [comment]
ping @pritidesai

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go [hunk 32]
```diff
@@ -449,6 +487,12 @@ const (
 	GracefullyStoppedSkip SkippingReason = "PipelineRun was gracefully stopped"
 	// MissingResultsSkip means the task was skipped because it's missing necessary results
 	MissingResultsSkip SkippingReason = "Results were missing"
+	// PipelineTimedOutSkip means the task was skipped because the PipelineRun has passed its overall timeout.
+	PipelineTimedOutSkip SkippingReason = "PipelineRun timeout has been reached"
```
Comment (pritidesai) [inline pkg/apis/pipeline/v1beta1/pipelinerun_types.go:491]: what is the existing behavior in terms what happens to the unscheduled tasks (dag and finally)? How is this different from what we have today?

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go [hunk 33]
```diff
@@ -449,6 +487,12 @@ const (
...
+	// TasksTimedOutSkip means the task was skipped because the PipelineRun has passed its Timeouts.Tasks.
+	TasksTimedOutSkip SkippingReason = "PipelineRun Tasks timeout has been reached"
+	// FinallyTimedOutSkip means the task was skipped because the PipelineRun has passed its Timeouts.Finally.
+	FinallyTimedOutSkip SkippingReason = "PipelineRun Finally timeout has been reached"
```
Comment (pritidesai) [inline pkg/apis/pipeline/v1beta1/pipelinerun_types.go:495]: How is this possible with the constraint we have [documented](https://github.com/tektoncd/pipeline/blob/main/docs/pipelineruns.md#configuring-a-failure-timeout)?

```
timeouts.pipeline >= timeouts.tasks + timeouts.finally
```

Does this reason only apply to `finally` tasks? or can also be applied to `dag tasks`?

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go (hunk 32 above)
Comment (abayer) [reply pkg/apis/pipeline/v1beta1/pipelinerun_types.go:491]: Right now, we create the tasks with a 1s timeout, so that they get created but immediately timeout. Skipping them instead is much more logical, imo.

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go (hunk 33 above)
Comment (abayer) [reply pkg/apis/pipeline/v1beta1/pipelinerun_types.go:495]: There are a few ways - dag tasks finishing quickly enough that the remaining time until the pipeline timeout is greater than the finally timeout, no pipeline timeout at all, etc. We’re using a different skipping reason for finally vs dag tasks to make the specific timeout setting that caused the timeout clear.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 34]
```diff
@@ -422,6 +482,45 @@ func (t *ResolvedPipelineTask) skipBecauseResultReferencesAreMissing(facts *Pipe
...
+			// If the elapsed time since the PipelineRun's start time is greater than the the PipelineRun's Tasks timeout, skip.
+			return facts.TimeoutsState.Clock.Since(*facts.TimeoutsState.StartTime) > *facts.TimeoutsState.TasksTimeout
+		}
+	}
+
+	return false
+}
+
+// skipBecausePipelineRunFinallyTimeoutReached returns true if the task shouldn't be launched because the elapsed time since
+// finally tasks started being executed is greater than the PipelineRun's finally timeout
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:512]: > `task shouldn't be launched`

which task shouldn't be launched? all finally tasks are suppose to start at the same time, will there any tasks left to meet this criteria? If the finally tasks are started and the finally time out hits, are they getting cancelled or skipped?

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:512]: In practice, this is probably only going to hit in some really bizarre edge case, but I feel like it’s better to be safe and keep handling past-timeout finally tasks the same way we do dag tasks, since that’s what we’re doing with the 1s timeout approach currently. I’d be open to just not bothering with finally tasks and letting the PR handle timing out all cases of executing finally tasks when we’re past the finally timeout.

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go (hunk 32 above)
Comment (pritidesai) [reply pkg/apis/pipeline/v1beta1/pipelinerun_types.go:491]: Wouldn't that be considered a behavior change? The users will start getting such tasks as part of the list of skipped tasks instead of `taskRun`s with cancelled status? 🤔  

> Skipping them instead is much more logical, imo.

`skip` was introduced for conditional tasks and since then we have extended its usage in many different scenarios which is fine for now.

File: pkg/apis/pipeline/v1beta1/taskrun_types_test.go [hunk 35]
```diff
@@ -120,7 +120,7 @@ func TestTaskRunIsDone(t *testing.T) {
 		},
 	}
 	if !tr.IsDone() {
-		t.Fatal("Expected pipelinerun status to be done")
+		t.Fatal("Expected taskrun status to be done")
```
Comment (pritidesai) [inline pkg/apis/pipeline/v1beta1/taskrun_types_test.go:123]: thank you for fixing this 🙏

**Comment by pritidesai** [comment]
I was trying to run these changes against an `e2e` test  without `alpha` feature flag enabled. The [TestPipelineRunTasksTimeout](https://github.com/tektoncd/pipeline/blob/main/test/timeout_test.go#L437) required alpha flag but [timeouts](https://github.com/tektoncd/pipeline/blob/main/docs/install.md#alpha-features) are no longer `alpha`.  Am I missing anything? 🤣 Should this be no longer be `alpha`?

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go (hunk 32 above)
Comment (abayer) [reply pkg/apis/pipeline/v1beta1/pipelinerun_types.go:491]: It is a slight behavior change, but not a functional one, since the end result is the same, just without the wasted steps of creating and immediately timing out the relevant task(s). I don’t think it’s an issue.

**Comment by abayer** [comment]
> I was trying to run these changes against an `e2e` test without `alpha` feature flag enabled. The [TestPipelineRunTasksTimeout](https://github.com/tektoncd/pipeline/blob/main/test/timeout_test.go#L437) required alpha flag but [timeouts](https://github.com/tektoncd/pipeline/blob/main/docs/install.md#alpha-features) are no longer `alpha`. Am I missing anything? 🤣 Should this no longer be `alpha`?

Ah, yeah, if `timeouts` is out of alpha, then I’ll do a followup PR removing the alpha requirement from any tests related to it.

**Comment by abayer** [comment]
So, weirdly, I saw `TestPipelineRunTasksTimeout` fail twice in a row on `pull-tekton-pipeline-integration-tests` after removing the `alpha` requirement on the test. It passed just fine both times on `pull-tekton-pipeline-alpha-integration-tests` and in local testing, and looks to have passed after I made a small tweak to not log/call the timeout function unless we had task names to timeout, but that shouldn't have made a difference! As best as I could tell from the failure logs, the failures were both due to the `finally` task getting cancelled when the `tasks` timeout was reached, which doesn't seem possible unless `ResolvedPipelineTask.IsFinalTask(facts)` is returning false incorrectly...I'm going to run the tests a few more times to see if it shows up again.

**Comment by abayer** [comment]
...dangit, I tried to prune a bunch of old coverage report comments to make the PR discussion easier to read and it decided to log each of them here, creating a big ol' list of me deleting things. Oops. =)

File: pkg/apis/pipeline/v1beta1/pipelinerun_types.go (hunk 32 above)
Comment (vdemeester) [reply pkg/apis/pipeline/v1beta1/pipelinerun_types.go:492]: Agreeing with @abayer

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 11 above)
Comment (vdemeester) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:259]: This sounds like a very weird behavior, but I agree, if we want to change it, it shouldn't be in that PR.

**Review by vdemeester — APPROVED** [review]

**Comment by abayer** [comment]
fwiw, it looks like that little change I made did get rid of the weird failures on the non-alpha test, so hey, we're all good. =)

**Comment by pritidesai** [comment]
Alright, thanks a bunch all of you @abayer @afrittoli @jerop @lbernick and @vdemeester Most of my concerns are addressed, I haven't got chance to review all the code changes but happy to cancel the hold, please feel free to merge this 🙏  

A few nice to have items:
- Most of these discussions/workflow can be captured in a doc
- Add more `e2e` tests to cover all possible edge cases

/cancel hold

**Comment by pritidesai** [comment]
is it not `/cancel hold` 🤔 

/hold cancel

**Comment by jerop** [comment]
/lgtm

excited to see none (or less xD) of the timeouts flakes, thank you again @abayer! 🎉
