### PR TITLE
Correctly report step start times

### LINKED ISSUE #1512: Step start times are reported inaccurately
# Expected Behavior

Step start times are recorded and reported accurately.

# Actual Behavior

Step start times are all reported to be the same as the beginning of the first step, because according to k8s all the containers started at once -- the entrypoint binary ensures the actual step's work doesn't start until a previous step finishes.

# Steps to Reproduce the Problem

```
steps:
- image: ubuntu
  command: ['sleep', '1000']
- image: ubuntu
  command: ['started']
```

After completing, this TaskRun's status will incorrectly show that the second step started at the same time as the first. It should report to have started 1000 seconds after the first.

### PR DESCRIPTION
**Pull request by othomann**
# Changes
These changes are setting accurate starting time for the different steps in the task.

This is accomplished by hijacking the `terminationMessagePath` (which is now always set to `/tekton/termination`), and having the injected entrypoint binary write the start time to that path when the step completes.

This is then picked up in `pkg/pod/status.go` to extract the reported start time and overwrite the container's `StartedAt` value.

Fixes #1512

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
This should fix issue https://github.com/tektoncd/pipeline/issues/1512
```

### CODE REVIEW

**Comment by othomann** [comment]
@googlebot I signed it!

File: pkg/termination/termination_test.go [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+		Value: now.Format(time.RFC3339),
+	})
+
+	WriteMessage(logger, tmpFile.Name(), output)
+
+	exists := Exists(tmpFile.Name())
+	if err != nil {
+		logger.Fatalf("Error checking file existance %v: %v", tmpFile.Name(), err)
+	}
+	if exists {
```
Comment (ImJasonH) [inline pkg/termination/termination_test.go]:
```go
if !exists {
  t.Fatalf("Expected file to exist")
}
... then all the rest ...
```

This moves the relevant code one level out in indentation, and makes it clearer to see that we fail (with a message) when the file unexpectedly doesn't exist.

File: pkg/termination/termination_test.go [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+		}
+		if err != nil {
+			logger.Fatalf("temp file cannot be deleted\n")
+		}
+		var existingEntries []v1alpha1.PipelineResourceResult
+
+		if err := json.Unmarshal([]byte(fileContents), &existingEntries); err != nil {
+			logger.Fatalf("Could not parse json message '%q' because of %w\n", fileContents, err)
+		}
+		if len(existingEntries) != 2 {
```
Comment (ImJasonH) [inline pkg/termination/termination_test.go]: Let's compare the exact expected contents, using `cmp.Diff` -- there should be other examples using `cmp.Diff` strewn about, but basically:

```go
want := `{"StartedAt":"...","FinishedAt":"..."}`
b, err := ioutil.ReadFile(tmpFile)
if d := cmp.Diff(want, string(b)); d != "" {
  t.Fatalf("Diff(-want, got): %s", d)
}
```

This means we should probably not have dynamic `time.Now()` values written above -- we can just add a value that says `"hello"` and see that it gets appended.

File: pkg/termination/termination_test.go [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+	WriteMessage(logger, tmpFile.Name(), output)
+
+	output = []v1alpha1.PipelineResourceResult{}
+	now = time.Now()
+	output = append(output, v1alpha1.PipelineResourceResult{
+		Key:   "FinishedAt",
+		Value: now.Format(time.RFC3339),
+	})
+
+	WriteMessage(logger, tmpFile.Name(), output)
```
Comment (ImJasonH) [inline pkg/termination/termination_test.go]: Perhaps `WriteMessage` should return an error, that we can `t.Fatal` on if we see here. `logger.Fatalf` inside of `WriteMessage` will make test failures harder to find, and it's probably just better hygiene anyway.

This will also let us remove `logger` as an arg to `WriteMessage`, since it was only taking it to be able to call `Fatalf` on it in error scenarios.

File: pkg/termination/termination_test.go [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+
+	exists := Exists(tmpFile.Name())
+	if err != nil {
```
Comment (ImJasonH) [inline pkg/termination/termination_test.go]: This isn't necessary `err` will already have been checked above.

File: pkg/termination/termination_test.go [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+	logger, _ := logging.NewLogger("", "test termination")
+	defer logger.Sync()
+	output := []v1alpha1.PipelineResourceResult{}
+	now := time.Now()
+	output = append(output, v1alpha1.PipelineResourceResult{
+		Key:   "StartedAt",
+		Value: now.Format(time.RFC3339),
+	})
+
+	WriteMessage(logger, tmpFile.Name(), output)
```
Comment (ImJasonH) [inline pkg/termination/termination_test.go]: We should check contents after writing the first message too, to make sure that we're writing and appending instead of just buffering writes or something. This probably means a `checkContents` test helper would be useful.

File: pkg/termination/termination.go [hunk 6]
```diff
@@ -17,29 +17,60 @@ package termination
...
+	if os.IsNotExist(err) {
+		return false
+	}
+	return !info.IsDir()
+}
+
 func WriteMessage(logger *zap.SugaredLogger, path string, pro []v1alpha1.PipelineResourceResult) {
+	// if the file at path exists, concatenate the new values otherwise create it
+	exists := Exists(path)
+	if exists {
```
Comment (sbwsg) [inline pkg/termination/termination.go]: `ioutil.ReadFile(path)` will return an error that `os.IsNotExists` can accept, and `os.OpenFile` will happily overwrite the file without it being deleted first. So I think we can remove `Exists(name)` and the call to `os.Remove(path)`, ending up with something like this:

```go
fileContents, err := ioutil.ReadFile(path)
if err == nil {
  if len(fileContents) != 0 {
    var existingEntries []v1alpha1.PipelineResourceResult
    if err := json.Unmarshal([]byte(fileContents), &existingEntries); err != nil {
      logger.Fatalf("Could not parse json message '%q' because of %w\n", fileContents, err)
    }
    pro = append(existingEntries, pro...)
  }
} else if ! os.IsNotExist(err) {
  logger.Fatalf("unexpected error reading %q: %v", path, err)
}
jsonOutput, err := json.Marshal(pro)
// ... and so on ...
```

Even this could be simplified - if `json.Unmarshal` returns an error I'd argue we simply print it and continue on as if the file didnt exist.  So we wouldn't need to worry about the `len(fileContents)` check either...

File: pkg/pod/status.go [hunk 7]
```diff
@@ -106,8 +108,33 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
 	trs.Steps = []v1alpha1.StepState{}
 	trs.Sidecars = []v1alpha1.SidecarState{}
+	logger, _ := logging.NewLogger("", "status")
+	defer logger.Sync()
+
 	for _, s := range pod.Status.ContainerStatuses {
 		if isContainerStep(s.Name) {
+			if s.State.Terminated != nil {
+				msg := s.State.Terminated.Message
+				logger.Infof("json message to parse '%q'", msg)
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/pod/status.go]: ok done and pushed. I am still looking at other errors in other tests.

File: pkg/pod/status.go [hunk 8]
```diff
@@ -106,8 +108,33 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
+				var r []v1alpha1.PipelineResourceResult
+				if err := json.Unmarshal([]byte(msg), &r); err != nil {
+					logger.Errorf("Could not parse json message '%q' because of %w\n", msg, err)
+				} else {
+					for _, i := range r {
+						logger.Infof("parsed entry '%q'", i)
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/pod/status.go]: ok done and pushed. I am still looking at other errors in other tests.

File: pkg/pod/status.go [hunk 9]
```diff
@@ -106,8 +108,33 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
+	defer logger.Sync()
+
 	for _, s := range pod.Status.ContainerStatuses {
 		if isContainerStep(s.Name) {
+			if s.State.Terminated != nil {
+				msg := s.State.Terminated.Message
+				logger.Infof("json message to parse '%q'", msg)
+				var r []v1alpha1.PipelineResourceResult
+				if err := json.Unmarshal([]byte(msg), &r); err != nil {
+					logger.Errorf("Could not parse json message '%q' because of %w\n", msg, err)
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/pod/status.go]: ok done and pushed. I am still looking at other errors in other tests.

File: pkg/pod/status.go [hunk 10]
```diff
@@ -106,8 +108,33 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
+				} else {
+					for _, i := range r {
+						logger.Infof("parsed entry '%q'", i)
+						if i.Key == "StartedAt" {
+							t, err := time.Parse(time.RFC3339, i.Value)
+							if err != nil {
+								logger.Errorf("Could not parse time: %q: %w\n", i.Value, err)
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/pod/status.go]: ok done and pushed. I am still looking at other errors in other tests.

File: pkg/termination/termination.go (hunk 6 above)
Comment (othomann) [reply pkg/termination/termination.go]: ok done and pushed. I am still looking at other errors in other tests.

File: pkg/termination/termination_test.go (hunk 5 above)
Comment (othomann) [reply pkg/termination/termination_test.go]: Done.

File: pkg/termination/termination_test.go (hunk 4 above)
Comment (othomann) [reply pkg/termination/termination_test.go]: done.

File: pkg/termination/termination_test.go (hunk 2 above)
Comment (othomann) [reply pkg/termination/termination_test.go]: done

File: pkg/termination/termination_test.go (hunk 1 above)
Comment (othomann) [reply pkg/termination/termination_test.go]: Done.

File: pkg/termination/termination_test.go (hunk 3 above)
Comment (othomann) [reply pkg/termination/termination_test.go]: Done with latest commit

**Comment by othomann** [comment]
@ImJasonH Looking at pull-tekton-pipeline-integration-tests I am not sure what the failure is. I will keep looking tomorrow.

**Comment by chengjingtao** [comment]
Great Changes. It provides an ability to pick more informations from taskstep container.
The PR is blocked by integration tests, is anyone dealing with this problem ?

**Comment by othomann** [comment]
@googlebot I fixed it

File: pkg/termination/termination.go [hunk 11]
```diff
@@ -17,29 +17,41 @@ package termination
...
 	if err != nil {
-		log.Fatalf("Unexpected error converting output to json %v: %v", pro, err)
+		return err
 	}
 	defer f.Close()
 
 	_, err = f.Write(jsonOutput)
 	if err != nil {
-		logger.Fatalf("Unexpected error converting output to json %v: %v", pro, err)
+		return err
```
Comment (ImJasonH) [inline pkg/termination/termination.go]: This is another opportunity to use the `if err := ` format.

File: pkg/termination/termination_test.go [hunk 12]
```diff
@@ -0,0 +1,71 @@
...
+	defer func() {
+		_ = logger.Sync()
+	}()
+	output := []v1alpha1.PipelineResourceResult{}
+	output = append(output, v1alpha1.PipelineResourceResult{
+		Key:   "key1",
+		Value: "hello",
+	})
+
+	err = WriteMessage(tmpFile.Name(), output)
```
Comment (ImJasonH) [inline pkg/termination/termination_test.go]: Here too

(and below)

File: pkg/termination/termination_test.go [hunk 13]
```diff
@@ -0,0 +1,71 @@
...
+		log.Fatal("Cannot create temporary file", err)
+	}
+	// Remember to clean up the file afterwards
+	defer os.Remove(tmpFile.Name())
+
+	logger, _ := logging.NewLogger("", "test termination")
+	defer func() {
+		_ = logger.Sync()
+	}()
+	output := []v1alpha1.PipelineResourceResult{}
```
Comment (ImJasonH) [inline pkg/termination/termination_test.go]: This could just be:

```go
output := []v1alpha1.PipelineResourceResult{{
  Key: ...
  Value: ...
}}
```

(and below)

File: pkg/pod/status.go [hunk 14]
```diff
@@ -108,8 +110,45 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
+						if result.Key == "StartedAt" {
+							t, err := time.Parse(time.RFC3339, result.Value)
+							if err != nil {
+								logger.Errorf("Could not parse time: %q: %w", result.Value, err)
+							} else {
+								s.State.Terminated.StartedAt = metav1.NewTime(t)
+								// remove the entry for the starting time
+								r = append(r[:index], r[index+1:]...)
+								if len(r) == 0 {
+									s.State.Terminated.Message = ""
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/pod/status.go]: There is a check that the termination message is empty in the integration tests.

File: pkg/termination/termination_test.go (hunk 13 above)
Comment (othomann) [reply pkg/termination/termination_test.go]: Done in last commit.

File: pkg/termination/termination_test.go (hunk 12 above)
Comment (othomann) [reply pkg/termination/termination_test.go]: Done in last commit.

File: pkg/termination/termination.go (hunk 11 above)
Comment (othomann) [reply pkg/termination/termination.go]: Done in last commit.

File: pkg/pod/status.go [hunk 15]
```diff
@@ -108,8 +110,45 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
+								} else {
+									bytes, err := json.Marshal(r)
+									if err != nil {
+										logger.Errorf("Error marshalling remaining results: %w", err)
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/pod/status.go]: Done in last commit.

File: pkg/entrypoint/entrypointer_test.go [hunk 16]
```diff
@@ -173,6 +184,12 @@ func TestEntrypointer(t *testing.T) {
 			if c.postFile == "" && fpw.wrote != nil {
 				t.Errorf("Wrote post file when not required")
 			}
+			if c.terminationPath != "" {
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/entrypoint/entrypointer_test.go]: Done in last commit.

File: pkg/entrypoint/entrypointer_test.go [hunk 17]
```diff
@@ -94,44 +96,53 @@ func TestEntrypointerFailures(t *testing.T) {
...
 func TestEntrypointer(t *testing.T) {
 	for _, c := range []struct {
-		desc, entrypoint, postFile string
-		waitFiles, args            []string
+		desc, entrypoint, postFile, terminationPath string
+		waitFiles, args                             []string
 	}{{
-		desc: "do nothing",
+		desc:            "do nothing",
+		terminationPath: "termination",
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/entrypoint/entrypointer_test.go]: Done in last commit.

File: pkg/entrypoint/entrypointer.go [hunk 18]
```diff
@@ -77,12 +90,20 @@ func (e Entrypointer) Go() error {
...
+		Key:   "StartedAt",
+		Value: t.Format(time.RFC3339),
+	})
 
 	err := e.Runner.Run(e.Args...)
 
 	// Write the post file *no matter what*
 	e.WritePostFile(e.PostFile, err)
-
+	writingErr := termination.WriteMessage(e.TerminationPath, output)
```
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/entrypoint/entrypointer.go]: Done in last commit.

File: cmd/imagedigestexporter/main.go [hunk 19]
```diff
@@ -78,5 +78,9 @@ func main() {
 
 	}
 
-	termination.WriteMessage(logger, *terminationMessagePath, output)
+	err := termination.WriteMessage(*terminationMessagePath, output)
```
[the remark this answers is not in the document]
Comment (othomann) [reply cmd/imagedigestexporter/main.go]: Done in last commit.

File: cmd/git-init/main.go [hunk 20]
```diff
@@ -68,5 +68,8 @@ func main() {
 		},
 	}
 
-	termination.WriteMessage(logger, terminationMessagePath, output)
+	err = termination.WriteMessage(terminationMessagePath, output)
```
[the remark this answers is not in the document]
Comment (othomann) [reply cmd/git-init/main.go]: Done in last commit.

File: pkg/entrypoint/entrypointer_test.go [hunk 21]
```diff
@@ -94,8 +99,8 @@ func TestEntrypointerFailures(t *testing.T) {
 
 func TestEntrypointer(t *testing.T) {
 	for _, c := range []struct {
-		desc, entrypoint, postFile string
-		waitFiles, args            []string
+		desc, entrypoint, postFile, terminationPath string
```
Comment (ImJasonH) [inline pkg/entrypoint/entrypointer_test.go]: can remove the `terminationPath` field now.

File: pkg/entrypoint/entrypointer.go [hunk 22]
```diff
@@ -1,5 +1,5 @@
 /*
-Copyright 2019 The Tekton Authors
+Copyright 2019, 2020 The Tekton Authors
```
Comment (ImJasonH) [inline pkg/entrypoint/entrypointer.go]: I don't think we need to worry about this, at least not in this change. If we decide we care we can make one automated change across the whole repo.

File: pkg/entrypoint/entrypointer.go [hunk 23]
```diff
@@ -77,12 +90,20 @@ func (e Entrypointer) Go() error {
 	if e.Entrypoint != "" {
 		e.Args = append([]string{e.Entrypoint}, e.Args...)
 	}
+	t := time.Now()
```
Comment (ImJasonH) [inline pkg/entrypoint/entrypointer.go]: nit: If `t` isn't used anywhere else, you can just inline it on line 96: `time.Now().Format(time.RFC3339)`

File: pkg/pod/status.go [hunk 24]
```diff
@@ -108,8 +110,45 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
+	logger, _ := logging.NewLogger("", "status")
+	defer func() {
+		_ = logger.Sync()
+	}()
+
 	for _, s := range pod.Status.ContainerStatuses {
 		if isContainerStep(s.Name) {
+			if s.State.Terminated != nil && len(s.State.Terminated.Message) != 0 {
+				msg := s.State.Terminated.Message
+				logger.Infof("json message to parse '%q'", msg)
```
[the remark this answers is not in the document]
Comment (ImJasonH) [reply pkg/pod/status.go]: Still seeing this debug logging.

File: pkg/pod/status.go [hunk 25]
```diff
@@ -108,8 +110,45 @@ func MakeTaskRunStatus(tr v1alpha1.TaskRun, pod *corev1.Pod, taskSpec v1alpha1.T
...
+				var r []v1alpha1.PipelineResourceResult
+				if err := json.Unmarshal([]byte(msg), &r); err != nil {
+					logger.Errorf("Could not parse json message %q because of %w", msg, err)
+				} else {
+					for index, result := range r {
+						logger.Infof("parsed entry %q", result)
+						if result.Key == "StartedAt" {
+							t, err := time.Parse(time.RFC3339, result.Value)
+							if err != nil {
+								logger.Errorf("Could not parse time: %q: %w", result.Value, err)
```
[the remark this answers is not in the document]
Comment (ImJasonH) [reply pkg/pod/status.go]: Here too

File: pkg/entrypoint/entrypointer_test.go (hunk 21 above)
Comment (othomann) [reply pkg/entrypoint/entrypointer_test.go]: done.

File: pkg/entrypoint/entrypointer.go (hunk 23 above)
Comment (othomann) [reply pkg/entrypoint/entrypointer.go]: done.

File: pkg/entrypoint/entrypointer.go (hunk 22 above)
Comment (othomann) [reply pkg/entrypoint/entrypointer.go]: done.

File: pkg/pod/status.go (hunk 25 above)
[the remark this answers is not in the document]
Comment (othomann) [reply pkg/pod/status.go]: Done now.
