### PR TITLE
Fixes #3086 - amd64 images are pulled on all the architectures

### LINKED ISSUE #3086: Fail to run task with multi-arch image on non amd64 cluster
# Expected Behavior
Task with multi-arch image should be successfully executable on non amd64 architetures.
# Actual Behavior
Task failed for s390x and ppc64le architectures with error
```
Error executing command: fork/exec /bin/bash: exec format error
```
Research of the pod logs showed that instead of pulling correct version of multi-arch image for appropriate architecture(s390x or ppc64le), always amd64 version is pulled. amd64 container image cannot run on another archirectire, as a result - `exec format error`
```
# kubectl describe pod wd-task-run-pod-9kbqj
Name:         wd-task-run-pod-9kbqj
Namespace:    default
Priority:     0
Node:         node3/192.168.122.29
Start Time:   Tue, 11 Aug 2020 11:54:04 +0200
Labels:       app.kubernetes.io/managed-by=tekton-pipelines
              tekton.dev/task=wd-task
              tekton.dev/taskRun=wd-task-run
Annotations:  pipeline.tekton.dev/release: devel
              tekton.dev/ready: READY
Status:       Failed
IP:           10.144.2.230
IPs:
  IP:           10.144.2.230
Controlled By:  TaskRun/wd-task-run
Init Containers:
  place-tools:
    Container ID:  docker://1799df7db1b9c82b41a4d38991b6cf67e032361aeee495a603a91ca411b6aea6
    Image:         sys-boe-dev-team-docker-local.artifactory.swg-devops.com/github.com/tektoncd/pipeline/cmd/entrypoint:test3@sha256:54b1c40d5769b0b4c69ae35eeb5b2a188f203acf8251980d999b1d548c502574
    Image ID:      docker-pullable://sys-boe-dev-team-docker-local.artifactory.swg-devops.com/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:54b1c40d5769b0b4c69ae35eeb5b2a188f203acf8251980d999b1d548c502574
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      /ko-app/entrypoint
      /tekton/tools/entrypoint
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 11 Aug 2020 11:54:05 +0200
      Finished:     Tue, 11 Aug 2020 11:54:05 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tekton/tools from tekton-internal-tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dx8kz (ro)
Containers:
  step-test:
    Container ID:  docker://0441ab2704b2c479da5392fd3fe16460b7dbd7238c6eccc369e5603dad0196fa
    Image:         index.docker.io/library/ubuntu@sha256:60f560e52264ed1cb7829a0d59b1ee7740d7580e0eb293aca2d722136edb1e24
    Image ID:      docker-pullable://ubuntu@sha256:60f560e52264ed1cb7829a0d59b1ee7740d7580e0eb293aca2d722136edb1e24
    Port:          <none>
    Host Port:     <none>
    Command:
      /tekton/tools/entrypoint
    Args:
      -wait_file
      /tekton/downward/ready
      -wait_file_content
      -post_file
      /tekton/tools/0
      -termination_path
      /tekton/termination
      -entrypoint
      /bin/bash
      --
      -c
      echo YES
    State:          Terminated
      Reason:       Error
      Message:      [{"key":"StartedAt","value":"2020-08-11T09:54:08.477Z","resourceRef":{}}]
      Exit Code:    1
      Started:      Tue, 11 Aug 2020 11:54:06 +0200
      Finished:     Tue, 11 Aug 2020 11:54:08 +0200
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:                0
      ephemeral-storage:  0
      memory:             0
    Environment:
      HOME:  /tekton/home
    Mounts:
      /tekton/creds from tekton-creds-init-home-pzxtp (rw)
      /tekton/downward from tekton-internal-downward (rw)
      /tekton/home from tekton-internal-home (rw)
      /tekton/results from tekton-internal-results (rw)
      /tekton/tools from tekton-internal-tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dx8kz (ro)
      /workspace from tekton-internal-workspace (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tekton-internal-workspace:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-home:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-results:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-tools:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-downward:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations['tekton.dev/ready'] -> ready
  tekton-creds-init-home-pzxtp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  default-token-dx8kz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dx8kz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  28m   default-scheduler  Successfully assigned default/wd-task-run-pod-9kbqj to node3
  Normal  Pulled     28m   kubelet, node3     Container image "sys-boe-dev-team-docker-local.artifactory.swg-devops.com/github.com/tektoncd/pipeline/cmd/entrypoint:test3@sha256:54b1c40d5769b0b4c69ae35eeb5b2a188f203acf8251980d999b1d548c502574" already present on machine
  Normal  Created    28m   kubelet, node3     Created container place-tools
  Normal  Started    28m   kubelet, node3     Started container place-tools
  Normal  Pulled     28m   kubelet, node3     Container image "index.docker.io/library/ubuntu@sha256:60f560e52264ed1cb7829a0d59b1ee7740d7580e0eb293aca2d722136edb1e24" already present on machine
  Normal  Created    28m   kubelet, node3     Created container step-test
  Normal  Started    28m   kubelet, node3     Started container step-test
```
# Steps to Reproduce the Problem
1. Use s390x k8s cluster and install Tekton pipeline on top.
2. Create Task
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wd-task
spec:
  steps:
  - args:
    - -c
    - echo YES
    image: ubuntu
    name: "test"
    resources: {}
    workingDir: /HELLOMOTO
```
3. Create TaskRun
```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/task: wd-task
  name: wd-task-run
spec:
  serviceAccountName: default
  taskRef:
    kind: Task
    name: wd-task
  timeout: 1h0m0s
```
4. Get TaskRun status - 
```
NAME          SUCCEEDED   REASON   STARTTIME   COMPLETIONTIME
wd-task-run   False       Failed   7m42s       7m35s
```

# Additional Info
This issue is open as part of initiative to enable Tekton for non amd64 architectures, specifically s390x -  https://github.com/tektoncd/pipeline/issues/3064

- Kubernetes version:

  **Output of `kubectl version`:**

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T14:17:52Z", GoVersion:"go1.13.13", Compiler:"gc", Platform:"linux/s390x"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/s390x"}
```

- Tekton Pipeline version:

Pipeline was installed to s390x k8s cluster using `ko apply -f config/` from master branch as per https://github.com/tektoncd/pipeline/blob/3a7a693429c605a67e30efa5b74675e403be79bb/DEVELOPMENT.md#install-pipeline

### PR DESCRIPTION
**Pull request by bahetiamit**
# Changes

This PR fixes an issue wherein even if the multi-arch image is available, always amd64 image is getting pulled (#3086)

This happens as go-containerregistry package pulls amd64 image by default (Reference - https://github.com/google/go-containerregistry/blob/9f2724c4b962e4eb0630f8611f9382fb83e4e2e7/pkg/v1/remote/options.go#L113 )

Although the change is generic and applicable for all other architectures, I was able to successfully test using following e2e test cases on POWER (ppc64le) platform for which ubuntu, busybox and alpine/git images are required and they are multi-arch images. 

1. TestWorkingDirCreated
2. TestWorkingDirIgnoredNonSlashWorkspace
3. TestEntrypointRunningStepsInOrder
4. TestGitPipelineRun
5. TestGitPipelineRunFail
6. TestTaskRun_EmbeddedResource

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

```release-note
The entrypoint lookup will pull the image for the controller's architecture instead of amd64 to better support different architectures
```

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
/cc @jonjohnsonjr @mattmoor

**Comment by mattmoor** [comment]
I literally hit this last night and was going to debug and fix this today.  I love OSS :)

File: pkg/pod/entrypoint_lookup_impl.go [hunk 1]
```diff
@@ -67,7 +67,13 @@ func (e *entrypointCache) Get(ref name.Reference, namespace, serviceAccountName
 		return nil, fmt.Errorf("error creating k8schain: %v", err)
 	}
 	mkc := authn.NewMultiKeychain(kc)
-	img, err := remote.Image(ref, remote.WithAuthFromKeychain(mkc))
+	//By default go-containerregistry pulls amd64 images.
+	//Setting correct image pull architecture based on the underlying platform
+	var pf = v1.Platform {
+        		Architecture: runtime.GOARCH ,
+	        	OS :          "linux",
+        	}
```
Comment (mattmoor) [inline pkg/pod/entrypoint_lookup_impl.go:75]: nit: `gofmt -s -w` this file

File: pkg/pod/entrypoint_lookup_impl.go [hunk 2]
```diff
@@ -67,7 +67,13 @@ func (e *entrypointCache) Get(ref name.Reference, namespace, serviceAccountName
...
+	img, err := remote.Image(ref, remote.WithAuthFromKeychain(mkc), remote.WithPlatform(pf))
```
Comment (mattmoor) [inline pkg/pod/entrypoint_lookup_impl.go:76]: This is probably the right band-aid for supporting multi-arch on homogeneous clusters short-term, but we should probably open an issue to further discuss heterogeneous clusters (where the controller may be running on a different platform than the pod gets scheduled on).

One problem with this in general is that different architectures could (technically) have different entrypoints, so to properly support multi-arch on heterogeneous clusters, I think we will need to pass through all of the arch-specific configs and have the endpoint select the appropriate one based on where it schedules.

Comment (mattmoor) [reply pkg/pod/entrypoint_lookup_impl.go:76]: To give an example of a subtle, but significant variation in config, when playing with multi-arch `kaniko` I rebuilt with Bazel and ended up with `/kaniko/executor_{arch}` as the entrypoint in the respective architecture images.  So while my early intuition was that these should largely be the same, I don't think we can assume that.

Again: this probably shouldn't hold up this tactical change for homogeneous clusters, but is something that should be considered for heterogeneous multi-arch support.

Comment (vdemeester) [reply pkg/pod/entrypoint_lookup_impl.go:76]: @mattmoor right, but we *do* fetch the image here to get the entrypoint from the config. So if the entrypoint is correctly set in the image to `/kaniko/executor_{arch}`, it shouldn't be a problem, should it ? :thinking:

Comment (jonjohnsonjr) [reply pkg/pod/entrypoint_lookup_impl.go:76]: > it shouldn't be a problem, should it ? 

Only if the arch where the pod will be scheduled matches the arch of the node where this code is running to look up the entrypoint. If you have a controller on amd64 and schedule a task on arm, you could run into issues (assuming I understand correctly what this code is doing).

File: pkg/pod/entrypoint_lookup_impl.go [hunk 3]
```diff
@@ -67,7 +67,13 @@ func (e *entrypointCache) Get(ref name.Reference, namespace, serviceAccountName
 		return nil, fmt.Errorf("error creating k8schain: %v", err)
 	}
 	mkc := authn.NewMultiKeychain(kc)
-	img, err := remote.Image(ref, remote.WithAuthFromKeychain(mkc))
+	//By default go-containerregistry pulls amd64 images.
+	//Setting correct image pull architecture based on the underlying platform
+	var pf = v1.Platform {
+        		Architecture: runtime.GOARCH ,
+	        	OS :          "linux",
```
Comment (mattmoor) [inline pkg/pod/entrypoint_lookup_impl.go:74]: Perhaps for good measure this should also be `runtime.GOOS`?

**Comment by mattmoor** [comment]
FWIW with this and some other changes I was able to perform a kaniko build on my RPi4 🤩 

It was crazy slow, but I will try graviton next 😉

File: pkg/pod/entrypoint_lookup_impl.go (hunk 1 above)
Comment (bahetiamit) [reply pkg/pod/entrypoint_lookup_impl.go]: Formatted the change.

File: pkg/pod/entrypoint_lookup_impl.go (hunk 3 above)
Comment (bahetiamit) [reply pkg/pod/entrypoint_lookup_impl.go]: Good suggestion. Made the required changes.

File: pkg/pod/entrypoint_lookup_impl.go (hunk 2 above)
Comment (vdemeester) [reply pkg/pod/entrypoint_lookup_impl.go:76]: > If you have a controller on amd64 and schedule a task on arm, you could run into issues (assuming I understand correctly what this code is doing).
Ah, indeed, I didn't thought of that one :sweat:

Comment (ImJasonH) [reply pkg/pod/entrypoint_lookup_impl.go:76]: I think it's worth calling out this behavior in a comment in the code. Something like:

```
// By default go-containerregistry pulls amd64 images.
// Setting correct image pull architecture based on the underlying platform
// _of the node that Tekton's controller is running on_. If the cluster
// is comprised of nodes of heterogeneous architectures, this might cause issues.
```

**Comment by ImJasonH** [comment]
@bahetiamit thanks for making this change! You'll need to [sign the LF CLA](https://api.lfcla.com/v2/repository-provider/github/sign/8049964/146641150/3337) to get this merged.

**Comment by bahetiamit** [comment]
> @bahetiamit thanks for making this change! You'll need to [sign the LF CLA](https://api.lfcla.com/v2/repository-provider/github/sign/8049964/146641150/3337) to get this merged.

@ImJasonH My bad. I am working towards it. As this needs to be corporate CLA, it is taking some time.

**Comment by snehlatamohite** [comment]
We have CLA approvals just need to confirm manager at our end, I have started confirmation on this.

File: pkg/pod/entrypoint_lookup_impl.go [hunk 4]
```diff
@@ -18,14 +18,14 @@ package pod
...
 	"fmt"
-
 	"github.com/google/go-containerregistry/pkg/authn"
 	"github.com/google/go-containerregistry/pkg/authn/k8schain"
 	"github.com/google/go-containerregistry/pkg/name"
 	v1 "github.com/google/go-containerregistry/pkg/v1"
 	"github.com/google/go-containerregistry/pkg/v1/remote"
 	lru "github.com/hashicorp/golang-lru"
 	"k8s.io/client-go/kubernetes"
+	"runtime"
```
Comment (mattmoor) [inline pkg/pod/entrypoint_lookup_impl.go:28]: technically `goimports` wants this up under `fmt` with a line of whitespace before the `github.com` imports.

Comment (bahetiamit) [reply pkg/pod/entrypoint_lookup_impl.go:28]: That's because of `gofmt`  - https://github.com/golang/go/issues/37719. Do you want me to change ordering? For this repo, we use `goimports` tool?

Comment (mattmoor) [reply pkg/pod/entrypoint_lookup_impl.go:28]: `gofmt` moved it down because you removed the blank line.  May as well stick it back up at the top and add the newline while we are waiting on CLA 😅 

Sort of annoying that different go tools futz with the same parts, but in inconsistent ways...  thanks 🙏

File: pkg/pod/entrypoint_lookup_impl.go [hunk 5]
```diff
@@ -67,7 +67,13 @@ func (e *entrypointCache) Get(ref name.Reference, namespace, serviceAccountName
 		return nil, fmt.Errorf("error creating k8schain: %v", err)
 	}
 	mkc := authn.NewMultiKeychain(kc)
-	img, err := remote.Image(ref, remote.WithAuthFromKeychain(mkc))
+	//By default go-containerregistry pulls amd64 images.
+	//Setting correct image pull architecture based on the underlying platform
+	var pf = v1.Platform{
```
Comment (mattmoor) [inline pkg/pod/entrypoint_lookup_impl.go:72]:
```suggestion
	// By default go-containerregistry pulls amd64 images.
	// Setting correct image pull architecture based on the underlying platform
	var pf = v1.Platform{
```

File: pkg/pod/entrypoint_lookup_impl.go (hunk 2 above)
Comment (mattmoor) [reply pkg/pod/entrypoint_lookup_impl.go:76]: Make a suggested edit with this above, since I was adding a nit for spacing anyhow.

**Comment by mattmoor** [comment]
This LGTM.  Any update on the CLA @bahetiamit ?

**Comment by bahetiamit** [comment]
> This LGTM. Any update on the CLA @bahetiamit ?

@mattmoor  Request to CLA manager is sent. May be in next few hours I will be in whitelist & we should be good to go.

**Comment by bahetiamit** [comment]
@mattmoor EasyCLA is now in place.

**Review by mattmoor — APPROVED** [review]
/ok-to-test
/lgtm

**Review by ImJasonH — COMMENTED** [review]
/lgtm

**Review by vdemeester — APPROVED** [review]
Added a release-note part :wink: 
/meow
