### PR TITLE
Fix Taskrun Failure for Preempted Pod of Taskrun

### LINKED ISSUE #6947: VolumeMounts generated for both step and steptemplate
# Expected Behavior
Taskrun should run successfully. For the successful run, `volumemounts` are created for `stepTemplate`.
# Actual Behavior
Sometimes, we get `volumemounts` for both step and steptemplate:
```
      message: 'failed to create task run pod "foo"-xcsd:
        workspace mount path "/workspace/additional-logs" must be unique: workspaces[0].mountpath.
        Maybe missing or invalid Task projects/foobar'
      reason: PodCreationFailed
```
This happens infrequently. And is not easily reproducible.

# Steps to Reproduce the Problem

1.  kc apply -f https://gist.githubusercontent.com/khrm/6f06e9e36b6aead4554d4671fc2b1b23/raw/81d37e32406d9d84a4635b8cee4d8b34116b5959/gistfile0.txt
2. for i in {1..7}; do kc create -f https://gist.githubusercontent.com/khrm/7e9546945e2088c96f9fa6cad38a2060/raw/0be00dd9661057262595b159345a86391f85b4c3/gistfile0.txt; done
3. Sometime, one of the taskrun generated will be failed for the above pipelineruns.
# Additional Info

- Kubernetes version:
1.25 (OpenShift 4.12.19)

- Tekton Pipeline version:
0.47.2

### PR DESCRIPTION
**Pull request by khrm**
This fixes the Taskrun failure for Preempted Pod of Taskrun. In CreatePod, we stop deep copying task spec since v46.0 which causes failure when we preempt pod. Killing the pod twice or thrice should fail the Taskrun because we overwrite information about task spec in the Taskrun status and when the pod is recreated, validation will fail. Like volume mount for workspace validation will fail in the case of PVC.

Fixes #6947 

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
This fixes the Taskrun failure for Preempted Pod of Taskrun which uses PVC. 
```

### CODE REVIEW

**Comment by khrm** [comment]
We will need to fix this for v0.46, v0.47, v0.48 and v0.49.

**Review by khrm — COMMENTED** [review]
/kind bug

File: pkg/reconciler/taskrun/taskrun.go [hunk 1]
```diff
@@ -709,6 +709,8 @@ func (c *Reconciler) createPod(ctx context.Context, ts *v1.TaskSpec, tr *v1.Task
 	defer span.End()
 	logger := logging.FromContext(ctx)
 
+	ts = ts.DeepCopy()
```
Comment (vdemeester) [inline pkg/reconciler/taskrun/taskrun.go:712]: We may want a comment on top explaining why this is here and needed (otherwise, I can definitely see someone else, later, removing it).

Also, any reason to to it here and not above (in what calls `createPod`) ?

**Review by vdemeester — COMMENTED** [review]
@khrm any way to write a regression test for this somehow ? (in `taskrun_test.go` or something)

**Comment by khrm** [comment]
@vdemeester Sure, I would write a test.

File: pkg/reconciler/taskrun/taskrun.go (hunk 1 above)
Comment (vdemeester) [reply pkg/reconciler/taskrun/taskrun.go:712]: right, we need a comment then 👼🏼

Comment (khrm) [reply pkg/reconciler/taskrun/taskrun.go:718]: Added the comment.

**Comment by khrm** [comment]
@vdemeester I have added the test. Please check.

**Review by vdemeester — COMMENTED** [review]
/lgtm

File: pkg/reconciler/taskrun/taskrun.go [hunk 2]
```diff
@@ -709,6 +709,14 @@ func (c *Reconciler) createPod(ctx context.Context, ts *v1.TaskSpec, tr *v1.Task
 	defer span.End()
 	logger := logging.FromContext(ctx)
 
+	// We don't want to mutatate tr.Status.TaskSpec inside
```
Comment (afrittoli) [inline pkg/reconciler/taskrun/taskrun.go:712]: NIT: s/mutatate/mutate

File: test/premption_test.go [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+	// Get the status of the Taskrun again.
+	err = WaitForTaskRunState(ctx, c, tr.Name, ExceededNodeResources(tr.Name), "TaskRunRunning", v1Version)
+	if err != nil {
+		t.Errorf("Error waiting for TaskRun %s to be ExceededNodeResources: %v", tr.Name, err)
+	}
+}
+
+// ExceededNodeResources provides a poll condition function that checks if the ConditionAccessor
+// resource is currently ExceededNodeResources.
+func ExceededNodeResources(name string) ConditionAccessorFn {
```
Comment (afrittoli) [inline test/premption_test.go:158]: NIT: this function does not need to be exported

**Review by afrittoli — COMMENTED** [review]
Thank you for fixing this bug!
/approve

File: test/premption_test.go (hunk 3 above)
Comment (khrm) [reply test/premption_test.go]: Changed to private.
