### PR TITLE
fix(pipeline): correct warning path for duplicate param name in pipeline tasks

### LINKED ISSUE #7650: When a duplicate parameter name is encountered in the pipeline, there is an issue with inaccurate path reporting.
# Expected Behavior

```
admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: params names must be unique, the same param: abc is defined multiple times at:
spec.tasks[0].params[1].name
```

# Actual Behavior

```
admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: parameter names must be unique, the parameter "abc" is also defined at:
spec.tasks.params[0][1].name, spec.tasks[0].params[1].name
```

# Steps to Reproduce the Problem

1. Create a pipeline
```
cat <<EOF | kubectl create -f -
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: name-1
      taskRef:
        name: hi
        kind: Task
      params:
        - name: "abc"
          value: ""
        - name: "abc"
          value: ""
EOF
```

# Additional Info

- Kubernetes version:

```
Client Version: v1.29.1
Server Version: v1.27.7
```

- Tekton Pipeline version:

```
v0.56.0
```

### PR DESCRIPTION
**Pull request by l-qing**
fix #7650

This error message has been present since v0.48. https://github.com/tektoncd/pipeline/commit/fd09e499de9e549007c39782c2b441b5abf6f1e7

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

/kind bug

# Release Notes

```release-note
fix: correct warning path for duplicate param name in pipeline tasks
```

### CODE REVIEW

File: pkg/apis/pipeline/v1/pipeline_validation.go [hunk 1]
```diff
@@ -382,7 +382,7 @@ func validatePipelineTaskParameterUsage(tasks []PipelineTask, params ParamSpecs)
 	}
 	errs = errs.Also(validatePipelineParametersVariables(tasks, "params", allParamNames, arrayParamNames, objectParameterNameKeys))
 	for i, task := range tasks {
-		errs = errs.Also(task.Params.validateDuplicateParameters().ViaFieldIndex("params", i))
+		errs = errs.Also(task.Params.validateDuplicateParameters().ViaField("params").ViaIndex(i))
```
Comment (l-qing) [inline pkg/apis/pipeline/v1/pipeline_validation.go:385]: reference:
https://github.com/tektoncd/pipeline/blob/e1c7828e0fad1006b6477a5ce0468a2a3182060b/pkg/apis/pipeline/v1/pipeline_validation.go#L414-L423

**Review by JeromeJu — APPROVED** [review]
Thanks for this fix @l-qing !
