### PR TITLE
fix: Prevent excessive reconciliation when timeout disabled

### LINKED ISSUE #8495: PipelineRun is reconciled thousands of times
# Expected Behavior
Reconciliation only happens on change

# Actual Behavior
Reconciliation happens thousands of times over and over again

# Steps to Reproduce the Problem
I still need to investigate further what might cause the behavior and how to reproduce it reliably. Eventually, the pipeline run completes successfully. However, while it is in progress, I can see in the controller's logs that it is reconciled repeatedly.

I´ve attached an example of logs of the controller.

[controller-logs.txt](https://github.com/user-attachments/files/18441668/controller-logs.txt)

# Additional Info

- Kubernetes version:

```
v1.30.6
```

- Tekton Pipeline version:

```
v0.66.0
```

Has anyone seen similar behavior?

Thanks,
Fabian

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

- Stop immediate requeue loops when default-timeout-minutes is "0"
- Remove redundant hasCondition checks (Knative already deduplicates)

This adds an e2e tests that looks at pipeline logs to see how much reconciler loop there is. If you run it before the fix, it would count more than 1500 reconciler loop, whereas with the fix, only about 10.

/cc @afrittoli @pritidesai @tektoncd/core-maintainers 

It took me a while to figure out, and I got some help from Claude (AI) to write the tests. The previous behavior seemed very weird as well, with no timeout, we would, re-queue instantly, which is.. madness 🙃 

/kind bug

Fixes #8495

This could be a good candidate to be backported.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Fix an issue where there was excessive reconciliation in case of no timeout on TaskRun or PipelineRun.
```

### CODE REVIEW

**Comment by vdemeester** [comment]
/hold
Getting help from Claude to figure out the e2e failures 😅 Will remove the hold once I get greens

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 1]
```diff
@@ -275,22 +274,39 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1.PipelineRun) pkgr
...
+		// If the main pipeline timeout is NoTimeoutDuration (0), it means no timeout is configured.
+		// This can happen in two ways:
+		// 1. User explicitly set pr.Spec.Timeouts.Pipeline to 0 (wants no timeout)
+		// 2. User didn't set pr.Spec.Timeouts.Pipeline (nil) AND default-timeout-minutes config is "0"
+		// In these cases, check if there are specific task or finally timeouts to enforce.
+		// If not, don't requeue - the reconciler will be triggered by watch events.
 		if timeout == config.NoTimeoutDuration {
-			waitTime = time.Duration(config.FromContextOrDefaults(ctx).Defaults.DefaultTimeoutMinutes) * time.Minute
+			// Check if we have a specific task timeout to wait for
+			if pr.Status.FinallyStartTime == nil && taskTimeout != nil && taskTimeout.Duration != config.NoTimeoutDuration {
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/pipelinerun.go]: The introduced checks here and the existing below are quite similar. I would keep the style consistent in both of them. The early returns is the way to go. Then this code is a bit easier to understand. I will add comments in each line where I would change up a bit.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 2]
```diff
@@ -275,22 +274,39 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1.PipelineRun) pkgr
...
+				waitTime := taskTimeout.Duration - elapsed
+				return controller.NewRequeueAfter(waitTime)
+			}
+			// Check if we have a finally timeout to wait for
+			if pr.Status.FinallyStartTime != nil && pr.FinallyTimeout() != nil && pr.FinallyTimeout().Duration != config.NoTimeoutDuration {
+				waitTime := pr.FinallyTimeout().Duration - c.Clock.Since(pr.Status.FinallyStartTime.Time)
+				return controller.NewRequeueAfter(waitTime)
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/pipelinerun.go]: Lets use the same variable naming as below. Is clearer.

```suggestion
				finallyWaitTime := pr.FinallyTimeout().Duration - c.Clock.Since(pr.Status.FinallyStartTime.Time)
				return controller.NewRequeueAfter(finallyWaitTime)
```

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 3]
```diff
@@ -275,22 +274,39 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1.PipelineRun) pkgr
...
+
+		// Pipeline timeout is set, calculate wait time based on the most restrictive timeout
+		waitTime := timeout - elapsed
 		if pr.Status.FinallyStartTime == nil && taskTimeout != nil {
-			waitTime = pr.TasksTimeout().Duration - elapsed
+			waitTime = taskTimeout.Duration - elapsed
 			if taskTimeout.Duration == config.NoTimeoutDuration {
-				waitTime = time.Duration(config.FromContextOrDefaults(ctx).Defaults.DefaultTimeoutMinutes) * time.Minute
+				waitTime = timeout - elapsed
 			}
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/pipelinerun.go]: Add an early return here like above and break the `if-else-if` apart. Like you have above.

```suggestion
						return controller.NewRequeueAfter(waitTime)
			}
```

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 4]
```diff
@@ -275,22 +274,39 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1.PipelineRun) pkgr
...
 		} else if pr.Status.FinallyStartTime != nil && pr.FinallyTimeout() != nil &&
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/pipelinerun.go]: Break the `else-if` and move `return controller.NewRequeueAfter(waitTime)` into the if.

```go
		}

		if pr.Status.FinallyStartTime != nil && pr.FinallyTimeout() != nil &&
			pr.FinallyTimeout().Duration != config.NoTimeoutDuration {
			finallyWaitTime := pr.FinallyTimeout().Duration - c.Clock.Since(pr.Status.FinallyStartTime.Time)
			if finallyWaitTime < waitTime {
				waitTime = finallyWaitTime
			}
			return controller.NewRequeueAfter(waitTime)
		}
	}
	return nil
}
```

Can't do a better suggestion on the hidden lines. This is how it should look like

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 5]
```diff
@@ -275,22 +274,39 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1.PipelineRun) pkgr
...
+		// If not, don't requeue - the reconciler will be triggered by watch events.
 		if timeout == config.NoTimeoutDuration {
-			waitTime = time.Duration(config.FromContextOrDefaults(ctx).Defaults.DefaultTimeoutMinutes) * time.Minute
+			// Check if we have a specific task timeout to wait for
+			if pr.Status.FinallyStartTime == nil && taskTimeout != nil && taskTimeout.Duration != config.NoTimeoutDuration {
+				waitTime := taskTimeout.Duration - elapsed
+				return controller.NewRequeueAfter(waitTime)
+			}
+			// Check if we have a finally timeout to wait for
+			if pr.Status.FinallyStartTime != nil && pr.FinallyTimeout() != nil && pr.FinallyTimeout().Duration != config.NoTimeoutDuration {
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/pipelinerun.go]: This check is identical to the check in 311-316. Don't you need this here too?:

```go
if finallyWaitTime < waitTime {
		waitTime = finallyWaitTime
}
```

**Review by twoGiants — COMMENTED** [review]
Great job for the fix :smile_cat: :+1:. My brain got challenged understanding the timeout order... :brain: :zap:. It looks good though! I would just keep the code a bit more consistent, will aid in future understanding.

See my comments below.

**Comment by vdemeester** [comment]
@twoGiants I changed a bit the if/else chains to make it.. less weird.. hopefully it's more readable.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 6]
```diff
@@ -275,31 +274,50 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1.PipelineRun) pkgr
...
+		// Check which phase we're in and handle timeout accordingly
+		if pr.Status.FinallyStartTime != nil {
+			// We're in finally phase - check for finally-specific timeout
+			if pr.FinallyTimeout() != nil && pr.FinallyTimeout().Duration != config.NoTimeoutDuration {
+				finallyWaitTime := pr.FinallyTimeout().Duration - c.Clock.Since(pr.Status.FinallyStartTime.Time)
+				// If pipeline timeout is also set, use the most restrictive timeout
+				if timeout != config.NoTimeoutDuration {
+					waitTime := timeout - elapsed
+					if finallyWaitTime < waitTime {
+						waitTime = finallyWaitTime
```
Comment (twoGiants) [inline pkg/reconciler/pipelinerun/pipelinerun.go:298]:
```suggestion
						return controller.NewRequeueAfter(finallyWaitTime)
```

File: test/excessive_reconciliation_test.go [hunk 7]
```diff
@@ -0,0 +1,328 @@
...
+}
+
+// TestPipelineRunExcessiveReconciliation verifies that PipelineRuns and their TaskRuns
+// don't get reconciled excessively while in Running state. This is a regression test for issue #8495.
+//
+// Without the fix, both the PipelineRun and TaskRun would be reconciled hundreds or thousands of times.
+// With the fix, reconciliations should stay well below 20 (typically around 10 or less).
+//
+// This test validates the fix by counting actual reconciliations from controller logs.
+func TestPipelineRunExcessiveReconciliation(t *testing.T) {
```
Comment (twoGiants) [inline test/excessive_reconciliation_test.go:62]: Categorize the test as a parallel test following the new categorization logic.

**Review by twoGiants — APPROVED** [review]
Looks good! :smile_cat: :+1: 

I would just add a category the tests => parallel and return early in a if.

/approve
/lgtm

**Comment by vdemeester** [comment]
arf, we probably need to do it manually ? 🤔 or something is fishy...
