### PR TITLE
Do not propagate managed-by annotation to Pods

### LINKED ISSUE #8827: Pipelines controller fails to apply app.kubernetes.io/managed-by: tekton-pipelines label when deploying PipelineRuns and TaskRuns via Helm, affecting environment variable injection
# Expected Behavior
Regardless of how the PipelineRun is created (via Helm or kubectl ), the Tekton Pipelines controller should:
   - Override the app.kubernetes.io/managed-by label on pods to tekton-pipelines.
   - Inject expected environment variables accordingly.
 
# Actual Behavior
When PipelineRuns are deployed via Helm, the pods created for the associated TaskRuns are labeled with:
`app.kubernetes.io/managed-by: Helm`
These pods do not receive certain environment variables such as SSL_CERT_DIR.

# Steps to Reproduce the Problem

1. Define a PipelineRun in a Helm chart template.
2. Deploy it using helm install.
3. Observe the labels on the resulting pods created for the TaskRuns.
4. Compare this with pods created by PipelineRuns triggered via kubectl or the Tekton dashboard.

# Additional Info

When PipelineRuns are created via kubectl apply or via the Tekton UI/CLI, the controller does set the correct label and injects the required env vars into pods.

When created via Helm, the label app.kubernetes.io/managed-by: Helm persists and pods lack required environment variables.

This leads to functional issues in environments where those variables (like SSL_CERT_DIR) are critical.

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Closes #8827

Let's make sure we are not propagating `app.kubernetes.io/managed-by`
annotation to Pods. Doing it can lead to weird behavior, for example
with applied with Helm, or if some admission controller is looking for
pipeline's Pods and do not get it if the `TaskRun` or `PipelineRun`
was created with an `app.kubernetes.io/managed-by`.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Pod created by the Pipeline controller will now always have app.kubernetes.io/managed-by set to the default configuration. Prior to this change, it would be overriden by the value of that label set on TaskRun (or PipelineRun).
```

### CODE REVIEW

**Comment by vdemeester** [comment]
cc @twoGiants @afrittoli @waveywaves

File: pkg/reconciler/constant.go [hunk 1]
```diff
@@ -19,4 +19,7 @@ package reconciler
 const (
 	// KubectlLastAppliedAnnotationKey is the key used by kubectl to store its last applied configuration (using kubectl apply)
 	KubectlLastAppliedAnnotationKey = "kubectl.kubernetes.io/last-applied-configuration"
+
+	// KubernetesLastAppliedAnnotationKey is the key used by tools to tell who is managing an object
```
Comment (twoGiants) [inline pkg/reconciler/constant.go:23]: Small typo: `// KubernetesLastAppliedAnnotationKey` => `// KubernetesManagedByAnnotationKey`

File: pkg/pod/pod.go [hunk 2]
```diff
@@ -543,6 +546,8 @@ func makeLabels(s *v1.TaskRun) map[string]string {
 	// specifies this label, it should be overridden by this value.
 	labels[pipeline.TaskRunLabelKey] = s.Name
 	labels[pipeline.TaskRunUIDLabelKey] = string(s.UID)
+	// Enforce app.kubernetes.io/managed-by to be the value configured
+	labels[tknreconciler.KubernetesManagedByAnnotationKey] = defaultManagedByLabelValue
```
Comment (twoGiants) [inline pkg/pod/pod.go:550]: Just thinking out loud: could this live in the pipelinerun reconciler when the TaskRun is created with it's labels and annotations? For example here in [`getTaskRunLabels` line 1408](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/pipelinerun.go#L1408). Then those labels should be correctly propagated down to the pod right?

And the same for excluding the annotation. You could enforce it here in the [`getTaskrunAnnotations` line 1358](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/pipelinerun.go#L1358).

Then no change to pod would be necessary and the source of truth remains the place where the labels and annotations are set in the first place.

Wdyt?

**Review by twoGiants — APPROVED** [review]
Looks good :smile_cat:  :+1: 

I found one typo and have a question/idea about the location of the change. It can be left as it is but maybe there is a better place, see my comment below.

File: pkg/pod/pod_test.go
Comment (twoGiants) [inline pkg/pod/pod_test.go:1]: You could also add a test which checks that the Annotation was not set.

And because this PR resolves a bug we could add a comment with the issue reference to the added tests mentioning that those test checks against a resolved bug from #8827.

File: pkg/pod/pod.go (hunk 2 above)
Comment (vdemeester) [reply pkg/pod/pod.go:550]: I am not sure, for me no matter what is there on TaskRun and PipelineRun, we *really* do not want this particular label to be propagated. So the quickest path to it was to do it when we create the Pod.

File: pkg/pod/pod.go [hunk 3]
```diff
@@ -491,7 +494,7 @@ func (b *Builder) Build(ctx context.Context, taskRun *v1.TaskRun, taskSpec v1.Ta
 				*metav1.NewControllerRef(taskRun, groupVersionKind),
 			},
 			Annotations: podAnnotations,
-			Labels:      makeLabels(taskRun),
+			Labels:      makeLabels(taskRun, defaultManagedByLabelValue),
```
Comment (waveywaves) [inline pkg/pod/pod.go:497]: ✨

**Review by waveywaves — APPROVED** [review]
