### PR TITLE
Unscheduled Runs shouldn't be included in full status

### LINKED ISSUE #5282: [REGRESSION] Unable to cancel pipeline run - error PipelineRunCouldntCancel reported on a pending custom task
# Expected Behavior

Pipeline run with unscheduled custom test should be cancellable.

Regression: **This scenario works correctly on v0.33.1.**

# Actual Behavior

When cancelling a pipeline run, which contains unscheduled custom test, the error `PipelineRunCouldntCancel` occurs.

# Steps to Reproduce the Problem

1. Install [wait-task](https://github.com/tektoncd/experimental/tree/main/wait-task) custom task controller.
2. Run a sample pipeline run with tow steps, one depended on the other:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cancel-test-
spec:
  pipelineSpec:
    tasks:
    - name: wait-1
      taskSpec:
        apiVersion: example.dev/v0
        kind: Wait
      params:
        - name: duration
          value: 1h
    - name: wait-2
      runAfter:
        - wait-1
      taskSpec:
        apiVersion: example.dev/v0
        kind: Wait
      params:
        - name: duration
          value: 10s
  serviceAccountName: pipeline-runner
```
3. Cancel the pipeline run setting `spec.status` to "Cancelled". The final `PipelineRun` status is:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: "2022-08-08T09:09:13Z"
  generateName: cancel-test-
  generation: 2
  labels:
    tekton.dev/pipeline: cancel-test-qwndq
  name: cancel-test-qwndq
  namespace: wait-task
  resourceVersion: "10224"
  uid: 5cb9a96f-fbfe-4103-961f-81ff775c0a33
spec:
  pipelineSpec:
    tasks:
    - name: wait-1
      params:
      - name: duration
        value: 1h
      taskSpec:
        apiVersion: example.dev/v0
        kind: Wait
        metadata: {}
        spec: null
    - name: wait-2
      params:
      - name: duration
        value: 10s
      runAfter:
      - wait-1
      taskSpec:
        apiVersion: example.dev/v0
        kind: Wait
        metadata: {}
        spec: null
  serviceAccountName: pipeline-runner
  status: Cancelled
  timeout: 1h0m0s
status:
  conditions:
  - lastTransitionTime: "2022-08-08T09:10:18Z"
    message: 'PipelineRun "cancel-test-qwndq" was cancelled but had errors trying
      to cancel TaskRuns and/or Runs: Failed to patch Run `cancel-test-qwndq-wait-2`
      with cancellation: runs.tekton.dev "cancel-test-qwndq-wait-2" not found'
    reason: PipelineRunCouldntCancel
    status: Unknown
    type: Succeeded
  pipelineSpec:
    tasks:
    - name: wait-1
      params:
      - name: duration
        value: 1h
      taskSpec:
        apiVersion: example.dev/v0
        kind: Wait
        metadata: {}
        spec: null
    - name: wait-2
      params:
      - name: duration
        value: 10s
      runAfter:
      - wait-1
      taskSpec:
        apiVersion: example.dev/v0
        kind: Wait
        metadata: {}
        spec: null
  runs:
    cancel-test-qwndq-wait-1:
      pipelineTaskName: wait-1
      status:
        extraFields: null
    cancel-test-qwndq-wait-2:
      pipelineTaskName: wait-2
  startTime: "2022-08-08T09:09:13Z"
``` 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:36:49Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.25.0
Pipeline version: v0.38.2
```

### PR DESCRIPTION
**Pull request by abayer**
# Changes

Fixes #5282

When removing conditions, I accidentally made `GetRunsStatus` not skip including custom task `ResolvedPipelineTask`s without `Run`s in the `PipelineRun.Status.Runs` map. This resulted in cancellation failing, because the cancellation logic tries to patch each `Run` or `TaskRun` in the `PipelineRun` status (either in the `Runs` and `TaskRuns` maps for full embedded status, or `ChildReferences` for minimal or both embedded status). Unscheduled `PipelineTask`s for `Task`s were already properly excluded from the status map, and `ChildReferences` was fine either way, but due to the oversight I mentioned above, unscheduled `PipelineTask`s for custom tasks _were_ included in the full embedded status map, and cancellation would error due to that.

This will need to be cherry-picked to v0.37.x and v0.38.x, since the issue was a regression.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Fix cancellation of PipelineRuns with unscheduled custom tasks.
```

### CODE REVIEW

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 1]
```diff
@@ -10004,3 +10004,61 @@ spec:
...
+      - name: wait-3
+        runAfter:
+          - wait-1
+        taskRef:
+          name: hello-world
+`)}
+
+	ts := []*v1beta1.Task{simpleHelloWorldTask}
+
+	cms := []*corev1.ConfigMap{withCustomTasks(newFeatureFlagsConfigMap())}
```
Comment (afrittoli) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:10041]: Would it make sense to make this a matrix test and check also the case

```golang
cms := []*corev1.ConfigMap{withCustomTasks(withEmbeddedStatus(newFeatureFlagsConfigMap(), config.MinimalEmbeddedStatus))}
```

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:10041]: Good call!

Comment (abayer) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go]: And done.

**Review by afrittoli — COMMENTED** [review]
🎉 

/approve

**Comment by abayer** [comment]
cc @tektoncd/core-maintainers - we're going to be cherry-picking this back to 0.37 and 0.38, so an lgtm would be much appreciated. =)

File: pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go [hunk 2]
```diff
@@ -2381,6 +2381,15 @@ spec:
 		}},
 		TaskRef: &v1beta1.TaskRef{Name: "unit-test-task"},
 	}
+	unscheduledPipelineTask := v1beta1.PipelineTask{
+		Name: "unit-test-2",
+		WhenExpressions: []v1beta1.WhenExpression{{
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go:2386]: What is the significance of `whenExpression` in the test?

Comment (abayer) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go:2386]: None - I just copy-pasted the task above.

Comment (pritidesai) [reply pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go:2386]: will be great to avoid such copy/paste specially given that it does not bring any value to the test, thanks 🙏

**Comment by pritidesai** [comment]
thanks @abayer 👍 

/lgtm
