### PR TITLE
Add a status_msg field to fix issue 5150.

### LINKED ISSUE #5150: TaskRuns and Runs support accepting a cancellation reason
Today, users can [cancel a TaskRun](https://tekton.dev/docs/pipelines/taskruns/#cancelling-a-taskrun), and this logic is also [used by the PipelineRun reconciler](https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/cancel.go) to cancel child TaskRuns when the PipelineRun is cancelled. 

In https://github.com/tektoncd/pipeline/pull/5134, we'd like to change how PipelineRuns time out their child TaskRuns. Instead of selecting the TaskRun timeout when it is first created based on the PipelineRun's `spec.timeouts`, we want to allow the PipelineRun to cancel the TaskRuns when it reaches its timeout in a way that indicates to the user what the reason for timeout is.

We'll probably want to do the same for Runs.

FYI @abayer @afrittoli @vdemeester

### PR DESCRIPTION
**Pull request by jagathprakash**
# Changes

- Adds a new field status_msg to taskrun spec and run spec. This field adds an user_defined / pre-defined messages for run status. 
- status_msg is used to propagate pipeline run cancellations to taskruns and tasks.

/kind bug
fixes #5150

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Users can now differentiate if a TaskRun was cancelled by the user or by cancellation of a PipelineRun of which the TaskRun was a part of, by looking at the TaskRun's spec.StatusMessage field.
```

### CODE REVIEW

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 1]
```diff
@@ -60,6 +60,10 @@ type RunSpec struct {
 	// +optional
 	Status RunSpecStatus `json:"status,omitempty"`
 
+	// Status message for cancellation.
+	// +optional
+	StatusMessage RunSpecStatusMessage `json:"status_msg,omitempty"`
```
Comment (abayer) [inline pkg/apis/pipeline/v1alpha1/run_types.go:65]: The json tag should be `statusMessage` for consistency.

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 2]
```diff
@@ -90,6 +94,14 @@ const (
 	RunSpecStatusCancelled RunSpecStatus = "RunCancelled"
 )
 
+// RunSpecStatusMessage defines human readable status messages for the TaskRun.
+type RunSpecStatusMessage string
+
+const (
+	// Run cancelled as the Pipeline running it was cancelled.
+	RunCancelledByPipelineMsg RunSpecStatusMessage = "Run cancelled as pipeline has been canceled."
```
Comment (abayer) [inline pkg/apis/pipeline/v1alpha1/run_types.go:102]: Should be `pipeline has been cancelled`. =)

File: pkg/apis/pipeline/v1alpha1/run_types_test.go [hunk 3]
```diff
@@ -172,6 +172,27 @@ func TestRunIsCancelled(t *testing.T) {
...
 		t.Fatal("Expected run status to be cancelled")
 	}
+	expected := ""
+	if string(run.GetStatusMessage()) != expected {
+		t.Fatalf("Expected StatusMessage is %s but got %s", expected, run.GetStatusMessage())
+	}
+}
+
+func TestRunIsCancelledWithMessage(t *testing.T) {
+	expected_status_message := "test message"
```
Comment (abayer) [inline pkg/apis/pipeline/v1alpha1/run_types_test.go:182]: This should be changed to `expectedStatusMessage`.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go [hunk 4]
```diff
@@ -52,6 +52,9 @@ type TaskRunSpec struct {
 	// Used for cancelling a taskrun (and maybe more later on)
 	// +optional
 	Status TaskRunSpecStatus `json:"status,omitempty"`
+	// Status message for cancellation.
+	// +optional
+	StatusMessage TaskRunSpecStatusMessage `json:"status_msg,omitempty"`
```
Comment (abayer) [inline pkg/apis/pipeline/v1beta1/taskrun_types.go:57]: As mentioned above in the `RunSpec`, this should be `statusMessage`, not `status_msg`.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go [hunk 5]
```diff
@@ -90,6 +93,14 @@ const (
 	TaskRunSpecStatusCancelled = "TaskRunCancelled"
 )
 
+// TaskRunSpecStatusMessage defines human readable status messages for the TaskRun.
+type TaskRunSpecStatusMessage string
+
+const (
+	// TaskRun cancelled as the Pipeline running it was cancelled.
+	TaskRunCancelledByPipelineMsg TaskRunSpecStatusMessage = "TaskRun cancelled as pipeline has been canceled."
```
Comment (abayer) [inline pkg/apis/pipeline/v1beta1/taskrun_types.go:101]: Again, as I noted above, `pipeline has been cancelled`, not `canceled`.

File: pkg/apis/pipeline/v1beta1/taskrun_types_test.go [hunk 6]
```diff
@@ -133,6 +133,27 @@ func TestTaskRunIsCancelled(t *testing.T) {
...
 		t.Fatal("Expected pipelinerun status to be cancelled")
 	}
+	expected := ""
+	if string(tr.GetStatusMessage()) != expected {
+		t.Fatalf("Expected StatusMessage is %s but got %s", expected, tr.GetStatusMessage())
+	}
+}
+
+func TestTaskRunIsCancelledWithMessage(t *testing.T) {
+	expected_status_message := "test message"
```
Comment (abayer) [inline pkg/apis/pipeline/v1beta1/taskrun_types_test.go:143]: `expectedStatusMessage`. =)

**Review by abayer — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks generally good, other than some naming tweaks.

**Comment by abayer** [comment]
`pull-tekton-pipeline-build-tests` failure is legit - https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5224/pull-tekton-pipeline-build-tests/1552276635263176704#1:build-log.txt%3A1538 - but it'll be fixed by renaming the field(s) to `statusMessage`.

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 2 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1alpha1/run_types.go:102]: Also, I think Pipeline-related constants should be defined either in the reconciler or in pipeline_types.

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 7]
```diff
@@ -189,6 +201,12 @@ func (r *Run) IsCancelled() bool {
 	return r.Spec.Status == RunSpecStatusCancelled
 }
 
+// GetStatusMessage function returns the status message is one is set on the TaskRun
```
Comment (lbernick) [inline pkg/apis/pipeline/v1alpha1/run_types.go:204]: TaskRun -> Run

File: pkg/apis/pipeline/v1alpha1/run_types_test.go [hunk 8]
```diff
@@ -172,6 +172,27 @@ func TestRunIsCancelled(t *testing.T) {
 	if !run.IsCancelled() {
 		t.Fatal("Expected run status to be cancelled")
 	}
+	expected := ""
+	if string(run.GetStatusMessage()) != expected {
+		t.Fatalf("Expected StatusMessage is %s but got %s", expected, run.GetStatusMessage())
+	}
+}
+
+func TestRunIsCancelledWithMessage(t *testing.T) {
```
Comment (lbernick) [inline pkg/apis/pipeline/v1alpha1/run_types_test.go:181]: It may be worth validating that the statusMessage is not set unless the status is set (in run_validation)

**Review by lbernick — COMMENTED** [review]
I'm wondering which would be more useful-- a human readable sentence, or a short one word reason (e.g. "ReasonPipelineRunCancelled"). [apis.Condition](https://github.com/tektoncd/pipeline/blob/55665765e4de35b3a4fb541549ae8cdef0996641/vendor/knative.dev/pkg/apis/condition_types.go#L58-L85) has both a "Reason" and a "Message" for this purpose. Thoughts?

Also @tektoncd/core-maintainers this is an API change but it is simple enough that I'm not sure a TEP is required, WDYT?

**Comment by abayer** [comment]
@lbernick Yeah, I don't think this requires a TEP.

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 1 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go:65]: Done.

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 7 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go:204]: Done

File: pkg/apis/pipeline/v1alpha1/run_types_test.go (hunk 3 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types_test.go:182]: Done

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 4 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:57]: Done

File: pkg/reconciler/taskrun/taskrun.go [hunk 9]
```diff
@@ -144,7 +144,7 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, tr *v1beta1.TaskRun) pkg
 
 	// If the TaskRun is cancelled, kill resources and update status
 	if tr.IsCancelled() {
-		message := fmt.Sprintf("TaskRun %q was cancelled", tr.Name)
+		message := fmt.Sprintf("TaskRun %q was cancelled. %s", tr.Name, tr.GetStatusMessage())
```
Comment (lbernick) [inline pkg/reconciler/taskrun/taskrun.go:147]: I think we'll want this message to be propagated to the `taskRun.status.conditions[].message`

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 10]
```diff
@@ -60,6 +60,10 @@ type RunSpec struct {
 	// +optional
 	Status RunSpecStatus `json:"status,omitempty"`
 
+	// Status message for cancellation.
+	// +optional
+	StatusMessage RunSpecStatusMessage `json:"statusMessage,omitempty"`
```
Comment (lbernick) [inline pkg/apis/pipeline/v1alpha1/run_types.go:65]: could you add some info to docs/runs.md about how custom task controllers should support this message?

**Comment by jagathprakash** [comment]
@abayer Thanks for the review. Modified the test/cancel_test.go to do an E2E test on this feature.

File: test/cancel_test.go [hunk 11]
```diff
@@ -145,6 +145,13 @@ spec:
 			}
 			for _, taskrunItem := range taskrunList.Items {
 				trName = append(trName, taskrunItem.Name)
+				if taskrunItem.Spec.Status != v1beta1.TaskRunSpecStatusCancelled {
+					t.Fatalf("Status is %s while it should have been %s", taskrunItem.Spec.Status, v1beta1.TaskRunSpecStatusCancelled)
+				}
+				if taskrunItem.Spec.StatusMessage != v1beta1.TaskRunCancelledByPipelineMsg {
+					t.Fatalf("Status message is set to %s while it should be %s.", taskrunItem.Spec.StatusMessage, v1beta1.TaskRunCancelledByPipelineMsg)
```
Comment (abayer) [inline test/cancel_test.go:152]: 👍

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 12]
```diff
@@ -90,6 +94,14 @@ const (
 	RunSpecStatusCancelled RunSpecStatus = "RunCancelled"
 )
 
+// RunSpecStatusMessage defines human readable status messages for the TaskRun.
+type RunSpecStatusMessage string
+
+const (
+	// Run cancelled as the Pipeline running it was cancelled.
```
Comment (abayer) [inline pkg/apis/pipeline/v1alpha1/run_types.go:101]: Please give this a valid godoc comment - i.e., one starting with `// RunCancelledByPipelineMsg ...`

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 13]
```diff
@@ -189,6 +201,12 @@ func (r *Run) IsCancelled() bool {
 	return r.Spec.Status == RunSpecStatusCancelled
 }
 
+// GetStatusMessage function returns the status message is one is set on the Run
+// If nothing is set as status message, GetStatusMessage returns an empty string.
+func (tr *Run) GetStatusMessage() RunSpecStatusMessage {
```
Comment (abayer) [inline pkg/apis/pipeline/v1alpha1/run_types.go:206]: Current `golangci-lint` versions will start barfing on the receiver name here not matching others in the file - so please change this to `func (r *Run) ...`.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go [hunk 14]
```diff
@@ -90,6 +93,14 @@ const (
 	TaskRunSpecStatusCancelled = "TaskRunCancelled"
 )
 
+// TaskRunSpecStatusMessage defines human readable status messages for the TaskRun.
+type TaskRunSpecStatusMessage string
+
+const (
+	// TaskRun cancelled as the Pipeline running it was cancelled.
```
Comment (abayer) [inline pkg/apis/pipeline/v1beta1/taskrun_types.go:100]: Please give this a valid godoc comment - i.e., one starting with `// TaskRunCancelledByPipelineMsg ...`

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 15]
```diff
@@ -90,6 +94,14 @@ const (
 	RunSpecStatusCancelled RunSpecStatus = "RunCancelled"
 )
 
+// RunSpecStatusMessage defines human readable status messages for the TaskRun.
+type RunSpecStatusMessage string
+
+const (
+	// Run cancelled as the Pipeline running it was cancelled.
+	RunCancelledByPipelineMsg RunSpecStatusMessage = "Run cancelled as pipeline has been cancelled."
```
Comment (abayer) [inline pkg/apis/pipeline/v1alpha1/run_types.go:102]: I'd also reword this (and the `TaskRun` equivalent) to something like `Run cancelled as the PipelineRun it belongs to has been cancelled.`

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 13 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go:206]: Done, thanks for pointing that out.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 14 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go:100]: Done

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 15 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go:102]: Done.

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 12 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go:101]: Done.

**Comment by abayer** [comment]
FYI, I've just changed the title of this PR to have `WIP: ` and marked it as ready for review, so that CI fires. Prow doesn't automatically run presubmit jobs for draft PRs. =)

**Comment by abayer** [comment]
`alpha-integration` failure is a flake, but `build-tests` failure is legit - https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5224/pull-tekton-pipeline-build-tests/1554476253346533376#1:build-log.txt%3A1649 - you really just need to run `hack/update-codegen.sh`, since that calls `hack/update-openapigen.sh`.

File: pkg/reconciler/taskrun/taskrun.go (hunk 9 above)
Comment (jagathprakash) [reply pkg/reconciler/taskrun/taskrun.go:147]: @lbernick This gets propagated to taskRun.status.conditions[].message. This like does the propagation. Also test file pkg/reconciler/taskrun/taskrun_test.go has a test which checks for this propagation.

Comment (lbernick) [reply pkg/reconciler/taskrun/taskrun.go:147]: you're right! sorry I missed that.

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 2 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go]: Fixed the spelling to be cancelled.

Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go]: These constants are pipeline related but are set on a Run object and pipeline does not have a field with this object. 
As such these constants, I think, should be in run_types.go.

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (jagathprakash) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go]: The v1 TaskRun is not yet implemented. I will add this in a separate PR.

**Comment by jagathprakash** [comment]
> FYI, I've just changed the title of this PR to have `WIP: ` and marked it as ready for review, so that CI fires. Prow doesn't automatically run presubmit jobs for draft PRs. =)

Thanks!

**Comment by jagathprakash** [comment]
> `alpha-integration` failure is a flake, but `build-tests` failure is legit - https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5224/pull-tekton-pipeline-build-tests/1554476253346533376#1:build-log.txt%3A1649 - you really just need to run `hack/update-codegen.sh`, since that calls `hack/update-openapigen.sh`.

@abayer hack/update-codegen.sh did not generate any files or changes. How do I fix this?

**Comment by abayer** [comment]
> hack/update-codegen.sh did not generate any files or changes. How do I fix this?

You might as well try running `hack/update-openapigen.sh` directly - that's where the issue is. When I run it locally, I get changes to `pkg/apis/pipeline/v1beta1/openapi_generated.go` and `pkg/apis/pipeline/v1beta1/swagger.json`.

**Comment by jagathprakash** [comment]
/test 

> Thanks for the PR! It looks generally good, other than some naming tweaks.
> 
> Oh, and I'd like to see this tested in the end-to-end tests, probably in `test/cancel_test.go`.

Added a test in test/cancel_test.go and also addressed all naming issues.

**Comment by jagathprakash** [comment]
> > hack/update-codegen.sh did not generate any files or changes. How do I fix this?
> 
> You might as well try running `hack/update-openapigen.sh` directly - that's where the issue is. When I run it locally, I get changes to `pkg/apis/pipeline/v1beta1/openapi_generated.go` and `pkg/apis/pipeline/v1beta1/swagger.json`.

Thanks! That worked, running all the tests now.

**Comment by abayer** [comment]
The unit test failure is a flake, the build test failure is a lint issue - https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5224/pull-tekton-pipeline-build-tests/1554577871807188992#1:build-log.txt%3A1648

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 10 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go:65]: Added some info in runs.md on how statusMessage can be used by the custom controller developer.

File: docs/runs.md [hunk 16]
```diff
@@ -192,7 +192,11 @@ Supporting timeouts is optional but recommended.
    (i.e. `Run.Spec.Status == RunCancelled`) and or `Run.HasTimedOut()` and take
    any corresponding actions (i.e. a clean up e.g., cancel a cloud build, stop
    the waiting timer, tear down the approval listener).
-4. Once resources or timers are cleaned up it is good practice to set a
+4. A Custom Task author can differentiate between a run cancelled by an user from a
+   run cancel intiated by a pipeline run cancel by looking at the Run.Spec.StatusMessage.
```
Comment (abayer) [inline docs/runs.md:196]: A few formatting/spelling notes:
* I'd go with "... a `Run` ..." rather than "... a run ..."
* "Run.Spec.StatusMessage" should be in backticks.
* "intiated" should be "initiated". =) And I'd phrase that as "a `Run` cancellation initiated by..."

Comment (jagathprakash) [reply docs/runs.md]: Done.
Also made some more changes to the doc on similar lines.

**Comment by jagathprakash** [comment]
> The unit test failure is a flake, the build test failure is a lint issue - https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5224/pull-tekton-pipeline-build-tests/1554577871807188992#1:build-log.txt%3A1648

Thanks for helping find this!

**Comment by abayer** [comment]
@jagathprakash Please add a release note in the PR description - and in the `release-note` block, remove the space between the three backticks and `release-note`. Thanks!

**Review by abayer — APPROVED** [review]

**Comment by jagathprakash** [comment]
> @jagathprakash Please add a release note in the PR description - and in the `release-note` block, remove the space between the three backticks and `release-note`. Thanks!

Done. Thanks for the tip!

File: pkg/apis/pipeline/v1alpha1/run_types.go [hunk 17]
```diff
@@ -189,6 +202,12 @@ func (r *Run) IsCancelled() bool {
 	return r.Spec.Status == RunSpecStatusCancelled
 }
 
+// GetStatusMessage function returns the status message is one is set on the Run
+// If nothing is set as status message, GetStatusMessage returns an empty string.
+func (r *Run) GetStatusMessage() RunSpecStatusMessage {
```
Comment (lbernick) [inline pkg/apis/pipeline/v1alpha1/run_types.go:207]: does this function need to exist?

File: pkg/apis/pipeline/v1beta1/taskrun_types.go [hunk 18]
```diff
@@ -424,6 +436,14 @@ func (tr *TaskRun) IsCancelled() bool {
 	return tr.Spec.Status == TaskRunSpecStatusCancelled
 }
 
+// GetStatusMessage function returns the status message is one is set on the TaskRun
+// If nothing is set as status message, GetStatusMessage returns an empty string.
+func (tr *TaskRun) GetStatusMessage() TaskRunSpecStatusMessage {
```
Comment (lbernick) [inline pkg/apis/pipeline/v1beta1/taskrun_types.go:441]: same comment here, I don't think this function is necessary

**Review by lbernick — COMMENTED** [review]
Looks great! just a nit but will lgtm once it is resolved

File: pkg/apis/pipeline/v1beta1/taskrun_types.go (hunk 18 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1beta1/taskrun_types.go]: Done. Removed the function.

File: pkg/apis/pipeline/v1alpha1/run_types.go (hunk 17 above)
Comment (jagathprakash) [reply pkg/apis/pipeline/v1alpha1/run_types.go]: Done. Removed the function.

**Comment by jagathprakash** [comment]
Thanks @abayer and @lbernick for the detailed reviews!
