### PR TITLE
Accept any sidecar termination reason

### LINKED ISSUE #1253: testSideCar is failing
`testSideCar` test is failing on our CI based on openshift. I am not really sure if it's an openshift issue or a test issue.

# Expected Behavior

Working tests

# Actual Behavior

```
=== RUN   TestSidecarTaskSupport/A_sidecar_that_runs_forever_is_terminated_when_Steps_complete
--- FAIL: TestSidecarTaskSupport (59.28s)
    init_test.go:113: Create namespace arendelle-g99jz to deploy to
    init_test.go:125: Verify SA "default" is created in namespace "arendelle-g99jz"
    --- FAIL: TestSidecarTaskSupport/A_sidecar_that_runs_forever_is_terminated_when_Steps_complete (58.74s)
        sidecar_test.go:84: Creating Task "sidecar-test-task-0"
        sidecar_test.go:89: Creating TaskRun "sidecar-test-task-run-0"
        sidecar_test.go:132: Sidecar container did not terminate as expected, Terminated state: &ContainerStateTerminated{ExitCode:137,Signal:0,Reason:Error,Message:,StartedAt:2019-08-30 08:49:51 +0200 CEST,FinishedAt:2019-08-30 08:50:30 +0200 CEST,ContainerID:cri-o://dc798098f24caa42cbb1d08eb507f921f43a5da74d32377f560209bbbd7e2c38,}
        sidecar_test.go:140: Either the primary or sidecar containers did not terminate
FAIL
-------
```

events :

```
33s         Warning   Failed      pod/sidecar-test-task-run-0-pod-993fa8   Error: container create failed: container_linux.go:336: starting container process caused "exec: \"sh\": executable file not found in $PATH"
```

# Steps to Reproduce the Problem

1. 
```
% go test -failfast -v -count=1 -tags=e2e -ldflags '-X github.com/tektoncd/pipeline/test.missingKoFatal=false' ./test -timeout=20m --kubeconfig $KUBECONFIG -run TestSidecarTaskSuppor
```

# Additional Info

```
% oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.13-201908210601+15d7c4b-dirty", GitCommit:"15d7c4b", GitTreeState:"dirty", BuildDate:"2019-08-21T13:24:47Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+df9cebc", GitCommit:"df9cebc", GitTreeState:"clean", BuildDate:"2019-08-06T18:31:45Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

Fixes #1253

When a sidecar is forcefully exited by the taskrun controller it may
error out. This happens because the sidecar is terminated by having its
image field rewritten to be tekton's nop container. The nop container is
bare bones and probably doesnt contain the entrypoint command configured
for the sidecar. When this occurs the container will exit with an error
of some kind. On GKE this error's Reason is "ContainerCannotRun" but on
MiniShift/OpenShift the error Reason is "Error".

The sidecar e2e test previously required a termination Reason of
`ContainerCannotRun` or `Completed` but this appears to be too rigid.
Instead the test now considers a sidecar that has been terminated for
any reason to be a success.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] ~~Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)~~
- [ ] ~~Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)~~
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

File: test/sidecar_test.go [hunk 1]
```diff
@@ -64,12 +64,12 @@ func TestSidecarTaskSupport(t *testing.T) {
 				tb.TaskSpec(
 					tb.Step(
 						primaryContainerName,
-						"ubuntu",
+						"busybox:1.31.0-musl",
```
Comment (dibyom) [inline test/sidecar_test.go]: Just curious, why was the container image changed?

Comment (dibyom) [reply test/sidecar_test.go]: Found it: https://github.com/tektoncd/pipeline/issues/1253#issuecomment-527464092

**Comment by chmouel** [comment]
@sbwsg FYI, I have tested this change on openshift and it was working! thanks
