### PR TITLE
Use kmeta.ChildName for child resources

### LINKED ISSUE #4358: Duplicated pod for a single TaskRun
# Expected Behavior
To have a single pod for each TaskRun

# Actual Behavior
Two or more pods for a single TaskRun

# Steps to Reproduce the Problem

We are noticing that on our cluster, but we didn't manage to reliably reproduce it.
We noticed that happens when the task fails.

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version: v0.22.0

- Other info 

I checked the logs from the controller, there are no errors related, but we can see two `Successfully reconciled taskrun ...` messages for each pod.

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

When a reconciler generates a child resource, it risks creating a
duplicate resource because of stale informer cache. This may happen
for instance when two reconciliations of the same resource happen
almost at the same time.
To avoid this risk, children resources should use a name that is uniquely
associated to that of the parent, so that any attempt of recreation would
fail. Such failure, when it happens, is considered as a transient error,
and it does not cause the TaskRun or the PipelineRun to fail.

We use kmeta.ChildName to generate the names. This applies to Pods
generated by TaskRuns and TaskRuns and Runs generated by PipelineRuns.
ChildName combines a base name with a suffix, and if the resulting name is
too long it shortens it by truncating it and appending an hash of the
original name: https://pkg.go.dev/github.com/knative/pkg/kmeta#ChildName

Resources that are not k8s resources, such as steps or scripts, are not
affected by this change.

Fixes #4358

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Name of `Pods` and  `TaskRuns` created by Tekton controllers are now generated with [`kmeta.ChildName`](https://pkg.go.dev/github.com/knative/pkg/kmeta#ChildName):

> ChildName generates a name for the resource based upon the parent resource and suffix. If the concatenated name is longer than K8s permits the name is hashed and truncated to permit construction of the resource, but still keeps it unique. If the suffix itself is longer than 31 characters, then the whole string will be hashed and `parent|hash|suffix` will be returned, where parent and suffix will be trimmed to fit (prefix of parent at most of length 31, and prefix of suffix at most length 30).

The name of the `Pods` owned by a `TaskRun`  is univocally associated to the owning resource. If a `TaskRun` resource is deleted and created with the same name, the child `Pod` will be created with the same name as before.
The base format of the name is `<taskrun-name>-pod`. The name may vary as described above if it becomes too long.
In case of retries, starting from the first retry, the base format of the name is `<taskrun-name>-retry<N>` where `N` is the retry number.

The name of the `TaskRuns` and `Runs` owned by a `PipelineRun`  are univocally associated to the owning resource. If a `PipelineRun` resource is deleted and created with the same name, the child `TaskRuns` will be created with the same name as before.
The base format of the name is `<pipelinerun-name>-<pipelinetask-name>`. The name may vary as described above if it becomes too long.
```

### CODE REVIEW

**Comment by imjasonh** [comment]
This looks great! What's WIP about it? (aside from unit tests 😈 )

**Comment by afrittoli** [comment]
There may be something to check about retries:
```
        status:
          completionTime: "2021-11-05T12:16:21Z"
          conditions:
          - lastTransitionTime: "2021-11-05T12:16:21Z"
            message: 'failed to create task run pod "retry-pipeline-retry-me": pods "retry-pipeline-retry-me-pod"
              already exists. Maybe invalid TaskSpec'
            reason: CouldntGetTask
            status: "False"
            type: Succeeded
```

Also I need to make sure that failures like this are considered transient and do not cause taskruns or pipelineruns to fail.

**Comment by afrittoli** [comment]
> There may be something to check about retries:
> 
> ```
>         status:
>           completionTime: "2021-11-05T12:16:21Z"
>           conditions:
>           - lastTransitionTime: "2021-11-05T12:16:21Z"
>             message: 'failed to create task run pod "retry-pipeline-retry-me": pods "retry-pipeline-retry-me-pod"
>               already exists. Maybe invalid TaskSpec'
>             reason: CouldntGetTask
>             status: "False"
>             type: Succeeded
> ```
> 
> Also I need to make sure that failures like this are considered transient and do not cause taskruns or pipelineruns to fail.

For retries, the `PipelineRun` controller saves the original `TaskRun` status in the list of retries, and it clears the `TaskRun` status, so that the `TaskRun` controllers sees a `TaskRun` that needs to be reconciled, and triggers a new `Pod` creation. The `Pod` name must include the number of retry, at least starting from the first retry on.

**Comment by afrittoli** [comment]
I think the failures on `pull-tekton-pipeline-alpha-integration-tests` may be flakes.
/cc @imjasonh @mattmoor @vdemeester

File: pkg/pod/pod.go [hunk 1]
```diff
@@ -296,16 +298,19 @@ func (b *Builder) Build(ctx context.Context, taskRun *v1beta1.TaskRun, taskSpec
 	}
 	activeDeadlineSeconds := int64(taskRun.GetTimeout(ctx).Seconds() * deadlineFactor)
 
-	pod := &corev1.Pod{
+	podNameSuffix := "-pod"
+	if taskRunRetries := len(taskRun.Status.RetriesStatus); taskRunRetries > 0 {
+		podNameSuffix = fmt.Sprintf("%s-retry%d", podNameSuffix, taskRunRetries)
+	}
+	newPod := &corev1.Pod{
```
Comment (afrittoli) [inline pkg/pod/pod.go:305]: Renamed to `newPod` as `pod` obfuscated the package name `pod`.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 2]
```diff
@@ -550,7 +551,7 @@ func getConditionCheckName(taskRunStatus map[string]*v1beta1.PipelineRunTaskRunS
 			}
 		}
 	}
-	return names.SimpleNameGenerator.RestrictLengthWithRandomSuffix(fmt.Sprintf("%s-%s", trName, conditionRegisterName))
```
Comment (mattmoor) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:553]: Is the names package still used anywhere?

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:553]: Yes, it's still used to generate step names, script filenames, internal volumes mount-point names.

I'm not sure whether it's actually needed in all of those places, but I wanted to focus on k8s resources first in this PR - which is where we have experience issues. Which has the advantage of making this PR easier to approach and review too :)

File: pkg/pod/pod_test.go [hunk 3]
```diff
@@ -1640,8 +1715,9 @@ func TestPodBuildwithAlphaAPIEnabled(t *testing.T) {
 				t.Fatalf("builder.Build: %v", err)
 			}
 
-			if !strings.HasPrefix(got.Name, "taskrun-name-pod-") {
-				t.Errorf("Pod name %q should have prefix 'taskrun-name-pod-'", got.Name)
+			expectedName := kmeta.ChildName(tr.Name, "-pod")
+			if d := cmp.Diff(expectedName, got.Name); d != "" {
+				t.Errorf("Pod name does not matc: %q", d)
```
Comment (sbwsg) [inline pkg/pod/pod_test.go:1720]: tiny nit: matc -> match

**Comment by sbwsg** [comment]
/lgtm

Way better without all those randomized strings in the names!

File: pkg/pod/pod_test.go (hunk 3 above)
Comment (afrittoli) [reply pkg/pod/pod_test.go]: Nice catch, fixed

**Comment by sbwsg** [comment]
The `run-steps-as-non-root` Example failed with:

```
        >>> Container step-show-user-1001:
        Signal 23 (URG) caught by ps (3.3.16).
        ps:ps/display.c:66: please report this bug
``` 

It looks like this has been recently [fixed in `ps` by ignoring the signal](https://gitlab.com/procps-ng/procps/-/commit/b6ccf865f83f98478a814c1d79d17a0b5212cc6e) so probably nothing for us to do here. Re-running.

/test pull-tekton-pipeline-integration-tests

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go [hunk 4]
```diff
@@ -572,8 +573,7 @@ func getRunName(runsStatus map[string]*v1beta1.PipelineRunRunStatus, ptName, prN
 			return k
 		}
 	}
-
-	return names.SimpleNameGenerator.RestrictLengthWithRandomSuffix(fmt.Sprintf("%s-%s", prName, ptName))
+	return kmeta.ChildName(prName, fmt.Sprintf("-%s", ptName))
```
Comment (jerop) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:576]: looks like you've made the same change to `Runs` as well, please documentation for that like you've done for `TaskRuns` and `Pods`

adding that detail to the commit message and pr description would be great too!

**Review by jerop — COMMENTED** [review]
thanks @afrittoli 🎉 

added a comment documenting the change to `Runs` as well

**Comment by pritidesai** [comment]
Thanks @afrittoli for this PR 🙏  I think this also fixes (both were closed but I just reopened them since the issues are still seen with recent releases) :

https://github.com/tektoncd/pipeline/issues/3126
https://github.com/tektoncd/pipeline/issues/3557

**Comment by pritidesai** [comment]
I might be missing something but can we please add some tests around the release note if they don't exist already:

```
> ChildName generates a name for the resource based upon the parent resource and suffix. If the concatenated name is longer than K8s permits the name is hashed and truncated to permit construction of the resource, but still keeps it unique. If the suffix itself is longer than 31 characters, then the whole string will be hashed and `parent|hash|suffix` will be returned, where parent and suffix will be trimmed to fit (prefix of parent at most of length 31, and prefix of suffix at most length 30).
```

Documenting some samples would be ideal for the folks creating `pipelineRuns` 🙏 .

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go (hunk 4 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go:576]: Nice catch, thank you. Fixed.

**Comment by afrittoli** [comment]
> I might be missing something but can we please add some tests around the release note if they don't exist already:
> 
> ```
> > ChildName generates a name for the resource based upon the parent resource and suffix. If the concatenated name is longer than K8s permits the name is hashed and truncated to permit construction of the resource, but still keeps it unique. If the suffix itself is longer than 31 characters, then the whole string will be hashed and `parent|hash|suffix` will be returned, where parent and suffix will be trimmed to fit (prefix of parent at most of length 31, and prefix of suffix at most length 30).
> ```
> 

Thank you - the logic of the `ChildName` function is tested on knative side, which is why I did not add tests.
I added some tests for that now so that if the logic is changed on the library side we will notice it and have a chance to update docs along with the tests accordingly.

> Documenting some samples would be ideal for the folks creating `pipelineRuns` 🙏 .

Good idea, done!

**Review by jerop — COMMENTED** [review]
`examples_test.go:144: exit status 1 Output: Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s": context deadline exceeded`

/test pull-tekton-pipeline-alpha-integration-tests

File: docs/pipelineruns.md [hunk 5]
```diff
@@ -627,6 +627,20 @@ Task Runs:
...
+The name of the `TaskRuns` and `Runs` owned by a `PipelineRun`  are univocally associated to the owning resource.
+If a `PipelineRun` resource is deleted and created with the same name, the child `TaskRuns` will be created with the
+same name as before. The base format of the name is `<pipelinerun-name>-<pipelinetask-name>`. The name may vary
+according the logic of [`kmeta.ChildName`](https://pkg.go.dev/github.com/knative/pkg/kmeta#ChildName).
+
+Some examples:
+
+| `PipelineRun` Name       | `PipelineTask` Name          | `TaskRun` Name    |
+|--------------------------|------------------------------|-------------------|
+| pipeline-run             | task1                        | my-pipeline-task1 |
```
Comment (pritidesai) [inline docs/pipelineruns.md:639]: NIT: will the `taskRun` name be `pipeline-run-task1` instead of `my-pipeline-task1`?

File: docs/pipelineruns.md [hunk 6]
```diff
@@ -627,6 +627,20 @@ Task Runs:
...
+| pipeline-run             | task2-0123456789-0123456789-0123456789-0123456789-0123456789 | pipeline-runee4a397d6eab67777d4e6f9991cd19e6-task2-0123456789-0 |
```
Comment (pritidesai) [inline docs/pipelineruns.md:640]: how are the dashes added when one or both of the resource names are long?

No dash after the `pipelineRun` name here and in the last example.

`pipeline-runee4a397d6eab67777d4e6f9991cd19e6-task2-0123456789-0` (pipelineRun name is `pipeline-run` and pipelineTask name is long)
`pipeline-run-0123456789-012345607ad8c7aac5873cdfabe472a68996b5c` (pipelineRun name and pipelineTask name are long)

**Review by pritidesai — APPROVED** [review]
thank you @afrittoli 

a couple of minor nits but otherwise looks great, thank you for fixing this 🙏

File: docs/pipelineruns.md (hunk 6 above)
Comment (afrittoli) [reply docs/pipelineruns.md:640]: `ChildName` does not add a dashes.
The way we're using it is to prepend a dash to the `PipelineTask` name.

```golang
     return kmeta.ChildName(prName, fmt.Sprintf("-%s", ptName))
```

When both names are too long an hash of the whole thing is used so that specific dash may not show up in the final name.

File: docs/pipelineruns.md (hunk 5 above)
Comment (afrittoli) [reply docs/pipelineruns.md:639]: Nice catch, thank you!

**Review by vdemeester — COMMENTED** [review]
/lgtm
