### PR TITLE
Readd mounting volumes in workingdir

### LINKED ISSUE #1608: Permission denied when checking out source to /workspace
# Expected Behavior

When checking out a `PipelineResource` with a Git resource checking it out in `/workspace` which run as *user* (as for example by default on OpenShift) the Git repository would probably be checked out in `/workspace/src`.

# Actual Behavior

This would be denied and can't create directory in `/workspace` 

```
mkdir: can't create directory '/workspace/source': Permission denied
```

# Steps to Reproduce the Problem

This is maybe an OpenShift specific issue or a K8s with a hardened policy to force running the pods as random user instead of privileged.

Running this on OpenShift4.2 with a simple Task with a PipelineResource of Git will do, i.e: 

```yaml
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: waitforever-with-src
spec:
  inputs:
    resources:
      - name: source
        type: git
        targetPath: src
  steps:
    - name: waitforever
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      workingdir: /workspace/src
      command: ["sleep", "infinity"]
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/rogertinsley/golang-k8s-helloworld
```

and run it with :

```yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: waitforever-with-src-run-
spec:
  inputs:
    resources:
    - name: source
      resourceRef:
        name: source
  taskRef:
    kind: Task
    name: waitforever-with-src
```

# Additional Info

Weirdly enough this only appeared *lately* like for the last two weeks or so but can't find anything obvious in the git logs (perhaps that's an OpenShift 4.2 specific bug too).

Debugging a bit into this, this would fail into the `initContainers` that initialize the `/workspace` directories.

The first container which does the `credsInit` run fine and adding some debugs I can see that I have the [sticky bit](https://en.wikipedia.org/wiki/Sticky_bit) set to be able to write into `/workspace` : 

image

While the second `initContainer` which does the `dir-init` step would fail, adding a `ls -l` just before doing the `mkdir -p` I can see that the the sticky bit has dropped in there and `mkdir` would fail because we are running as user and directory is set as root : 

image

/kind bug

### PR DESCRIPTION
**Pull request by chmouel**
Mounting volume was dropped when we did the large refactoring in
d7f492cb8e018a8d2c65a8702b3746e710501616 which basically making
it ineffective and fails when not running as root.

Readding it in there

Closes #1608

/cc @ImJasonH 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```
Fix workingdir-init to mount the volumes when starting the initContainer.
```

### CODE REVIEW

File: pkg/pod/workingdir_init_test.go [hunk 1]
```diff
@@ -28,6 +28,11 @@ import (
 const shellImage = "shell-image"
 
 func TestWorkingDirInit(t *testing.T) {
+	volumeMounts := []corev1.VolumeMount{{
```
Comment (ImJasonH) [inline pkg/pod/workingdir_init_test.go]: `implicitVolumeMounts` also includes the home mount (`/builder/home`)

Otherwise LGTM!

Comment (chmouel) [reply pkg/pod/workingdir_init_test.go]: Thanks! I have added the `home` in there,

**Comment by chmouel** [comment]
@ImJasonH good point on the integration test, but this make me wonder, do we. need the workingdir ? since it seems that nobody has realised it wasn't and nothing catastrophic has been discovered since then without it ?

**Comment by ImJasonH** [comment]
Nobody may have noticed it was broken in the past few days, but most people don't run so aggressively from head either (plus, Kubecon).

If we decide to change the behavior, we should do it slowly over a couple releases with ample notice, but I don't really think we would since it's easy enough to support (when I'm not breaking it! 🤣)

/lgtm
/approve

**Comment by afrittoli** [comment]
> @ImJasonH good point on the integration test, but this make me wonder, do we. need the workingdir ? since it seems that nobody has realised it wasn't and nothing catastrophic has been discovered since then without it ?

I think the implicit mounts are quite handy to pass content between containers. 
If `/workspace/` wasn't there I would end up mounting a shared folder, so it's nice to have it done by Tetkon automatically :)
