### PR TITLE
Make examples runnable with kubectl 🐇

### LINKED ISSUE #3498: example/pipelinerun: Error: InvalidImageName
# Expected Behavior
try to run the example examples/v1beta1/pipelineruns/pipelinerun.yaml on OpenShift 4.5

# Actual Behavior

Failed to apply default image tag "**ko://github.com/tektoncd/pipeline/cmd/git-init**": couldn't parse image reference "ko://github.com/tektoncd/pipeline/cmd/git-init": invalid reference format
Error: InvalidImageName

# Steps to Reproduce the Problem

1. Install OpenShift 4.5
2. Install OpenShift Pipelines with Operator
3. oc new-project demo-pipelines
4. oc apply -f https://github.com/tektoncd/pipeline/raw/master/examples/v1beta1/pipelineruns/pipelinerun.yaml

# Additional Info

- Kubernetes version:

  ** Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2fbd7c7", GitCommit:"2fbd7c7", GitTreeState:"clean", BuildDate:"2020-10-15T16:25:45Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"} **

 ```
Successfully assigned demo-pipeline/demo-pipeline-run-1-fetch-from-git-8ll7x-pod-5dkpg to compute-1
Add eth0 [10.129.2.100/23]
Pulling image "registry.redhat.io/openshift-pipelines-tech-preview/pipelines-creds-init-rhel8@sha256:3281407e27ed0a13dbbedb73102450ee6317feb1d5b6bc28b3085f6c0661cc56"
Successfully pulled image "registry.redhat.io/openshift-pipelines-tech-preview/pipelines-creds-init-rhel8@sha256:3281407e27ed0a13dbbedb73102450ee6317feb1d5b6bc28b3085f6c0661cc56"
Created container credential-initializer
Started container credential-initializer
Pulling image "registry.access.redhat.com/ubi8/ubi-minimal:latest"
Successfully pulled image "registry.access.redhat.com/ubi8/ubi-minimal:latest"
Created container place-scripts
Started container place-scripts
Pulling image "registry.redhat.io/openshift-pipelines-tech-preview/pipelines-entrypoint-rhel8@sha256:f7d7c0330ab3f10d8ca65f8989b03eb00a2226eee8af7f694931242771ac318c"
Successfully pulled image "registry.redhat.io/openshift-pipelines-tech-preview/pipelines-entrypoint-rhel8@sha256:f7d7c0330ab3f10d8ca65f8989b03eb00a2226eee8af7f694931242771ac318c"
Created container place-tools
Started container place-tools
Failed to apply default image tag "ko://github.com/tektoncd/pipeline/cmd/git-init": couldn't parse image reference "ko://github.com/tektoncd/pipeline/cmd/git-init": invalid reference format
Error: InvalidImageName
```

- Tekton Pipeline version:

  ** v0.14.3 **

```
$ oc get tasks git-clone -o yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: demo-pipeline
spec:
  params:
  - description: git url to clone
    name: url
    type: string
  - default: master
    description: git revision to checkout (branch, tag, sha, ref…)
    name: revision
    type: string
  - default: "true"
    description: defines if the resource should initialize and fetch the submodules
    name: submodules
    type: string
  - default: "1"
    description: performs a shallow clone where only the most recent commit(s) will
      be fetched
    name: depth
    type: string
  - default: "true"
    description: defines if http.sslVerify should be set to true or false in the global
      git config
    name: sslVerify
    type: string
  - default: ""
    description: subdirectory inside the "output" workspace to clone the git repo
      into
    name: subdirectory
    type: string
  - default: "false"
    description: clean out the contents of the repo's destination directory (if it
      already exists) before trying to clone the repo there
    name: deleteExisting
    type: string
  results:
  - description: The precise commit SHA that was fetched by this Task
    name: commit
  steps:
  - image: ko://github.com/tektoncd/pipeline/cmd/git-init
    name: clone
    resources: {}
    script: |
      CHECKOUT_DIR="$(workspaces.output.path)/$(params.subdirectory)"
      cleandir() {
        # Delete any existing contents of the repo directory if it exists.
        #
        # We don't just "rm -rf $CHECKOUT_DIR" because $CHECKOUT_DIR might be "/"
        # or the root of a mounted volume.
        if [[ -d "$CHECKOUT_DIR" ]] ; then
          # Delete non-hidden files and directories
          rm -rf "$CHECKOUT_DIR"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "$CHECKOUT_DIR"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "$CHECKOUT_DIR"/..?*
        fi
      }
      if [[ "$(params.deleteExisting)" == "true" ]] ; then
        cleandir
      fi
      /ko-app/git-init \
        -url "$(params.url)" \
        -revision "$(params.revision)" \
        -path "$CHECKOUT_DIR" \
        -sslVerify="$(params.sslVerify)" \
        -submodules="$(params.submodules)" \
        -depth="$(params.depth)"
      cd "$CHECKOUT_DIR"
      RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
      EXIT_CODE="$?"
      if [ "$EXIT_CODE" != 0 ]
      then
        exit $EXIT_CODE
      fi
      # Make sure we don't add a trailing newline to the result!
      echo -n "$RESULT_SHA" > $(results.commit.path)
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    name: output
```

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This remove the use of `ko://` in the examples folder, using the
`:latest` release image for those. This allow users to apply those
with `kubectl` directly.

To keep testing the "currently" built image, this introduce a
`test/yamls` folder where we use `ko://`. This updates the tests to
run both (`examples` and `test/yamls`).

Fixes #3498 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind misc
/area testing

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by chmouel** [comment]
Is there any reasons why people would want to run the test manually ? Just wondering why

**Comment by vdemeester** [comment]
> Is there any reasons why people would want to run the test without KO ? Just wondering why

See the linked issue, most people assume that the root `examples` folder is `kubectl` appliable (no need for ko, nor having the tektoncd source really).

**Comment by pritidesai** [comment]
@vdemeester do we need to remove both `yaml`s (`pipelinerun-with-final-tasks.yaml` and `pipelinerun.yaml` ) from `examples/` folder since they exists under `test/yamls/` now?

**Comment by vdemeester** [comment]
> @vdemeester do we need to remove both `yaml`s (`pipelinerun-with-final-tasks.yaml` and `pipelinerun.yaml` ) from `examples/` folder since they exists under `test/yamls/` now?

So, I didn't because they are still "valid" example for users to look at, they are just using "normal" images instead of using the `ko://` notation.

File: test/examples_test.go [hunk 1]
```diff
@@ -135,7 +142,7 @@ func exampleTest(path string, waitValidateFunc waitFunc, kind string) func(t *te
 			t.Skipf("Couldn't substitute environment: %v", err)
 		}
 
-		out, err := koCreate(subbedInput, namespace)
```
Comment (sbwsg) [inline test/examples_test.go:138]: Super tiny nit: there's a comment on line 151, `// Parse from koCreate for now` that I think is no longer right with this change?  Maybe `// Parse from createFunc for now`?

**Review by sbwsg — APPROVED** [review]
