### PR TITLE
Fix embedded-status conversion for PipelineRuns

### LINKED ISSUE #5964: Pipelines `v0.43.1` installation nondeterministically fails to update PipelineRun status with TaskRun statuses
# Expected Behavior

(Edited: moved error message from tkn to tektoncd/cli#1847)

`PipelineRun` status reflects status of the child TaskRuns

# Actual Behavior

`tkn pr list` shows the `PipelineRun` as `Running` even though `tkn tr list` shows all related `TaskRun`s as `Succeeded`

# Steps to Reproduce the Problem

1. Use a v1beta1 `PipelineRun` that ran cleanly in `v0.42.0`
2. Upgrade to `v0.43.1`
3. Run the pipeline via `kubectl create|apply --filename ...`
4. `tkn pr logs --last -f`
5. wait

# Additional Info

- Kubernetes version:

```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.900", GitCommit:"e35c4457f66187eff006dda6d2c0fe12144ef2ec", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:34Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
$ tkn version
Client version: 0.28.0
Chains version: v0.13.1
Pipeline version: v0.43.1
```

I expected this to be resolved in `v0.43.1` by https://github.com/tektoncd/pipeline/pull/5945 and https://github.com/tektoncd/pipeline/pull/5948, but no joy.  😿

### PR DESCRIPTION
**Pull request by lbernick**
This commit updates conversion for PipelineRun child objects stored in the status to depend on the value of the feature flag `embedded-status`.

Possibly fixes #5964
/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- n/a Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- n/a Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Update PipelineRun conversion between API versions to account for embedded-status feature flag
```

### CODE REVIEW

**Review by JeromeJu — APPROVED** [review]
Thanks for the fix 🧯  @lbernick

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go [hunk 1]
```diff
@@ -309,12 +311,20 @@ func (prs *PipelineRunStatus) ConvertFrom(ctx context.Context, source *v1.Pipeli
...
+	if embeddedStatus == config.BothEmbeddedStatus || embeddedStatus == config.MinimalEmbeddedStatus {
+		prs.ChildReferences = nil
+		for _, cr := range source.ChildReferences {
+			new := ChildStatusReference{}
+			new.convertFrom(ctx, cr)
+			prs.ChildReferences = append(prs.ChildReferences, new)
+		}
+	}
+	if embeddedStatus == config.BothEmbeddedStatus || embeddedStatus == config.FullEmbeddedStatus {
+		prs.TaskRuns = taskRuns
```
Comment (JeromeJu) [inline pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go:324]: nit: we might not need `cmpopts.EquateEmpty()` added in all test casese if we check the length of serialized taskRuns and runs?
```
		if len(taskRuns) != 0 {
			prs.TaskRuns = taskRuns
		}
		if len(runs) != 0 {
			prs.Runs = runs
		}
```

Comment (lbernick) [reply pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go:324]: Here's the closest thing I found in the go style guide: https://google.github.io/styleguide/go/decisions#nil-slices
Doesn't seem like there's clear guidance in this situation so I'm going to go with my personal preference, to keep EquateEmpty. (I think our tests shouldn't care whether there's an empty slice or nil pointer.)

Comment (JeromeJu) [reply pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go:324]: Thanks Lee! Makes perfect sense.

**Review by bendory — APPROVED** [review]
LGTM -- I especially like the round-trip tests (rather than single-direction from both sides)

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go [hunk 2]
```diff
@@ -235,8 +238,7 @@ func (ptrs *PipelineTaskRunSpec) convertFrom(ctx context.Context, source v1.Pipe
 	ptrs.ComputeResources = source.ComputeResources
 }
 
-// ConvertTo implements apis.Convertible
-func (prs *PipelineRunStatus) ConvertTo(ctx context.Context, sink *v1.PipelineRunStatus) error {
+func (prs *PipelineRunStatus) convertTo(ctx context.Context, sink *v1.PipelineRunStatus) error {
```
Comment (Yongxuanzhang) [inline pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go:241]: just want to doublecheck there are no issues to make these functions private?

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go [hunk 3]
```diff
@@ -446,23 +450,22 @@ func TestPipelineRunConversionFromDeprecated(t *testing.T) {
...
-// Assumptions: The `embedded-status` is defaulted as `Full` as in config.DefaultEmbeddedStatus:
 func TestPipelineRunConversionEmbeddedStatusRoundTrip(t *testing.T) {
 	taskRuns["tr-0"] = trs
 	runs["r-0"] = rrs
 
 	tests := []struct {
-		name string
-		in   *v1beta1.PipelineRun
-		want *v1beta1.PipelineRun
+		name           string
```
Comment (Yongxuanzhang) [inline pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go:466]: just wonder if it makes sense to make the `name` of each test case more descriptive? Now they are `taskRuns`, `runs`. etc. We could consider including what `embeddedStatus` is set in each case?

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go [hunk 4]
```diff
@@ -724,16 +702,92 @@ func TestPipelineRunConversionEmbeddedStatusConvertFrom(t *testing.T) {
...
+			},
+		},
+		embeddedStatus: config.MinimalEmbeddedStatus,
+	}, {
+		name: "full",
+		in: &v1.PipelineRun{
+			ObjectMeta: metav1.ObjectMeta{
+				Name:      "foo",
+				Namespace: "bar",
+				Annotations: map[string]string{
```
Comment (Yongxuanzhang) [inline pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go:747]: wonder if it makes sense to make this map as a var if it is used in different cases?

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go (hunk 2 above)
Comment (JeromeJu) [reply pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go:241]: Thanks Yongxuan and yeah I think these changes are good:) We are not importing on PipelineRunStatus Conversion elsewhere.

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go (hunk 4 above)
Comment (JeromeJu) [reply pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go:747]: Sorry can you elaborate more about what it means by making it into a var? From my understanding, the annotation is a field in ObjectMeta https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/ ?

Comment (lbernick) [reply pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go]: done

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go (hunk 2 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go:241]: `PipelineRunStatus` doesn't need to implement apis.Convertible, and we don't rely on this anywhere else in pipelines (and probably not other repos but I haven't checked). We don't have compat policies defined for our go libraries, although this technically isn't a backwards compatible change. I can add a release note for anyone who might be using this method.

File: pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go (hunk 3 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1beta1/pipelinerun_conversion_test.go:466]: done
