### PR TITLE
Use a hash of the workspace name in PVCs from template

### LINKED ISSUE #2941: volumeClaimTemplates do not work if the workspace name has capital letters
# Expected Behavior

It should be possible to use a workspace that has capital letters with volumeClaimTemplates

# Actual Behavior

The run fails because Tekton attempts to create a PVC that has capital letters

# Steps to Reproduce the Problem

1. Use this TaskRun:
    ```yaml
    ---
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      name: test-vct
    spec:
      taskRef:
        name: write-hello
      workspaces:
      - name: myVolumeTemplate
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 100m
            accessModes:
            - ReadWriteOnce
    ---
    apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      name: write-hello
    spec:
      steps:
      - image: ubuntu:latest
        name: hello-0
        script: cat hello > $(workspaces.myVolumeTemplate.path)/hello
      workspaces:
      - name: myVolumeTemplate
    ```
2. Apply it
3. Observe this message in the status:
    ```
    Failed to create PVC for TaskRun default/test-vct workspaces correctly: failed to create PVC myVolumeTemplate-test-vct: PersistentVolumeClaim \"myVolumeTemplate-test-vct\" is invalid: metadata.name: Invalid value: \"myVolumeTemplate-test-vct\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    ```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T11:30:02Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.10.0
Pipeline version: v0.13.0-apple.1
Triggers version: unknown
```

This looks like the source of the error. Seems like there should be some logic here to kebab-case the workspace name when determining the PVC name:

https://github.com/tektoncd/pipeline/blob/7a2bc9cef9f9a2255132aeca8fdbef275d12f89e/pkg/reconciler/volumeclaim/pvchandler.go#L92..L97

### PR DESCRIPTION
**Pull request by jlpettersson**
# Changes

Today, PVC name from volumeClaimTemplate is retrieved from
an optionally user submitted prefix in addition to the workspace name
and the owner name (PipelineRun name or TaskRun name).

The problem with this is that the workspace name need to follow the
naming requirements for Kubernetes resource names. It might also
be sensitive to very long names.

This commit only uses a fixed length hash of the workspace name
and the owner name (PipelineRun name or TaskRun name)

Closes #2941
/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
PersistentVolumeClaims created from volumeClaimTemplate now ends with a hash instead of the workspace name and run name
```

### CODE REVIEW

File: pkg/reconciler/volumeclaim/pvchandler.go [hunk 1]
```diff
@@ -91,7 +92,13 @@ func getPersistentVolumeClaims(workspaceBindings []v1alpha1.WorkspaceBinding, ow
 // must be a PersistentVolumeClaim from set's VolumeClaims template.
 func GetPersistentVolumeClaimName(claim *corev1.PersistentVolumeClaim, wb v1alpha1.WorkspaceBinding, owner metav1.OwnerReference) string {
 	if claim.Name == "" {
```
Comment (dlorenc) [inline pkg/reconciler/volumeclaim/pvchandler.go:94]: Would it make sense to use the existing name generator we have?

https://github.com/tektoncd/pipeline/blob/master/pkg/names/generate.go#L54

You can see it in use for something similar here: https://github.com/tektoncd/pipeline/blob/master/pkg/pod/creds_init.go#L75

Comment (jlpettersson) [reply pkg/reconciler/volumeclaim/pvchandler.go:94]: the problem is that its is _random_. This name must be a consistent hash, e.g. every time a workspaceName+ownerName is passed to the function, the same hash must be returned.

random name is also useful, but in this context we need a consistent hashed name.

Comment (dlorenc) [reply pkg/reconciler/volumeclaim/pvchandler.go:94]: Ah - makes sense. Would you mind adding a comment explaining that here? It's still not clear to me why we need it to be consistent.

**Comment by sbwsg** [comment]
/approve

/hold

Adding a hold just so you can add the comment mentioned in the review.  Feel free to remove the hold.

File: pkg/reconciler/volumeclaim/pvchandler.go (hunk 1 above)
Comment (jlpettersson) [reply pkg/reconciler/volumeclaim/pvchandler.go:96]: @dlorenc Good point, I added an explanation in the function-comment.

Initially, a PVC is created - with workspace-name and an owner-name as input (owner-name is a TaskRun or a PipelineRun name and typically consist of a random part - using the function you referred).

Then, every TaskRun that use this workspace (within the same PipelineRun) - must refer to the exact same PVC-name. This can be handled in two ways - use a consistent name-lookup (e.g. always return the same output given two input values) or use some way to _pass_ the PVC name. 

We currently rely on returning the same PVC-name given a specific combination of ws-name and owner-name. I think this is an easier way to implement it.
