### PR TITLE
fix: do not set default kind when taskRef resolver is present

### LINKED ISSUE #7762: Unexpected Default ‘kind’ in taskRef When Using Resolver in Tekton Pipelines
# Expected Behavior

When using a `resolver` to reference a Task in Tekton Pipeline, the taskRef should not automatically have a default `kind` type value set as the `Task` is not applicable in the context of resolvers.

Despite using a resolver to reference a Task, the taskRef still has a default `kind` type value inserted, which appears to be added by the webhook. This addition seems unnecessary and can cause confusion as it modifies the user’s configuration without a clear purpose within resolver usage.

# Actual Behavior

# Steps to Reproduce the Problem

1. Execute the following script
```
kubectl apply -f - <<EOF
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-default-taskref-kind
  namespace: default
spec:
  description: |
    A simple task that prints the date.
  steps:
    - name: echo
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Hello, world!"
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: test-default-taskref-kind
spec:
  taskRef:
    resolver: cluster
    params:
      - name: kind
        value: task
      - name: name
        value: test-default-taskref-kind
      - name: namespace
        value: default
EOF
```

2. The `TaskRun`
```
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: test-default-taskref-kind
spec:
  serviceAccountName: default
  taskRef:
    kind: Task                <- This default value is set
    params:
    - name: kind
      value: task
    - name: name
      value: test-default-taskref-kind
    - name: namespace
      value: default
    resolver: cluster
  timeout: 1h0m0s
status:
  taskSpec:
    description: |
      A simple task that prints the date.
    steps:
    - computeResources: {}
      image: bash:latest
      name: echo
      script: |
        #!/usr/bin/env bash
        echo "Hello, world!"

```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.35.1
Pipeline version: v0.57.0
```

### PR DESCRIPTION
**Pull request by l-qing**
fix #7762

Do not set default kind when taskRef resolver is present, keep the original configuration of the user.

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
fix: do not set default kind when taskRef resolver is present
```

/kind bug

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
/lgtm

File: test/conversion_test.go [hunk 1]
```diff
@@ -746,10 +745,9 @@ metadata:
   namespace: %s
 spec:
   taskRunTemplate:
-  timeouts: 
+  timeouts:
     pipeline: 1h
   pipelineRef:
-    kind: Pipeline
```
Comment (l-qing) [inline test/conversion_test.go:752]: The `pipelineRef` does not have a `kind` field.

https://github.com/tektoncd/pipeline/blob/d7145450d6d87d64261abc08798876a41f607f68/pkg/apis/pipeline/v1beta1/pipelineref_types.go#L19-L37

https://github.com/tektoncd/pipeline/blob/d7145450d6d87d64261abc08798876a41f607f68/pkg/apis/pipeline/v1/pipelineref_types.go#L19-L32

File: pkg/apis/pipeline/v1beta1/taskref_conversion.go [hunk 2]
```diff
@@ -49,6 +49,7 @@ func (tr *TaskRef) ConvertFrom(ctx context.Context, source v1.TaskRef) {
 // default and it will be in beta before the stored version of CRD getting swapped to v1.
 func (tr TaskRef) convertBundleToResolver(sink *v1.TaskRef) {
 	if tr.Bundle != "" {
+		sink.Kind = ""
```
Comment (l-qing) [inline pkg/apis/pipeline/v1beta1/taskref_conversion.go:52]: Remove the original "kind" attribute to stay consistent with the behavior elsewhere: once a resolver is used, "kind" is no longer necessary.

**Comment by l-qing** [comment]
Hi, @vdemeester.
I've resolved the e2e failure issue; please review it when you have time, thank you!

**Review by afrittoli — COMMENTED** [review]
Looks good, thank you!
/approve

File: pkg/apis/pipeline/v1/pipeline_defaults.go [hunk 3]
```diff
@@ -50,12 +50,12 @@ func (ps *PipelineSpec) SetDefaults(ctx context.Context) {
...
-		if pt.TaskRef.Kind == "" {
-			pt.TaskRef.Kind = NamespacedTaskKind
-		}
 		if pt.TaskRef.Name == "" && pt.TaskRef.Resolver == "" {
 			pt.TaskRef.Resolver = ResolverName(cfg.Defaults.DefaultResolverType)
 		}
+		if pt.TaskRef.Kind == "" && pt.TaskRef.Resolver == "" {
+			pt.TaskRef.Kind = NamespacedTaskKind
+		}
 	}
```
Comment (afrittoli) [inline pkg/apis/pipeline/v1/pipeline_defaults.go:59]: This will continue to work even after [TEP-0154](https://github.com/tektoncd/community/blob/main/teps/0154-concise-remote-resolver-syntax.md) is done
