### PR TITLE
Fix no logs in stdout/stderr if uses stdoutConfig

### LINKED ISSUE #6136: No logs in stdout/stderr if uses stdoutConfig
# Expected Behavior

Should have log

# Actual Behavior

No logs

# Steps to Reproduce the Problem

1. Run `kubectl create -f test.yaml` to create a taskrun
2. Run `k get pod | grep test` to the pod id
3.  Run `kl pod/testlvv64-pod`, there is no any log. but the doc says `Once stdoutConfig.path or stderrConfig.path is specified, the corresponding output stream will be duplicated to both the given file and the standard output stream of the container, so users can still view the output through the Pod log API.`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-08T10:15:09Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-eks-ffeb93d", GitCommit:"abb98ec0631dfe573ec5eae40dc48fd8f2017424", GitTreeState:"clean", BuildDate:"2022-11-29T18:45:03Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.28.0
Pipeline version: v0.42.0
Triggers version: v0.22.0
Dashboard version: v0.31.0
Operator version: v0.64.0
```

the test.yaml file

```yaml
kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test
spec:
  serviceAccountName: default
  taskSpec:
    volumes:
      - name: data
    steps:
      - name: echo
        image: alpine
        volumeMounts:
          - name: data
            mountPath: /data
        onError: continue
        script: |
          #!/bin/sh

          echo -n "hello world"
          echo "not an error" && nonsense
        stdoutConfig:
          path: /data/log
        stderrConfig:
          path: /data/error
```

### PR DESCRIPTION
**Pull request by chengjoey**
# Changes
fix #6136 
used to only collect stdout and err to a file if the std{out/err}Path is specified, now add both os.std{out/err} and the std{out/err}Path to multiwriter to collect logs.

there is a full test to verify the stdoutConfig, in addition, this pr adds the verification of whether to print the log to standard output in the `TestRealRunnerStdoutAndStderrPaths` test

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
users can still view the output through the Pod log API if stdoutConfig.path or stderrConfig.path is specified
```

### CODE REVIEW

**Comment by chengjoey** [comment]
/assign @wlynch 
could you please take a review?🙏

**Review by vdemeester — APPROVED** [review]
This will probably need a `release-note` entry 👼🏼

**Comment by chengjoey** [comment]
> This will probably need a `release-note` entry 👼🏼

thanks @vdemeester , i added the `release-note` and marked the `release-note` checklist

**Comment by afrittoli** [comment]
@wlynch it would be nice if you could review this one since you changed this code last 🙏

**Comment by chengjoey** [comment]
> @chengjoey thanks for this fix.
> 
> As you pointed out, there is a test for this, which was already succeeding, which unfortunately means there is full coverage for this change - it could be inadvertently broken again and the tests would not catch it. Would it be possible to add test coverage to make sure we do not lose pod logs when using `stdoutConfig`?

Of course, i added verification in `TestRealRunnerStdoutAndStderrPaths` that whether `realRunner` print the log to std{out/err}. Thanks for the reminder, your advice is great!

File: cmd/entrypoint/runner_test.go [hunk 1]
```diff
@@ -39,10 +41,48 @@ func TestRealRunnerStdoutAndStderrPaths(t *testing.T) {
...
 	}
+
+	// capture the std{out/err} output to verify whether we print log in the std
+	oldStdout := os.Stdout // keep backup of the real stdout
+	outReader, outWriter, _ := os.Pipe()
+	os.Stdout = outWriter
+
+	oldStderr := os.Stderr
+	errReader, errWriter, _ := os.Pipe()
+	os.Stderr = errWriter
```
Comment (wlynch) [inline cmd/entrypoint/runner_test.go:52]: This seems brittle since it modifies global state.

How about we:

1. Modify realRunner to take in io.Writers 
2. Have main.go initialize the multiwriters if the flag is set.
3. If the writers are nil, default to os.Stdout/Stderr

This way in tests we can just use a buffer and remove a bunch of the path manipulation?

**Review by wlynch — COMMENTED** [review]
One thing, otherwise LGTM!

File: cmd/entrypoint/runner_test.go (hunk 1 above)
Comment (chengjoey) [reply cmd/entrypoint/runner_test.go:52]: The test here is to verify that logs can be printed to standard output. If you modify realRunner to accept io.Writers, you need to pass in os.stdout, which is the same as the current situation.

File: cmd/entrypoint/runner.go [hunk 2]
```diff
@@ -161,19 +143,11 @@ func (rr *realRunner) Run(ctx context.Context, args ...string) error {
...
-// be used for multiple streams if desired.
-// The behavior of the Reader is the same as io.TeeReader - reads from the pipe
-// will be written to the file.
-func newTeeReader(pipe func() (io.ReadCloser, error), path string) (*namedReader, error) {
-	in, err := pipe()
-	if err != nil {
-		return nil, fmt.Errorf("error creating pipe: %w", err)
-	}
-
+// be used for multiple streams if desired. note that close after use
```
Comment (Yongxuanzhang) [inline cmd/entrypoint/runner.go:149]: Is this docstring missing after "note that close after use"?

**Review by Yongxuanzhang — APPROVED** [review]

File: cmd/entrypoint/runner.go (hunk 2 above)
Comment (chengjoey) [reply cmd/entrypoint/runner.go:149]: It's not missing, I just modified the note here and added it to where it was used.
notes related to teaReader are no longer needed here

**Comment by vdemeester** [comment]
@chengjoey @pritidesai @jerop should this be cherry-picked in the latest LTS ? (0.41 and 0.44)

**Comment by chengjoey** [comment]
> @chengjoey @pritidesai @jerop should this be cherry-picked in the latest LTS ? (0.41 and 0.44)

when i try to cherry-pick to 0.41, there are some conflicts, I manually submitted a hotfix pr, is this the correct hotfix process
