### PR TITLE
clarify in docs to not use apiVersion for taskRef for non-customtask

### LINKED ISSUE #6682: ClusterTask creates CustomRun (v0.41.1 -> v0.44.2)
# Expected Behavior

I get an error/warning when I create my `ClusterTasks` or they run as normal `TaskRuns`.

# Actual Behavior

My `ClusterTasks` create `CustomRuns` instead of `TaskRuns` when I update from `v0.41.1` to `v0.44.2`.

# Steps to Reproduce the Problem

1. `minikube start --driver=kvm2 --cpus=4 --memory=6g --disk-size=30GB --embed-certs`
2. `kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.41.1/release.yaml`
3. `kubect apply --filename dummy.yaml` (file below)
4. `kubect get pipelinerun dummy` (this should complete after a while)
5. `kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.44.2/release.yaml`
6. `kubect apply --filename dummy.yaml` (file below)
7. `kubect get pipelinerun dummy` (this should hang)
8. `kubectl get customruns` (this should return a single one, called `dummy-init`)

<details>
<summary>dummy.yaml</summary>

```
# dummy.yaml
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dummy-2
  namespace: default
spec:
  tasks:
  - name: init
    params:
    - name: resource
      value: resouce
    taskRef:
      apiVersion: tekton.dev/v1beta1
      kind: ClusterTask
      name: init
    workspaces:
    - name: output
      workspace: shared
  workspaces:
  - description: Main workspace that is shared across each task in the build pipeline
    name: shared
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: init
spec:
  workspaces:
    - name: output
  params:
  - name: resource
    type: string
  steps:
  - name: hello
    image: registry.access.redhat.com/ubi9-micro:latest
    args: ["$(params.resource)"]
    command: ["echo"]
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dummy
spec:
  pipelineRef:
    name: dummy-2
  workspaces:
  - name: shared
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi

```

</details>

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.41.1

v0.44.2
```

I am trying to understand why this is happening. Thanks!

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes

This commit closes #6682. When apiversion and kind are both set for
task, it is also considered to be a custom task. If users want to refer
to tasks or cluster tasks, apiVersion shouldn't be set. This commit
clarify this in the docs.

/kind bug

Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

File: pkg/apis/pipeline/v1beta1/pipeline_types.go [hunk 1]
```diff
@@ -224,7 +224,7 @@ type PipelineTask struct {
 func (et *EmbeddedTask) IsCustomTask() bool {
 	// Note that if `apiVersion` is set to `"tekton.dev/v1beta1"` and `kind` is set to `"Task"`,
 	// the reference will be considered a Custom Task - https://github.com/tektoncd/pipeline/issues/6457
-	return et != nil && et.APIVersion != "" && et.Kind != ""
+	return et != nil && et.APIVersion != "" && et.Kind != "" && et.Kind != string(ClusterTaskKind)
```
Comment (Yongxuanzhang) [inline pkg/apis/pipeline/v1beta1/pipeline_types.go:227]: I wonder if we check (et.APIVersion!="v1beta1"&&et.Kind != string(ClusterTaskKind)) would be better?

Comment (jerop) [reply pkg/apis/pipeline/v1beta1/pipeline_types.go:227]: ah don't think we should handle `ClusterTask` differently from `Task` -- maybe what we need is better documentation?

**Review by jerop — COMMENTED** [review]
maybe what we need is better documentation that if `apiversion` and `kind` are set, we will create a `customrun` -- https://github.com/tektoncd/pipeline/issues/6457

**Comment by lbernick** [comment]
From the linked issue, it sounds like this used to create TaskRuns instead of CustomRuns, and this was a regression when updating to v0.44. If you can't specify "ClusterTask" as the "kind" in a TaskRef, how would you specify a cluster task?

**Comment by jerop** [comment]
To clarify, you can create a "ClusterTask" with "kind" in TaskRef -- you just can't put APIVersion as well because that creates a CustomRun -- the user removed APIVersion and this resolved their issue

**Comment by Yongxuanzhang** [comment]
Yes, I wonder if we need to fix it in code so users can still use apiversion+kind for cluster tasks? 
Or we need to document and also tell users that you shouldn't use  apiversion+kind for cluster task or tasks if you want to use them normally. 
It seems that this is an hidden issue but triggered by we enable the custom task by default

**Comment by jerop** [comment]
@Yongxuanzhang please update the commit and PR with more context, including https://github.com/tektoncd/pipeline/pull/6505 and https://github.com/tektoncd/pipeline/issues/6457

**Comment by Yongxuanzhang** [comment]
What confused me is the "apiversion", if it is only used for custom tasks, and we don't use it for cluster task, tasks (since the storage version in the cluster is fixed, it is not possible to refer v1 tasks and v1beta1 tasks in the same cluster). 

I lean to update the docs to clarify it now, since there's no need to use "apiversion"+"kind" for cluster tasks and tasks, pipelines. Though we do support it in previous versions when the custom task is not enabled by default and we should have called this out to users when we introduced this change.

**Comment by Yongxuanzhang** [comment]
> > To clarify, you can create a "ClusterTask" with "kind" in TaskRef -- you just can't put APIVersion as well because that creates a CustomRun -- the user removed APIVersion and this resolved their issue
> 
> Ah sorry, I missed that. However, it does still sound like the user experienced different behavior for existing CRDs when upgrading. @Yongxuanzhang I'm curious why you say this might have started happening when we enabled custom tasks by default?
> 
> I agree with Yongxuan that if we only use APIVersion for custom tasks, it would be nice to rename it in some way. (We can't remove it but can add a new field and document that instead.)
> 
> I still find it confusing that "kind=Task" or ClusterTask, Pipeline, etc creates a custom task when apiversion is used :( but I'm ok with improving docs for now

Previously, if custom task is not enabled, users can use apiversion+task/clustertask in taskref to refer tasks, but after we enabled it by default, the taskref will be considered as a custom task and creates customrun instead of taskrun

**Comment by lbernick** [comment]
Yongxuan can you check if we have any examples in the docs that use APIVersion for TaskRefs that aren't custom tasks?

**Comment by Yongxuanzhang** [comment]
> Yongxuan can you check if we have any examples in the docs that use APIVersion for TaskRefs that aren't custom tasks?

I cannot find any examples in docs, but found one in unit tests, just removed it

**Comment by lbernick** [comment]
Thanks, this lgtm, just two quick suggestions:
- This is a docs update, so I don't think it needs a release note
- Let's update the custom run docs to specify that a non-empty api version will always create a customrun, and apiversion is for customruns only

File: docs/pipelines.md [hunk 2]
```diff
@@ -1537,7 +1539,7 @@ that is responsible for watching and updating `CustomRun`s which reference their
 ### Specifying the target Custom Task
 
 To specify the custom task type you want to execute, the `taskRef` field
-must include the custom task's `apiVersion` and `kind` as shown below:
+must include the custom task's `apiVersion` and `kind` as shown below, `apiVersion` is only used to create `CustomRun`:
```
Comment (lbernick) [inline docs/pipelines.md:1542]:
```suggestion
must include the custom task's `apiVersion` and `kind` as shown below.
Using `apiVersion` will always create a `CustomRun`. If `apiVersion` is set, `kind` is required as well.
```

**Review by lbernick — COMMENTED** [review]
I think you may need to update the PR description

**Review by lbernick — APPROVED** [review]

**Review by jerop — APPROVED** [review]
/lgtm
