### PR TITLE
Fix git-init in case `master` is not the default branch

### LINKED ISSUE #2822: git-init: do not assume `master` as default branch
As of today, when the user doesn't specific a revision (branch, commit, …), we are defaulting to `master`. There is some problems with that: `master` might not be present on the remote. The recent wave of change of default branches on several project, including https://github.com/spring-projects/spring-petclinic are putting this problem into light : see https://github.com/tektoncd/catalog/pull/365.

Instead of making the assumption that we should use `master` when the revision is empty, we should *inspect* the remote. `git` can give us this information.

```
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/spring-projects/spring-petclinic
  Push  URL: https://github.com/spring-projects/spring-petclinic
  HEAD branch: main
  Remote branches:
    gh-pages  new (next fetch will store in remotes/origin)
    main      new (next fetch will store in remotes/origin)
    wavefront new (next fetch will store in remotes/origin)
```

After doing the `git init` and adding the remote `git remote add origin …`, we should get the default branch (remote HEAD) if the revision isn't specified. The way to do it should be as simple as `git symbolic-ref refs/remotes/origin/HEAD` :angel: 

/kind bug

### PR DESCRIPTION
**Pull request by vinamra28**
# Changes

This fix will patch the `git-init` such that if user doesn't provides revision then instead of taking `master` as the default branch we are doing the `symbolic-link` to the HEAD branch. Instead of making the assumption that we should use master when the revision is empty, we are inspecting the remote.

Fixes #2822 

Signed-off-by: vinamra28 <vinjain@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

## Release Notes

```
The Git PipelineResource now inspects remote repository to determine the correct default branch to use when no revision has been specified.
```

/kind bug

### CODE REVIEW

**Comment by vinamra28** [comment]
@vdemeester could you please take a look at the PR :slightly_smiling_face:

File: pkg/git/git.go [hunk 1]
```diff
@@ -65,7 +65,7 @@ func Fetch(logger *zap.SugaredLogger, spec FetchSpec) error {
 	}
 
 	if spec.Revision == "" {
-		spec.Revision = "master"
+		spec.Revision = "HEAD"
```
Comment (vdemeester) [inline pkg/git/git.go:68]: I think we should run `git symbolic-ref refs/remotes/origin/HEAD` only if `spec.Revision` is empty and extract the default branch name from it. So something like :

```go
remoteHead, err := run(logger, "", "symbolic-ref", "refs/remotes/origin/HEAD")
if err != nil {
	return err
}
spec.Revision = strings.ReplaceAll(remoteHead, "refs/remotes/origin/", "") // this would display `master` or `main`, or …
```

Comment (vinamra28) [reply pkg/git/git.go:68]: @vdemeester : I tried this out locally on my terminal and also as you suggested but this didn't worked out. On my terminal I got the following error:-
```
[vinjain@vinjain output]$ git remote show origin
* remote origin
  Fetch URL: https://github.com/spring-projects/spring-petclinic.git
  Push  URL: https://github.com/spring-projects/spring-petclinic.git
  HEAD branch: main
  Remote branches:
    gh-pages  new (next fetch will store in remotes/origin)
    main      new (next fetch will store in remotes/origin)
    wavefront new (next fetch will store in remotes/origin)
[vinjain@vinjain output]$ git symbolic-ref refs/remotes/origin/HEAD
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
```

Comment (vdemeester) [reply pkg/git/git.go:68]: @vinamra28 you are right, it needs to happend after the fetch :thinking:

**Comment by vinamra28** [comment]
@vdemeester added e2e tests as well for both `v1beta1` and `v1alpha1` for `spring-petclinic` repository

File: pkg/apis/resource/v1alpha1/git/git_resource_test.go [hunk 2]
```diff
@@ -675,6 +675,44 @@ func TestGitResource_GetDownloadTaskModifier(t *testing.T) {
...
+			NOProxy:    "no-proxy.git.com",
+		},
+		want: corev1.Container{
+			Name:    "git-source-git-resource-twkr2",
+			Image:   "override-with-git:latest",
+			Command: []string{"/ko-app/git-init"},
+			Args: []string{
+				"-url",
+				"git@github.com:test/test.git",
+				"-revision",
```
Comment (sbwsg) [inline pkg/apis/resource/v1alpha1/git/git_resource_test.go:701]: nit: should we just leave the flag out completely if there's no revision?

Comment (vinamra28) [reply pkg/apis/resource/v1alpha1/git/git_resource_test.go:701]: I tried removing this but the unit test is failing :sweat_smile:

Comment (sbwsg) [reply pkg/apis/resource/v1alpha1/git/git_resource_test.go:701]: Indeed, you would also need to update line 149 in `pkg/apis/resource/v1alpha1/git/git_resource.go` to only add the `-revision` flag if `s.Revision != ""`

Comment (vinamra28) [reply pkg/apis/resource/v1alpha1/git/git_resource_test.go]: thanks :sweat_smile:

File: test/v1alpha1/git_checkout_test.go [hunk 3]
```diff
@@ -297,6 +297,63 @@ func TestGitPipelineRunFail_HTTPS_PROXY(t *testing.T) {
...
+			}
+		})
+	}
+}
+
+// getGitPipelineResourceSpringPetClinic will help to clone the spring-petclinic repository which does not contains master branch
+func getGitPipelineResourceSpringPetClinic(revision, refspec, sslverify, httpproxy, httpsproxy, noproxy string) *v1alpha1.PipelineResource {
+	return tb.PipelineResource(gitSourceResourceName, tb.PipelineResourceSpec(
+		v1alpha1.PipelineResourceTypeGit,
+		tb.PipelineResourceSpecParam("Url", "https://github.com/spring-projects/spring-petclinic"),
```
Comment (vdemeester) [inline test/v1alpha1/git_checkout_test.go:347]: I think, long term, we should use a project we control (just in case) :stuck_out_tongue_closed_eyes:

Comment (vinamra28) [reply test/v1alpha1/git_checkout_test.go:347]: actually there was no repo in `tektoncd/*` which does not have `master` as the default branch. Earlier we had the `v1beta1` branch in `tektoncd/catalog` as the default branch but now it has been merged to `master`. That's why I went to `spring-petclinic` repo for testing :sweat_smile:

Comment (vdemeester) [reply test/v1alpha1/git_checkout_test.go:347]: @vinamra28 yep, that's fine for now :wink:

**Comment by sbwsg** [comment]
I think there are two more things that need to be resolved and then this is ready to merge:

1. `docs/resources.md` should include a description of this new behavior.  Right now it says:

    > `_If no revision is specified, the resource will default to `master`.

2. We should have Release Notes in the PR description describing the user-visible change. Something like this:

    > The Git PipelineResource now inspects remote repositories to determine the correct default branch to use when no revision has been specified.

As an aside, we'll need to also update documentation for the `git-clone` catalog entry when we move to this new version of `git-init`.  I'll create an issue for this.

**Comment by vinamra28** [comment]
Thank you @sbwsg. Will do this. Thanks for guidance :smile:

File: test/v1alpha1/git_checkout_test.go (hunk 3 above)
Comment (sbwsg) [reply test/v1alpha1/git_checkout_test.go:347]: Created https://github.com/tektoncd/pipeline/issues/2854 to track.
