### PR TITLE
TaskRunStatus includes sidecar status

### LINKED ISSUE #1511: Record digests of images used as sidecars
# Expected Behavior

TaskRun status indicates the specific digest of an image used as a sidecar.

Digests of images used in steps are surfaced, and this makes it easier to reproduce a TaskRun in cases where the image is specified by tag and that tag points at something else now. No such faculty is available for sidecar images.

# Actual Behavior

This information isn't recorded or surfaced. Someone could dig into the TaskRun's Pod to find it, with some effort.

# Additional Information

Fairly straightforward: add a field to TaskRunStatus, and when translating a PodStatuts to a TaskRunStatus, copy over the sidecar image's digest information.

### PR DESCRIPTION
**Pull request by fraenkel**
# Changes

Record the sidecar name and image id for posterity.

Fixes #1511

I didn't include the container name because it is the same as the name.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
The status of a task run includes the image ids of all sidecars.
```

### CODE REVIEW

File: pkg/status/taskrunpod.go [hunk 1]
```diff
@@ -55,8 +56,16 @@ func UpdateStatusFromPod(taskRun *v1alpha1.TaskRun, pod *corev1.Pod, resourceLis
 				ContainerName:  s.Name,
 				ImageID:        s.ImageID,
 			})
+		} else {
```
Comment (ImJasonH) [inline pkg/status/taskrunpod.go]: Non-blocking idea for a future change in this area: We should prefix sidecar containers with something like `sidecar-` like we do for step containers, to prevent possible collisions, and so we can definitively identify them here (`IsSidecarStep`). In the future we might have some third type of container we might want to identify separately.

(Not for this PR, but if you felt like doing it that'd be fine. Otherwise I can file an issue to track it for later)

File: pkg/status/taskrunpod.go [hunk 2]
```diff
@@ -55,8 +56,16 @@ func UpdateStatusFromPod(taskRun *v1alpha1.TaskRun, pod *corev1.Pod, resourceLis
...
+			sidecars = append(taskRun.Status.Sidecars, v1alpha1.SidecarState{
+				Name:    s.Name,
+				ImageID: s.ImageID,
+			})
 		}
 	}
+	if len(sidecars) > 0 {
```
Comment (ImJasonH) [inline pkg/status/taskrunpod.go]: You could just get rid of the `sidecars` slice and on line 60 do `taskRun.Status.Sidecars = append(taskRun.Status.Sidecars, v1alpha1.SidecarState{...})` like we do for step containers.

**Comment by ImJasonH** [comment]
The build failures indicate you need to run `./hack/update-codegen.sh` to account for the new fields added to `TaskRunStatus`.

File: pkg/status/taskrunpod.go (hunk 1 above)
Comment (fraenkel) [reply pkg/status/taskrunpod.go]: I will do it in a separate commit. If its on the larger side I will just split it off into a separate PR.

File: pkg/status/taskrunpod.go (hunk 2 above)
Comment (fraenkel) [reply pkg/status/taskrunpod.go]: I did that first and didn't want to update all the tests, but I switched to be consistent.
