### PR TITLE
Delete artifact storage PVCs upon completion of PipelineRun

### LINKED ISSUE #823: Artifact storage PVCs aren't cleaned up until the PipelineRun is deleted
# Expected Behavior

Artifact storage PVCs get deleted after the completion of the `PipelineRun`.

# Actual Behavior

Artifact storage PVCs don't get deleted automatically until/unless the owning `PipelineRun` itself is deleted.

# Steps to Reproduce the Problem

1. Run a `Pipeline` with multiple `Task`s, with one having its workspace as output and another having that workspace as input.
2. Notice that the PVC created for that input/output isn't deleted after completion of the `PipelineRun`.

# Additional Info

### PR DESCRIPTION
**Pull request by abayer**
# Changes

We currently don't delete artifact storage PVCs until their owner
PipelineRun is deleted. Since PipelineRuns may be kept around for a
very long time, this can result in a giant pile of PVCs sitting around
indefinitely, which is markedly suboptimal. Let's nuke them when the
PipelineRun completes.

Fixes #823 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

n/a

### CODE REVIEW

**Comment by abayer** [comment]
So the e2e tests may hang - they're hanging for me locally in the first init container, but that may just be something weird in my local setup, hence me opening the PR.

File: pkg/artifacts/artifact_storage_test.go [hunk 1]
```diff
@@ -155,6 +155,9 @@ func TestInitializeArtifactStorageWithConfigMap(t *testing.T) {
 			if err != nil {
 				t.Fatalf("Somehow had error initializing artifact storage run out of fake client: %s", err)
 			}
+			if err := CleanupArtifactStorage(c.pipelinerun, fakekubeclient, logger); err != nil {
```
Comment (bobcatfish) [inline pkg/artifacts/artifact_storage_test.go]: could we have separate unit test cases specifically for `CleanupArtifactStorage` instead of adding this call to the existing tests?

File: pkg/artifacts/artifacts_storage.go [hunk 2]
```diff
@@ -59,6 +59,22 @@ func InitializeArtifactStorage(pr *v1alpha1.PipelineRun, c kubernetes.Interface,
...
+	if shouldCreatePVC {
+		err = deletePVC(pr, c)
+		if err != nil {
+			return err
+		}
+	}
+	return nil
+}
+
 func needsPVC(configMap *corev1.ConfigMap, err error, logger *zap.SugaredLogger) (bool, error) {
```
Comment (bobcatfish) [inline pkg/artifacts/artifacts_storage.go]: id love to see some test cases for `needsPVC` too if possible :)

File: pkg/artifacts/artifacts_storage.go [hunk 3]
```diff
@@ -59,6 +59,22 @@ func InitializeArtifactStorage(pr *v1alpha1.PipelineRun, c kubernetes.Interface,
 	return NewArtifactBucketConfigFromConfigMap(configMap)
 }
 
+// CleanupArtifactStorage will delete the PipelineRun's PVC if it exists.
+func CleanupArtifactStorage(pr *v1alpha1.PipelineRun, c kubernetes.Interface, logger *zap.SugaredLogger) error {
+	configMap, err := c.CoreV1().ConfigMaps(system.GetNamespace()).Get(v1alpha1.BucketConfigName, metav1.GetOptions{})
+	shouldCreatePVC, err := needsPVC(configMap, err, logger)
+	if err != nil {
+		return err
```
Comment (bobcatfish) [inline pkg/artifacts/artifacts_storage.go]: can we add some context to these errors when we return them? e.g. something like `Couldn't determine if PVC was needed from config map: %s', err)`

File: pkg/artifacts/artifact_storage_test.go (hunk 1 above)
Comment (abayer) [reply pkg/artifacts/artifact_storage_test.go]: Sure? Though it feels to me like this is the right place for it - otherwise we're just going to have tests that also call `InitializeArtifactStorage` before calling `CleanupArtifactStorage` anyway.

File: pkg/artifacts/artifacts_storage.go (hunk 2 above)
Comment (abayer) [reply pkg/artifacts/artifacts_storage.go]: Reasonable!

File: pkg/artifacts/artifacts_storage.go (hunk 3 above)
Comment (abayer) [reply pkg/artifacts/artifacts_storage.go]: Sure thing!

File: pkg/artifacts/artifacts_storage.go (hunk 2 above)
Comment (abayer) [reply pkg/artifacts/artifacts_storage.go]: Actually, again, this is covered by `TestInitializeArtifactStorageWithConfigMap` and `TestInitializeArtifactStorageWithoutConfigMap`, I think? Does it really make sense to break that out into additional duplicative unit tests?

File: pkg/artifacts/artifact_storage_test.go (hunk 1 above)
Comment (abayer) [reply pkg/artifacts/artifact_storage_test.go]: Done.

File: pkg/artifacts/artifacts_storage.go (hunk 2 above)
Comment (abayer) [reply pkg/artifacts/artifacts_storage.go]: Done.

**Comment by abayer** [comment]
An interesting question here - do we want to be cleaning up the bucket here too?

**Comment by dlorenc** [comment]
> An interesting question here - do we want to be cleaning up the bucket here too?

Initial gut reaction is that this is less important, but I'm open to other opinions here.

**Comment by bobcatfish** [comment]
> An interesting question here - do we want to be cleaning up the bucket here too?

It [seems like](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#how-are-resources-shared-between-tasks) the bucket has to exist before the controller runs, so it doesn't seem like it should get deleted automatically.

You probably are suggesting erasing the contents? If we do that, we should be sure to only delete contents added by the controller. I'm happy to leave this decision up to you @abayer ! As a user of this functionality you probably have a better idea what makes sense :D

File: pkg/artifacts/artifact_storage_test.go [hunk 4]
```diff
@@ -165,6 +256,132 @@ func TestInitializeArtifactStorageWithConfigMap(t *testing.T) {
...
+		},
+		hasPVC: false,
+	}} {
+		t.Run(c.desc, func(t *testing.T) {
+			fakekubeclient := fakek8s.NewSimpleClientset(c.configMap)
+
+			if c.hasPVC {
+				fakekubeclient = fakek8s.NewSimpleClientset(c.configMap, GetPVCSpec(c.pipelinerun))
+			}
+			if c.hasPVC {
```
Comment (bobcatfish) [inline pkg/artifacts/artifact_storage_test.go]: could be combined with previous block?

File: pkg/artifacts/artifact_storage_test.go [hunk 5]
```diff
@@ -165,6 +256,132 @@ func TestInitializeArtifactStorageWithConfigMap(t *testing.T) {
...
+				Name:      "pipelineruntest",
+			},
+		},
+		hasPVC: false,
+	}} {
+		t.Run(c.desc, func(t *testing.T) {
+			fakekubeclient := fakek8s.NewSimpleClientset(c.configMap)
+
+			if c.hasPVC {
+				fakekubeclient = fakek8s.NewSimpleClientset(c.configMap, GetPVCSpec(c.pipelinerun))
```
Comment (bobcatfish) [inline pkg/artifacts/artifact_storage_test.go]: maybe we shouldn't call the line above in this case (i.e. move line above to `else`?)

File: pkg/artifacts/artifact_storage_test.go [hunk 6]
```diff
@@ -165,6 +256,132 @@ func TestInitializeArtifactStorageWithConfigMap(t *testing.T) {
...
+				}
+			}
+			if err := CleanupArtifactStorage(c.pipelinerun, fakekubeclient, logger); err != nil {
+				t.Fatalf("Error cleaning up artifact storage: %s", err)
+			}
+			_, err := fakekubeclient.CoreV1().PersistentVolumeClaims(c.pipelinerun.Namespace).Get(GetPVCName(c.pipelinerun), metav1.GetOptions{})
+			if err != nil && !errors.IsNotFound(err) {
+				t.Fatalf("Error checking if PVC %s for PipelineRun %s has been cleaned up: %s", GetPVCName(c.pipelinerun), c.pipelinerun.Name, err)
+			}
+			if !errors.IsNotFound(err) {
```
Comment (bobcatfish) [inline pkg/artifacts/artifact_storage_test.go]: i think this block and the previous could be made a bit easier to read, e.g.:

```
if err == nil {
   t.Fatalf("expected error....")
} else if !errors.IsNotFound(err) {
   t.Fatalf("found PVC...")
}
```

File: pkg/artifacts/artifacts_storage.go [hunk 7]
```diff
@@ -59,7 +59,25 @@ func InitializeArtifactStorage(pr *v1alpha1.PipelineRun, c kubernetes.Interface,
 	return NewArtifactBucketConfigFromConfigMap(configMap)
 }
 
-func needsPVC(configMap *corev1.ConfigMap, err error, logger *zap.SugaredLogger) (bool, error) {
+// CleanupArtifactStorage will delete the PipelineRun's PVC if it exists.
```
Comment (bobcatfish) [inline pkg/artifacts/artifacts_storage.go]: maybe elaborate in the comment here about what a "PipelineRun's PVC" is? (i.e. it's not that _all_ PVCs a Run is using will automatically get cleaned up, it's specifically PVCs that are used for sharing between TaskRuns right?)

File: pkg/artifacts/artifact_storage_test.go [hunk 8]
```diff
@@ -165,6 +256,132 @@ func TestInitializeArtifactStorageWithConfigMap(t *testing.T) {
...
+				v1alpha1.BucketServiceAccountSecretKey:  "sakey",
+			},
+		},
+		pipelinerun: &v1alpha1.PipelineRun{
+			ObjectMeta: metav1.ObjectMeta{
+				Namespace: "foo",
+				Name:      "pipelineruntest",
+			},
+		},
+		hasPVC: false,
```
Comment (bobcatfish) [inline pkg/artifacts/artifact_storage_test.go]: im a bit confused about what `hasPVC` means - maybe it would be clearer to split this into two separate functions completely, one dealing with all the `hasPVC` cases, and one dealing with the `hasPVC: false` cases (which I think is used to indicate that the configmap configuration is wrong, so there is no PVC to be created?)

File: test/pipelinerun_test.go [hunk 9]
```diff
@@ -172,6 +174,14 @@ func TestPipelineRun(t *testing.T) {
 			if len(events) != td.expectedNumberOfEvents {
 				t.Fatalf("Expected %d number of successful events from pipelinerun and taskrun but got %d; list of receieved events : %#v", td.expectedNumberOfEvents, len(events), events)
 			}
+			pvc, err := c.KubeClient.Kube.CoreV1().PersistentVolumeClaims(namespace).Get(artifacts.GetPVCName(pipelineRun), metav1.GetOptions{})
```
Comment (bobcatfish) [inline test/pipelinerun_test.go]: maybe include a comment here explaining what this block of code is testing?

File: test/pipelinerun_test.go [hunk 10]
```diff
@@ -263,7 +273,7 @@ func getFanInFanOutGitResources(namespace string) []*v1alpha1.PipelineResource {
 	return []*v1alpha1.PipelineResource{
 		tb.PipelineResource("kritis-resource-git", namespace, tb.PipelineResourceSpec(
 			v1alpha1.PipelineResourceTypeGit,
-			tb.PipelineResourceSpecParam("Url", "https://github.com/grafeas/kritis"),
+			tb.PipelineResourceSpecParam("Url", "https://github.com/abayer/build-pipeline"),
```
Comment (bobcatfish) [inline test/pipelinerun_test.go]: does this need to change?

File: pkg/artifacts/artifact_storage_test.go [hunk 11]
```diff
@@ -155,6 +237,15 @@ func TestInitializeArtifactStorageWithConfigMap(t *testing.T) {
 			if err != nil {
 				t.Fatalf("Somehow had error initializing artifact storage run out of fake client: %s", err)
 			}
+			if c.storagetype == "pvc" {
```
Comment (bobcatfish) [inline pkg/artifacts/artifact_storage_test.go]: could you include a comment here explaining what this block is for and why `CleanupArtifactStorage` is now being called in this test?

**Comment by afrittoli** [comment]
Thanks for this. While I agree that PVC are expensive to keep around, deleting them right away will make troubleshooting more complicated. 
A workaround for troubleshooting could be to pre-provision the PVC, so that it won't be deleted; an alternative could be a configuration option to enable / disable the PVC deletion. Either case I think it would be nice to document the alternatives.

File: pkg/artifacts/artifact_storage_test.go (hunk 4 above)
Comment (abayer) [reply pkg/artifacts/artifact_storage_test.go]: Good catch.

File: pkg/artifacts/artifact_storage_test.go (hunk 5 above)
Comment (abayer) [reply pkg/artifacts/artifact_storage_test.go]: Weirdly, I can't figure out how to get it to work with `fakekubeclient` as a `var` - can't get the typing to match up for some reason.

File: pkg/artifacts/artifact_storage_test.go (hunk 6 above)
Comment (abayer) [reply pkg/artifacts/artifact_storage_test.go]: Okiedokie.

File: pkg/artifacts/artifacts_storage.go (hunk 7 above)
Comment (abayer) [reply pkg/artifacts/artifacts_storage.go]: Done.

File: pkg/artifacts/artifact_storage_test.go (hunk 8 above)
Comment (abayer) [reply pkg/artifacts/artifact_storage_test.go]: I just copied in a bunch of test cases from existing tests. Really, we probably don't need the cases where `hasPVC` is false, so I'll remove them.

File: test/pipelinerun_test.go (hunk 9 above)
Comment (abayer) [reply test/pipelinerun_test.go]: Done.

File: test/pipelinerun_test.go (hunk 10 above)
Comment (abayer) [reply test/pipelinerun_test.go]: Something didn't work right when I was using the default, but I can't for the life of me remember what it was, so lemme try changing it back.

File: pkg/artifacts/artifact_storage_test.go (hunk 11 above)
Comment (abayer) [reply pkg/artifacts/artifact_storage_test.go]: Yup.

**Comment by vbatts** [comment]
a general question: is this artifact storage PVC expected to always be deleted?
(like would it store artifacts that may be referenced later?)
(or if they are to be reused, then it should be a step in the PipelineRun?)

**Comment by abayer** [comment]
No, this PVC is just used for copying artifacts/workspaces from one `Task` to the next `Task`, and is automatically deleted when the `PipelineRun` is deleted. But if you keep around `PipelineRun`s (which we do with Jenkins X, for example), not deleting the PVCs when they're no longer needed (that is, after their owner `PipelineRun` completes) leaves them lying around forever.

**Comment by abayer** [comment]
It's not a user-facing PVC at all, too - it's created internally when a `Task` has `resources.output.type` == `git`.

**Comment by vbatts** [comment]
got it. Thanks for the clarification.

**Comment by bobcatfish** [comment]
> It's not a user-facing PVC at all, too - it's created internally when a Task has resources.output.type == git.

Does that address your concerns too @afrittoli ? Seems like something we may not need to document for users if it's not intended to be user facing at all - I think if users wanted to persist artifacts explicitly we'd want them to be doing that with `PipelineResources` :thinking:

File: pkg/artifacts/artifacts_storage.go (hunk 3 above)
Comment (bobcatfish) [reply pkg/artifacts/artifacts_storage.go]: bump :D

Comment (abayer) [reply pkg/artifacts/artifacts_storage.go]: whoops! Updated `NeedsPVC` to give a better error.

**Comment by abayer** [comment]
Squashed!

**Comment by bobcatfish** [comment]
oh something is wrong

```
I0516 22:37:51.177] pkg/artifacts/artifacts_storage.go:171:2: S1021: should merge variable declaration with assignment on next line (gosimple)
I0516 22:37:51.177] 	var pvcSizeBytes int64
I0516 22:37:51.177] 	^
```

**Comment by bobcatfish** [comment]
but in the meantime:

/approve

**Comment by abayer** [comment]
@bobcatfish yeah, fixed - that's @dlorenc's linting kicking in, catching something I didn't even do! =)

**Comment by bobcatfish** [comment]
> catching something I didn't even do! =)

hahaha classic :D thanks for fixing it!!
