### PR TITLE
Fix and work around timeout handler data races

### LINKED ISSUE #1124: Data Race in Pipelinerun reconciler tests
The reconciler tests seem to occasionally fail with a panic. Looks like https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/timeout_handler.go#L265 is being called after the test exits. (My assumption is that the [`defer cancel()`](https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go#L741) should ensure that the timeout goroutines get cleaned up but I understand very little about how this works)

### Additional Information
` go test -run "^TestReconcilePropagateLabels" ./pkg/reconciler/v1alpha1/pipelinerun/ -count 10`

```
panic: Log in goroutine after TestReconcilePropagateLabels/without_pipelinetask_name has completed

goroutine 101 [running]:
testing.(*common).logDepth(0xc000222300, 0xc000786240, 0xbd, 0x3)
        /usr/lib/google-golang/src/testing/testing.go:634 +0x3a6
testing.(*common).log(...)
        /usr/lib/google-golang/src/testing/testing.go:614
testing.(*common).Logf(0xc000222300, 0x18b328b, 0x2, 0xc0003b4080, 0x1, 0x1)
        /usr/lib/google-golang/src/testing/testing.go:649 +0x7f
github.com/tektoncd/pipeline/vendor/go.uber.org/zap/zaptest.testingWriter.Write(0x1bd0060, 0xc000222300, 0x0, 0xc0007a8400, 0xbe, 0x400, 0xc0007a8400, 0x1635f40, 0xc0003b4070)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/vendor/go.uber.org/zap/zaptest/logger.go:130 +0xfc
github.com/tektoncd/pipeline/vendor/go.uber.org/zap/zapcore.(*ioCore).Write(0xc0003d7050, 0x0, 0xbf46480bc791818a, 0x10edee7, 0x2b0e160, 0xc0004fcf00, 0x36, 0xc000358000, 0x42, 0x1, ...)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/vendor/go.uber.org/zap/zapcore/core.go:90 +0x107
github.com/tektoncd/pipeline/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000457550, 0x0, 0x0, 0x0)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/vendor/go.uber.org/zap/zapcore/entry.go:215 +0x119
github.com/tektoncd/pipeline/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0003de388, 0x0, 0x18c895c, 0x15, 0xc000719de8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/vendor/go.uber.org/zap/sugar.go:234 +0x101
github.com/tektoncd/pipeline/vendor/go.uber.org/zap.(*SugaredLogger).Infof(...)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/vendor/go.uber.org/zap/sugar.go:138
github.com/tektoncd/pipeline/pkg/reconciler.(*TimeoutSet).setTimer(0xc000445c80, 0x1b7b400, 0xc00023e780, 0x34630b755cc, 0xc0002de3b0)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/pkg/reconciler/timeout_handler.go:265 +0x4d3
github.com/tektoncd/pipeline/pkg/reconciler.(*TimeoutSet).waitRun(0xc000445c80, 0x1b7b400, 0xc00023e780, 0x34630b8a000, 0xc0000f4640, 0xc0002de3b0)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/pkg/reconciler/timeout_handler.go:241 +0x29d
github.com/tektoncd/pipeline/pkg/reconciler.(*TimeoutSet).WaitPipelineRun(0xc000445c80, 0xc00023e780, 0xc0000f4640)
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/pkg/reconciler/timeout_handler.go:227 +0x68
created by github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/pipelinerun.(*Reconciler).Reconcile
        /usr/local/google/home/dibyajyoti/dev/go/src/github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/pipelinerun/pipelinerun.go:141 +0x1224
FAIL    github.com/tektoncd/pipeline/pkg/reconciler/v1alpha1/pipelinerun        0.221s
```

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

This mostly fixes #1124, will still need to update the `gcr.io/tekton-releases/tests/test-runner` to use a newer version of go which can catch this race.

Will re-add logging to the timeout handler in #1307

## Remove logging from timeout handler :pencil2: 

Logging in the timeout handler was added as part of #731 cuz it helped
us debug when the timeout handler didn't work as expected. Unfortunately
it looks like the logger we're using can't be used in multiple go
routines (uber-go/zap#99 may be related).
Removing this logging to fix #1124, hopefully can find a safe way to add
logging back in #1307.

## Make GetRunKey threadsafe :lock: 

GetRunKey is accessed in goroutines via the timeout_handler; accessing
attributes of an object in a goroutine is not threadsafe. This is used
as a key in a map, so for now replacing this with a value that should be
unique but also threadsafe to fix #1124

## Remove unused function :ghost: 

The function `GetLogMessages` isn't used anywhere. I had tried to remove
it to see if it was causing the data race in #1124 - it _isnt_ but still
it's not being used anywhere so why not remove :)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Removes potential race conditions in timeout handler
```

### CODE REVIEW

**Comment by afrittoli** [comment]
I cannot reproduce the races with this code, nice!

File: pkg/apis/pipeline/v1alpha1/pipelinerun_types.go [hunk 1]
```diff
@@ -246,7 +246,8 @@ func (pr *PipelineRun) IsCancelled() bool {
 
 // GetRunKey return the pipelinerun key for timeout handler map
 func (pr *PipelineRun) GetRunKey() string {
-	return fmt.Sprintf("%s/%s/%s", pipelineRunControllerName, pr.Namespace, pr.Name)
+	// The address of the pointer is a threadsafe unique identifier for the pipelinerun
+	return fmt.Sprintf("%s/%p", pipelineRunControllerName, pr)
```
Comment (dibyom) [inline pkg/apis/pipeline/v1alpha1/pipelinerun_types.go]: nice!

File: test/controller.go [hunk 2]
```diff
@@ -86,7 +76,6 @@ type Informers struct {
 // TestAssets holds references to the controller, logs, clients, and informers.
 type TestAssets struct {
 	Controller *controller.Impl
-	Logs       *observer.ObservedLogs
```
Comment (afrittoli) [inline test/controller.go]: This is strange - I remember using Logs to debug a test in the past, before the controller refactor.
I might be nice to have GetLogMessages populate the Logs field here, which would give tests access to logs and would enable testing on seeing a certain log message. 

But I agree since it's not used now we can remove it and add it back if needed in future.

File: pkg/reconciler/timeout_handler.go [hunk 3]
```diff
@@ -170,7 +170,6 @@ func backoffDuration(count uint, jf jitterFunc) time.Duration {
 func (t *TimeoutSet) checkPipelineRunTimeouts(namespace string, pipelineclientset clientset.Interface) {
 	pipelineRuns, err := pipelineclientset.TektonV1alpha1().PipelineRuns(namespace).List(metav1.ListOptions{})
 	if err != nil {
-		t.logger.Errorf("Can't get pipelinerun list in namespace %s: %s", namespace, err)
```
Comment (afrittoli) [inline pkg/reconciler/timeout_handler.go]: I'm not super-happy to remove logging just ahead of a release - it may make troubleshooting harder for folks. That said, removing non-thread safe behavior is probably more important, so I'm ok with this - and we still have a chance to bring logging back before the release anyways.
