### PR TITLE
Sync the pipelinerun status from the informers

### LINKED ISSUE #2558: TaskRuns may be orphaned by a PipelineRun
# Expected Behavior
The `PipelineRun` controller should always be aware of `TaskRuns` owned by a `PipelineRun` even when the `PipelineRun` status is stale (because of API issues).
Before using the `PipelineRun` status as a source of truth, we should check it against the list ot `TaskRuns` owned by the `PipelineRun`.

# Actual Behavior
When `TaskRuns` are created during the reconcile cycle of a `PipelineRun`, they are added to the `PipelineRun` status which is then sync'ed back to etcd. The sync may fail whatever error condition - if that happens, the `TaskRuns` are partially "orphaned": the `PipelineRun` will be queued for reconcile when they change and they will be deleted when the `PipelineRun` is deleted, however the `PipelineRun` controller will not be aware that they exist at all, and it will create new duplicate `TaskRuns`.

This happens because [`ResolvePipelineRun`](https://github.com/tektoncd/pipeline/blob/fe5981e4e75ffec7f50a4aaab5eb6899742dd0f2/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L288) relies on the `PipelineRun` status alone, via the [`getTaskRunName`](https://github.com/tektoncd/pipeline/blob/fe5981e4e75ffec7f50a4aaab5eb6899742dd0f2/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L385-L394) function.

# Steps to Reproduce the Problem

1. I would like to be able to reproduce this. It might be worth building a test case to reproduce this situation but it might be difficult. If we can disable specific API calls from functioning we could allow creating a taskrun while prevent updating a pipelinerun.

# Additional Info

- Tekton Pipeline version:

`v0.12.0`

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

When we reconcile a pipelinerun, we should ensure that the
pipelinerun status is always in sync with the actual list of taskruns
that can be provided by the taskrun informer.

The only way to filter taskruns is by labels tekton.dev/pipelinerun.
In case an orphaned taskrun is found, we can use the other labels
on the taskrun to reconstruct the missing entry in the pipelinerun
status.

Fixes #2558 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by afrittoli** [comment]
@n3wscott @mattmoor any feedback on this would be really welcome :)

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 1]
```diff
@@ -2188,3 +2188,287 @@ func Test_storePipelineSpec(t *testing.T) {
...
+	c := testAssets.Controller
+	clients := testAssets.Clients
+
+	if err := c.Reconciler.Reconcile(context.Background(), "foo/"+prOutOfSync.Name); err != nil {
+		t.Fatalf("Error reconciling: %s", err)
+	}
+
+	// if len(clients.Pipeline.Actions()) != 2 {
+	// 	t.Fatalf("Expected client to have updated the TaskRun status for a completed PipelineRun, but it did not")
+	// }
```
Comment (vdemeester) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:2375]: This should be removed

**Comment by afrittoli** [comment]
```
>> Waiting for tests to finish for pipelinerun
ERROR: tests timed out
```

@vdemeester perhaps we are at the time limit with alpha + beta + the new test? Shall I increase the timeout a bit?

**Comment by afrittoli** [comment]
I wonder if the new pool could be related to the timeout @bobcatfish?
I couldn't find a way to see if there is any variation in test duration... or even to see for sure how the last test run took :(

**Comment by afrittoli** [comment]
`conditional-pr` is one of the pipelines that was in status `Unknown` when the YAML test for beta API hit timeout in the test run. The second task in the pipeline never ran. Looking at events I can see that the pod was killed:
```
default     45m         Normal    Scheduled                      pod/condtional-pr-then-check-qzr27-pod-npgpc                              Successfully assigned default/condtional-pr-then-check-qzr27-pod-npgpc to gke-tpipeline-e2e-
cls126-default-pool-16f28bca-4z3c
default     45m         Normal    Pulled                         pod/condtional-pr-then-check-qzr27-pod-npgpc                              Container image "busybox@sha256:a2490cec4484ee6c1068ba3a05f89934010c85242f736280b35343483b2264b6" already present on machine
default     45m         Normal    Created                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Created container place-scripts
default     45m         Normal    Started                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Started container place-scripts
default     45m         Normal    Pulled                         pod/condtional-pr-then-check-qzr27-pod-npgpc                              Container image "gcr.io/tekton-prow-6/tpipeline-e2e-img/entrypoint-bff0a22da108bc2f16c818c97641a296@sha256:f24e5923f6fb0da0dfe3a303a2b367b9a59a3392d2e21192b4dad29f8c0c6864" already present on machine
default     45m         Normal    Created                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Created container place-tools
default     45m         Normal    Started                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Started container place-tools
default     45m         Normal    Pulling                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Pulling image "ubuntu"
default     45m         Normal    Pulled                         pod/condtional-pr-then-check-qzr27-pod-npgpc                              Successfully pulled image "ubuntu"
default     45m         Normal    Created                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Created container step-echo
default     45m         Normal    Started                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Started container step-echo
default     38m         Normal    Killing                        pod/condtional-pr-then-check-qzr27-pod-npgpc                              Stopping container step-echo
default     45m         Normal    Started                        taskrun/condtional-pr-then-check-qzr27
default     45m         Normal    Pending                        taskrun/condtional-pr-then-check-qzr27                                    Pending
default     57m         Normal    Running                        pipelinerun/condtional-pr                                                 Tasks Completed: 0, Incomplete: 2, Skipped: 0
default     56m         Normal    Running                        pipelinerun/condtional-pr                                                 Tasks Completed: 1, Incomplete: 1, Skipped: 0
default     32m         Normal    Running                        pipelinerun/condtional-pr                                                 Tasks Completed: 0, Incomplete: 2, Skipped: 0
default     32m         Warning   PipelineRunFailed              pipelinerun/condtional-pr                                                 PipelineRun failed to update labels/annotations
default     30m         Normal    Running                        pipelinerun/condtional-pr                                                 Tasks Completed: 1, Incomplete: 1, Skipped: 0
```

**Comment by afrittoli** [comment]
Seeing also:
```
default     38m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 2705 (k8s_metadata) score 569 or sacrifice child
Killed process 2705 (k8s_metadata) total-vm:821036kB, anon-rss:42948kB, file-rss:26904kB, shmem-rss:0kB
default     37m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 175552 (k8s_metadata) score 569 or sacrifice child
Killed process 175552 (k8s_metadata) total-vm:689964kB, anon-rss:43224kB, file-rss:26648kB, shmem-rss:0kB
default     23m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 180624 (k8s_metadata) score 578 or sacrifice child
Killed process 180624 (k8s_metadata) total-vm:690220kB, anon-rss:43672kB, file-rss:26584kB, shmem-rss:0kB
default     20m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 3056 (heapster) score 0 or sacrifice child
Killed process 3056 (heapster) total-vm:214200kB, anon-rss:87552kB, file-rss:29568kB, shmem-rss:0kB
default     16m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 209047 (k8s_metadata) score 563 or sacrifice child
Killed process 209047 (k8s_metadata) total-vm:624428kB, anon-rss:43156kB, file-rss:26456kB, shmem-rss:0kB
default     15m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 236820 (k8s_metadata) score 552 or sacrifice child
Killed process 236820 (k8s_metadata) total-vm:698164kB, anon-rss:42928kB, file-rss:26136kB, shmem-rss:0kB
default     14m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 242662 (k8s_metadata) score 564 or sacrifice child
Killed process 242662 (k8s_metadata) total-vm:689644kB, anon-rss:43372kB, file-rss:26264kB, shmem-rss:0kB
default     14m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 224839 (heapster) score 244 or sacrifice child
Killed process 224839 (heapster) total-vm:214264kB, anon-rss:120256kB, file-rss:29120kB, shmem-rss:0kB
default     13m         Warning   OOMKilling                     node/gke-tpipeline-e2e-cls126-default-pool-16f28bca-4z3c                  Memory cgroup out of memory: Kill process 247622 (k8s_metadata) score 562 or sacrifice child
Killed process 247622 (k8s_metadata) total-vm:567028kB, anon-rss:43296kB, file-rss:26264kB, shmem-rss:0kB
```

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 2]
```diff
@@ -935,3 +945,82 @@ func storePipelineSpec(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1
...
+	// Then loop by pipelinetask name over all the TaskRuns associated to Conditions
+	for pipelineTaskName, actualConditionTaskRuns := range conditionTaskRuns {
+		taskRunName, ok := taskRunByPipelineTask[pipelineTaskName]
+		if !ok {
+			// The pipelineTask associated to the conditions was not found in the pipelinerun
+			// status. This means that the conditions were orphaned, and never added to the
+			// status. In this case we need to generate a new TaskRun name, that will be used
+			// to run the TaskRun if the conditions are passed.
+			taskRunName = resources.GetTaskRunName(pr.Status.TaskRuns, pipelineTaskName, pr.Name)
+			pr.Status.TaskRuns[taskRunName] = &v1alpha1.PipelineRunTaskRunStatus{
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:994]: I think we are using `v1beta1` throughout now 😉 instead of `v1alpha1`

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 3]
```diff
@@ -935,3 +945,82 @@ func storePipelineSpec(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1
...
+				PipelineTaskName: pipelineTaskName,
+				Status:           nil,
+				ConditionChecks:  nil,
+			}
+		}
+		// Build the map of condition checks for the taskrun
+		// If there were no other condition, initialise the map
+		conditionChecks := pr.Status.TaskRuns[taskRunName].ConditionChecks
+		if conditionChecks == nil {
+			conditionChecks = make(map[string]*v1alpha1.PipelineRunConditionCheckStatus)
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1004]: same as above `v1beta1` ⬆️

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 4]
```diff
@@ -935,3 +945,82 @@ func storePipelineSpec(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1
...
+			}
+			conditionTaskRuns[pipelineTaskName] = append(conditionTaskRuns[pipelineTaskName], taskrun)
+			continue
+		}
+		// Map pipeline task to taskrun name
+		taskRunByPipelineTask[pipelineTaskName] = taskrun.Name
+		if _, ok := pr.Status.TaskRuns[taskrun.Name]; !ok {
+			// This taskrun was missing from the status.
+			// Add it without conditions, which are handled in the next loop
+			pr.Status.TaskRuns[taskrun.Name] = &v1alpha1.PipelineRunTaskRunStatus{
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:978]: should be `v1beta1` 🤔

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 5]
```diff
@@ -935,3 +945,82 @@ func storePipelineSpec(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1
...
+			conditionChecks = make(map[string]*v1alpha1.PipelineRunConditionCheckStatus)
+		}
+		for i, foundTaskRun := range actualConditionTaskRuns {
+			lbls := foundTaskRun.GetLabels()
+			if _, ok := conditionChecks[foundTaskRun.Name]; !ok {
+				// The condition check was not found, so we need to add it
+				// We only add the condition name, the status can now be gathered by the
+				// normal reconcile process
+				if conditionName, ok := lbls[pipeline.GroupName+pipeline.ConditionNameKey]; ok {
+					conditionChecks[foundTaskRun.Name] = &v1alpha1.PipelineRunConditionCheckStatus{
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1013]: same as above v1beta1 ⬆️

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 6]
```diff
@@ -2239,3 +2239,283 @@ func Test_storePipelineSpec(t *testing.T) {
...
+	// but it fails to sync the update on the status back. This test verifies that
+	// the reconciler is able to coverge back to a consistent state with the orphaned
+	// TaskRuns back in the PipelineRun status.
+	// For more details, see https://github.com/tektoncd/pipeline/issues/2558
+	prOutOfSyncName := "test-pipeline-run-out-of-sync"
+	helloWorldTask := tb.Task("hello-world", tb.TaskNamespace("foo"))
+
+	// Condition checks for the third task
+	prccs3 := make(map[string]*v1beta1.PipelineRunConditionCheckStatus)
+	conditionCheckName3 := prOutOfSyncName + "hello-world-3-always-true-xxxyyy"
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:2254]: NIT: missing `-` here: `conditionCheckName3 := prOutOfSyncName + "-hello-world-3-always-true-xxxyyy"`

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 7]
```diff
@@ -2239,3 +2239,283 @@ func Test_storePipelineSpec(t *testing.T) {
...
+						Type:   apis.ConditionSucceeded,
+						Status: corev1.ConditionUnknown,
+					},
+				},
+			},
+		},
+	}
+	// Condition checks for the fourth task
+	prccs4 := make(map[string]*v1beta1.PipelineRunConditionCheckStatus)
+	conditionCheckName4 := prOutOfSyncName + "hello-world-4-always-true-xxxyyy"
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:2270]: NIT: missing `-` here same as above: `conditionCheckName4 := prOutOfSyncName + "-hello-world-4-always-true-xxxyyy"`

**Comment by pritidesai** [comment]
thanks @afrittoli 

couple of minor nits, otherwise /lgtm

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 2 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun.go:994]: Nice catch, thank you!

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 1 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go]: Done

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 2 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun.go]: done

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 3 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun.go]: done

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 5 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun.go]: done

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 6 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go]: done

File: pkg/reconciler/pipelinerun/pipelinerun_test.go (hunk 7 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go]: done

**Comment by afrittoli** [comment]
The integration tests are failing way too often on this PR, perhaps it's better to hold this one until I get a better understanding of the reason for that.
/hold

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 8]
```diff
@@ -935,3 +945,82 @@ func storePipelineSpec(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1
 	}
 	return nil
 }
+
+func (c *Reconciler) updatePipelineRunStatusFromInformer(pr *v1beta1.PipelineRun) error {
+	pipelineRunLabels := getTaskrunLabels(pr, "")
+	taskRuns, err := c.taskRunLister.TaskRuns(pr.Namespace).List(labels.SelectorFromSet(pipelineRunLabels))
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:951]: @afrittoli the `pipelineTask` associated to a condition (could be more than one condition as well) is not added to the `PipelineRunStatus` as its not executed/created until condition successfully finishes.

but this query returns `conditionCheckContainer` as well and it forces to iterate over those condition containers at line 961

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 9]
```diff
@@ -935,3 +945,82 @@ func storePipelineSpec(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1
...
+			// Add it without conditions, which are handled in the next loop
+			pr.Status.TaskRuns[taskrun.Name] = &v1beta1.PipelineRunTaskRunStatus{
+				PipelineTaskName: pipelineTaskName,
+				Status:           &taskrun.Status,
+				ConditionChecks:  nil,
+			}
+		}
+	}
+	// Then loop by pipelinetask name over all the TaskRuns associated to Conditions
+	for pipelineTaskName, actualConditionTaskRuns := range conditionTaskRuns {
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:986]: @afrittoli `pr.Status.TaskRuns` holds an entry for the `pipelineTask` associated to a condition (could be more than one condition as well) with nil `TaskRunStatus` and one or more checks under `ConditionChecks` as in `pr.Status.TaskRuns[PipelineTaskRunName].ConditionChecks`.

Condition containers are always under `ConditionChecks` and not part of the map pr.Status.TaskRuns.

For example, for a pipelineTask with two conditions, `conditionTaskRuns` contains two containers, one for each condition and after these condition containers are created, this query returns them as valid taskRuns associated with the current pipeline: 
```c.taskRunLister.TaskRuns(pr.Namespace).List(labels.SelectorFromSet(pipelineRunLabels))```

so in the looping over those tasks, as they are conditionalChecks, line 974 is not executed and assumes the pipelineTask was not found in line 987 and creates a new taskRun name.

Hope its making sense 😉 

After the first iteration, 

PipelineRunTaskRunStatus holds map of

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 4 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun.go]: done

File: pkg/reconciler/pipelinerun/pipelinerun.go (hunk 9 above)
Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun.go:986]: Thank you so much for looking into this!

L974 is designed explicitly to only track `TaskRun` not associated to conditions, but I agree the logic is broken there. It works fine in case of orphaned conditions, but it doesn't in case of non-orphaned ones.

If the conditions are created and still running, there will be `TaskRun`s for them in the list, they can be identified as condition ones from the labels. The main `TaskRun` does not exists yet, however its name, under normal conditions, will already be in the `PipelineRun` status so that it may contain the status of the conditions:

```
taskrun-name (not yet created)
    PipelineTaskName: pipelineTaskName,
    Status:                    nil,
    ConditionChecks:  [array of condition checks],
```

Since my loops are based on what I get from the `TaskRun` list, I do not discover the existing `TaskRunName` with no real `TaskRun` under which conditions are hosted. I create a new one, and I end up having two `TaskRuns` with the same conditions - I think.

I will work on fixing this. I now separated my function in two parts, one which doesn't need the controller and takes the list of taskruns as input, so that it should be easier to write extra tests.

Comment (afrittoli) [reply pkg/reconciler/pipelinerun/pipelinerun.go:1000]: I fixed the issue now by initializing `taskRunByPipelineTask` from the known PR status, and adding to it as orphaned `TaskRuns` are recovered.
I added much more test coverage, hopefully it will work ok this time.

**Comment by afrittoli** [comment]
@pritidesai @bobcatfish this should be ready now - CI is green and test coverage much improved now.

**Comment by pritidesai** [comment]
sorry @afrittoli havent got chance to review it, its in my todo list for tomorrow :)

**Comment by pritidesai** [comment]
thanks @afrittoli 
/lgtm
