### PR TITLE
string results that can be parsed as json should not fail

### LINKED ISSUE #5803: result value type is not same as defined
# Expected Behavior
When defining the result type as string, the result value should be a string no matter what data it contains.
# Actual Behavior
If the string data is JSON then the result type will be recognized as object and cause pipelineRun to fail.

# Steps to Reproduce the Problem

1. Deploy pipeline with the latest commit
2. Apply task pipeline and pipelineRun to cluster
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: wrong-type-result-pipeline
spec:
  tasks:
    - name: wrongtype
      taskRef:
        name: wrong-type-task
  results:
    - name: string0
      value: $(tasks.wrongtype.results.string0)
      type: string
    - name: string1
      value: $(tasks.wrongtype.results.string1)
      type: string
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: wrong-type-task
spec:
  results:
    - name: string0
      type: string
    - name: string1
      type: string
  steps:
    - name: add
      image: alpine:latest
      script: |
        #!/bin/sh
        echo -n '{"key": "value"}' | tee $(results.string0.path);
        echo -n "key:value" | tee $(results.string1.path)
        # echo -n "key:value" | tee $(results.string0.path);
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: wrong-type-result-pipeline-
spec:
  pipelineRef:
    name: wrong-type-result-pipeline
```
3. Check the result
image

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.19.1
Pipeline version: devel
Dashboard version: v0.30.0
```
Deploy with latest commit b3e4f35712f on branch main

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes

This commit fixes #5803. In tep75&76 we introduced object results. The object results is inferred from the emitted message, and if the message is of json format, then the result type could be object or array. We later validate the type with the type we defined in taskspec. So if the taskpec type is string it will fail validation. Based on the discussions in #5803, if the type in taskpec is string, we should keep the results as is and don't convert it to object or array.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Task can emit string type results that can be parsed as json.  
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow

File: pkg/pod/status.go [hunk 1]
```diff
@@ -170,7 +170,15 @@ func setTaskRunStatusBasedOnStepStatus(logger *zap.SugaredLogger, stepStatuses [
 					logger.Errorf("error extracting the exit code of step %q in taskrun %q: %v", s.Name, tr.Name, err)
 					merr = multierror.Append(merr, err)
 				}
-				taskResults, pipelineResourceResults, filteredResults := filterResultsAndResources(results)
+				// collect results from taskspec
+				specResults := []v1beta1.TaskResult{}
+				if tr.Spec.TaskSpec != nil {
+					specResults = append(specResults, tr.Spec.TaskSpec.Results...)
```
Comment (chitrangpatel) [inline pkg/pod/status.go:176]: Just wondering if this works if `tr.Spec.TaskSpec.Results` is nil?

File: pkg/pod/status.go [hunk 2]
```diff
@@ -170,7 +170,15 @@ func setTaskRunStatusBasedOnStepStatus(logger *zap.SugaredLogger, stepStatuses [
...
+				}
+				if ts != nil {
+					specResults = append(specResults, ts.Results...)
```
Comment (chitrangpatel) [inline pkg/pod/status.go:179]: same point as above here.

Comment (chitrangpatel) [reply pkg/pod/status.go:179]: just thinking if you also need `&& ts.Results != nil` in the if condition.

File: pkg/pod/status.go (hunk 1 above)
Comment (Yongxuanzhang) [reply pkg/pod/status.go:176]: yes, tr.Spec.TaskSpec.Results is a list, so if it is an empty list it should be fine.

File: pkg/pod/status.go (hunk 2 above)
Comment (Yongxuanzhang) [reply pkg/pod/status.go:179]: ts.Results is also a list, so it should be fine if we have an empty list

File: pkg/pod/status.go (hunk 1 above)
Comment (chitrangpatel) [reply pkg/pod/status.go:176]: SGTM!

File: pkg/pod/status.go (hunk 2 above)
Comment (chitrangpatel) [reply pkg/pod/status.go:179]: SGTM!

**Review by chitrangpatel — APPROVED** [review]

**Comment by Yongxuanzhang** [comment]
@chuangw6 sorry I forgot to cc you. please take a look

File: pkg/pod/status.go [hunk 3]
```diff
@@ -224,22 +232,36 @@ func createMessageFromResults(results []v1beta1.PipelineResourceResult) (string,
...
+				v := v1beta1.ResultValue{}
+				err := v.UnmarshalJSON([]byte(r.Value))
+				if err != nil {
+					continue
+				}
+				taskRunResult = v1beta1.TaskRunResult{
+					Name:  r.Key,
+					Type:  v1beta1.ResultsType(v.Type),
+					Value: v,
+				}
```
Comment (chuangw6) [inline pkg/pod/status.go:264]: It's interesting to see that UnmarshalJSON never returns an error. For example, if one writes an invalid json string to an object result, UnmarshalJSON will not return error, and instead set the result type to string, and return nil. This will cause the task run to fail because of `missmatched Types for these results` - declared is object but the taskrun  parses as string.

The following taskrun is an example. We do need to return some error and fail the taskrun, but I am curious if the `missmatch` error is desired/appropriate, or we should handle this case differently.
```yaml
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: obj-result
spec:
  taskSpec:
    results:
      - name: echo-output
        type: object
        properties:
          key: {}
    steps:
      - name: write-invalid-object
        image: bash
        script: |
          set -e
          echo -n '{"key": "value"' | tee $(results.echo-output.path)
```

**Review by chuangw6 — COMMENTED** [review]
Thanks @Yongxuanzhang !!

File: pkg/pod/status.go (hunk 3 above)
Comment (Yongxuanzhang) [reply pkg/pod/status.go:264]: yes very good point!
I think the previous problem is that we we do UnmarshalJSON we don't know what the type we want to Unmarshal to, so if it is an invalid json, it should work if the expected type is string (no error return).

But I think we may improve this, since in this PR we pass the results type to this function. And we may use the type to guide the UnmarshalJSON

File: pkg/pod/status.go [hunk 4]
```diff
@@ -224,22 +232,36 @@ func createMessageFromResults(results []v1beta1.PipelineResourceResult) (string,
 	return string(bytes), nil
 }
 
-func filterResultsAndResources(results []v1beta1.PipelineResourceResult) ([]v1beta1.TaskRunResult, []v1beta1.PipelineResourceResult, []v1beta1.PipelineResourceResult) {
+func filterResultsAndResources(results []v1beta1.PipelineResourceResult, specResults []v1beta1.TaskResult) ([]v1beta1.TaskRunResult, []v1beta1.PipelineResourceResult, []v1beta1.PipelineResourceResult) {
 	var taskResults []v1beta1.TaskRunResult
 	var pipelineResourceResults []v1beta1.PipelineResourceResult
 	var filteredResults []v1beta1.PipelineResourceResult
+	neededTypes := make(map[string]string)
```
Comment (afrittoli) [inline pkg/pod/status.go:239]: NIT: I guess this could be `map[string]v1beta1.ResultsTypeString`

**Review by afrittoli — COMMENTED** [review]
Thank you for this.
A small nit but nothing blocking.
Would you mind updating the release notes to include what changes as opposed to what should be.
/approve

**Comment by zhouhaibing089** [comment]
Thanks for fixing this. This is a blocker for us to upgrade to the latest release.

I wonder whether it makes sense to add notes to the released version (since the validation was added) with additional description like **Known Issues**.

```
Task can't emit string type results that can be parsed as json 
```

**Comment by Yongxuanzhang** [comment]
> Thanks for fixing this. This is a blocker for us to upgrade to the latest release.
> 
> I wonder whether it makes sense to add notes to the released version (since the validation was added) with additional description like **Known Issues**.
> 
> ```
> Task can't emit string type results that can be parsed as json 
> ```

Sure. @zhouhaibing089  What did you mean by adding notes to the released version?

**Comment by Yongxuanzhang** [comment]
@jerop Can we merge this into v0.43 btw? Thanks!

File: pkg/pod/status.go [hunk 5]
```diff
@@ -152,10 +152,19 @@ func MakeTaskRunStatus(ctx context.Context, logger *zap.SugaredLogger, tr v1beta
 	return *trs, merr.ErrorOrNil()
 }
 
-func setTaskRunStatusBasedOnStepStatus(ctx context.Context, logger *zap.SugaredLogger, stepStatuses []corev1.ContainerStatus, tr *v1beta1.TaskRun, podPhase corev1.PodPhase, kubeclient kubernetes.Interface) *multierror.Error {
+func setTaskRunStatusBasedOnStepStatus(ctx context.Context, logger *zap.SugaredLogger, stepStatuses []corev1.ContainerStatus, tr *v1beta1.TaskRun, podPhase corev1.PodPhase, kubeclient kubernetes.Interface, ts *v1beta1.TaskSpec) *multierror.Error {
 	trs := &tr.Status
 	var merr *multierror.Error
 
+	// collect results from taskrun spec and taskspec
+	specResults := []v1beta1.TaskResult{}
```
Comment (bendory) [inline pkg/pod/status.go:160]: maybe shorted to just `results`?

File: pkg/pod/status.go [hunk 6]
```diff
@@ -245,22 +256,35 @@ func createMessageFromResults(results []v1beta1.PipelineResourceResult) (string,
 	return string(bytes), nil
 }
 
-func filterResultsAndResources(results []v1beta1.PipelineResourceResult) ([]v1beta1.TaskRunResult, []v1beta1.PipelineResourceResult, []v1beta1.PipelineResourceResult) {
+func filterResultsAndResources(results []v1beta1.PipelineResourceResult, specResults []v1beta1.TaskResult) ([]v1beta1.TaskRunResult, []v1beta1.PipelineResourceResult, []v1beta1.PipelineResourceResult) {
```
Comment (bendory) [inline pkg/pod/status.go:259]: suggest `taskResults` b/c that's what it actually is?

File: pkg/pod/status.go [hunk 7]
```diff
@@ -245,22 +256,35 @@ func createMessageFromResults(results []v1beta1.PipelineResourceResult) (string,
...
+			taskRunResult := v1beta1.TaskRunResult{}
+			if neededTypes[r.Key] == v1beta1.ResultsTypeString {
+				taskRunResult = v1beta1.TaskRunResult{
+					Name:  r.Key,
+					Type:  v1beta1.ResultsTypeString,
+					Value: *v1beta1.NewStructuredValues(r.Value),
+				}
+			} else {
+				v := v1beta1.ResultValue{}
+				err := v.UnmarshalJSON([]byte(r.Value))
```
Comment (bendory) [inline pkg/pod/status.go:279]:
```suggestion
			if err := v.UnmarshalJSON([]byte(r.Value)); err != nil {
			    continue
			}
```

Comment (bendory) [reply pkg/pod/status.go:279]: See Go style guide: https://go.dev/doc/effective_go#control-structures

File: pkg/pod/status.go (hunk 6 above)
Comment (Yongxuanzhang) [reply pkg/pod/status.go:259]: realized that taskResults is used for TaskRunResult
