### PR TITLE
Merge steps and containerTemplate during Task validation

### LINKED ISSUE #824: Task validation ignores containerTemplate
When validating a Task before creation, it should take the attributes from `containerTemplate` into account. Defining an `image` attribute on `containerTemplate` but not on the `steps` should pass the validation but right now fails with:

```
Error from server (InternalError): error when creating "tasks/buildah-task.yml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: missing field(s): steps.Image
```

Example task:
```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildah
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
    params:
    - name: dockerfile
      description: The path to the dockerfile to build
      default: ./Dockerfile
    - name: verifyTLS
      description: Verify registry certificates
      default: "true"
  outputs:
    resources:
    - name: image
      type: image
  containerTemplate:
    image: quay.io/openshift-pipeline/buildah:testing
    command:
      - buildah
    volumeMounts:
    - name: libcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  steps:
  - name: build
    args: 
      - bud
      - --layers
      - --tls-verify=${inputs.params.verifyTLS}
      - -f
      - ${inputs.params.dockerfile}
      - -t
      - ${outputs.resources.image.url}
      - .
  - name: push
    args: 
      - push
      - --tls-verify=${inputs.params.verifyTLS}
      - ${outputs.resources.image.url}
  volumes:
    - name: libcontainers
      emptyDir: {}
```

### PR DESCRIPTION
**Pull request by abayer**
# Changes

We actually care about what the Task steps will look like *after*
they've been merged with the containerTemplate, if it exists, so we
should be merging them together in validation, not just in runtime.

fixes #824 

/assign @vdemeester 
/assign @bobcatfish 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

n/a

### CODE REVIEW

File: pkg/apis/pipeline/v1alpha1/task_validation.go [hunk 1]
```diff
@@ -19,6 +19,7 @@ package v1alpha1
 import (
 	"context"
 	"fmt"
+	"github.com/tektoncd/pipeline/pkg/merge"
```
Comment (vdemeester) [inline pkg/apis/pipeline/v1alpha1/task_validation.go]: nit: wrong place for the commit

Comment (abayer) [reply pkg/apis/pipeline/v1alpha1/task_validation.go]: stupid IDE!
