### PR TITLE
param validation - execution status variable

### LINKED ISSUE #3681: context variables validation - $(tasks.dagtask.status)
Context variable to access execution status is supported as a param value without any other params or extra string. This validation is missing from the PR #3390 that it implemented this feature. PR #3390 has documented the guidelines in [pipelines.md](https://github.com/tektoncd/pipeline/pull/3390/files#diff-778db8afe943ee8b2b7f3acf5ec1eb68d7bf0c926a1ddb46866125d1a4c0ce7fR857):

```
`$(tasks.<pipelineTask>.status)` is instantiated and available at runtime and must be used as a param value
as is without concatenating it with any other param or string, for example, this kind of usage is not validated/supported
`task status is $(tasks.<pipelineTask>.status)`. 

Use it as a param value:
     params:
        - name: task1Status
          value: "$(tasks.task1.status)"
```

First, lets evaluate whether we should enforce this restriction, i.e. `$(tasks.dagtask.status)` can not be used with any other param or concatenated with other string.

To apply such enforcement, add validation for:

1. A dag task with a param value set to `$(tasks.dagtask.status)` with or without any other param or string is prohibited (part of this validation is implemented in PR #3390 which includes validating dag task with param value set to `$(tasks.dagtask.status)` without any extra concatenation).
2. A finally task with param value referring  to `$(tasks.dagtask.status)` must not have any other params or string around it.

PR #3390 has implemented validating existence of `dagtask` in `$(tasks.dagtask.status)`.  This issue only focuses on validation (1) and (2).

### LINKED ISSUE #3692: v0.20.0: PipelineRun validation failed when task result name is "status"
# Expected Behavior

I'm able to use task result name "status".

# Actual Behavior

Executing PipelineRun with task result name "status" causing validation error:
```
for: "pipelinerun-results-with-params.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: pipeline tasks can not refer to execution status of any other pipeline task: spec.pipelinespec.tasks[1].params[arg].value
```

# Steps to Reproduce the Problem

pipelinerun-results-with-params.yaml:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-case
  name: test-case-run
spec:
  params:
  - name: prefix
    value: prefix
  pipelineSpec:
    params:
    - name: prefix
    tasks:
    - name: generate-suffix
      taskSpec:
        results:
        - name: status
        steps:
        - name: generate-suffix
          image: alpine
          script: |
            echo -n "suffix" > $(results.status.path)
    - name: do-something
      taskSpec:
        params:
        - name: arg
        steps:
        - name: do-something
          image: alpine
          script: |
            echo "$(params.arg)" | grep "prefix:suffix"
      params:
      - name: arg
        value: "$(params.prefix):$(tasks.generate-suffix.results.status)"
```
```
$ kubectl apply -f pipelinerun-results-with-params.yaml
Error from server (BadRequest): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"tekton.dev/v1beta1\",\"kind\":\"PipelineRun\",\"metadata\":{\"annotations\":{},\"generateName\":\"test-case\",\"name\":\"test-case-run\",\"namespace\":\"tekton-execution\"},\"spec\":{\"params\":[{\"name\":\"prefix\",\"value\":\"prefix\"}],\"pipelineSpec\":{\"params\":[{\"name\":\"prefix\"}],\"tasks\":[{\"name\":\"generate-suffix\",\"taskSpec\":{\"results\":[{\"name\":\"status\"}],\"steps\":[{\"image\":\"alpine\",\"name\":\"generate-suffix\",\"script\":\"echo -n \\\"suffix\\\" \\u003e $(results.status.path)\\n\"}]}},{\"name\":\"do-something\",\"params\":[{\"name\":\"arg\",\"value\":\"$(params.prefix):$(tasks.generate-suffix.results.status)\"}],\"taskSpec\":{\"params\":[{\"name\":\"arg\"}],\"steps\":[{\"image\":\"alpine\",\"name\":\"do-something\",\"script\":\"echo \\\"$(params.arg)\\\" | grep \\\"prefix:suffix\\\"\\n\"}]}}]}}}\n"}},"spec":{"pipelineSpec":{"params":[{"name":"prefix"}],"tasks":[{"name":"generate-suffix","taskSpec":{"results":[{"name":"status"}],"steps":[{"image":"alpine","name":"generate-suffix","script":"echo -n \"suffix\" \u003e $(results.status.path)\n"}]}},{"name":"do-something","params":[{"name":"arg","value":"$(params.prefix):$(tasks.generate-suffix.results.status)"}],"taskSpec":{"params":[{"name":"arg"}],"steps":[{"image":"alpine","name":"do-something","script":"echo \"$(params.arg)\" | grep \"prefix:suffix\"\n"}]}}]}}}
to:
Resource: "tekton.dev/v1beta1, Resource=pipelineruns", GroupVersionKind: "tekton.dev/v1beta1, Kind=PipelineRun"
Name: "test-case-run", Namespace: "tekton-execution"
for: "pipelinerun-results-with-params.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: pipeline tasks can not refer to execution status of any other pipeline task: spec.pipelinespec.tasks[1].params[arg].value
```

It works fine in tekton v0.19.0.

# Additional Info

It works fine in tekton v0.19.0.

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.15.0
Pipeline version: v0.20.0
Triggers version: v0.10.0
```

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Adding param validation while accessing execution status along with any other param or extra string. Updated pipelines documenting the limitation.

Also, avoiding task results validation as it follows very similar pattern with `$(tasks.taskname.results.status)` where
"status" being the result of some task.

Closes #3681 
Closes #3692 

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by sbwsg** [comment]
Might be worth adding a unit test to check that variables of form `$(tasks.foo.results.status)` are considered valid, to cover the case presented in https://github.com/tektoncd/pipeline/issues/3692

**Comment by pritidesai** [comment]
> $(tasks.foo.results.status)

Thanks @sbwsg I have added such unit test.

@afrittoli, this PR will needs cherry picking into `0.20` 🙏

**Review by sbwsg — APPROVED** [review]

**Comment by GregDritschler** [comment]
looks good to me

File: pkg/apis/pipeline/v1beta1/pipeline_validation.go [hunk 1]
```diff
@@ -291,40 +291,68 @@ func validatePipelineContextVariables(tasks []PipelineTask) *apis.FieldError {
...
+					}
+				}
+			}
 		}
 	}
 	return errs
 }
 
+func validateExecutionStatusVariables(tasks []PipelineTask, finallyTasks []PipelineTask) (errs *apis.FieldError) {
+	errs = errs.Also(validateExecutionStatusVariablesInTasks(tasks))
```
Comment (souleb) [inline pkg/apis/pipeline/v1beta1/pipeline_validation.go:351]: Isn't it better to only have the tasks range loop in only one function? I see it is used in validateExecutionStatusVariablesInTasks and validateExecutionStatusVariablesInFinally. Could be one loop and passing params ref.

File: pkg/apis/pipeline/v1beta1/pipeline_validation.go [hunk 2]
```diff
@@ -291,40 +291,68 @@ func validatePipelineContextVariables(tasks []PipelineTask) *apis.FieldError {
...
+				// validate tasks.pipelineTask.status if this expression is not a result reference
+				if !LooksLikeContainsResultRefs(ps) {
+					for _, p := range ps {
+						// check for a prefix and suffix
+						if strings.HasPrefix(p, "tasks.") && strings.HasSuffix(p, ".status") {
+							pt := strings.TrimSuffix(strings.TrimPrefix(p, "tasks."), ".status")
+							// report an error if the task name does not exist in the list of dag tasks
+							if !pipelineRunTasksContextNames.Has(pt) {
+								errs = errs.Also(apis.ErrInvalidValue(fmt.Sprintf("pipeline task %s is not defined in the pipeline", pt),
+									"value").ViaFieldKey("params", param.Name).ViaFieldIndex("finally", idx))
```
Comment (souleb) [inline pkg/apis/pipeline/v1beta1/pipeline_validation.go:339]: can be in a helper func as it is re-used

Comment (pritidesai) [reply pkg/apis/pipeline/v1beta1/pipeline_validation.go]: yup definitely, created a helper function.

File: pkg/apis/pipeline/v1beta1/pipeline_validation.go (hunk 1 above)
Comment (pritidesai) [reply pkg/apis/pipeline/v1beta1/pipeline_validation.go:355]: we want to have receiver functions for such functionalities, created one for retrieving pipeline task names.

**Review by vdemeester — COMMENTED** [review]
/lgtm
