### PR TITLE
fix(taskrun): emit warning for missing secret in ServiceAccount instead of failing

### LINKED ISSUE #7760: TaskRun Fails to Create Pod When ServiceAccount References Non-Existent Secret
# Expected Behavior

When repairing a ServiceAccount that includes a reference to a non-existent secret, I expect the TaskRun to issue a warning and proceed with the creation of the Pod, similar to Kubernetes’ behavior of handling missing imagePullSecrets within a Pod’s service account configuration.

[Log a warning if a ImagePullSecrets does not exist](https://github.com/kubernetes/kubernetes/pull/117927/files)

# Actual Behavior

Currently, if a ServiceAccount is referenced by a TaskRun and contains a non-existent secret, the TaskRun fails to create the associated Pod and results in an error.

# Steps to Reproduce the Problem

1. Execute the following script:
```
kubectl apply -f - <<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskrun-sa
secrets:
- name: not-exist
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: test-sa-has-not-found-secret
spec:
  serviceAccountName: taskrun-sa
  taskSpec:
    description: |
      A simple task that prints the date.
    steps:
      - name: echo
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "Hello, world!"
status:
  conditions:
  - message: 'failed to create task run pod "test-sa-has-not-found-secret": translating
      TaskSpec to Pod: secrets "not-exist" not found. Maybe invalid TaskSpec'
    reason: PodCreationFailed
    status: "False"
    type: Succeeded
EOF

```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.35.1
Pipeline version: v0.57.0
```

### PR DESCRIPTION
**Pull request by l-qing**
fix #7760

Log a warning if a Secrets in service account does not exist

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
fix(taskrun): emit warning for missing secret in ServiceAccount instead of failing
```

/kind bug

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/ok-to-test

File: pkg/pod/creds_init.go [hunk 1]
```diff
@@ -51,7 +56,8 @@ var dnsLabel1123Forbidden = regexp.MustCompile("[^a-zA-Z0-9-]+")
 // Any errors encountered during this process are returned to the
 // caller. If no matching annotated secrets are found, nil lists with a
 // nil error are returned.
-func credsInit(ctx context.Context, serviceAccountName, namespace string, kubeclient kubernetes.Interface) ([]string, []corev1.Volume, []corev1.VolumeMount, error) {
+func credsInit(ctx context.Context, obj runtime.Object, serviceAccountName, namespace string, kubeclient kubernetes.Interface) ([]string, []corev1.Volume, []corev1.VolumeMount, error) {
```
Comment (afrittoli) [inline pkg/pod/creds_init.go:59]: The `serviceAccountName` could not be obtained from the `runtime.Object` by casting it to a task, but this approach keeps the code simpler the che change smaller, so I'm fine with it.

**Review by afrittoli — COMMENTED** [review]
/approve
