### PR TITLE
fix: Populate step statuses before TaskRun timeout handling

### LINKED ISSUE #731: TestTaskRunTimeout is flakey : fix timeouts
# Expected Behavior

`TestTaskRunTimeout` should pass all the time :100: 

# Actual Behavior

`TestTaskRunTimeout` is failing a lot. I'll skip it so that 

Here are some examples of failures:
* From https://github.com/tektoncd/pipeline/pull/713:
  * https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/713/pull-tekton-pipeline-integration-tests/1113345177981816832/
  * https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/713/pull-tekton-pipeline-integration-tests/1113137811692720130/
  * https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/713/pull-tekton-pipeline-integration-tests/1113331336749256704/
* From https://github.com/tektoncd/pipeline/pull/711:
  * https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/711/pull-tekton-pipeline-integration-tests/1113053757723119616/
* From https://github.com/tektoncd/pipeline/pull/691:
  * https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/691/pull-tekton-pipeline-integration-tests/1116632841082376194/

# Steps to Reproduce the Problem

1. Open a PR
2. See it fail :hankey: 
3. Run `/retest` and :pray: 

I'm working on it in https://github.com/tektoncd/pipeline/pull/691 but it's at a point where it makes a lot of build fail, and I'm really thinking of marking the test as skip and track the re-enablement of it here

cc @bobcatfish 

/kind bug
/assign

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This prevent some race condition where timeout fires before pod status
fetch. TestTaskRunTimeout validates that steps are terminated, but it
can be not populated from time to time (in my test 4/5 times out of 25).

Fixes #731
This should reduce *a lot* flakes on timeout tests.

I am not sure if we need a release note or not. It does fix a bug though.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Fix a race condition on timeout that would result in a TaskRun status without steps statuses.
```

### CODE REVIEW

**Comment by vdemeester** [comment]
cc @tektoncd/core-maintainers

**Comment by vdemeester** [comment]
I wonder if there is other issues related to this in the issue tracker 🤔

File: pkg/reconciler/taskrun/taskrun_test.go [hunk 1]
```diff
@@ -1345,6 +1345,9 @@ spec:
     name: test-task
 status:
   podName: the-pod
+  taskSpec:
+    steps:
+    - image: foo
 `)
```
Comment (afrittoli) [inline pkg/reconciler/taskrun/taskrun_test.go:1351]: Do you think it may be possible to write a test that would trigger the previous race condition to verify that it's fixed?

Comment (vdemeester) [reply pkg/reconciler/taskrun/taskrun_test.go:1351]: I can try 😛

Comment (vdemeester) [reply pkg/reconciler/taskrun/taskrun_test.go:1351]: https://github.com/tektoncd/pipeline/pull/9184/files#diff-4ea88af6550888502f0643b753b9fb1fe2db224c00be6365053858ad7970fdf9R44

**Review by afrittoli — COMMENTED** [review]
/approve

**Comment by twoGiants** [comment]
Examples are failing.

/retest
