### PR TITLE
avoid requeuing taskrun in case of permanent error

### LINKED ISSUE #3045: Error count "failed" taskrun for metric of Prometheus
# Expected Behavior
Count correct the number
# Actual Behavior
Incorrect
# Steps to Reproduce the Problem
Create a `taskrun` which cannot find `task` refer to.
check the `tekton_taskrun_count{status="failed"}`

# Additional Info
When such exception happened, 
https://github.com/tektoncd/pipeline/blob/c1852961039d0cd05def5e05cb1d180db8a72344/pkg/reconciler/taskrun/taskrun.go#L240-L245
a `PermanentError` was raised, the `knative/pkg` will `forget` the `taskrun` from `workqueue`, I guess that we expected.
but we also update the `.status`, that's will enqueue another `taskrun` object (same but with different .status), and it will enter :
https://github.com/tektoncd/pipeline/blob/c1852961039d0cd05def5e05cb1d180db8a72344/pkg/reconciler/taskrun/taskrun.go#L109-L110
directly, then count as `tekton_taskrun_count{status="failed"}` if any error in this section (`if tr.IsDone()`), a normal error will be raised, that's means the `taskrun` will re-enqueue again and again based on implements of this:
https://github.com/kubernetes/client-go/blob/00dbcca6ee44c678754d3f5fda1bd0e704b26fe2/util/workqueue/default_rate_limiters.go#L89

A candidate solution is wrapper all error in this section as `PermanentError` to let workqueue forget it.

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

When a taskrun is rejected with permanent error, reconciler should not requeue that taskrun.

After a permanent error is raised in [prepare](https://github.com/tektoncd/pipeline/blob/3a7a693429c605a67e30efa5b74675e403be79bb/pkg/reconciler/taskrun/taskrun.go#L233) function call, reconciler enters the [tr.IsDone](https://github.com/tektoncd/pipeline/blob/3a7a693429c605a67e30efa5b74675e403be79bb/pkg/reconciler/taskrun/taskrun.go#L109) block. In this block, sidecars were being terminated without any check on pod name. The rejected `taskrun` has no pod name associated with it since pod was never created. Reconciler fails to run this [Get](https://github.com/tektoncd/pipeline/blob/3a7a693429c605a67e30efa5b74675e403be79bb/pkg/reconciler/taskrun/taskrun.go#L124) command and returns a normal error. Next reconciler cycle runs with this normal error instead of permanent error and tries to requeue the `taskrun` until reconciler exhausts the allowed retries.

These changes are introduced to add a check if pod was created for a taskrun before cleaning up the sidecars.

Most of the changes in this PR are implemented based on the `pipelinerun.go`.

I have recorded [logs](https://gist.github.com/pritidesai/ca789848187184717ba920fea7ea7e02) for the following `taskrun` on master and with this PR so that its easy to compare.

**Note** that the [reconciler](https://gist.github.com/pritidesai/ca789848187184717ba920fea7ea7e02#gistcomment-3408809) exhausts the number of retries for the following `TaskRun` even though its declared failure with permanent error. After introducing these changes, the [reconciler](https://gist.github.com/pritidesai/ca789848187184717ba920fea7ea7e02#gistcomment-3408811) exits after seeing the permanent error and does not requeue that `TaskRun`. 

```
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-failure
spec:
  taskRef:
    name: does-not-exist
```

Closes #3045 
/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Do not requeue taskrun if it was rejected with permanent error. This bug was causing the incorrect metrics for tekton_taskrun_count{status="failed"}. 
```

### CODE REVIEW

**Comment by pritidesai** [comment]
Its ready for review, PTAL 🙏

**Review by sbwsg — APPROVED** [review]

**Comment by jerop** [comment]
thank you @pritidesai! 

/lgtm

**Comment by afrittoli** [comment]
Sorry about the hold @pritidesai I just wanted to clarify one bit as I was reviewing this PR.

File: pkg/reconciler/taskrun/taskrun.go [hunk 1]
```diff
@@ -108,54 +110,44 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, tr *v1beta1.TaskRun) pkg
...
+		// We may be reading a version of the object that was stored at an older version
+		// and may not have had all of the assumed default specified.
+		tr.SetDefaults(contexts.WithUpgradeViaDefaulting(ctx))
+
 		// Try to send cloud events first
 		cloudEventErr := cloudevent.SendCloudEvents(tr, c.cloudEventClient, logger)
 		// Regardless of `err`, we must write back any status update that may have
 		// been generated by `sendCloudEvents`
-		_, updateErr := c.updateLabelsAndAnnotations(ctx, tr)
-		merr = multierror.Append(cloudEventErr, updateErr)
```
Comment (afrittoli) [inline pkg/reconciler/taskrun/taskrun.go:117]: I was confused by the removal of this one, but I think it may not be needed indeed?
It's not clear to me how this change is related to this PR though

Comment (afrittoli) [reply pkg/reconciler/taskrun/taskrun.go:117]: never mind, I was confusing myself

**Comment by afrittoli** [comment]
Sorry about the confusion 🙏 I was in the middle of reviewing and I though I saw an issue but I was wrong.
Thanks for this!!

**Comment by pritidesai** [comment]
no worries @afrittoli, thanks a bunch for the review @sbwsg @afrittoli @jerop 🙏
