### PR TITLE
fix: avoid fan out matrix task failed due to result ref

### LINKED ISSUE #8324: InvalidTaskResultsReference when dynamically generating subsequent tasks in a pipeline using matrix
# Expected Behavior
Pipeline runs and taskruns from all 3 tasks are generated.
# Actual Behavior
PipelineRun fails with `'invalid result reference in pipeline task "printer": unable to validate result referencing pipeline task "platforms": task spec not found'`
# Steps to Reproduce the Problem

Run a pipeline with 3 tasks:
- first task generates an array type result
- second task references the array type result generated from the first task to dynamically generate taskruns using matrix. Each of these runs then sets a string type result
- third task references the aggregated results of taskruns from the second task to dynamically fan out tasks once again using matrix, as described in the documentation [here](https://tekton.dev/docs/pipelines/matrix/#results-from-fanned-out-matrixed-pipelinetasks). This will fail with the following error: `'invalid result reference in pipeline task "printer": unable to validate result referencing pipeline task "platforms": task spec not found'`

```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: array-emitter
spec:
  results:
  - name: array
    type: array
  steps:
    - name: echo
      image: mirror.gcr.io/alpine
      script: |
        echo -n "[\"linux\",\"max\",\"windows\"]" > $(results.array.path)
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: platform-browsers
spec:
  params:
    - name: platform
    - name: testmatrixed
  results:
  - name: str
    type: string
  steps:
    - name: echo
      image: mirror.gcr.io/alpine
      script: |
        echo "$(params.platform)"
        echo -n "PARAM" > $(results.str.path)
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: printer
spec:
  params:
    - name: test
  steps:
    - name: echo
      image: mirror.gcr.io/alpine
      script: |
        echo $(params.test)
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: matrixed-pr
spec:
  taskRunTemplate:
    serviceAccountName: "default"
  pipelineSpec:
    tasks:

    - name: array-emitter
      taskRef:
        name: array-emitter

    - name: platforms
      params:
        - name: test
          value: test
      matrix:
        params:
          - name: platform
            value: $(tasks.array-emitter.results.array[*])
      taskRef:
        name: platform-browsers

    - name: printer
      taskRef:
        name: printer
      matrix:
        params:
          - name: platform
            value: $(tasks.platforms.results.str[*])
```
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.1

```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.64.0
```

### PR DESCRIPTION
**Pull request by l-qing**
fix #8324
Continuing development based on this PR: https://github.com/tektoncd/pipeline/pull/8327

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
fix: avoid fan out matrix task failed due to result ref
```

/kind bug

### 1. Reproducible steps
```shell
$ kubectl version

Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.28.8

$ tkn version

Client version: 0.39.0
Pipeline version: v0.66.0
```

```shell
cat <<'EOF' | kubectl replace -f -
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: array-emitter
spec:
  results:
  - name: array
    type: array
  steps:
    - name: echo
      image: mirror.gcr.io/alpine
      script: |
        echo -n "[\"linux\",\"max\",\"windows\"]" > $(results.array.path)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: platform-browsers
spec:
  params:
    - name: platform
  results:
  - name: str
    type: string
  steps:
    - name: echo
      image: mirror.gcr.io/alpine
      script: |
        echo -n "$(params.platform)" | tee $(results.str.path)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: printer
spec:
  params:
    - name: platform
      default: "default-platform"
    - name: platforms
      default: []
  steps:
    - name: echo
      image: mirror.gcr.io/alpine
      args:
        - "$(params.platforms)"
      script: |
        if [ -z "$(params.platform)" ]; then
          echo "platform: $(params.platform)"
        fi
        if [ $# -gt 0 ]; then
          echo "platforms: $@"
        fi

---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: matrixed-pr
spec:
  taskRunTemplate:
    serviceAccountName: "default"
  pipelineSpec:
    tasks:

    - name: array-emitter
      taskRef:
        name: array-emitter

    - name: platforms
      params:
        - name: test
          value: test
      matrix:
        params:
          - name: platform
            value: $(tasks.array-emitter.results.array[*])
      taskRef:
        name: platform-browsers

    - name: printer-matrix
      taskRef:
        name: printer
      matrix:
        params:
          - name: platform
            value: $(tasks.platforms.results.str[*])

    - name: printer-all-platforms
      taskRef:
        name: printer
      params:
        - name: platforms
          value: $(tasks.platforms.results.str[*])
EOF
```

### 2. Error message

`invalid result reference in pipeline task "printer-matrix": unable to validate result referencing pipeline task "platforms": task spec not found`

```yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  creationTimestamp: "2025-01-14T07:40:10Z"
  generation: 1
  name: matrixed-pr
  namespace: default
  resourceVersion: "26861"
  uid: feba93ac-759d-4817-8512-700eb8eef059
spec:
  pipelineSpec:
    tasks:
    - name: array-emitter
      taskRef:
        kind: Task
        name: array-emitter
    - matrix:
        params:
        - name: platform
          value: $(tasks.array-emitter.results.array[*])
      name: platforms
      params:
      - name: test
        value: test
      taskRef:
        kind: Task
        name: platform-browsers
    - matrix:
        params:
        - name: platform
          value: $(tasks.platforms.results.str[*])
      name: printer-matrix
      taskRef:
        kind: Task
        name: printer
    - name: printer-all-platforms
      params:
      - name: platforms
        value: $(tasks.platforms.results.str[*])
      taskRef:
        kind: Task
        name: printer
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
status:
  completionTime: "2025-01-14T07:40:12Z"
  conditions:
  - lastTransitionTime: "2025-01-14T07:40:12Z"
    message: 'invalid result reference in pipeline task "printer-matrix": unable to
      validate result referencing pipeline task "platforms": task spec not found'
    reason: InvalidTaskResultReference
    status: "False"
    type: Succeeded
  pipelineSpec:
    tasks:
    - name: array-emitter
      taskRef:
        kind: Task
        name: array-emitter
    - matrix:
        params:
        - name: platform
          value: $(tasks.array-emitter.results.array[*])
      name: platforms
      params:
      - name: test
        value: test
      taskRef:
        kind: Task
        name: platform-browsers
    - matrix:
        params:
        - name: platform
          value: $(tasks.platforms.results.str[*])
      name: printer-matrix
      taskRef:
        kind: Task
        name: printer
    - name: printer-all-platforms
      params:
      - name: platforms
        value: $(tasks.platforms.results.str[*])
      taskRef:
        kind: Task
        name: printer
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      Coschedule: workspaces
      DisableAffinityAssistant: false
      DisableCredsInit: false
      DisableInlineSpec: ""
      EnableAPIFields: beta
      EnableArtifacts: false
      EnableCELInWhenExpression: false
      EnableConciseResolverSyntax: false
      EnableKeepPodOnCancel: false
      EnableKubernetesSidecar: false
      EnableParamEnum: false
      EnableProvenanceInStatus: true
      EnableStepActions: false
      EnforceNonfalsifiability: none
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      SendCloudEventsForRuns: false
      SetSecurityContext: false
      VerificationNoMatchPolicy: ignore
  startTime: "2025-01-14T07:40:12Z"
```

##### a. `validateResultRef`: `unable to validate result referencing pipeline task`

`if ptMap[ref.PipelineTask].ResolvedTask == nil || ptMap[ref.PipelineTask].ResolvedTask.TaskSpec == nil {`

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/resources/validate_dependencies.go#L75-L77

##### b. `ValidatePipelineTaskResults`: `invalid result reference in pipeline task`

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/resources/validate_dependencies.go#L31-L36

##### c. `PipelineRun-Reconcile`: call `ValidatePipelineTaskResults`

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/pipelinerun.go#L697-L702

##### d. `pipelineRunFacts.State`: come from `resolvePipelineState`

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/pipelinerun.go#L612-L627

##### e. `resolvePipelineState`: resolvedTask - `ResolvePipelineTask`

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/pipelinerun.go#L368-L377

##### f. **`ResolvePipelineTask`**: call `CountCombinations`

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L602-L630

##### h1. `CountCombinations`: Calculate the number of TaskRuns

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/apis/pipeline/v1/matrix_types.go#L220-L242

##### h2. **Error**: The calculated count is 0.

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/apis/pipeline/v1/matrix_types.go#L233-L239

Because the `param.Value.StringVale` is `$(tasks.platforms.results.str[*])` and `param.Value.ArrayVal` is empty.

##### j1. `ResolvePipelineTask`: call `GetNamesOfTaskRuns`

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L628-L630

##### j2. `GetNamesOfTaskRuns`: call `getNewRunNames` the `numberOfRuns` is 0, the result `taskRunNames` is empty

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L749-L771

##### k. `ResolvePipelineTask`: `setTaskRunsAndResolvedTask` has not been called.

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L628-L632

##### l. `setTaskRunsAndResolvedTask`: `ResolvedTask` has not been set.

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L641-L662

### CODE REVIEW

File: pkg/apis/pipeline/v1/matrix_types_test.go [hunk 1]
```diff
@@ -782,7 +782,7 @@ func TestPipelineTask_CountCombinations(t *testing.T) {
 	}{{
 		name: "combinations count is zero",
 		matrix: &v1.Matrix{
-			Params: v1.Params{{}}},
+			Params: v1.Params{}},
```
Comment (l-qing) [inline pkg/apis/pipeline/v1/matrix_types_test.go:785]: The behavior is different between having no param and having a param with an empty value.

File: pkg/apis/pipeline/v1/matrix_types_test.go [hunk 2]
```diff
@@ -915,11 +915,20 @@ func TestPipelineTask_CountCombinations(t *testing.T) {
 				}},
 			}},
 		want: 7,
+	}, {
+		name: "matrix params with string value containing variable reference",
+		matrix: &v1.Matrix{
+			Params: v1.Params{{
+				Name: "GOARCH", Value: v1.ParamValue{ArrayVal: []string{"linux/amd64", "linux/ppc64le", "linux/s390x"}},
+			}, {
+				Name: "version", Value: v1.ParamValue{StringVal: "$(tasks.platforms.results.str[*])"}},
```
Comment (l-qing) [inline pkg/apis/pipeline/v1/matrix_types_test.go:924]: The problem to be solved this time involves referencing an array parameter within a string value.

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 3]
```diff
@@ -8942,8 +8942,14 @@ spec:
            script: |
              echo "$(params.platform)"
     - name: b-task
-      taskRef:
-        name: mytask
+      taskSpec:
```
Comment (l-qing) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:8945]: Avoid returning early due to the `PipelineRunReasonCouldntGetTask` error.

File: pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go [hunk 4]
```diff
@@ -3801,10 +3801,10 @@ func TestResolvePipelineRunTask_WithMatrix(t *testing.T) {
 		name: "task with matrix - whole array results",
 		pt:   pts[2],
 		want: &ResolvedPipelineTask{
-			TaskRunNames: nil,
+			TaskRunNames: []string{"pipelinerun-pipelinetask-with-whole-array-results"},
```
Comment (l-qing) [inline pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go:3804]: The current behavior will return a definition of TaskSpec, facilitating subsequent verification.

File: test/matrix_test.go [hunk 5]
```diff
@@ -157,6 +180,13 @@ spec:
            params:
             - name: GOARCH
               value: I-do-not-exist
+    - name: printer-matrix
+      taskRef:
+        name: printer
+      matrix:
+        params:
+          - name: platform
+            value: $(tasks.matrix-include.results.str[*])
```
Comment (l-qing) [inline test/matrix_test.go:189]: Added a usage that is supported this time.

**Comment by l-qing** [comment]
It seems that this usage might bypass the limitation of `DefaultMaxMatrixCombinationsCount`.

https://github.com/tektoncd/pipeline/blob/1dd488eda738a124e9dfe8874dbb192f8bc30839/pkg/apis/pipeline/v1/matrix_types.go#L294-L301

**Comment by l-qing** [comment]
Hi, @afrittoli can you help me review it when you have time?

**Comment by fabricebrito** [comment]
Looking forward for this fix 👍🏽

File: pkg/apis/pipeline/v1/matrix_types_test.go (hunk 1 above)
Comment (vdemeester) [reply pkg/apis/pipeline/v1/matrix_types_test.go:785]: btw, the indentation is really weird here. We should format it better.

```
&v1.Matrix{
    Params: v1.Params{},
}
// or 
&v1.Matrix{Params: v1.Params{}}
```

File: pkg/apis/pipeline/v1/matrix_types.go [hunk 6]
```diff
@@ -236,7 +236,9 @@ func (m *Matrix) countGeneratedCombinationsFromParams() int {
 	}
 	count := 1
 	for _, param := range m.Params {
-		count *= len(param.Value.ArrayVal)
+		if len(param.Value.ArrayVal) > 0 {
+			count *= len(param.Value.ArrayVal)
```
Comment (vdemeester) [inline pkg/apis/pipeline/v1/matrix_types.go:240]: nit: can we just go with `count = count * len(…)` ?

Comment (l-qing) [reply pkg/apis/pipeline/v1/matrix_types.go]:
```shell
Running [/home/runner/golangci-lint-1.62.2-linux-amd64/golangci-lint run  --timeout=10m] in [/home/runner/work/pipeline/pipeline] ...

Error: pkg/apis/pipeline/v1/matrix_types.go:240:4: assignOp: replace `count = count * len(param.Value.ArrayVal)` with `count *= len(param.Value.ArrayVal)` (gocritic)
```

**Comment by l-qing** [comment]
assign @vdemeester @afrittoli

**Comment by l-qing** [comment]
The logical changes in this PR are minimal, almost just three lines.
The rest are changes to unit tests and e2e.

File: pkg/apis/pipeline/v1/matrix_types.go (hunk 6 above)
Comment (vdemeester) [reply pkg/apis/pipeline/v1/matrix_types.go:240]: Intesresting 🙃

**Review by vdemeester — APPROVED** [review]

**Comment by l-qing** [comment]
I will adjust this branch after the golangci-lint pipeline passes on the main branch.
It is unclear what exactly caused the failure in golangci-lint.

When I use the same version 1.62.2 of the golangci-lint tool for local scanning, my computer freezes.

**Comment by vdemeester** [comment]
@l-qing see https://github.com/tektoncd/pipeline/pull/8570 👼🏼

**Comment by l-qing** [comment]
> The logical changes in this PR are minimal, almost just three lines. The rest are changes to unit tests and e2e.

@afrittoli Can you help assign a suitable person for this PR?  
The code changes are not extensive; mainly, there are a lot of e2e tests.

**Comment by l-qing** [comment]
@waveywaves I adjusted the unit test code here. Do you think this is okay? https://github.com/tektoncd/pipeline/pull/8487/commits/c6fbd8bc30833599b63554c06e8f4e86f79706c2

Due to the previous reconciliation, the calculated `numCombinations` was `0`, so it wouldn't enter the process of retrieving tasks `rpt.setTaskRunsAndResolvedTask`, which is why it reached the subsequent checks.

https://github.com/tektoncd/pipeline/blob/1d2ea8b90d03dc4cad2699ac9a3149284afb9ba0/pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go#L613-L631

So in order to proceed to the subsequent tests, I need to resolve the issue of the task not existing in the original unit tests.

**Comment by l-qing** [comment]
It seems that the failure was due to a failure in pulling the image. However, I am unsure of the specific reason for the failure.  
Since I cannot retry the failed action individually, I can only close and then reopen the PR.

```
2025-03-05T13:55:44.9179983Z --- FAIL: TestExamples (0.08s)
2025-03-05T13:55:44.9201720Z     --- FAIL: TestExamples/v1/pipelineruns/workspace-from-volumeclaimtemplate (268.32s)
```

```
2025-03-05T13:51:24.6457141Z     examples_test.go:59: Failed waiting for V1 pipeline run done: "run-with-template-rgb8p" failed
2025-03-05T13:51:24.6460770Z     panic.go:629: ############################################
2025-03-05T13:51:24.6466331Z     panic.go:629: ### Dumping objects from arendelle-7fb9f ###
2025-03-05T13:51:24.6467823Z     panic.go:629: ############################################
2025-03-05T13:51:24.6468870Z I0305 13:51:24.644474  119818 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
2025-03-05T13:51:24.6470031Z I0305 13:51:24.644542  119818 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
2025-03-05T13:51:24.7458764Z     panic.go:629: 
2025-03-05T13:51:24.7461464Z         ---
2025-03-05T13:51:24.7462951Z         apiVersion: tekton.dev/v1
2025-03-05T13:51:24.7463423Z         kind: TaskRun
2025-03-05T13:51:24.7463799Z         metadata:
2025-03-05T13:51:24.7464171Z           annotations:
2025-03-05T13:51:24.7466174Z             pipeline.tekton.dev/affinity-assistant: affinity-assistant-5f80ef0f76
2025-03-05T13:51:24.7467075Z             pipeline.tekton.dev/release: ce4baf2
2025-03-05T13:51:24.7467762Z           creationTimestamp: "2025-03-05T13:47:05Z"
2025-03-05T13:51:24.7468432Z           generation: 1
2025-03-05T13:51:24.7469120Z           labels:
2025-03-05T13:51:24.7469766Z             app.kubernetes.io/managed-by: tekton-pipelines
2025-03-05T13:51:24.7470460Z             tekton.dev/memberOf: tasks
2025-03-05T13:51:24.7471177Z             tekton.dev/pipeline: volume-from-template
2025-03-05T13:51:24.7471993Z             tekton.dev/pipelineRun: run-with-template-rgb8p
2025-03-05T13:51:24.7473244Z             tekton.dev/pipelineRunUID: f571fb9a-c771-43dc-9850-1c8251c8ac4c
2025-03-05T13:51:24.7474226Z             tekton.dev/pipelineTask: reader
2025-03-05T13:51:24.7475080Z           name: run-with-template-rgb8p-reader
2025-03-05T13:51:24.7475857Z           namespace: arendelle-7fb9f
2025-03-05T13:51:24.7476546Z           ownerReferences:
2025-03-05T13:51:24.7477385Z           - apiVersion: tekton.dev/v1
2025-03-05T13:51:24.7478441Z             blockOwnerDeletion: true
2025-03-05T13:51:24.7478976Z             controller: true
2025-03-05T13:51:24.7479637Z             kind: PipelineRun
2025-03-05T13:51:24.7480391Z             name: run-with-template-rgb8p
2025-03-05T13:51:24.7481262Z             uid: f571fb9a-c771-43dc-9850-1c8251c8ac4c
2025-03-05T13:51:24.7482009Z           resourceVersion: "19838"
2025-03-05T13:51:24.7482793Z           uid: f88d79be-20ab-4f86-8f88-150574d2f73d
2025-03-05T13:51:24.7483421Z         spec:
2025-03-05T13:51:24.7483889Z           serviceAccountName: default
2025-03-05T13:51:24.7484384Z           taskSpec:
2025-03-05T13:51:24.7484616Z             steps:
2025-03-05T13:51:24.7485042Z             - computeResources: {}
2025-03-05T13:51:24.7485410Z               image: mirror.gcr.io/ubuntu
2025-03-05T13:51:24.7485849Z               name: read
2025-03-05T13:51:24.7486288Z               script: cat $(workspaces.myws.path)/foo | grep bar
2025-03-05T13:51:24.7486780Z             workspaces:
2025-03-05T13:51:24.7487036Z             - name: myws
2025-03-05T13:51:24.7487423Z           timeout: 1h0m0s
2025-03-05T13:51:24.7487670Z           workspaces:
2025-03-05T13:51:24.7488367Z           - name: myws
2025-03-05T13:51:24.7488713Z             persistentVolumeClaim:
2025-03-05T13:51:24.7489373Z               claimName: pvc-5e72df2b7e
2025-03-05T13:51:24.7489628Z         status:
2025-03-05T13:51:24.7489935Z           completionTime: "2025-03-05T13:51:23Z"
2025-03-05T13:51:24.7490289Z           conditions:
2025-03-05T13:51:24.7490635Z           - lastTransitionTime: "2025-03-05T13:51:23Z"
2025-03-05T13:51:24.7491263Z             message: 'the step "read" in TaskRun "run-with-template-rgb8p-reader" failed to
2025-03-05T13:51:24.7491998Z               pull the image "". The pod errored with the message: "Back-off pulling image
2025-03-05T13:51:24.7492461Z               "mirror.gcr.io/ubuntu"."'
2025-03-05T13:51:24.7492820Z             reason: TaskRunImagePullFailed
2025-03-05T13:51:24.7493131Z             status: "False"
2025-03-05T13:51:24.7493391Z             type: Succeeded
2025-03-05T13:51:24.7493752Z           podName: run-with-template-rgb8p-reader-pod`
```

**Review by vdemeester — APPROVED** [review]

**Comment by aThorp96** [comment]
@waveywaves are your requested changes still blocking? Can this be merged?
