### PR TITLE
Fix duplicate TaskRuns when Pipeline/PipelineRun labels are changed

### LINKED ISSUE #3126: Executing a Pipeline with a single Task results in multiple TaskRuns
Hi,

I have a simple pipeline that consists only of a single task. When creating a PipelineRun for it, I expect that one TaskRun is created. Sometimes however, I observe two TaskRuns being created for the same PipelineRun. Here is an example: PipelineRun `uiveri5-lunchmenu-1598256551145` resulted in two TaskRuns `uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh` and `uiveri5-lunchmenu-1598256551145-uiveri5-vllbc`.

Is my expectation right that only one TaskRun should be created? Any ideas what could lead to this situation?

Thank you!

tekton-pipelines-controller logs
```
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145\", UID:\"9d70ede0-b3c3-4bf0-9928-505cd905d655\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479590\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"6d12d1e"}
{"level":"info","logger":"tekton","caller":"timeout/handler.go:277","msg":"About to start timeout timer for PipelineRun/0xc001ffcb40. started at 2020-08-24 08:09:11.370358788 +0000 UTC m=+7101.475560498, timeout is 1h0m0s, running for 106.715µs","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:686","msg":"Creating a new TaskRun object uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh","commit":"6d12d1e","knative.dev/traceid":"eba2b022-8d22-474c-8b21-ebb15b3ccf75","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11.482441283 +0000 UTC m=+7101.587642959} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"eba2b022-8d22-474c-8b21-ebb15b3ccf75","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145\", UID:\"9d70ede0-b3c3-4bf0-9928-505cd905d655\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479590\", FieldPath:\"\"}): type: 'Normal' reason: 'Running' Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0","commit":"6d12d1e"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479591\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"f6fabc35-1410-452c-87f6-10e8bf45c62f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"warn","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"artifacts/artifacts_storage.go:139","msg":"the configmap key \"location\" is empty","commit":"6d12d1e","knative.dev/traceid":"f6fabc35-1410-452c-87f6-10e8bf45c62f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton","caller":"timeout/handler.go:277","msg":"About to start timeout timer for TaskRun/0xc0024fc280. started at 2020-08-24 08:09:11.483483998 +0000 UTC m=+7101.588685700, timeout is 1h0m0s, running for 111.00709ms","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb49e396383c, ext:7101702249044, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"Pending\"}","commit":"6d12d1e","knative.dev/traceid":"f6fabc35-1410-452c-87f6-10e8bf45c62f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479591\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' Pending","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 419.623362ms","commit":"6d12d1e","knative.dev/traceid":"eba2b022-8d22-474c-8b21-ebb15b3ccf75","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145\", UID:\"9d70ede0-b3c3-4bf0-9928-505cd905d655\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479594\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"6d12d1e"}
{"level":"info","logger":"tekton","caller":"timeout/handler.go:277","msg":"About to start timeout timer for PipelineRun/0xc001b9e900. started at 2020-08-24 08:09:11.790093798 +0000 UTC m=+7101.895295483, timeout is 1h0m0s, running for 3.226751ms","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:686","msg":"Creating a new TaskRun object uiveri5-lunchmenu-1598256551145-uiveri5-vllbc","commit":"6d12d1e","knative.dev/traceid":"8e09a60f-efdf-4574-9f71-333c0b7f263e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 472.182934ms","commit":"6d12d1e","knative.dev/traceid":"f6fabc35-1410-452c-87f6-10e8bf45c62f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-vllbc\", UID:\"b0d01c48-af18-45bf-a2d7-ca3372b76e12\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479602\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11.959656331 +0000 UTC m=+7102.064858010} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"8e09a60f-efdf-4574-9f71-333c0b7f263e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145\", UID:\"9d70ede0-b3c3-4bf0-9928-505cd905d655\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479594\", FieldPath:\"\"}): type: 'Normal' reason: 'Running' Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"9b31da45-cdf3-4025-b0c6-7947cda24751","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"9bc017be-61eb-47be-b0b2-5ae23c49792a","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb49fa531c6e, ext:7102083726974, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [working-dir-initializer place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"9b31da45-cdf3-4025-b0c6-7947cda24751","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479601\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' pod status \"Initialized\":\"False\"; message: \"containers with incomplete status: [working-dir-initializer place-tools]\"","commit":"6d12d1e"}
{"level":"warn","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"artifacts/artifacts_storage.go:139","msg":"the configmap key \"location\" is empty","commit":"6d12d1e","knative.dev/traceid":"9bc017be-61eb-47be-b0b2-5ae23c49792a","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 145.827255ms","commit":"6d12d1e","knative.dev/traceid":"9b31da45-cdf3-4025-b0c6-7947cda24751","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"e2dbe703-242a-45a9-9e7a-d8c70532421c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4a076f6ff3, ext:7102229945344, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [working-dir-initializer place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"e2dbe703-242a-45a9-9e7a-d8c70532421c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 23.19643ms","commit":"6d12d1e","knative.dev/traceid":"e2dbe703-242a-45a9-9e7a-d8c70532421c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton","caller":"timeout/handler.go:277","msg":"About to start timeout timer for TaskRun/0xc00386c780. started at 2020-08-24 08:09:11.959093614 +0000 UTC m=+7102.064295304, timeout is 1h0m0s, running for 184.991567ms","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4a08ac26c6, ext:7102250701511, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"Pending\"}","commit":"6d12d1e","knative.dev/traceid":"9bc017be-61eb-47be-b0b2-5ae23c49792a","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-vllbc\", UID:\"b0d01c48-af18-45bf-a2d7-ca3372b76e12\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479602\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' Pending","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 372.105315ms","commit":"6d12d1e","knative.dev/traceid":"8e09a60f-efdf-4574-9f71-333c0b7f263e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"2f3abe22-7ddf-4ff0-bac5-0ccbacdbc165","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 18.099055ms","commit":"6d12d1e","knative.dev/traceid":"2f3abe22-7ddf-4ff0-bac5-0ccbacdbc165","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"74af8e68-3064-4267-8fc8-d15ef6037c53","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 55.81474ms","commit":"6d12d1e","knative.dev/traceid":"74af8e68-3064-4267-8fc8-d15ef6037c53","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 448.180396ms","commit":"6d12d1e","knative.dev/traceid":"9bc017be-61eb-47be-b0b2-5ae23c49792a","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"616ac362-2672-46f6-bffc-91d5fcfc7dc8","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"02c5858e-1c8a-48b0-8c18-6562ff627471","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4a1998ec7b, ext:7102534654087, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [working-dir-initializer place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"616ac362-2672-46f6-bffc-91d5fcfc7dc8","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-vllbc\", UID:\"b0d01c48-af18-45bf-a2d7-ca3372b76e12\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479610\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' pod status \"Initialized\":\"False\"; message: \"containers with incomplete status: [working-dir-initializer place-tools]\"","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 83.988831ms","commit":"6d12d1e","knative.dev/traceid":"02c5858e-1c8a-48b0-8c18-6562ff627471","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"d313af46-1f16-4848-b2ca-21cf00e7c0ec","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 14.292536ms","commit":"6d12d1e","knative.dev/traceid":"d313af46-1f16-4848-b2ca-21cf00e7c0ec","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 97.114422ms","commit":"6d12d1e","knative.dev/traceid":"616ac362-2672-46f6-bffc-91d5fcfc7dc8","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"e8534463-59c1-47f6-b045-4e6775f5b740","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"de0634d6-ddee-4f0f-9011-5e52b427cd1f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4a29a34b68, ext:7102803769205, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [working-dir-initializer place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"de0634d6-ddee-4f0f-9011-5e52b427cd1f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 188.005259ms","commit":"6d12d1e","knative.dev/traceid":"de0634d6-ddee-4f0f-9011-5e52b427cd1f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 327.580992ms","commit":"6d12d1e","knative.dev/traceid":"e8534463-59c1-47f6-b045-4e6775f5b740","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"50133f3a-7230-4dea-89fa-d550c9c776b9","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 52.387014ms","commit":"6d12d1e","knative.dev/traceid":"50133f3a-7230-4dea-89fa-d550c9c776b9","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"c8b21709-caf4-407e-8f13-c1463f732b8e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4a452739a3, ext:7103191658418, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [working-dir-initializer place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"c8b21709-caf4-407e-8f13-c1463f732b8e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 24.151068ms","commit":"6d12d1e","knative.dev/traceid":"c8b21709-caf4-407e-8f13-c1463f732b8e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"0347b371-e59d-497b-b6d7-90efe7bdeae1","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4a601aba5e, ext:7103643824237, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [working-dir-initializer place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"0347b371-e59d-497b-b6d7-90efe7bdeae1","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 27.375089ms","commit":"6d12d1e","knative.dev/traceid":"0347b371-e59d-497b-b6d7-90efe7bdeae1","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"a4349823-8372-4893-815e-93559861aaba","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4aa2995ffb, ext:7104685678600, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"a4349823-8372-4893-815e-93559861aaba","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-vllbc\", UID:\"b0d01c48-af18-45bf-a2d7-ca3372b76e12\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479613\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' pod status \"Initialized\":\"False\"; message: \"containers with incomplete status: [place-tools]\"","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"3b4afa99-0f48-44e2-9770-c606f965dc96","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4aa3735231, ext:7104699961917, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"3b4afa99-0f48-44e2-9770-c606f965dc96","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479603\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' pod status \"Initialized\":\"False\"; message: \"containers with incomplete status: [place-tools]\"","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 97.556794ms","commit":"6d12d1e","knative.dev/traceid":"3b4afa99-0f48-44e2-9770-c606f965dc96","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 125.652934ms","commit":"6d12d1e","knative.dev/traceid":"a4349823-8372-4893-815e-93559861aaba","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"28dee744-a7fd-4a41-8cc7-3cc0129b3e51","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"81b78711-0504-4dd7-829c-6d66abddde73","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"728ea771-e3b3-4422-8738-2cc34499bf37","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4aa976acf3, ext:7104800845055, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"28dee744-a7fd-4a41-8cc7-3cc0129b3e51","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 25.313452ms","commit":"6d12d1e","knative.dev/traceid":"28dee744-a7fd-4a41-8cc7-3cc0129b3e51","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4aa9af6b6e, ext:7104804563835, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Initialized\\\":\\\"False\\\"; message: \\\"containers with incomplete status: [place-tools]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"728ea771-e3b3-4422-8738-2cc34499bf37","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 23.030917ms","commit":"6d12d1e","knative.dev/traceid":"728ea771-e3b3-4422-8738-2cc34499bf37","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 111.598368ms","commit":"6d12d1e","knative.dev/traceid":"81b78711-0504-4dd7-829c-6d66abddde73","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"7ba4018f-5a70-4237-9421-d2a0c587b175","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 16.438572ms","commit":"6d12d1e","knative.dev/traceid":"7ba4018f-5a70-4237-9421-d2a0c587b175","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"6bf350f4-ae00-4758-9c76-b3cba1918b6a","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4ae86a842d, ext:7105783270981, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Ready\\\":\\\"False\\\"; message: \\\"containers with unready status: [step-git-source-workspace-spgfc step-uiveri5]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"6bf350f4-ae00-4758-9c76-b3cba1918b6a","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-vllbc\", UID:\"b0d01c48-af18-45bf-a2d7-ca3372b76e12\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479637\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' pod status \"Ready\":\"False\"; message: \"containers with unready status: [step-git-source-workspace-spgfc step-uiveri5]\"","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"7d5b288d-ac72-4d25-8b45-f04f1921f30d","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4aecfa67e9, ext:7105859809783, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Ready\\\":\\\"False\\\"; message: \\\"containers with unready status: [step-git-source-workspace-2lfxv step-uiveri5]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"7d5b288d-ac72-4d25-8b45-f04f1921f30d","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479636\", FieldPath:\"\"}): type: 'Normal' reason: 'Pending' pod status \"Ready\":\"False\"; message: \"containers with unready status: [step-git-source-workspace-2lfxv step-uiveri5]\"","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 133.680265ms","commit":"6d12d1e","knative.dev/traceid":"6bf350f4-ae00-4758-9c76-b3cba1918b6a","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"860dee3c-07d3-4936-99da-382a0461e4e5","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"ec47e79a-9d42-4480-ab59-62d94204f07f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4af0707cb6, ext:7105917880005, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Ready\\\":\\\"False\\\"; message: \\\"containers with unready status: [step-git-source-workspace-spgfc step-uiveri5]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"860dee3c-07d3-4936-99da-382a0461e4e5","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 23.344591ms","commit":"6d12d1e","knative.dev/traceid":"860dee3c-07d3-4936-99da-382a0461e4e5","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 95.536509ms","commit":"6d12d1e","knative.dev/traceid":"7d5b288d-ac72-4d25-8b45-f04f1921f30d","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"0cc939c0-84f4-4ad4-9484-df28435e6b9c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4af31ce534, ext:7105962733379, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Pending\", Message:\"pod status \\\"Ready\\\":\\\"False\\\"; message: \\\"containers with unready status: [step-git-source-workspace-2lfxv step-uiveri5]\\\"\"}","commit":"6d12d1e","knative.dev/traceid":"0cc939c0-84f4-4ad4-9484-df28435e6b9c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 30.83189ms","commit":"6d12d1e","knative.dev/traceid":"0cc939c0-84f4-4ad4-9484-df28435e6b9c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 69.901954ms","commit":"6d12d1e","knative.dev/traceid":"ec47e79a-9d42-4480-ab59-62d94204f07f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"4d83a223-491a-43c7-a421-abf49fd671f5","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 95.761668ms","commit":"6d12d1e","knative.dev/traceid":"4d83a223-491a-43c7-a421-abf49fd671f5","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"07d38e78-d298-4af6-9cb0-e9f1046f0678","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 15.68744ms","commit":"6d12d1e","knative.dev/traceid":"07d38e78-d298-4af6-9cb0-e9f1046f0678","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"298cefc8-2c6e-4ead-aac4-69c7b099dd4f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"0ccd48f7-3d5b-4c6c-a9b2-26b5db72448c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4b33a1dc19, ext:7106971447359, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"298cefc8-2c6e-4ead-aac4-69c7b099dd4f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-vllbc\", UID:\"b0d01c48-af18-45bf-a2d7-ca3372b76e12\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479643\", FieldPath:\"\"}): type: 'Normal' reason: 'Running' Not all Steps in the Task have finished executing","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4b34fb0ae4, ext:7106994069266, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"0ccd48f7-3d5b-4c6c-a9b2-26b5db72448c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479644\", FieldPath:\"\"}): type: 'Normal' reason: 'Running' Not all Steps in the Task have finished executing","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 313.704808ms","commit":"6d12d1e","knative.dev/traceid":"298cefc8-2c6e-4ead-aac4-69c7b099dd4f","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"b9a8d568-43d4-4d9a-8973-edc858f3ca6b","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"621aa81a-24b8-484b-802f-cd02d87a063b","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 310.662778ms","commit":"6d12d1e","knative.dev/traceid":"0ccd48f7-3d5b-4c6c-a9b2-26b5db72448c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0x0, ext:63733853356, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"b9a8d568-43d4-4d9a-8973-edc858f3ca6b","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 34.435854ms","commit":"6d12d1e","knative.dev/traceid":"b9a8d568-43d4-4d9a-8973-edc858f3ca6b","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"c300455c-19fe-4ab2-b08e-a78a4a495f1c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb4b4afdf934, ext:7107289618247, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"c300455c-19fe-4ab2-b08e-a78a4a495f1c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479644\", FieldPath:\"\"}): type: 'Normal' reason: 'Running' Not all Steps in the Task have finished executing","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 69.290271ms","commit":"6d12d1e","knative.dev/traceid":"621aa81a-24b8-484b-802f-cd02d87a063b","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"416cd7ec-5739-4465-8e69-5164a1229972","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 140.464732ms","commit":"6d12d1e","knative.dev/traceid":"416cd7ec-5739-4465-8e69-5164a1229972","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"1aa30693-e011-431e-ae35-cc90850111d5","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 14.890052ms","commit":"6d12d1e","knative.dev/traceid":"1aa30693-e011-431e-ae35-cc90850111d5","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 232.165837ms","commit":"6d12d1e","knative.dev/traceid":"c300455c-19fe-4ab2-b08e-a78a4a495f1c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"68326d7f-9ed8-41a0-b7cc-6ae81e475bc6","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"1cfc858a-dcd3-4b68-aabc-e1f366ed871c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 17.389688ms","commit":"6d12d1e","knative.dev/traceid":"1cfc858a-dcd3-4b68-aabc-e1f366ed871c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0x0, ext:63733853357, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"68326d7f-9ed8-41a0-b7cc-6ae81e475bc6","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 33.780464ms","commit":"6d12d1e","knative.dev/traceid":"68326d7f-9ed8-41a0-b7cc-6ae81e475bc6","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"7e134d2f-6c08-43b7-8ffd-645b2616e37e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0x0, ext:63733853357, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"7e134d2f-6c08-43b7-8ffd-645b2616e37e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 33.628007ms","commit":"6d12d1e","knative.dev/traceid":"7e134d2f-6c08-43b7-8ffd-645b2616e37e","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"06c4e6c5-f0fd-49e5-bdce-199496e1786c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"f584a489-4394-4ba4-af25-0b9b7f455408","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0x0, ext:63733853356, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"06c4e6c5-f0fd-49e5-bdce-199496e1786c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0x0, ext:63733853357, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"f584a489-4394-4ba4-af25-0b9b7f455408","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 118.024919ms","commit":"6d12d1e","knative.dev/traceid":"06c4e6c5-f0fd-49e5-bdce-199496e1786c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 122.166858ms","commit":"6d12d1e","knative.dev/traceid":"f584a489-4394-4ba4-af25-0b9b7f455408","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"5560efe4-3511-4c60-91dc-d7a010689107","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"0335e504-1b7f-4883-9dc3-6c9b34448895","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"82fbd93d-c595-4c51-b243-a0056f22c98c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0x0, ext:63733853356, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"0335e504-1b7f-4883-9dc3-6c9b34448895","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"Unknown\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0x0, ext:63733853357, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Running\", Message:\"Not all Steps in the Task have finished executing\"}","commit":"6d12d1e","knative.dev/traceid":"82fbd93d-c595-4c51-b243-a0056f22c98c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 80.240557ms","commit":"6d12d1e","knative.dev/traceid":"5560efe4-3511-4c60-91dc-d7a010689107","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"dc2c02dc-ed52-499b-980f-5249c86a55e0","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 16.768409ms","commit":"6d12d1e","knative.dev/traceid":"dc2c02dc-ed52-499b-980f-5249c86a55e0","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 107.605075ms","commit":"6d12d1e","knative.dev/traceid":"0335e504-1b7f-4883-9dc3-6c9b34448895","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 165.027083ms","commit":"6d12d1e","knative.dev/traceid":"82fbd93d-c595-4c51-b243-a0056f22c98c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"fb195edb-95a8-423f-a50c-70b6d2605abb","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"False\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb554ca9b227, ext:7147317649493, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Failed\", Message:\"\\\"step-uiveri5\\\" exited with code 1 (image: \\\"docker-pullable://docker.wdf.sap.corp:51175/platformcoe/beekeeper/uiveri5@sha256:d27c785eeafc0115265eff0da5668819c243d0fd8ee83c7762095749b1ca9a91\\\"); for logs run: kubectl -n site logs uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh-pod-rrh9d -c step-uiveri5\\n\"}","commit":"6d12d1e","knative.dev/traceid":"fb195edb-95a8-423f-a50c-70b6d2605abb","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh\", UID:\"39c36de3-fb9b-4128-bc76-56956d640711\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479673\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' \"step-uiveri5\" exited with code 1 (image: \"docker-pullable://docker.wdf.sap.corp:51175/platformcoe/beekeeper/uiveri5@sha256:d27c785eeafc0115265eff0da5668819c243d0fd8ee83c7762095749b1ca9a91\"); for logs run: kubectl -n site logs uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh-pod-rrh9d -c step-uiveri5\n","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:315","msg":"Cloud Events: []","commit":"6d12d1e","knative.dev/traceid":"aaa2e175-c4d8-4ff6-8171-1d84d7831366","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:406","msg":"Successfully reconciled taskrun uiveri5-lunchmenu-1598256551145-uiveri5-vllbc/site with status: &apis.Condition{Type:\"Succeeded\", Status:\"False\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfc8fb554f4cf7ae, ext:7147361904088, loc:(*time.Location)(0x3307a80)}}}, Reason:\"Failed\", Message:\"\\\"step-uiveri5\\\" exited with code 1 (image: \\\"docker-pullable://docker.wdf.sap.corp:51175/platformcoe/beekeeper/uiveri5@sha256:d27c785eeafc0115265eff0da5668819c243d0fd8ee83c7762095749b1ca9a91\\\"); for logs run: kubectl -n site logs uiveri5-lunchmenu-1598256551145-uiveri5-vllbc-pod-hxxx2 -c step-uiveri5\\n\"}","commit":"6d12d1e","knative.dev/traceid":"aaa2e175-c4d8-4ff6-8171-1d84d7831366","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145-uiveri5-vllbc\", UID:\"b0d01c48-af18-45bf-a2d7-ca3372b76e12\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479672\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' \"step-uiveri5\" exited with code 1 (image: \"docker-pullable://docker.wdf.sap.corp:51175/platformcoe/beekeeper/uiveri5@sha256:d27c785eeafc0115265eff0da5668819c243d0fd8ee83c7762095749b1ca9a91\"); for logs run: kubectl -n site logs uiveri5-lunchmenu-1598256551145-uiveri5-vllbc-pod-hxxx2 -c step-uiveri5\n","commit":"6d12d1e"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 115.360571ms","commit":"6d12d1e","knative.dev/traceid":"fb195edb-95a8-423f-a50c-70b6d2605abb","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:110","msg":"taskrun done : uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh \n","commit":"6d12d1e","knative.dev/traceid":"75da5794-3c2d-4135-b49d-14576a06884c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded Unknown  {2020-08-24 08:09:11 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"6ae703aa-b1bb-4d4f-8cf6-d1e5fb927052","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 16.556962ms","commit":"6d12d1e","knative.dev/traceid":"6ae703aa-b1bb-4d4f-8cf6-d1e5fb927052","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 155.969785ms","commit":"6d12d1e","knative.dev/traceid":"aaa2e175-c4d8-4ff6-8171-1d84d7831366","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:110","msg":"taskrun done : uiveri5-lunchmenu-1598256551145-uiveri5-vllbc \n","commit":"6d12d1e","knative.dev/traceid":"1655147b-86c8-457c-b538-80c34294d6b8","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-vllbc"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:474","msg":"Reconcile succeeded. Time taken: 68.834907ms","commit":"6d12d1e","knative.dev/traceid":"75da5794-3c2d-4135-b49d-14576a06884c","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145-uiveri5-d7fkh"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"resources/pipelinerunresolution.go:567","msg":"All TaskRuns have finished for PipelineRun uiveri5-lunchmenu-1598256551145 so it has finished","commit":"6d12d1e","knative.dev/traceid":"db8350ff-d88a-44c8-80d9-5137f3322681","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-pipelinerun.Reconciler","caller":"pipelinerun/pipelinerun.go:475","msg":"PipelineRun uiveri5-lunchmenu-1598256551145 status is being set to &{Succeeded False  {2020-08-24 08:09:57.374219509 +0000 UTC m=+7147.479421185} Failed Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0}","commit":"6d12d1e","knative.dev/traceid":"db8350ff-d88a-44c8-80d9-5137f3322681","knative.dev/key":"site/uiveri5-lunchmenu-1598256551145"}
{"level":"info","logger":"tekton.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"site\", Name:\"uiveri5-lunchmenu-1598256551145\", UID:\"9d70ede0-b3c3-4bf0-9928-505cd905d655\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"28479674\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0","commit":"6d12d1e"}
```

pipeline
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    fluxcd.io/sync-checksum: 61a317e9bf1eba3100f64a57c618d5a346e7c82b
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{"fluxcd.io/sync-checksum":"61a317e9bf1eba3100f64a57c618d5a346e7c82b"},"labels":{"fluxcd.io/sync-gc-mark":"sha256.D5QWv8-8W1lY3-H4_5LxwilzVXygk0aSWl7S0KuLAcI"},"name":"uiveri5-pipeline-v3","namespace":"site"},"spec":{"params":[{"description":"Secret containing the user for text execution","name":"user-secret","type":"string"}],"resources":[{"name":"source-repo","type":"git"}],"tasks":[{"name":"uiveri5","params":[{"name":"user-secret","value":"$(params.user-secret)"}],"resources":{"inputs":[{"name":"workspace","resource":"source-repo"}]},"taskRef":{"name":"uiveri5-v3"}}]}}
  creationTimestamp: "2020-04-03T08:15:14Z"
  generation: 2
  labels:
    fluxcd.io/sync-gc-mark: sha256.D5QWv8-8W1lY3-H4_5LxwilzVXygk0aSWl7S0KuLAcI
  name: uiveri5-pipeline-v3
  namespace: site
  resourceVersion: "23364481"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/site/pipelines/uiveri5-pipeline-v3
  uid: 65d47673-14ca-4668-b439-e9f89718a8fd
spec:
  params:
  - description: Secret containing the user for test execution
    name: user-secret
    type: string
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: uiveri5
    params:
    - name: user-secret
      value: $(params.user-secret)
    resources:
      inputs:
      - name: workspace
        resource: source-repo
    taskRef:
      kind: Task
      name: uiveri5-v3
```

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
v0.15.2
```

### PR DESCRIPTION
**Pull request by GregDritschler**
Fixes #3126

The PipelineRun reconciler may be handed a PipelineRun that does not have a previous status update containing the names of TaskRuns it created.  The PipelineRun reconciler attempts to deal with this by looking at the TaskRun lister cache for TaskRuns associated with the PipelineRun that are missing from the status and adding them.  It uses the PipelineRun's labels to find them.  If the user changes the PipelineRun's labels (or the Pipeline's labels which are propagated to the PipelineRun) while the pipeline is running, it may cause the code to not find existing TaskRuns and as a result it may duplicate them.

# Changes

The reconciler is changed to use only the `tekton.dev/pipelineRun` label when listing TaskRuns associated with the PipelineRun.

/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Fix an issue where the PipelineRun controller could create duplicate TaskRuns if a Pipeline's or PipelineRun's labels are changed while the PipelineRun is running
```

### CODE REVIEW

**Comment by vdemeester** [comment]
@GregDritschler I think we need a release-note entry though :angel:

**Review by vdemeester — APPROVED** [review]

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 1]
```diff
@@ -3105,8 +3105,78 @@ func TestReconcileOutOfSyncPipelineRun(t *testing.T) {
...
+
+	// Add a label to the PipelineRun.  This tests a scenario in issue 3126 which could prevent the reconciler
+	// from finding TaskRuns that are missing from the status.
+	reconciledRun.ObjectMeta.Labels["bah"] = "humbug"
+	reconciledRun, err := clients.Pipeline.TektonV1beta1().PipelineRuns("foo").Update(prt.TestAssets.Ctx, reconciledRun, metav1.UpdateOptions{})
+	if err != nil {
+		t.Fatalf("unexpected error when updating status: %v", err)
+	}
+
+	// The label update triggers another reconcile.  Depending on timing, the PipelineRun passed to the reconcile may or may not
```
Comment (afrittoli) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:3157]: Nice trick :)

**Review by afrittoli — COMMENTED** [review]
Thanks for this, nice catch and fix!
/lgtm

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 2]
```diff
@@ -3105,8 +3105,78 @@ func TestReconcileOutOfSyncPipelineRun(t *testing.T) {
...
+	for k := range reconciledRun.Status.TaskRuns {
+		if k != taskRunName {
+			t.Fatalf("Status has unexpected taskrun %s", k)
+		}
+	}
+}
+
 func TestUpdatePipelineRunStatusFromTaskRuns(t *testing.T) {
 
+	prUID := types.UID("9c04a4d9-33b8-4641-ad11-2aceed91af7b")
```
Comment (ImJasonH) [inline pkg/reconciler/pipelinerun/pipelinerun_test.go:3177]: Do these UIDs have to be actual UUIDs to pass some check? Why not something easier to read like `first` and `second`? It's a bit hard to tell these are two different strings at a 
quick glance.

Comment (GregDritschler) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go]: I changed the strings to make them more obviously different.

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 3]
```diff
@@ -3105,8 +3105,78 @@ func TestReconcileOutOfSyncPipelineRun(t *testing.T) {
...
+	// status does not have the TaskRun.
+	reconciledRun.Status = v1beta1.PipelineRunStatus{}
+	if _, err := clients.Pipeline.TektonV1beta1().PipelineRuns("foo").UpdateStatus(prt.TestAssets.Ctx, reconciledRun, metav1.UpdateOptions{}); err != nil {
+		t.Fatalf("unexpected error when updating status: %v", err)
+	}
+
+	reconciledRun, _ = prt.reconcileRun("foo", "test-pipeline-run", wantEvents, false)
+
+	// Verify that the reconciler found the existing TaskRun instead of creating a new one.
+	for k := range reconciledRun.Status.TaskRuns {
```
[the remark this answers is not in the document]
Comment (GregDritschler) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go:3169]: done

File: pkg/reconciler/pipelinerun/pipelinerun_test.go [hunk 4]
```diff
@@ -3105,8 +3105,78 @@ func TestReconcileOutOfSyncPipelineRun(t *testing.T) {
...
+	}
+
+	// Reconcile the PipelineRun.  This creates a Taskrun.
+	reconciledRun, clients := prt.reconcileRun("foo", "test-pipeline-run", wantEvents, false)
+
+	// Save the name of the TaskRun that was created.
+	taskRunName := ""
+	for k := range reconciledRun.Status.TaskRuns {
+		if taskRunName != "" {
+			t.Fatalf("Expected 1 TaskRun but got more")
```
[the remark this answers is not in the document]
Comment (GregDritschler) [reply pkg/reconciler/pipelinerun/pipelinerun_test.go]: done

**Comment by sbwsg** [comment]
/lgtm

Thanks for digging into this @GregDritschler !
