### PR TITLE
Fix Pipeline/Task to *Run label/annotation propagation 🥨

### LINKED ISSUE #4477: Annotations and Labels from `Task` are not propagated to the `Pod`
# Expected Behavior

As documented [here](https://tekton.dev/docs/pipelines/labels/#label-propagation) for labels (and it used to be the same for annotations), labels and annotations set on the `Task` should be propagated to the underlying `Pod` when run.

# Actual Behavior

As of today, annotations and labels set on the `Task` are *lost in translation* and only labels and annotations from the `TaskRun` are passed to the generated `Pod`.

# Steps to Reproduce the Problem

1. Create a `Task` with an annotation and a label
2. Create a `TaskRun` that reference it
3. Look at the `Pod` associated with the `TaskRun`, it will not have the annotation nor the label set on the `Task`

# Additional Info

- Kubernetes version:

Any version

- Tekton Pipeline version:

Current main and most likely since this [PR](https://github.com/tektoncd/pipeline/pull/3941), meaning since 0.25 or 0.26 ? 🤔 

---

The main reason for this bug is that, because we are using the `.Status.Spec` to re-construct the `Task` definition and we are not storing annotation and labels in there, we are not using them when creating the `Pod`.

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Before this fix, we are "forgetting" the Task and Pipeline
metadata (Labels/Annotations) when using them in a Run (PipelineRun or
TaskRun).

It is however documented that those metadata get propagated to the
generated Pod, and even the code after storing the Spec is written
that way.

Because we only store the spec, the second time we were reconciling
the TaskRun or PipelineRun, we wouldn't fetch the referenced Task or
Pipeline anymore, and thus, we would not propagate them.

Fixes #4477

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

This most likely need an additional unit test or e2e test, I will be working on this 👼🏼 

/kind bug
/cc @pritidesai @sbwsg @chmouel @bobcatfish 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Fix labels and annotation propagation from Task/Pipeline to TaskRun/PipelineRun and thus the generated Pod
```

### CODE REVIEW

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 1]
```diff
@@ -1147,10 +1130,28 @@ func (c *Reconciler) makeConditionCheckContainer(ctx context.Context, rprt *reso
 	return &cc, err
 }
 
-func storePipelineSpec(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1.PipelineSpec) error {
+func storePipelineSpecAndMergeMeta(ctx context.Context, pr *v1beta1.PipelineRun, ps *v1beta1.PipelineSpec, meta *metav1.ObjectMeta) error {
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1133]: since we are updating this function here, please drop `ctx` since its not used in this function

**Review by pritidesai — APPROVED** [review]
thank you @vdemeester 👍
