### PR TITLE
Ignore tekton reserved annotations

### LINKED ISSUE #6435: Ignore certain Tekton annotations when creating resources
# Expected Behavior

When creating a TaskRun or PipelineRun resource, any annotation that starts with `*.tekton.dev/` should be removed.

# Actual Behavior

Chains completely ignores the resource because 

# Steps to Reproduce the Problem

1. Create a TaskRun or PipelineRun with the following annotation: `chains.tekton.dev/signed: 'true'`
2. Notice that Chains completely ignores the resource.

Furthermore, other annotations, like `chains.tekton.dev/transparency`, can cause confusion to users.

This is, of course, not isolated to Chains. Tekton Results is also affected by this issue.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
🐚 kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.25.4+77bec7a

```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
🐚 tkn version
Client version: 0.29.0
Chains version: v0.13.1
Pipeline version: v0.41.1
Triggers version: v0.22.2
Operator version: v0.63.0

```

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This "filters" out annotation that looks like `*.tekton.dev/*` at creation for `PipelineRun` and `TaskRun`, as well as not propagating this annotation from `PipelineRun` to `TaskRun`.

Closes #6435 

**Why is this required ?**

This is a little bit explained in https://github.com/tektoncd/pipeline/issues/6435. But in a nutshell, if a client has a re-run feature and copies all annotations from one `PipelineRun` to a new one, it might end up copying some "reserved" annotations, like `chains.tekton.dev/*` — which can be a problem. For chains, having those will make chains ignore the `PipelineRun` or `TaskRun` and not handle it at all. For results, it could be marking a `PipelineRun` or `TaskRun` as taken care of even if it is not, …

cc @lcarva 
@tektoncd/core-maintainers I would suggest to cherry-pick this fix to all LTS as well as this "affects" all versions 🙏🏼 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Reserved annotations (`results.tekton.dev/*` and `chains.tekton.dev/*`) are now filter at creation (and not passed from PipelineRun to TaskRun).
```

### CODE REVIEW

**Comment by vdemeester** [comment]
Note: I am not sure where to document this 🙃 😅

**Review by lcarva — APPROVED** [review]
Nice!

**Comment by vdemeester** [comment]
It probably relates to https://github.com/tektoncd/pipeline/issues/4366 as well.

**Review by lbernick — COMMENTED** [review]
Would it also make sense to prevent creation of crds with `tekton.dev` labels? all the labels examples I can think of for tekton.dev are set by the controller rather than the user

**Comment by vdemeester** [comment]
> Would it also make sense to prevent creation of crds with `tekton.dev` labels? all the labels examples I can think of for tekton.dev are set by the controller rather than the user

Yeah, I wrote it wrong in the description I think. It's `.*tekton.dev/.*`, so any `tekton.dev/something` would be ignored as well. I am not sure if we also want to ignore `tekton.dev` or `foo.tekton.dev` (without the `/`) though ?

File: pkg/apis/pipeline/v1/pipelinerun_defaults.go [hunk 1]
```diff
@@ -18,19 +18,30 @@ package v1
...
 )
 
 var _ apis.Defaultable = (*PipelineRun)(nil)
 
 // SetDefaults implements apis.Defaultable
 func (pr *PipelineRun) SetDefaults(ctx context.Context) {
 	pr.Spec.SetDefaults(ctx)
+
+	// Silently filtering out Tekton Reserved annotations at creation
+	if apis.IsInCreate(ctx) {
```
[the remark this answers is not in the document]
Comment (vdemeester) [reply pkg/apis/pipeline/v1/pipelinerun_defaults.go:39]: @lbernick yes. The trick with deletion is that it was *still* trying to marshall/unmarshall the type (prior to going into this part of the code), which was the main problem, if I remember correctly.

File: pkg/apis/pipeline/v1/pipelinerun_defaults.go [hunk 2]
```diff
@@ -18,19 +18,30 @@ package v1
...
+		pr.ObjectMeta.Annotations = kmap.Filter(pr.ObjectMeta.Annotations, func(s string) bool {
+			r := regexp.MustCompile(pipeline.TektonReservedAnnotationExpr)
```
[the remark this answers is not in the document]
Comment (vdemeester) [reply pkg/apis/pipeline/v1/pipelinerun_defaults.go:41]: > nit: this function can panic, I'd prefer calling MustCompile in an `init` function or using `regexp.Compile`

Good point 👍🏼

**Comment by lbernick** [comment]
> > Would it also make sense to prevent creation of crds with `tekton.dev` labels? all the labels examples I can think of for tekton.dev are set by the controller rather than the user
> 
> Yeah, I wrote it wrong in the description I think. It's `.*tekton.dev/.*`, so any `tekton.dev/something` would be ignored as well. I am not sure if we also want to ignore `tekton.dev` or `foo.tekton.dev` (without the `/`) though ?

I think keeping the "/" in is fine-- my question was more about labels vs annotations

**Review by lbernick — APPROVED** [review]

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 3]
```diff
@@ -1125,7 +1126,10 @@ func getTaskrunAnnotations(pr *v1beta1.PipelineRun) map[string]string {
 	for key, val := range pr.ObjectMeta.Annotations {
 		annotations[key] = val
 	}
-	return annotations
+	return kmap.Filter(annotations, func(s string) bool {
```
Comment (pritidesai) [inline pkg/reconciler/pipelinerun/pipelinerun.go:1129]: NIT: can we please add a simple unit test for this? 🙏

**Comment by pritidesai** [comment]
Filtering out such annotations without logging sounds a little mysterious, should we at least add a log of what happened? But at the same time, logs might not be even accessible to the users but at least helps a little.

not a blocker though ...

**Comment by pritidesai** [comment]
Build is failing with:

```
pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go:45: unnecessary trailing newline (whitespace)
}
make: *** [Makefile:175: golangci-lint-check] Error 1
```

You will have to fix the linting error.

File: pkg/apis/pipeline/constant.go [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package pipeline
+
+const (
+	// TektonReservedAnnotationExpr is the expression we use to filter out reserved key in annotation
+	TektonReservedAnnotationExpr = ".*tekton.dev/.*"
```
Comment (afrittoli) [inline pkg/apis/pipeline/constant.go:21]: I think `".*\.tekton.dev/.*"` would be a better regex, so that we only filter things that use the `.tekton.dev` domain.
Something like `myannotation.mytekton.dev` should be fine.

**Comment by afrittoli** [comment]
Release notes should include "action required" as folks might be using `tekton.dev` labels. 
We are using the for instance in our plumbing setup, so we'll need to change things there.

The part that prevents the "signed" annotation from being propagated from pipelinerun to taskrun can be seen as a fix, but this PR filters much more than that, so it should be highlighted in the release notes very well.

Another concern I have with this is that today we copy annotations from tasks to `TaskRuns`, like https://github.com/tektoncd/catalog/blob/835896be3d306356f896c51d1b53fd1130ecfa6a/task/git-clone/0.9/git-clone.yaml#L7-L12, e.g.

```yaml
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    description: |
      Run python unit tests against a root folder.
    managed-by: Tekton
    pipeline.tekton.dev/affinity-assistant: affinity-assistant-7ae9d2e448
    pipeline.tekton.dev/release: 6db52ca
    tekton.dev/categories: Git
    tekton.dev/displayName: git batch merge
    tekton.dev/gitRevision: 6ee0c0faa905d97f920235c41648118ccc9fff3e
    tekton.dev/gitURL: https://github.com/tektoncd/website
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le,linux/arm64
    tekton.dev/tags: git
    tekton.dev/v1beta1Resources: '{}'
    tekton.dev/v1beta1ResourcesResult: '[{"key":"url","value":"https://github.com/tektoncd/website"}]'
```

All those annotations won't be there anymore, which may break users who may rely on them.
The ` tekton.dev/v1beta1Resources` resources will probably be fine, but I'm not 100% sure they're never added on create. The fact that this PR only acts on create and not on update seems like a possible source of issues and confusion.

To be honest I would feel much more comfortable with an implementation that filtered out specific namespaces, like `chains.tekton.dev` and `results.tekton.dev` - and perhaps adding a config option to filter out more on demand.

**Comment by afrittoli** [comment]
@vdemeester is this still something you want to do? Do we need to discuss it in the API WG or Pipeline WG?

**Comment by vdemeester** [comment]
@afrittoli rebased and updated 👼🏼

**Review by JeromeJu — APPROVED** [review]

**Comment by lbernick** [comment]
@vdemeester can I move this to the next milestone or do you want to get it merged today?

**Comment by vdemeester** [comment]
I would love for it to get merged today if possible 🙏🏼

File: pkg/apis/pipeline/constant.go [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package pipeline
+
+const (
+	// TektonReservedAnnotationExpr is the expression we use to filter out reserved key in annotation
+	TektonReservedAnnotationExpr = "(results.tekton.dev|chains.tekton.dev)/.*"
```
Comment (khrm) [inline pkg/apis/pipeline/constant.go:21]: We need to avoid filtering all Results annotations during creation.  See https://github.com/tektoncd/pipeline/issues/6857
