### PR TITLE
Custom task without api version return validation error

### LINKED ISSUE #6459: Any non-empty `Kind` with empty `APIVersion` in `TaskRef` is a `Task`
# Expected Behavior

Setting `Kind` to any non-empty string and `APIVersion` to an empty string in a `TaskRef` will be considered a validation error.

Note that I don't expect it to be considered a `Custom Task` because `APIVersion` is empty. 

# Actual Behavior

Setting `Kind` to any non-empty string and `APIVersion` to an empty string in a `TaskRef` will be considered a `Task`, and attempt to create a `TaskRun`. This is especially a problem if `Kind` is not set to `"Task"`. 

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-
spec:
  pipelineSpec:
    tasks:
      - name: greeting
        taskRef:
          kind: Example
          name: foo
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pr-6whfx
spec:
  pipelineSpec:
    tasks:
    - name: greeting
      taskRef:
        kind: Example
        name: foo
status:
  completionTime: "2023-03-29T16:34:42Z"
  conditions:
  - lastTransitionTime: "2023-03-29T16:34:42Z"
    message: 'Pipeline default/pr-6whfx can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "foo": failed to get task: tasks.tekton.dev "foo" not found'
    reason: CouldntGetTask
    status: "False"
    type: Succeeded
  pipelineSpec:
    tasks:
    - name: greeting
      taskRef:
        kind: Example
        name: foo
```

# Steps to Reproduce the Problem

1. Create a `PipelineRun` with a `TaskRef` where the `Kind` is set to a non-empty string that's not `"Task"`
2. Observe the `PipelineRun` status

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes
This commit closes #6459. For a customtask reference in a pipelinetask, if the Kind is non-empty and not "Task" or "ClusterTask", then it should be a Custom task and api version should be set. If not then validation webhook should return error.  TaskRun's taskRef validation will be handled separately in https://github.com/tektoncd/pipeline/issues/6557

/kind bug

Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Custom task without api version returns validation error
```

### CODE REVIEW

File: pkg/apis/pipeline/v1/pipeline_types.go [hunk 1]
```diff
@@ -478,9 +478,15 @@ func (pt PipelineTask) Validate(ctx context.Context) (errs *apis.FieldError) {
...
+		NamespacedTaskKind: true,
+		"ClusterTask":      true,
+	}
 	// Pipeline task having taskRef/taskSpec with APIVersion is classified as custom task
 	switch {
+	case pt.TaskRef != nil && !notCustomTaskKinds[pt.TaskRef.Kind]:
+		errs = errs.Also(pt.validateCustomTask())
 	case pt.TaskRef != nil && pt.TaskRef.APIVersion != "":
 		errs = errs.Also(pt.validateCustomTask())
 	case pt.TaskSpec != nil && pt.TaskSpec.APIVersion != "":
```
Comment (lbernick) [inline pkg/apis/pipeline/v1/pipeline_types.go:492]: It looks like this change will only apply to taskRefs, and not taskSpecs. It also looks like it will only apply to taskRefs in pipeline tasks, and not taskrefs in taskruns. What's the reason for this?

**Review by lbernick — CHANGES_REQUESTED** [review]
We'll need to modify the `isCustomTask` functions introduced in https://github.com/tektoncd/pipeline/pull/6447.

Also (nit) there are some typos in the PR title/description where custom is spelled "custome", please fix.

File: pkg/apis/pipeline/v1/pipeline_types.go (hunk 1 above)
Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1/pipeline_types.go:492]: I think we probably miss custom task validation for taskSpecs and taskrefs in taskruns. That may be an issue we need to address. I don't have too much context/background on why we only have the "validateCustomTask" for pipelineTask. 🙃

Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1/pipeline_types.go:492]: Sorry I'm not sure what needs to be modified for `isCustomTask`, isCustomTask is used to tell if it is custom task, it requires both of the apiversion and kind. But here we're validating it, so if either is empty we should return error.

File: pkg/apis/pipeline/v1/pipeline_types.go [hunk 2]
```diff
@@ -478,11 +478,19 @@ func (pt PipelineTask) Validate(ctx context.Context) (errs *apis.FieldError) {
 	errs = errs.Also(pt.validateRefOrSpec())
 
 	errs = errs.Also(pt.validateEmbeddedOrType())
-
+	notCustomTaskKinds := map[TaskKind]bool{
+		"":                 true,
+		NamespacedTaskKind: true,
```
Comment (lbernick) [inline pkg/apis/pipeline/v1/pipeline_types.go:483]: @jerop can you take a look here? I'm not sure if validation runs before or after defaulting. If the user sets "kind" = Task, didn't we decide that should be a custom task?

File: pkg/apis/pipeline/v1/pipeline_types.go (hunk 1 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1/pipeline_types.go:494]: Thanks Yongxuan! would you mind testing whether validation is applied for custom tasks in taskrun refs and creating an issue for that?

Re: isCustomTask, I think returning an error is probably the right approach even though we'll have to add the extra return value

File: pkg/apis/pipeline/v1/pipeline_types.go (hunk 2 above)
Comment (jerop) [reply pkg/apis/pipeline/v1/pipeline_types.go:483]: if user sets kind to task:
- if apiversion is non-empty --> custom task
- if apiversion is empty --> task (because this is what we default to, we add kind but leave apiversion as empty)

File: pkg/apis/pipeline/v1/pipeline_types.go [hunk 3]
```diff
@@ -478,11 +478,19 @@ func (pt PipelineTask) Validate(ctx context.Context) (errs *apis.FieldError) {
...
+		"ClusterTask":      true,
+	}
 	// Pipeline task having taskRef/taskSpec with APIVersion is classified as custom task
 	switch {
+	case pt.TaskRef != nil && !notCustomTaskKinds[pt.TaskRef.Kind]:
+		errs = errs.Also(pt.validateCustomTask())
```
Comment (jerop) [inline pkg/apis/pipeline/v1/pipeline_types.go:489]: the apiversion has to be non-empty

**Review by jerop — COMMENTED** [review]
please update the docs and add release notes 🙏🏾

File: pkg/apis/pipeline/v1/pipeline_types.go (hunk 1 above)
Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1/pipeline_types.go:494]: yes, taskrun ref has the same issue, this is a tracking issue: https://github.com/tektoncd/pipeline/issues/6557
Thanks!

File: pkg/apis/pipeline/v1/pipeline_validation.go [hunk 4]
```diff
@@ -126,11 +126,19 @@ func (pt PipelineTask) Validate(ctx context.Context) (errs *apis.FieldError) {
 	errs = errs.Also(pt.validateRefOrSpec())
 
 	errs = errs.Also(pt.validateEmbeddedOrType())
-
+	notCustomTaskKinds := map[TaskKind]bool{
+		"":                 true,
+		NamespacedTaskKind: true,
+		"ClusterTask":      true,
```
Comment (lbernick) [inline pkg/apis/pipeline/v1/pipeline_validation.go:132]: Based on Jerop's comment, "Task" and "ClusterTask" kinds are considered normal tasks if the api version is not set, and customtasks otherwise. so I think the variable name `notCustomTaskKinds` is misleading

File: pkg/apis/pipeline/v1/pipeline_validation.go [hunk 5]
```diff
@@ -126,11 +126,19 @@ func (pt PipelineTask) Validate(ctx context.Context) (errs *apis.FieldError) {
...
+	}
 	// Pipeline task having taskRef/taskSpec with APIVersion is classified as custom task
 	switch {
+	case pt.TaskRef != nil && !notCustomTaskKinds[pt.TaskRef.Kind]:
+		errs = errs.Also(pt.validateCustomTask())
 	case pt.TaskRef != nil && pt.TaskRef.APIVersion != "":
```
Comment (lbernick) [inline pkg/apis/pipeline/v1/pipeline_validation.go:138]: This might be more readable as:
```
case pt.TaskRef != nil:
  if pt.TaskRef.APIVersion != "" || !notCustomTaskKinds[pt.TaskRef.Kind] {
    pt.validateCustomTask()
  }
```

(Also could the double negative !notCustomTaskKinds be made into a positive?)

File: pkg/apis/pipeline/v1/pipeline_types.go (hunk 1 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1/pipeline_types.go]: Thanks! would you mind just noting in the commit message/PR description that taskrun taskrefs will be handled separately, and linking to the issue in the PR description?

File: pkg/apis/pipeline/v1/pipeline_validation.go (hunk 4 above)
Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1/pipeline_validation.go:132]: 🤔 what could be a good naming... maybe rename to `taskKinds` and add comment here to explain?

File: pkg/apis/pipeline/v1/pipeline_validation.go (hunk 5 above)
Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1/pipeline_validation.go:138]: It's not so easy to merge these 2, there are some cases in this switch control, it seems not add readability with this

File: pkg/apis/pipeline/v1/pipeline_validation.go [hunk 6]
```diff
@@ -126,11 +126,21 @@ func (pt PipelineTask) Validate(ctx context.Context) (errs *apis.FieldError) {
 	errs = errs.Also(pt.validateRefOrSpec())
 
 	errs = errs.Also(pt.validateEmbeddedOrType())
-
+	// taskKinds contains the kinds when the apiVersion is not set, they are not custom tasks,
+	// if apiVersion is set they are custom tasks.
+	taskKinds := map[TaskKind]bool{
+		"":                 true,
+		NamespacedTaskKind: true,
+		"ClusterTask":      true,
```
Comment (jerop) [inline pkg/apis/pipeline/v1/pipeline_validation.go:134]: we don't have cluster tasks in v1
```suggestion
```

File: pkg/apis/pipeline/v1beta1/pipeline_validation.go [hunk 7]
```diff
@@ -134,12 +134,22 @@ func (pt PipelineTask) Validate(ctx context.Context) (errs *apis.FieldError) {
 	if pt.Resources != nil {
 		errs = errs.Also(apis.ErrDisallowedFields("resources"))
 	}
-
+	// taskKinds contains the kinds when the apiVersion is not set, they are not custom tasks,
+	// if apiVersion is set they are custom tasks.
+	taskKinds := map[TaskKind]bool{
+		"":                 true,
+		NamespacedTaskKind: true,
+		"ClusterTask":      true,
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/pipeline_validation.go:142]: please use `ClusterTaskKind` constant 

https://github.com/tektoncd/pipeline/blob/79f6e4c48b1b815ec910da593a505db8f0a92b41/pkg/apis/pipeline/v1beta1/taskref_types.go#L54 

```suggestion
		ClusterTaskKind:      true,
```

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go [hunk 8]
```diff
@@ -71,6 +71,22 @@ func TestPipeline_Validate_Success(t *testing.T) {
 				}},
 			},
 		},
+	}, {
+		name: "valid Task without apiversion",
+		p: &Pipeline{
+			ObjectMeta: metav1.ObjectMeta{Name: "pipeline"},
+			Spec: PipelineSpec{
+				Tasks: []PipelineTask{{Name: "foo", TaskRef: &TaskRef{Name: "task", Kind: NamespacedTaskKind}}},
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/pipeline_validation_test.go:79]: having "task" in the name as well is confusing 

```suggestion
				Tasks: []PipelineTask{{Name: "foo", TaskRef: &TaskRef{Name: "bar", Kind: NamespacedTaskKind}}},
```

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go [hunk 9]
```diff
@@ -71,6 +71,22 @@ func TestPipeline_Validate_Success(t *testing.T) {
...
+			},
+		},
+	}, {
+		name: "valid Cluster Task without apiversion",
+		p: &Pipeline{
+			ObjectMeta: metav1.ObjectMeta{Name: "pipeline"},
+			Spec: PipelineSpec{
+				Tasks: []PipelineTask{{Name: "foo", TaskRef: &TaskRef{Name: "task", Kind: "ClusterTask"}}},
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/pipeline_validation_test.go:87]: may be confusing to give a ClusterTask the name "task", also please use the constant

```suggestion
				Tasks: []PipelineTask{{Name: "foo", TaskRef: &TaskRef{Name: "bar", Kind: ClusterTaskKind}}},
```

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go [hunk 10]
```diff
@@ -125,6 +141,27 @@ func TestPipeline_Validate_Failure(t *testing.T) {
 			Message: `expected at least one, got none`,
 			Paths:   []string{"spec.description", "spec.params", "spec.resources", "spec.tasks", "spec.workspaces"},
 		},
+	}, {
+		name: "pipelinetask custom task references missing apiversion",
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/pipeline_validation_test.go:145]:
```suggestion
		name: "custom task reference in taskref missing apiversion",
```

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go [hunk 11]
```diff
@@ -125,6 +141,27 @@ func TestPipeline_Validate_Failure(t *testing.T) {
...
+		p: &Pipeline{
+			ObjectMeta: metav1.ObjectMeta{Name: "pipeline"},
+			Spec: PipelineSpec{
+				Tasks: []PipelineTask{{Name: "foo", TaskRef: &TaskRef{Kind: "Example", Name: ""}}},
+			},
+		},
+		expectedError: *apis.ErrInvalidValue("custom task ref must specify apiVersion", "taskRef.apiVersion").ViaFieldIndex("spec.tasks", 0),
+	}, {
+		name: "pipelinetask taskspec custom task missing apiversion",
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/pipeline_validation_test.go:154]:
```suggestion
		name: "custom task reference in taskspec missing apiversion",
```

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go [hunk 12]
```diff
@@ -125,6 +141,27 @@ func TestPipeline_Validate_Failure(t *testing.T) {
 			Message: `expected at least one, got none`,
 			Paths:   []string{"spec.description", "spec.params", "spec.resources", "spec.tasks", "spec.workspaces"},
 		},
+	}, {
+		name: "pipelinetask custom task references missing apiversion",
+		p: &Pipeline{
+			ObjectMeta: metav1.ObjectMeta{Name: "pipeline"},
+			Spec: PipelineSpec{
+				Tasks: []PipelineTask{{Name: "foo", TaskRef: &TaskRef{Kind: "Example", Name: ""}}},
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/pipeline_validation_test.go:149]: what happens if there was apiversion but no kind?

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go [hunk 13]
```diff
@@ -125,6 +141,27 @@ func TestPipeline_Validate_Failure(t *testing.T) {
...
+		},
+		expectedError: *apis.ErrInvalidValue("custom task ref must specify apiVersion", "taskRef.apiVersion").ViaFieldIndex("spec.tasks", 0),
+	}, {
+		name: "pipelinetask taskspec custom task missing apiversion",
+		p: &Pipeline{
+			ObjectMeta: metav1.ObjectMeta{Name: "pipeline"},
+			Spec: PipelineSpec{
+				Tasks: []PipelineTask{{Name: "foo", TaskSpec: &EmbeddedTask{
+					TypeMeta: runtime.TypeMeta{
+						Kind: "Example",
```
Comment (jerop) [inline pkg/apis/pipeline/v1beta1/pipeline_validation_test.go:160]: what happens if there was apiversion but no kind?

**Review by jerop — COMMENTED** [review]
please add docs and release notes

File: pkg/apis/pipeline/v1beta1/pipeline_validation.go (hunk 7 above)
Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1beta1/pipeline_validation.go:142]: oh thanks!

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go (hunk 12 above)
Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1beta1/pipeline_validation_test.go:149]: It's tested in another test case, I will move these cases there.

File: pkg/apis/pipeline/v1beta1/pipeline_validation_test.go (hunk 8 above)
Comment (Yongxuanzhang) [reply pkg/apis/pipeline/v1beta1/pipeline_validation_test.go]: oh ok!

File: pkg/apis/pipeline/v1/pipeline_validation.go (hunk 4 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1/pipeline_validation.go]: I think what you have now looks good!

**Review by lbernick — APPROVED** [review]

**Review by jerop — COMMENTED** [review]
/lgtm

File: pkg/apis/pipeline/v1/pipeline_validation.go (hunk 6 above)
Comment (lbernick) [reply pkg/apis/pipeline/v1/pipeline_validation.go]: I think this might not have been correct: https://github.com/tektoncd/pipeline/issues/6587
