### PR TITLE
Fixes flaky metrics unit tests

### LINKED ISSUE #1659: Unit tests are broken
# Expected Behavior
Unit tests pass in CI and in (nightly) releases.

# Actual Behavior
Unit tests pass in CI but fail in releases:

```
2019-11-27T02:02:43.168Z	ERROR	TestReconcile_InvalidPipelineRuns/invalid-pipeline-run-params-dont-exist-shd-stop-reconciling	pipelinerun/controller.go:61	Failed to create pipelinerun metrics recorder running_pipelineruns_count: cannot register view "running_pipelineruns_count"; a different view with the same name is already registered
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.NewController.func1
	/workspace/src/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/controller.go:61
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.getPipelineRunController
	/workspace/src/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun_test.go:73
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.TestReconcile_InvalidPipelineRuns.func1
	/workspace/src/github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun_test.go:373
testing.tRunner
	/usr/local/go/src/testing/testing.go:865
```

# Steps to Reproduce the Problem

1. Run the unit tests task used by the release pipeline
2.
3.

# Additional Info

### PR DESCRIPTION
**Pull request by hrishin**
# Changes
Quite often unit test failure showing "*** a different view
with the same name is already registered" messages at many places.
At the beginning of every metrics test, it tries to register respective
metrics views(metrics data it want present), publish metrics and
uniregister views. Uniregister view is important becuase for next
test it dont need to hold the old metrics data.
unregister() views were getting called using `defer` in
table test for loop, just like
for _, td := range tests {
	defer unregister()
	.......
}
This were resulting unwanted execution behaviour
for unregister() views function, which umtimately faling tests.
Its better to unregister() views before start executing the
tests.

This patch fixes the behaviour by calling uniregister() views function
at the end of loop.

Fixes #1659

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

File: pkg/reconciler/pipelinerun/metrics_test.go [hunk 1]
```diff
@@ -102,6 +101,8 @@ func TestRecordPipelineRunDurationCount(t *testing.T) {
 			assertErrIsNil(err, "DurationAndCount recording recording got an error", t)
 			metricstest.CheckDistributionData(t, "pipelinerun_duration_seconds", test.expectedTags, 1, test.expectedDuration, test.expectedDuration)
 			metricstest.CheckCountData(t, "pipelinerun_count", test.expectedTags, test.expectedCount)
+
+			unregisterMetrics()
```
Comment (ImJasonH) [inline pkg/reconciler/pipelinerun/metrics_test.go]: This means metrics won't be unregistered if any of the above t.Fatal or panic. Is that intended?

Comment (ImJasonH) [reply pkg/reconciler/pipelinerun/metrics_test.go]: When `defer`ed, `unregister` is called after each `t.Run`, I think that's the correct behavior isn't it?

Comment (hrishin) [reply pkg/reconciler/pipelinerun/metrics_test.go]: > This means metrics won't be unregistered if any of the above t.Fatal or panic. Is that intended?

@ImJasonH you are right, I didnt realised the other case. 

>When defered, unregister is called after each t.Run, I think that's the correct behavior isn't it?

That's how it should be however looks like its not working the intended way. Im not getting concrete proof about it but I guess that is what happening

Comment (hrishin) [reply pkg/reconciler/pipelinerun/metrics_test.go]: Ahh you're right @ImJasonH  its `metricstest.Unregister` could behave asynchronously, defer is working intended way.

**Comment by vdemeester** [comment]
@hrishin you go `gofmt`ed

```
I1211 09:37:18.161] -------------------------------------------
I1211 09:37:18.161] ---- Checking go code style with gofmt ----
I1211 09:37:18.161] -------------------------------------------
I1211 09:37:18.698] diff -u pkg/reconciler/taskrun/metrics_test.go.orig pkg/reconciler/taskrun/metrics_test.go
I1211 09:37:18.698] --- pkg/reconciler/taskrun/metrics_test.go.orig	2019-12-11 09:37:18.432424121 +0000
I1211 09:37:18.698] +++ pkg/reconciler/taskrun/metrics_test.go	2019-12-11 09:37:18.432424121 +0000
I1211 09:37:18.698] @@ -308,4 +308,3 @@
I1211 09:37:18.699]  func unregisterMetrics() {
I1211 09:37:18.699]  	metricstest.Unregister("taskrun_duration_seconds", "pipelinerun_taskrun_duration_seconds", "taskrun_count", "running_taskruns_count", "taskruns_pod_latency")
I1211 09:37:18.699]  }
I1211 09:37:18.699] -
```

**Comment by hrishin** [comment]
@vdemeester ohh yeah(_need to align tooling on on dev machine_)
