### PR TITLE
Fixing nil pointer in case of no timeout ⏲

### LINKED ISSUE #3234: Nil pointer when PipelineRun created v0.16.x
# Expected Behavior

PipelineRun reconciles don't panic.

# Actual Behavior

Upgrade Tekton pipeline from v0.15.2 (ok) to v0.16.0 - v0.16.2. Tasks and TaskRuns work fine, but creating a PipelineRun crashes the controller with a nil pointer panic.

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17f56d1]
goroutine 164 [running]:
github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun.(*Reconciler).ReconcileKind(0xc0003a7080, 0x216c240, 0xc000d8d770, 0xc000d48a00, 0xc000d48a00, 0x0)
        github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun.go:147 +0x1281
github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun.(*reconcilerImpl).Reconcile(0xc00074db80, 0x216c240, 0xc000d8d710, 0xc000c79680, 0x12, 0xc00087cc70, 0x216c240)
        github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/pipelinerun/reconciler.go:237 +0x1299
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0008ed0e0, 0xc00096ba00)
        github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:465 +0x785
github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext.func3(0xc000eef960, 0xc0008ed0e0)
        github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:403 +0x53
created by github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller.(*Impl).RunContext
        github.com/tektoncd/pipeline/vendor/knative.dev/pkg/controller/controller.go:401 +0x1f5
```

# Steps to Reproduce the Problem

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debug-task
  namespace: tekton
spec:
  steps:
    - name: foo
      image: docker.io/alpine:3.12
      script: |
        echo "hello"
```

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: debug-pipeline
  namespace: tekton
spec:
  tasks:
    - name: task
      taskRef:
        name: debug-task
```

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: debug-
  namespace: tekton
spec:
  pipelineRef:
    name: debug-pipeline
```

```
kubectl apply -f task.yaml
kubectl apply -f pipeline.yaml
kubectl create -f pipelinerun.yaml
```

# Additional Info

- Kubernetes version: v1.19.1
- Tekton Pipeline version: v0.16.2

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

If `pr.Spec.Timeout` is nil (aka no timeout applied), dereferencing
it (`*pr.Spec.Timout`) will panic.

*Note*: it shouldn't really happen because default should be applied **but** if, for some dark reason they are not applied, this definitely panics.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

Closes #3234

/kind bug
/cc @pritidesai @bobcatfish @afrittoli 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Fix a possible `nil` pointer exception in case the PipelineRun timeout is not specified (nor default applied)
````

### CODE REVIEW

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 1]
```diff
@@ -144,7 +144,9 @@ func (c *Reconciler) ReconcileKind(ctx context.Context, pr *v1beta1.PipelineRun)
 			pr.Status.StartTime = &pr.CreationTimestamp
 		}
 		// start goroutine to track pipelinerun timeout only startTime is not set
-		go c.timeoutHandler.Wait(pr.GetNamespacedName(), *pr.Status.StartTime, *pr.Spec.Timeout)
```
Comment (vdemeester) [inline pkg/reconciler/pipelinerun/pipelinerun.go:147]: Actually, we pass `*pr.Spec.Timeout` **just** for the log ? :scream_cat:

Comment (vdemeester) [reply pkg/reconciler/pipelinerun/pipelinerun.go:147]: nevermind, it's used below.

File: pkg/reconciler/pipelinerun/pipelinerun.go [hunk 2]
```diff
@@ -817,6 +818,13 @@ func combineTaskRunAndTaskSpecAnnotations(pr *v1beta1.PipelineRun, pipelineTask
 	return annotations
 }
 
+func getPipelineRunTimeout(pr *v1beta1.PipelineRun) metav1.Duration {
+	if pr.Spec.Timeout == nil {
+		return metav1.Duration{Duration: config.DefaultTimeoutMinutes * time.Minute}
```
Comment (sbwsg) [inline pkg/reconciler/pipelinerun/pipelinerun.go:823]: Is `config.FromContextOrDefaults(ctx).DefaultTimeoutMinutes` the newer way to get the value in case it's been overridden?  I see that used in the taskrun reconciler.  Not sure if applicable here as well.

Comment (vdemeester) [reply pkg/reconciler/pipelinerun/pipelinerun.go:823]: oh right, I can work with that :+1:

**Review by sbwsg — APPROVED** [review]

**Comment by pritidesai** [comment]
/lgtm

interestingly not catching it in CI, @ImJasonH cleanup test builder effort (in `pipelinerun_test.go`) might uncover this in CI.

**Review by afrittoli — COMMENTED** [review]
Nice, thank you!
I was reviewing it and then it was merged :D
