### PR TITLE
feat(matrix): Fix matrix param type mismatch problem for ref array result from customrun scenario

### LINKED ISSUE #8022: Matrix: invalid param type when consuming results from CustomRun on task matrix.params field
# Expected Behavior
I expect the validation to pass and the tasks to run successfully.

# Actual Behavior
A reconciliation error is preventing the pipeline from executing successfully. 
Received an error message stating:
```
'[User error] Failed to validate matrix "parameters of type array only
      are allowed, but param \"arch\" has type \"string\" in pipelineTask \"matrix-job\""
      with error %!w(MISSING)'
```

# Steps to Reproduce the Problem
We have the pipelinerun data segment as following:  
```yaml
  pipelineSpec:
    displayName: test
    tasks:
    - displayName: prepare
      name: prepare
      taskSpec:
        steps:
        - args:
          - -step-name=arch
          command:
          - /user/bin/entry
          image: busybox
          name: arch
    - name: matrix-job-eval
      params:
      - name: expression
        value: '{"matrix-param-arch":"${{jobs.prepare.outputs.arch}}"}'
      runAfter:
      - prepare
      taskRef:
        ## matrix-job-eval is a customrun
        apiVersion: spel.taskline.dev/v1alpha1
        kind: SpEL
    - displayName: matrix-job
      matrix:
        params:
        - name: arch
          value: $(tasks.matrix-job-eval.results.matrix-param-arch)
      name: matrix-job
      runAfter:
      - matrix-job-eval
      taskSpec:
        params:
        - name: arch
          type: string
        spec: null
        steps:
        - args:
          - arch=$(params.arch)
          command:
          - /user/bin/consume-arch
          image: busybox
          name: step-0
```
Note: it's not a full resource yaml data for the consideration of sensitive data, but I believe it's enough to show the problem.   

What's going on here is that `matrix-job-eval` task is a customrun and will emit a array semantic result:   
```yaml
  results:
  - name: matrix-param-arch
    value: '[ "arm", "amd64" ]'
```
We expect `matrix-job` task could fan out to 2 taskruns according to the matrix-param-arch value, but we just got the user error I mentioned above.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-alibaba.126-dc14a4e28076cf", GitCommit:"dc14a4e28076cfaf6c0bf010c837eec6029bd97f", GitTreeState:"clean", BuildDate:"2023-11-06T11:02:05Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
v0.57.0
```

### PR DESCRIPTION
**Pull request by hittyt**
fix #8022 

# Changes

Adjust `resolveCustomResultRef` implementation in Tekton to handle array results from CustomRun tasks correctly. This change resolves a type mismatch issue when using array results as matrix parameters, ensuring compatibility and proper functioning in scenarios where previous CustomRun emits array results.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

File: pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go [hunk 1]
```diff
@@ -841,3 +842,52 @@ func TestValidateArrayResultsIndex(t *testing.T) {
...
+			},
+			want: &v1.ParamValue{
+				Type:      "string",
+				StringVal: "amd64",
+			},
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			if got := paramValueFromCustomRunResult(tt.args.result); !reflect.DeepEqual(got, tt.want) {
```
Comment (vdemeester) [inline pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go:888]: We use `cmp` for comparisons (see [here](https://github.com/tektoncd/pipeline/blob/68336fc53578516f33dd3aff5f22dff3fb2e9ed4/pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go#L540) for example)

Comment (hittyt) [reply pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go]: Thanks for the feedback! I've updated the comparison to use cmp as per the project's coding conventions. Please take a look at the latest commit.

**Review by vdemeester — APPROVED** [review]
cc @tektoncd/core-maintainers

**Comment by hittyt** [comment]
Hi @tektoncd/core-maintainer,

When you get a chance, could you please review this PR? It has already received positive reviews from @vdemeester and is awaiting your `lgtm` label. This fix is particularly important for us at Alibaba, as we have a significant use-case that depends on its integration.

We would greatly appreciate a review at your earliest convenience to facilitate progress. I believe the PR is fully compliant with the project's contribution guidelines and is ready for merge.

Thank you for your attention to this matter and for your continued work on this project.
