### PR TITLE
Poll multiple times that the pvc is deleted in TestPipelineRun

### LINKED ISSUE #915: Flaky TestPipelineRun when provisioning pvcs
# Expected Behavior

When the cloud provider volume are slow to deprovision, the test fails due of failing to delete the PVC .

# Actual Behavior

Fails without even trying again 😢

# Additional Info

```
 pipelinerun_test.go:185: PVC pipelinerun1-pvc still exists after PipelineRun pipelinerun1 has completed: &PersistentVolumeClaim{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:pipelinerun1-pvc,GenerateName:,Namespace:arendelle-mqvsl,SelfLink:/api/v1/namespaces/arendelle-mqvsl/persistentvolumeclaims/pipelinerun1-pvc,UID:f15546ed-80e7-11e9-ab9a-1292abff36cc,ResourceVersion:16028,Generation:0,CreationTimestamp:2019-05-28 01:28:48 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[{tekton.dev/v1alpha1 PipelineRun pipelinerun1 e9891d43-80e7-11e9-b427-0af0f4807604 0xc420a06d9b 0xc420a06d9c}],Finalizers:[kubernetes.io/pvc-protection],ClusterName:,Initializers:nil,},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{5368709120 0} {<nil>} 5Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*gp2,VolumeMode:*Filesystem,DataSource:nil,},Status:PersistentVolumeClaimStatus{Phase:Pending,AccessModes:[],Capacity:ResourceList{},Conditions:[],},}
```

### PR DESCRIPTION
**Pull request by chmouel**
Let's poll for up to 10mn that the PersistentVolumeClaims has the
DeletionTimestamp set.

Fixes #915

Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>

# Changes
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ✔️ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ 🤷🏼‍♂️ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ✔️ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by chmouel** [comment]
/unhold

Should work know, not 100% sure but the future will hold truth

**Comment by abayer** [comment]
...I really wrote a lousy test, didn't I. =)

**Comment by chmouel** [comment]
@abayer arf not it's fine, there is way worse things :)

File: test/pipelinerun_test.go [hunk 1]
```diff
@@ -175,15 +176,23 @@ func TestPipelineRun(t *testing.T) {
...
+			// the PersistentVolumeClaims has the DeletionTimestamp
+			if err := wait.PollImmediate(interval, timeout, func() (bool, error) {
+				// Check to make sure the PipelineRun's artifact storage PVC has been "deleted" at the end of the run.
+				pvc, errWait := c.KubeClient.Kube.CoreV1().PersistentVolumeClaims(namespace).Get(artifacts.GetPVCName(pipelineRun), metav1.GetOptions{})
+				if errWait != nil && !errors.IsNotFound(errWait) {
+					return true, fmt.Errorf("Error looking up PVC %s for PipelineRun %s: %s", artifacts.GetPVCName(pipelineRun), prName, errWait)
+				}
+				return pvc.DeletionTimestamp == nil, errWait
+			}); err != nil {
 				if !errors.IsNotFound(err) {
```
Comment (vdemeester) [inline test/pipelinerun_test.go]: :thinking: shouldn't that check be in the `PollImmediate` ? (and returning `true` + `nil` as error) so that we don't have to do the check twice ?

File: test/pipelinerun_test.go [hunk 2]
```diff
@@ -175,15 +176,23 @@ func TestPipelineRun(t *testing.T) {
...
+
+			// Wait for up to 10 minutes and restart every 30seconds to check if
+			// the PersistentVolumeClaims has the DeletionTimestamp
+			if err := wait.PollImmediate(interval, timeout, func() (bool, error) {
+				// Check to make sure the PipelineRun's artifact storage PVC has been "deleted" at the end of the run.
+				pvc, errWait := c.KubeClient.Kube.CoreV1().PersistentVolumeClaims(namespace).Get(artifacts.GetPVCName(pipelineRun), metav1.GetOptions{})
+				if errWait != nil && !errors.IsNotFound(errWait) {
+					return true, fmt.Errorf("Error looking up PVC %s for PipelineRun %s: %s", artifacts.GetPVCName(pipelineRun), prName, errWait)
+				}
+				return pvc.DeletionTimestamp == nil, errWait
```
Comment (vdemeester) [inline test/pipelinerun_test.go]: I don't think we need to return `errWait` here, as it's only be `IsNotFound` as an error, and in this case, we don't want it to fail (as it's already gone)

Comment (chmouel) [reply test/pipelinerun_test.go]: 👍

**Comment by chmouel** [comment]
Seems like it works when testing the test locally 


```bash
% go test -failfast -v -count=1 -tags=e2e -ldflags '-X github.com/tektoncd/pipeline/test.missingKoFatal=false' ./test -timeout=20m --kubeconfig $KUBECONFIG -run TestPipelineRun/service_account_propagation 2>&1 |tee /tmp/log
Using kubeconfig at `/Users/chmouel/.kube/config` with cluster ``
=== RUN   TestPipelineRun
=== PAUSE TestPipelineRun
=== RUN   TestPipelineRunTimeout
2019-05-29T10:35:01.537+0200	info	logging/config.go:39	Successfully created the logger.	{"knative.dev/jsonconfig": "{\n\t  \"level\": \"info\",\n\t  \"encoding\": \"console\",\n\t  \"outputPaths\": [\"stdout\"],\n\t  \"errorOutputPaths\": [\"stderr\"],\n\t  \"encoderConfig\": {\n\t    \"timeKey\": \"ts\",\n\t    \"messageKey\": \"message\",\n\t    \"levelKey\": \"level\",\n\t    \"nameKey\": \"logger\",\n\t    \"callerKey\": \"caller\",\n\t    \"messageKey\": \"msg\",\n\t    \"stacktraceKey\": \"stacktrace\",\n\t    \"lineEnding\": \"\",\n\t    \"levelEncoder\": \"\",\n\t    \"timeEncoder\": \"iso8601\",\n\t    \"durationEncoder\": \"\",\n\t    \"callerEncoder\": \"\"\n\t  }\n\t}"}
2019-05-29T10:35:01.537+0200	info	logging/config.go:39	Logging level set to info
2019-05-29T10:35:01.537+0200	warn	logging/config.go:41	Fetch GitHub commit ID from kodata failed: "KO_DATA_PATH" does not exist or is empty
=== PAUSE TestPipelineRunTimeout
=== RUN   TestPipelineRunFailedAndRetry
=== PAUSE TestPipelineRunFailedAndRetry
=== CONT  TestPipelineRun
=== CONT  TestPipelineRunTimeout
=== CONT  TestPipelineRunFailedAndRetry
=== RUN   TestPipelineRun/service_account_propagation
=== PAUSE TestPipelineRun/service_account_propagation
=== CONT  TestPipelineRun/service_account_propagation
--- PASS: TestPipelineRun (0.00s)
    --- PASS: TestPipelineRun/service_account_propagation (35.85s)
        init_test.go:100: Create namespace arendelle-lqhsw to deploy to
        init_test.go:112: Verify SA "default" is created in namespace "arendelle-lqhsw"
        pipelinerun_test.go:127: Setting up test resources for "service account propagation" test in namespace arendelle-lqhsw
        pipelinerun_test.go:136: Waiting for PipelineRun pipelinerun1 in namespace arendelle-lqhsw to complete
        pipelinerun_test.go:141: Making sure the expected TaskRuns [task1] were created
        pipelinerun_test.go:164: Checking that labels were propagated correctly for TaskRun pipelinerun1-task1-wq69c
        pipelinerun_test.go:170: Making sure 2 events were created from taskrun and pipelinerun with kinds map[PipelineRun:[pipelinerun1] TaskRun:[pipelinerun1-task1-wq69c]]
        pipelinerun_test.go:194: Successfully finished test "service account propagation"
        pipelinerun_test.go:195: Deleting namespace arendelle-lqhsw
--- PASS: TestPipelineRunTimeout (39.58s)
    init_test.go:100: Create namespace arendelle-zttbd to deploy to
    init_test.go:112: Verify SA "default" is created in namespace "arendelle-zttbd"
    timeout_test.go:43: Creating Task in namespace arendelle-zttbd
    timeout_test.go:63: Waiting for Pipelinerun pear in namespace arendelle-zttbd to be started
    timeout_test.go:83: Waiting for TaskRuns from PipelineRun pear in namespace arendelle-zttbd to be running
    timeout_test.go:114: Waiting for PipelineRun pear in namespace arendelle-zttbd to be timed out
    timeout_test.go:132: Waiting for TaskRuns from PipelineRun pear in namespace arendelle-zttbd to be cancelled
    timeout_test.go:175: Waiting for PipelineRun kiwi in namespace arendelle-zttbd to complete
    timeout_test.go:179: Deleting namespace arendelle-zttbd
--- PASS: TestPipelineRunFailedAndRetry (47.15s)
    init_test.go:100: Create namespace arendelle-7zhwf to deploy to
    init_test.go:112: Verify SA "default" is created in namespace "arendelle-7zhwf"
    timeout_test.go:189: Creating Task in namespace arendelle-7zhwf
    timeout_test.go:208: Waiting for Pipelinerun pear in namespace arendelle-7zhwf to be started
    timeout_test.go:231: Deleting namespace arendelle-7zhwf
PASS
ok  	github.com/tektoncd/pipeline/test	47.777s
```

I am going to increase the timeout and see if that changes things

**Comment by chmouel** [comment]
/hold

still working on this,

**Comment by chmouel** [comment]
/hold cancel

yay this should now!! it took me a while to figure out because between my local dev env on openshift4 and on CI/k8 the behavior seems to be different,  the volume are around a longer time after the test in OS4
