### PR TITLE
Bugfix: deduplicate concurrent resolver cache requests with singleflight.

### LINKED ISSUE #9364: Resolver cache race condition causes duplicate upstream pulls
# Expected Behavior

With N resolver replicas, resolving the same digest-pinned bundle for multiple concurrent TaskRuns should produce at most N upstream registry pulls (one per replica to warm its cache).

# Actual Behavior

Concurrent resolution requests within the same replica all miss the cache independently and each call the upstream source, causing a cache stampede. With 4 replicas and 20 TaskRuns, 13 registry pulls were observed instead of the expected 4.

The race: multiple goroutines check the cache before the first resolution completes, all see a miss, and all resolve independently. The cache only prevents duplicates *after* the first store, not during in-flight resolution.

# Steps to Reproduce the Problem

1. Deploy Tekton Pipelines with 4 resolver replicas and default cache settings
2. Create 20 TaskRuns simultaneously referencing the same bundle by digest
3. Check registry logs/metrics for manifest GET request count

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: v1.34.2
Kustomize Version: v5.7.1
Server Version: v1.34.0
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.43.0
Pipeline version: devel
Triggers version: v0.34.0
Dashboard version: v0.65.0
```

Fix: add `singleflight.Group` to deduplicate concurrent in-flight resolutions for the same cache key. Affects all resolvers (bundle, git, cluster).

### PR DESCRIPTION
**Pull request by twoGiants**
# Changes

Fix race condition in resolver cache where concurrent requests for the same resource bypass the cache and independently resolve upstream (cache stampede / thundering herd).

## What changed

Before this change, cache lookup (`Get`) and storage (`Add`) were separate operations exposed on `resolverCache`, and the orchestration lived in `GetFromCacheOrResolve` in `operations.go`. 

Now the entire check-or-resolve flow is a single `GetCachedOrResolveFromRemote` method on `resolverCache` that wraps the resolve callback with `golang.org/x/sync/singleflight`. Only one in-flight resolution proceeds per cache key; all concurrent callers share its result. The separate `Get`, `Add`, `Remove`, and `GetFromCacheOrResolve` public methods are removed — the cache surface is now just `GetCachedOrResolveFromRemote` and `Clear`.

## Other changes

- Use `strings.Builder` in `generateCacheKey` instead of repeated string concatenation
- Remove unused `resolverType` parameter from `ShouldUse`
- Rework e2e tests to verify caching by counting actual registry GET requests (via container logs and registry `/metrics` endpoint) instead of checking resolver log messages
- Add multi-replica resolver e2e test (4 replicas, 80 TaskRuns) to validate singleflight works per-replica
- Allow `-run` flag to bypass category filtering in `TestMain` so individual tests can run in isolation
- Minor markdown lint fixes in `test/README.md`

@vdemeester also found and fixed a small bug in the e2e test annotations. I wasn't able to run tests in isolation. Now the little fix does the magic 🐱.

Fixes #9364

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Fix resolver cache race condition causing duplicate upstream pulls under concurrent load.
```

### CODE REVIEW

**Comment by twoGiants** [comment]
@waveywaves check out the fix! :smiley_cat:

File: pkg/remoteresolution/resolver/framework/cache/operations.go [hunk 1]
```diff
@@ -47,7 +47,6 @@ func ShouldUse(
 	ctx context.Context,
 	resolver ImmutabilityChecker,
 	params []v1.Param,
-	resolverType string,
```
Comment (aThorp96) [inline pkg/remoteresolution/resolver/framework/cache/operations.go:50]: Huh, I'm surprised Go hadn't complained about an unused variable earlier 🤔 Thanks for cleaning up

File: pkg/remoteresolution/resolver/framework/cache/cache.go [hunk 2]
```diff
@@ -137,7 +141,9 @@ func (c *resolverCache) Clear() {
 
 func generateCacheKey(resolverType string, params []pipelinev1.Param) string {
```
Comment (aThorp96) [inline pkg/remoteresolution/resolver/framework/cache/cache.go:150]: Out of scope note: I don't suspect that we'd see exceedingly large numbers of params per request, but since this gets called three times for during a cache miss (during the [first cache `Get()`](https://github.com/tektoncd/pipeline/blob/30e7bdf291e8c05d335e91de1392bdd00f57f5f4/pkg/remoteresolution/resolver/framework/cache/operations.go#L112), on a miss to [get the singleflight key](https://github.com/tektoncd/pipeline/blob/30e7bdf291e8c05d335e91de1392bdd00f57f5f4/pkg/remoteresolution/resolver/framework/cache/operations.go#L112), and [then again](https://github.com/tektoncd/pipeline/blob/30e7bdf291e8c05d335e91de1392bdd00f57f5f4/pkg/remoteresolution/resolver/framework/cache/operations.go#L128) when adding the item to the cache), as a followup it would be good to cache this key

Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache.go:150]: Yeah, I wasn't to happy with it too tbh 😒 

Lets keep it clean. I will refactor it. 

I have moved this logic into cache.go and cleaned up a bit more. A few more unit tests will follow. The e2e tests still pass.

The cache API surface becomes smaller what I like and it's still good enough testable.

Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache.go:150]: Re-worked the entire thing and removed a bunch of nonsense unit tests and added correct unit tests.

Haven't figured out yet how to implement a good regression unit test for this issue. But the e2e tests are catching this bug currently so it's something.

The cache is now more focused. I like it better.

File: test/resolver_cache_test.go [hunk 3]
```diff
@@ -56,147 +58,268 @@ var cacheGitFeatureFlags = requireAllGates(map[string]string{
...
+	var wg sync.WaitGroup
+	startSignal := make(chan struct{})
+	for _, tr := range taskRuns {
+		wg.Add(1)
+
+		go func(tr *v1.TaskRun, begin <-chan struct{}) {
+			defer wg.Done()
+
+			<-begin
+			createTaskRunAndWait(ctx, t, c, tr)
```
Comment (vdemeester) [inline test/resolver_cache_test.go]: `createTaskRunAndWait` calls `t.Fatalf`, which internally calls `runtime.Goexit()`. Go's testing documentation explicitly states: *"FailNow must be called from the goroutine running the test … not from other goroutines created during the test."* Calling `t.Fatalf` from a non-test goroutine can cause a panic or allow the test to silently pass after a failure. This is likely the cause of the flaky beta e2e CI failure. Consider collecting errors via a channel and checking them after `wg.Wait()`, or switching to `t.Errorf` in `createTaskRunAndWait`.

File: pkg/remoteresolution/resolver/framework/cache/cache.go [hunk 4]
```diff
@@ -20,25 +20,32 @@ import (
...
 	"crypto/sha256"
 	"encoding/hex"
+	"errors"
 	"sort"
+	"strings"
 	"time"
 
 	pipelinev1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
+	v1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
 	resolutionframework "github.com/tektoncd/pipeline/pkg/resolution/resolver/framework"
```
Comment (vdemeester) [inline pkg/remoteresolution/resolver/framework/cache/cache.go]: Same package imported under two aliases. This compiles but is confusing — `pipelinev1` is used throughout `generateCacheKey`, while `v1` is only used in the `GetCachedOrResolveFromRemote` signature. Pick one and use it consistently.

```suggestion
	pipelinev1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
```

File: test/resolver_cache_test.go (hunk 3 above)
Comment (twoGiants) [reply test/resolver_cache_test.go]: As it turns out, that's not it :shrug:. The tests still break when run in parallel. But it was a good catch of a potential issue, so I reworked this part anyway. I am returning errors from `createTaskRunAndWait` now and collect them in an error channel in `createTaskRunsInParallelAndWait` as you suggested.

It looks like the actual error is scaling up and down of resolver replicas. The `TestBundleResolverCache` is flaking because I believe `TestBundleResolverCacheWithFourResolverReplicas` is scaling up to 4 resolver replicas and a bit later scales back down to 1. `TestBundleResolverCache` finishes earlier and expects 1 registry request but is having 4 because of the scaled up resolver replicas.

I am working on it. I've set the `TestBundleResolverCacheWithFourResolverReplicas` test to serial but it fails with a [different issue now](https://github.com/tektoncd/pipeline/actions/runs/22518303053/job/65239444078?pr=9365) which relates to Prometheus metrics gathering in the test assertions :thinking:.

Comment (twoGiants) [reply test/resolver_cache_test.go]: The issue was a `prometheus/common` breaking change. Fixed the test helpers.

The e2e tests pass now! We're good.

**Comment by twoGiants** [comment]
We're good, take another look: @vdemeester @aThorp96 

I updated the code, answered and marked the comments as resolved.

File: pkg/remoteresolution/resolver/framework/cache/cache.go [hunk 5]
```diff
@@ -75,57 +82,57 @@ func (c *resolverCache) MaxSize() int {
...
-	params []pipelinev1.Param,
-	resource resolutionframework.ResolvedResource,
-) resolutionframework.ResolvedResource {
-	key := generateCacheKey(resolverType, params)
-	c.infow("Adding to cache", "key", key, "expiration", c.ttl)
+	// If cache miss, resolve from remote using singleflight
+	untyped, err, _ := c.flightGroup.Do(key, func() (any, error) {
+		resolved, err := resolveFromRemote()
+		if err != nil {
+			return nil, err
```
Comment (waveywaves) [inline pkg/remoteresolution/resolver/framework/cache/cache.go:109]: should we also add a test for a scenario for resolve failing ? it's only tested with a single caller right now, not concurrent callers

File: pkg/remoteresolution/resolver/framework/cache/cache.go [hunk 6]
```diff
@@ -75,57 +82,57 @@ func (c *resolverCache) MaxSize() int {
...
-// annotated version of the resource.
-func (c *resolverCache) Add(
-	resolverType string,
-	params []pipelinev1.Param,
-	resource resolutionframework.ResolvedResource,
-) resolutionframework.ResolvedResource {
-	key := generateCacheKey(resolverType, params)
-	c.infow("Adding to cache", "key", key, "expiration", c.ttl)
+	// If cache miss, resolve from remote using singleflight
+	untyped, err, _ := c.flightGroup.Do(key, func() (any, error) {
```
Comment (waveywaves) [inline pkg/remoteresolution/resolver/framework/cache/cache.go]: the shared return value from singleflight.Do is discarded here, might be worth logging it so we can see how often dedup actually kicks in

File: pkg/remoteresolution/resolver/framework/cache/cache_test.go [hunk 7]
```diff
@@ -384,369 +221,172 @@ func TestCacheLRUEvictionWithAccess(t *testing.T) {
...
-				if j%3 == 0 {
-					cache.Get(resolverType, params)
-				}
-			}
-		}(i)
-	}
+		if !errors.Is(actualErr, expectedError) {
+			t.Fatalf("expected error %v, got error %v", expectedError, actualErr)
+		}
+	})
```
Comment (waveywaves) [inline pkg/remoteresolution/resolver/framework/cache/cache_test.go:374]: should we also check that after a failed resolve, a retry with a working resolveFn actually goes through ? just to make sure the singleflight group resets and doesn't block the key permanently

File: pkg/remoteresolution/resolver/framework/cache/cache.go (hunk 5 above)
Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache.go:109]: > should we also add a test for a scenario for resolve failing ? 

I have added a [unit test for a resolution error](https://github.com/tektoncd/pipeline/pull/9365/changes#diff-f36c11beb89be1a9d721710a7b305a8cabcc23b4bb6645f540364beb030e8569R323).

> it's only tested with a single caller right now, not concurrent callers

No, it's actually tested with multiple callers (that would be parallel created TaskRuns right?) and multiple resolver replicas. I have added the e2e test [TestBundleResolverCacheWithFourResolverReplicas](https://github.com/tektoncd/pipeline/pull/9365/changes#diff-c0c825ed4e67d524e53445967d32f92b8027ecd413c23b3ee7489cf4f861b4f5R89) which simulates what @aThorp96 found. I am scaling up to 4 resolver replicas and perform concurrent resolutions. This works now as expected.

File: pkg/remoteresolution/resolver/framework/cache/cache.go (hunk 6 above)
Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache.go]: Good idea. Will add it.

Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache.go]: Added without unit test => is acceptable I guess. It just adds some observability.

File: pkg/remoteresolution/resolver/framework/cache/cache_test.go (hunk 7 above)
Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache_test.go:374]: Added.

**Comment by twoGiants** [comment]
PTAL @waveywaves @vdemeester @aThorp96

File: pkg/remoteresolution/resolver/framework/cache/cache.go [hunk 8]
```diff
@@ -75,57 +82,61 @@ func (c *resolverCache) MaxSize() int {
...
-	}
 
-	resource, ok := value.(resolutionframework.ResolvedResource)
-	if !ok {
-		c.infow("Failed casting cached resource", "key", key)
-		return nil, false
-	}
+	if untyped, found := c.cache.Get(key); found {
+		cached, ok := untyped.(resolutionframework.ResolvedResource)
+		if !ok {
```
Comment (afrittoli) [inline pkg/remoteresolution/resolver/framework/cache/cache.go:94]: This seems inherited from the current behaviour rather than a new issue, but since you're touching this, I think it would make sense to evict this entry from the cache or else we'll keep failing on it.

File: pkg/remoteresolution/resolver/framework/cache/cache_test.go [hunk 9]
```diff
@@ -86,277 +70,130 @@ func TestGenerateCacheKey(t *testing.T) {
...
-	if !ok {
-		t.Fatal("Expected cache hit immediately after adding, but got cache miss")
+	// THEN
+	if err != nil {
+		t.Fatalf("unexpected error %v", err)
+	}
+
+	if resource.Annotations()[cacheOperationKey] != cacheOperationStore {
+		t.Fatalf("expected cache miss and cache operation 'store', got %s", resource.Annotations()[cacheOperationKey])
 	}
```
Comment (afrittoli) [inline pkg/remoteresolution/resolver/framework/cache/cache_test.go:168]: NIT: This could still be the same original resource with the same annotation, rather than a new one re-fetched after TTL. Perhaps you could add a counter into the mock resolver function, and check that it's invoked again.

File: pkg/remoteresolution/resolver/framework/cache/cache_test.go [hunk 10]
```diff
@@ -384,369 +221,193 @@ func TestCacheLRUEvictionWithAccess(t *testing.T) {
...
+		cacheWrapper.cache.Add(key, "poisoned-resource", cacheWrapper.TTL())
+		result, castingFailedErr := cacheWrapper.GetCachedOrResolveFromRemote(
+			params,
+			bundleresolution.LabelValueBundleResolverType,
+			resolveFn,
+		)
+
+		// THEN
+		if cachePopulationResult == nil {
+			t.Error("expected resolved recourse, got nil")
```
Comment (afrittoli) [inline pkg/remoteresolution/resolver/framework/cache/cache_test.go]: NIT: resource

File: pkg/remoteresolution/resolver/framework/cache/cache.go [hunk 11]
```diff
@@ -75,57 +82,61 @@ func (c *resolverCache) MaxSize() int {
...
+			c.infow("Failed casting cached resource", "key", key)
+			return nil, errors.New("failed casting cached resource")
```
Comment (khrm) [inline pkg/remoteresolution/resolver/framework/cache/cache.go:97]: Shouldn't we remove the cache in this case? Otherwise, it will keep failing until cache TTL. Isn't it so?

File: test/init_test.go [hunk 12]
```diff
@@ -62,6 +62,15 @@ func TestMain(m *testing.M) {
...
 
+	// Check if user provided explicit -run flag
+	// If so, skip category filtering and run normally to respect user's choice
+	runFlag := flag.Lookup("test.run")
+	if runFlag != nil && runFlag.Value.String() != "" {
+		exitCode := m.Run()
+		fmt.Fprintf(os.Stderr, "Using kubeconfig at `%s` with cluster `%s`\n", knativetest.Flags.Kubeconfig, knativetest.Flags.Cluster)
+		os.Exit(exitCode)
+	}
+
```
Comment (vdemeester) [inline test/init_test.go:74]: 😻

File: test/init_test.go [hunk 13]
```diff
@@ -62,6 +62,15 @@ func TestMain(m *testing.M) {
 		os.Exit(0)
 	}
 
+	// Check if user provided explicit -run flag
+	// If so, skip category filtering and run normally to respect user's choice
+	runFlag := flag.Lookup("test.run")
+	if runFlag != nil && runFlag.Value.String() != "" {
+		exitCode := m.Run()
+		fmt.Fprintf(os.Stderr, "Using kubeconfig at `%s` with cluster `%s`\n", knativetest.Flags.Kubeconfig, knativetest.Flags.Cluster)
```
Comment (vdemeester) [inline test/init_test.go]: shouldn't this be "before" `m.Run()` though ?

File: pkg/remoteresolution/resolver/framework/cache/cache.go (hunk 8 above)
Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache.go:94]: Yes, you're right. 

There is a big **BUT** 😆 => this type cast can't fail in the current implementation because we store a `resolutionframework.ResolvedResource` so the type cast back always succeeds. I tried to write a unit test for this condition but failed to do so, so I just left it untested.

But again you both ( @afrittoli, @khrm) are right here and I will add an eviction, I think it's cleaner. But it will have no unit test 😺 .

[Edited]: All good, I know how to test it, I actually already did it but forgot about it! :face_with_peeking_eye: :smile:

File: pkg/remoteresolution/resolver/framework/cache/cache.go (hunk 11 above)
Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache.go:97]: Answered [here](https://github.com/tektoncd/pipeline/pull/9365/changes/BASE..5d9c078a7916d6380a4574f1858499d816d675af#r2954072308).

File: pkg/remoteresolution/resolver/framework/cache/cache_test.go (hunk 9 above)
Comment (twoGiants) [reply pkg/remoteresolution/resolver/framework/cache/cache_test.go:168]: No, if TTL would be broken and the entry would still be in the cache, then the second `GetCache*` would receive a resource with the `resolution.tekton.dev/cache-operation=retrieve` annotation but it doesn't. This is what the second check is validating, it checks again if the annotation is `resolution.tekton.dev/cache-operation=store` because this will be set on a cache miss.

But I've added a clarifying comment above the second check:

```go
// cacheOperationStore proves this is a fresh resolution, not a cache hit
// (a cache hit would produce cacheOperationRetrieve instead)
``` 

:smile_cat: :magic_wand:

File: test/init_test.go (hunk 13 above)
Comment (twoGiants) [reply test/init_test.go]: Good point! I moved it after `flag.Parse` at the top and removed duplication. Now it's shown for every case before the e2e tests run, which is better anyway :smile_cat:

**Comment by twoGiants** [comment]
@afrittoli @khrm @vdemeester Thank you for taking a look :smile_cat: :+1: 

I addressed your comments in the latest commit 7de253c57144c19c3920dc782cb3e9f5843b9aa9 PTAL. If you approve I squash or you can merge as is => let me know.

**Review by waveywaves — COMMENTED** [review]
Thank you for this fix @twoGiants 🤗

**Comment by vdemeester** [comment]
@twoGiants @waveywaves should we cherry-pick this ?
