### PR TITLE
Fix converted legacy bundle->remote resolver syntax to be case-insensitive for kind

### LINKED ISSUE #6058: Legacy bundle syntax does not work with remote resoruces
# Expected Behavior

I can use the legacy bundle syntax in Tekton v0.44:

```yaml
    taskRef:
      kind: Task
      params:
      - name: bundle
        value: gcr.io/tekton-releases/catalog/upstream/git-batch-merge:0.2
      - name: name
        value: git-batch-merge
      - name: kind
        value: Task
```

# Actual Behavior

```
Pipeline tekton-ci/tekton-image-build can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "": failed to get task: error requesting remote resource: error getting "bundleresolver" "tekton-ci/bundles-e48f9a9d47f93b59899b7d303fe7799a": could not find object in image with kind: Task and name: git-batch-merge
```

# Steps to Reproduce the Problem

1. Any of the Tekton CI jobs in plumbing
2.
3.

# Additional Info

- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14-gke.1800", GitCommit:"1eab5b8da4acab130c72aea21eb7ed3e96523ca2", GitTreeState:"clean", BuildDate:"2022-12-07T09:32:46Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.28.0
Chains version: v0.8.0
Pipeline version: v0.44.0
Triggers version: v0.22.1
Dashboard version: v0.32.0
```

### PR DESCRIPTION
**Pull request by abayer**
# Changes

fixes #6058

When we finished deprecating the legacy bundle resolution syntax, we recommended users change from:
```
      taskRef:
        name: git-batch-merge
        bundle: gcr.io/tekton-releases/catalog/upstream/git-batch-merge:0.2
```
to
```
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: gcr.io/tekton-releases/catalog/upstream/git-batch-merge:0.2
          - name: name
            value: git-batch-merge
          - name: kind
            value: Task
```

But that created a problem - we have been comparing the `kind` parameter to the `dev.tekton.image.kind` annotation value in the bundle, which is generally all lower-case. Since we generally use `Task`, `Pipeline`, etc for `kind` values in our syntax, we've created a situation where the "normal" way to specify a `kind`, i.e., capitalized, is not going to work for most, if not all, bundles.

To fix this, we're changing the check in the remote bundles resolver to do a case-insensitive comparison.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
The remote bundles resolver now matches the kind value in its parameters and in bundle layers in a case-insensitive manner.
```

### CODE REVIEW

File: pkg/resolution/resolver/bundle/resolver_test.go [hunk 1]
```diff
@@ -295,6 +296,16 @@ func TestResolve(t *testing.T) {
 			},
 			imageName:      "single-task",
 			expectedStatus: internal.CreateResolutionRequestStatusWithData(taskAsYAML),
+		}, {
```
Comment (JeromeJu) [inline pkg/resolution/resolver/bundle/resolver_test.go:299]: Thanks for the fix, wondering if we shall specify and have the mismatched test cases in the test case name?

**Review by JeromeJu — APPROVED** [review]

**Comment by JeromeJu** [comment]
LTGM just one last nit will it be helpful to also include this 'notice' at https://github.com/tektoncd/pipeline/blob/main/docs/bundle-resolver.md?

**Review by jerop — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
/lgtm
